# Auto-generated — Rhino 8 — Eto

class AttachableMemberIdentifier:
    """.NET: Eto.AttachableMemberIdentifier"""
    def __init__(self, *args) -> None: ...
    DeclaringType: Type
    MemberName: str
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, ) -> str: ...

class AutoInitializeAttribute(Attribute):
    """.NET: Eto.AutoInitializeAttribute"""
    def __init__(self, *args) -> None: ...
    Initialize: bool
    TypeId: object

class CollectionChangedHandler:
    """.NET: Eto.CollectionChangedHandler`2"""
    def __init__(self, *args) -> None: ...
    Collection: TCollection
    Count: int
    def AddItem(self, item: TItem) -> None: ...
    def AddRange(self, items: IEnumerable) -> None: ...
    def ElementAt(self, index: int) -> TItem: ...
    def IndexOf(self, item: TItem) -> int: ...
    def InsertItem(self, index: int, item: TItem) -> None: ...
    def InsertRange(self, index: int, items: IEnumerable) -> None: ...
    def Register(self, collection: TCollection) -> bool: ...
    def RemoveAllItems(self, ) -> None: ...
    def RemoveItem(self, index: int) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def ReplaceItem(self, index: int, newItem: TItem) -> None: ...
    def ReplaceRange(self, index: int, newItems: IEnumerable) -> None: ...
    def Reset(self, ) -> None: ...
    def Unregister(self, ) -> None: ...

class ContentPropertyAttribute(Attribute):
    """.NET: Eto.ContentPropertyAttribute"""
    def __init__(self, *args) -> None: ...
    Name: str
    TypeId: object

class DataStoreChangedHandler(CollectionChangedHandler):
    """.NET: Eto.DataStoreChangedHandler`2"""
    def __init__(self, *args) -> None: ...
    Count: int
    Collection: TCollection
    def GetEnumerator(self, ) -> IEnumerator: ...

class DefaultStyleProvider:
    """.NET: Eto.DefaultStyleProvider"""
    def __init__(self, *args) -> None: ...
    Inherit: bool
    def Add(self, style: str, handler: Action) -> None: ...
    def Clear(self, ) -> None: ...

class EnumerableChangedHandler:
    """.NET: Eto.EnumerableChangedHandler`1 | Eto.EnumerableChangedHandler`2"""
    def __init__(self, *args) -> None: ...
    Count: int
    Collection: IEnumerable

class EtoEnvironment:
    """.NET: Eto.EtoEnvironment"""
    def __init__(self, *args) -> None: ...
    Platform: OperatingSystemPlatform
    Is64BitProcess: bool
    @staticmethod
    def GetFolderPath(folder: EtoSpecialFolder) -> str: ...

class EtoMemberIdentifier(AttachableMemberIdentifier):
    """.NET: Eto.EtoMemberIdentifier"""
    def __init__(self, *args) -> None: ...
    DeclaringType: Type
    MemberName: str

class EtoSpecialFolder:
    """.NET: Eto.EtoSpecialFolder"""
    def __init__(self, *args) -> None: ...
    ...

class ExportHandlerAttribute(PlatformExtensionAttribute):
    """.NET: Eto.ExportHandlerAttribute"""
    def __init__(self, *args) -> None: ...
    WidgetType: Type
    HandlerType: Type
    PlatformID: str
    TypeId: object
    def Register(self, platform: Platform) -> None: ...

class ExportInitializerAttribute(PlatformExtensionAttribute):
    """.NET: Eto.ExportInitializerAttribute"""
    def __init__(self, *args) -> None: ...
    InitializerType: Type
    PlatformID: str
    TypeId: object
    def Register(self, platform: Platform) -> None: ...

class ExtendedObservableCollection(ObservableCollection):
    """.NET: Eto.ExtendedObservableCollection`1"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: T
    def AddRange(self, items: IEnumerable) -> None: ...
    def Sort(self, comparer: IComparer) -> None: ...

class FileAction:
    """.NET: Eto.FileAction"""
    def __init__(self, *args) -> None: ...
    ...

class HandlerAttribute(Attribute):
    """.NET: Eto.HandlerAttribute"""
    def __init__(self, *args) -> None: ...
    Type: Type
    TypeId: object

class HandlerCreatedEventArgs(EventArgs):
    """.NET: Eto.HandlerCreatedEventArgs"""
    def __init__(self, *args) -> None: ...
    Instance: object

class HotReloadAttribute(Attribute):
    """.NET: Eto.HotReloadAttribute"""
    def __init__(self, *args) -> None: ...
    MethodName: str
    TypeId: object

class HotReloadService:
    """.NET: Eto.HotReloadService"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    @staticmethod
    def Initialize() -> None: ...
    @staticmethod
    def WatchFile(control: object, fileName: str, onChanged: Action, sourcePath: str) -> bool: ...

class ICallbackSource:
    """.NET: Eto.ICallbackSource"""
    def __init__(self, *args) -> None: ...
    Callback: object

class IControlObjectSource:
    """.NET: Eto.IControlObjectSource"""
    def __init__(self, *args) -> None: ...
    ControlObject: object

class IHandlerSource:
    """.NET: Eto.IHandlerSource"""
    def __init__(self, *args) -> None: ...
    Handler: object

class IPlatformInitializer:
    """.NET: Eto.IPlatformInitializer"""
    def __init__(self, *args) -> None: ...
    def Initialize(self, platform: Platform) -> None: ...

class IStyleProvider:
    """.NET: Eto.IStyleProvider"""
    def __init__(self, *args) -> None: ...
    Inherit: bool
    def ApplyCascadingStyle(self, container: object, widget: object, style: str) -> None: ...
    def ApplyDefault(self, widget: object) -> None: ...
    def ApplyStyle(self, widget: object, style: str) -> None: ...

class ITypeDescriptorContext:
    """.NET: Eto.ITypeDescriptorContext"""
    def __init__(self, *args) -> None: ...
    ...

class NamespaceInfo:
    """.NET: Eto.NamespaceInfo"""
    def __init__(self, *args) -> None: ...
    Assembly: Assembly
    Namespace: str
    def FindResource(self, resourceName: str) -> Stream: ...
    def FindType(self, typeName: str) -> Type: ...

class OperatingSystemPlatform:
    """.NET: Eto.OperatingSystemPlatform"""
    def __init__(self, *args) -> None: ...
    IsMono: bool
    IsNetCore: bool
    IsNetFramework: bool
    IsWindows: bool
    IsWinRT: bool
    IsUnix: bool
    IsMac: bool
    IsLinux: bool

class Platform:
    """.NET: Eto.Platform"""
    def __init__(self, *args) -> None: ...
    ID: str
    IsMac: bool
    IsWinForms: bool
    IsWpf: bool
    IsGtk: bool
    IsIos: bool
    IsAndroid: bool
    IsDesktop: bool
    IsMobile: bool
    IsValid: bool
    SupportedFeatures: PlatformFeatures
    Instance: Platform
    Detect: Platform
    AllowReinitialize: bool
    Context: IDisposable
    def Add(self, type: Type, instantiator: Func) -> None: ...
    def Cache(self, cacheKey: object) -> Dictionary: ...
    @staticmethod
    def Copy(platform: Platform) -> Platform: ...
    def Create(self, type: Type) -> object: ...
    def CreateShared(self, type: Type) -> object: ...
    def Find(self, type: Type) -> Func: ...
    @staticmethod
    def Get(generatorType: str) -> Platform: ...
    @staticmethod
    def Initialize(platform: Platform) -> None: ...
    def Invoke(self, action: Action) -> None: ...
    def LoadAssembly(self, assemblyName: str) -> None: ...
    def Supports(self, type: Type) -> bool: ...
    def ThreadStart(self, ) -> IDisposable: ...

class PlatformExtensionAttribute(Attribute):
    """.NET: Eto.PlatformExtensionAttribute"""
    def __init__(self, *args) -> None: ...
    PlatformID: str
    TypeId: object
    def Register(self, platform: Platform) -> None: ...
    def Supports(self, platform: Platform) -> bool: ...

class PlatformFeatures:
    """.NET: Eto.PlatformFeatures"""
    def __init__(self, *args) -> None: ...
    ...

class Platforms:
    """.NET: Eto.Platforms"""
    def __init__(self, *args) -> None: ...
    ...

class PropertyStore(Dictionary):
    """.NET: Eto.PropertyStore"""
    def __init__(self, *args) -> None: ...
    Parent: object
    Comparer: IEqualityComparer
    Count: int
    Keys: KeyCollection
    Values: ValueCollection
    Item: object
    def AddEvent(self, key: object, value: Delegate) -> None: ...
    def AddHandlerEvent(self, key: str, value: Delegate) -> None: ...
    def Create(self, key: object, create: Func) -> T: ...
    def Get(self, key: object, defaultValue: T) -> T: ...
    def GetCommand(self, key: object) -> ICommand: ...
    def RemoveEvent(self, key: object, value: Delegate) -> None: ...
    def Set(self, key: object, value: T, propertyChanged: PropertyChangedEventHandler, defaultValue: T, propertyName: str) -> bool: ...
    def SetCommand(self, key: object, value: ICommand, setEnabled: Action, addExecute: Action, removeExecute: Action, getParameter: Func) -> None: ...
    def TriggerEvent(self, key: object, sender: object, args: T) -> None: ...
    def TrySet(self, key: object, value: T, defaultValue: T) -> bool: ...
    def UnbindCommand(self, key: object) -> None: ...
    def UpdateCommandCanExecute(self, key: object) -> None: ...

class RuntimeNamePropertyAttribute(Attribute):
    """.NET: Eto.RuntimeNamePropertyAttribute"""
    def __init__(self, *args) -> None: ...
    Name: str
    TypeId: object

class Style:
    """.NET: Eto.Style"""
    def __init__(self, *args) -> None: ...
    Provider: IStyleProvider
    @staticmethod
    def Add(style: str, handler: StyleWidgetHandler) -> None: ...

class StyleHandler:
    """.NET: Eto.StyleHandler`1"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, handler: THandler, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, handler: THandler) -> None: ...

class StyleWidgetHandler:
    """.NET: Eto.StyleWidgetHandler`1"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, widget: TWidget, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, widget: TWidget) -> None: ...

class TypeConverter:
    """.NET: Eto.TypeConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertFromInvariantString(self, context: ITypeDescriptorContext, text: str) -> object: ...
    def ConvertFromString(self, context: ITypeDescriptorContext, culture: CultureInfo, text: str) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...
    def ConvertToInvariantString(self, context: ITypeDescriptorContext, value: object) -> str: ...
    def ConvertToString(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> str: ...
    def IsValid(self, context: ITypeDescriptorContext, value: object) -> bool: ...

class TypeConverterAttribute(Attribute):
    """.NET: Eto.TypeConverterAttribute"""
    def __init__(self, *args) -> None: ...
    ConverterTypeName: str
    TypeId: object

class TypeDescriptor:
    """.NET: Eto.TypeDescriptor"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetConverter(type: Type) -> TypeConverter: ...

class UnhandledExceptionEventArgs(EventArgs):
    """.NET: Eto.UnhandledExceptionEventArgs"""
    def __init__(self, *args) -> None: ...
    ExceptionObject: object
    IsTerminating: bool

class Widget:
    """.NET: Eto.Widget"""
    def __init__(self, *args) -> None: ...
    Platform: Platform
    Handler: object
    NativeHandle: IntPtr
    Properties: PropertyStore
    ID: str
    Style: str
    ControlObject: object
    IsDisposed: bool
    def Dispose(self, ) -> None: ...
    def ToString(self, ) -> str: ...

class WidgetCreatedEventArgs(EventArgs):
    """.NET: Eto.WidgetCreatedEventArgs"""
    def __init__(self, *args) -> None: ...
    Instance: Widget

class WidgetHandler:
    """.NET: Eto.WidgetHandler`1 | Eto.WidgetHandler`2 | Eto.WidgetHandler`3"""
    def __init__(self, *args) -> None: ...
    Widget: TWidget
    ID: str
    NativeHandle: IntPtr
    Control: TControl
    HasControl: bool
    Callback: TCallback
    def AttachEvent(self, id: str) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def GetControl(widget: TWidget) -> TControl: ...
    def HandleEvent(self, id: str, defaultEvent: bool) -> None: ...
    def IsEventHandled(self, id: str) -> bool: ...
