# Auto-generated — Rhino 8 — Eto.IO

class IconSize:
    """.NET: Eto.IO.IconSize"""
    def __init__(self, *args) -> None: ...
    ...

class StaticIconType:
    """.NET: Eto.IO.StaticIconType"""
    def __init__(self, *args) -> None: ...
    ...

class SystemIcons:
    """.NET: Eto.IO.SystemIcons"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetFileIcon(fileName: str, size: IconSize) -> Icon: ...
    @staticmethod
    def GetStaticIcon(type: StaticIconType, size: IconSize) -> Icon: ...
