# Auto-generated — Tekla 2026 — Tekla.Structures

class Assertion:
    """.NET: Tekla.Structures.Assertion"""
    def __init__(self, *args) -> None: ...
    Message: str
    DetailedMessage: str
    MethodName: str
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, ) -> str: ...

class AutoDirectionTypeEnum:
    """.NET: Tekla.Structures.AutoDirectionTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class ClashCheckOptions:
    """.NET: Tekla.Structures.ClashCheckOptions"""
    def __init__(self, *args) -> None: ...
    BoltHeadDiameter: float
    NutThickness: float

class ComponentDefinitionTypeEnum:
    """.NET: Tekla.Structures.ComponentDefinitionTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class ComponentOptions:
    """.NET: Tekla.Structures.ComponentOptions"""
    def __init__(self, *args) -> None: ...
    PlateProfileName: str
    FoldedPlateProfileName: str
    BoltEdgeDistanceFactor: float
    BoltEdgeDistanceReference: BoltEdgeDistanceReferenceEnum
    BoltStandard: str
    BoltSize: str
    PartMaterial: str
    PartWeldedToPrimaryStartNumber: int
    PartWeldedToPrimaryPositionPrefix: str
    PartWeldedToSecondaryStartNumber: int
    PartWeldedToSecondaryPositionPrefix: str
    LoosePartStartNumber: int
    LoosePartPositionPrefix: str
    AssemblyLoosePartStartNumber: int
    AssemblyLoosePartPositionPrefix: str

class ConnectionStatusEnum:
    """.NET: Tekla.Structures.ConnectionStatusEnum"""
    def __init__(self, *args) -> None: ...
    ...

class DetailTypeEnum:
    """.NET: Tekla.Structures.DetailTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class Identifier:
    """.NET: Tekla.Structures.Identifier"""
    def __init__(self, *args) -> None: ...
    ID: int
    ID2: int
    GUID: Guid
    def Equals(self, otherIdentifier: Identifier) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsValid(self, ) -> bool: ...
    def ToString(self, ) -> str: ...

class ModuleManager:
    """.NET: Tekla.Structures.ModuleManager"""
    def __init__(self, *args) -> None: ...
    Configuration: ProgramConfigurationEnum
    MultimaterialModeling: bool
    LoadModeling: bool
    SteelDetailing: bool
    ConcreteDetailing: bool
    RebarModeling: bool
    CIPModeling: bool
    AnalysisAndDesign: bool
    TaskManagement: bool

class PositionTypeEnum:
    """.NET: Tekla.Structures.PositionTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class PropertyTypeEnum:
    """.NET: Tekla.Structures.PropertyTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class TeklaStructuresDatabaseTypeEnum:
    """.NET: Tekla.Structures.TeklaStructuresDatabaseTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class TeklaStructuresFiles:
    """.NET: Tekla.Structures.TeklaStructuresFiles"""
    def __init__(self, *args) -> None: ...
    PropertyFileDirectories: List
    SessionLogFile: FileInfo
    def GetAttributeFile(self, searchDirectories: List, fileName: str) -> FileInfo: ...
    @staticmethod
    def GetFileDictionaryByExtension(fileExtension: str, modelPath: str) -> Dictionary: ...
    def GetMultiDirectoryFileList(self, fileExtension: str, fullpath: bool) -> List: ...
    @staticmethod
    def LocateFile(searchDirectories: List, fileName: str, absoluteFileName: str) -> bool: ...

class TeklaStructuresInfo:
    """.NET: Tekla.Structures.TeklaStructuresInfo"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetBuildNumber() -> str: ...
    @staticmethod
    def GetCommonAppDataFolder() -> str: ...
    @staticmethod
    def GetCopyRightText() -> str: ...
    @staticmethod
    def GetCurrentProgramVersion() -> str: ...
    @staticmethod
    def GetCurrentUser() -> str: ...
    @staticmethod
    def GetFullTSRegistryKeyText() -> str: ...
    @staticmethod
    def GetLocalAppDataFolder() -> str: ...
    @staticmethod
    def GetPluginsFolder() -> str: ...
    @staticmethod
    def GetRevisionDate() -> str: ...

class TeklaStructuresSettings:
    """.NET: Tekla.Structures.TeklaStructuresSettings"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetAdvancedOption(VariableName: str, Value: bool) -> bool: ...
    @staticmethod
    def GetAdvancedOptionPaths(advancedOption: str, paths: List, errorHandler: InvalidPathCallback) -> bool: ...
    @staticmethod
    def GetOptions(Options: ClashCheckOptions) -> bool: ...
    @staticmethod
    def IsPourEnabled() -> bool: ...
    @staticmethod
    def IsToolOptionOn(toolOptionName: str) -> bool: ...
    @staticmethod
    def SetOptions(Options: ClashCheckOptions) -> bool: ...

class TeklaStructuresVariables:
    """.NET: Tekla.Structures.TeklaStructuresVariables"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Add(key: str) -> None: ...
    @staticmethod
    def ContainsVariable(key: str) -> bool: ...
    @staticmethod
    def Get(key: str) -> str: ...
