# Auto-generated — Tekla 2026 — Tekla.Structures.CatalogInternal

class CDelegate(CDelegateWrapper):
    """.NET: Tekla.Structures.CatalogInternal.CDelegate"""
    def __init__(self, *args) -> None: ...
    ...

class CDelegateSetter:
    """.NET: Tekla.Structures.CatalogInternal.CDelegateSetter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def SetInstanceForUnitTesting(cdelegate: ICDelegate) -> None: ...

class CDelegateSynchronized:
    """.NET: Tekla.Structures.CatalogInternal.CDelegateSynchronized"""
    def __init__(self, *args) -> None: ...
    InvokeRequired: bool
    def AddCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def BeginInvoke(self, method: Delegate, args: list) -> IAsyncResult: ...
    def CleanAndModifyShape(self, pInput: dotcatShape_t, cleaningParams: dotcatShapeCleanParams_t, pIsSolid: bool) -> int: ...
    def CleanAndModifyShapeByName(self, name: str, cleaningParams: dotcatShapeCleanParams_t, isSolid: bool) -> int: ...
    def DeleteCrossSection(self, ProfileName: str, CrossSectionNumber: int) -> int: ...
    def DeleteShape(self, pShape: dotcatShape_t) -> int: ...
    def EndInvoke(self, pEnumerator: dotcatProfileItemEnumerator_t, result: IAsyncResult) -> object: ...
    def EnumerateShapes(self, pShapeEnumerator: dotcatShapeEnumerator_t) -> int: ...
    def ExportAddProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportBoltAssemblyToFile(self, pBoltItemExport: dotcatBoltItemExport_t) -> int: ...
    def ExportConvertFabricatorProfilesAndMaterialsToTS(self, FabricatorDataFilePaths: dotcatFabricatorDataFilePaths_t) -> int: ...
    def ExportCopyProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportCreateSavePoint(self, ) -> bool: ...
    def ExportCustomComponentItemToFile(self, pComponentItem: dotcatComponentName_t, ExportFile: str) -> int: ...
    def ExportDeleteMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportDeleteProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserParametricProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportEnumerateBoltLengths(self, Grade: str, Size: float, BoltLengths: List) -> int: ...
    def ExportEnumerateBolts(self, pBoltEnumerator: dotcatBoltItemEnumerator_t) -> int: ...
    def ExportEnumerateComponents(self, pComponentEnumerator: dotcatComponentItemEnumerator_t) -> int: ...
    def ExportEnumerateMaterials(self, pMaterialEnumerator: dotcatMaterialItemEnumerator_t) -> int: ...
    def ExportEnumeratePrinters(self, pPrinterEnumerator: dotcatPrinterItemEnumerator_t) -> int: ...
    def ExportEnumerateProfiles(self, pProfileEnumerator: dotcatProfileItemEnumerator_t) -> int: ...
    def ExportEnumerateUserProperties(self, pUserPropertyEnumerator: dotcatUserPropertyItemEnumerator_t) -> int: ...
    def ExportFinalizeImportProfilesFromFolder(self, pConflicts: List) -> int: ...
    def ExportFinalizeImportProfilesFromFolderWithoutSave(self, pConflicts: List) -> bool: ...
    def ExportFinishList(self, ) -> List: ...
    def ExportGetModelPath(self, Path: str) -> int: ...
    def ExportGetParametricProfilePrefixFromSubtype(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportGetParametricProfileTypeByPrefix(self, pProfilePrefix: str, rProfileType: int) -> int: ...
    def ExportGetProfileCrossSection(self, pCrossSection: dotcatCrossSection_t) -> int: ...
    def ExportGetProfileType(self, pProfileName: str, rProfileType: int) -> int: ...
    def ExportGetTranslatedOptionLabels(self, userPropertyOption2: dotcatUserPropertyOption2_t) -> int: ...
    def ExportImportBoltAssembliesFromFolder(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPath(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPathWithUpdateCheck(self, Path: str, ForcedUpdate: bool) -> int: ...
    def ExportImportLibraryProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportMaterialsFromFolder(self, Path: str) -> int: ...
    def ExportImportMeshesFromFolder(self, Path: str) -> int: ...
    def ExportImportParametricProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportRebarsFromFolder(self, Path: str) -> int: ...
    def ExportInitializeImportProfilesFromFolder(self, item: dotcatImportItem_t, pConflicts: List) -> int: ...
    def ExportInsertMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportInsertUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportMaterialExists(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportMaterialItemToFile(self, pMaterialItem: dotcatMaterialItem_t, ExportFile: str) -> int: ...
    def ExportMaterialNameMaxLength(self, ) -> int: ...
    def ExportMeshToFile(self, pMeshItemExport: dotcatMeshItemExport_t) -> int: ...
    def ExportModifyMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportModifyProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportModifyUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportProfileItemProperties(self, pProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ExportProfileItemToFile(self, pProfileItem: dotcatProfileItem_t, ExportFile: str) -> int: ...
    def ExportProfileItemsToFile(self, profileNames: dotcatProfileNames_t, path: str, fileName: str) -> int: ...
    def ExportProfileTreeToFile(self, pProfileTreePath: dotcatProfileTreePath_t, ExportFile: str) -> int: ...
    def ExportRebarToFile(self, pRebarItemExport: dotcatRebarItemExport_t) -> int: ...
    def ExportRenameProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportRollbackToSavePoint(self, ) -> bool: ...
    def ExportSaveProfileDatabase(self, ) -> int: ...
    def ExportSaveProfileDatabaseNew(self, ) -> int: ...
    def ExportSelectMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportSelectParametricProfileItemByPrefix(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByProfileName(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByTypeAndSubType(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemByTypeAndSubType(self, ProfileItemType: int, ProfileItemSubType: int, CrossSectionNumber: int, rProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemSubTypes(self, pProfileItem: dotcatProfileItem_t, pProfileItemSubTypeEnumerator: dotcatProfileItemSubTypeEnumerator_t) -> int: ...
    def ExportSelectUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportSelectUserPropertyItemObjectTypes(self, pUserPropertyItemObjectTypes: dotcatUserPropertyItemObjectTypes_t) -> int: ...
    def ExportShapeItemToFile(self, pShapeItem: dotcatShape_t, ExportFile: str) -> int: ...
    def ExportUserPropertyItemObjectTypeOperation(self, pUserPropertyItemObjectTypeOperation: dotcatUserPropertyItemObjectTypeOperation_t) -> int: ...
    def GetProfileItemCrossSection(self, ProfileName: str, isParametric: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetProfileItemPropertiesByTypeAndSubType(self, Type: int, SubType: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetShapeByGuid(self, shape: dotcatShape_t, shapeGuid: str) -> int: ...
    def ImportShape(self, pEntry: dotcatShapeImport_t, pShape: dotcatShape_t) -> int: ...
    def InsertShape(self, pInput: dotcatShape_t, pResultShape: dotcatShape_t, AllowGeoDuplicates: bool) -> int: ...
    def Invoke(self, method: Delegate, args: list) -> object: ...
    def ModifyCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def ModifyProfileItemProperties(self, ProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ModifyShape(self, pInput: dotcatShape_t, pResultShape: dotcatShape_t) -> int: ...
    def RenameShape(self, input: dotcatShape_t, Name: str) -> int: ...
    def SelectShape(self, pShape: dotcatShape_t) -> int: ...
    def SetEquivalentType(self, ProfileName: str, CrossSectionNumber: int, EquivalentType: int) -> int: ...
    def ShapeExists(self, GeoHash: str) -> int: ...
    def ShapeExistsByName(self, Name: str) -> int: ...
    def ShapeLocation(self, Name: str) -> int: ...
    @staticmethod
    def dotExportConvertFabricatorProfilesAndMaterialsToTS(FabricatorDataFilePaths: dotcatFabricatorDataFilePaths_t) -> int: ...
    @staticmethod
    def dotcatAddCrossSection(ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    @staticmethod
    def dotcatCleanAndModifyShape(pInput: dotcatShape_t, cleaningParams: dotcatShapeCleanParams_t, pIsSolid: bool) -> int: ...
    @staticmethod
    def dotcatCleanAndModifyShapeByName(name: str, cleaningParam: dotcatShapeCleanParams_t, pIsSolids: bool) -> int: ...
    @staticmethod
    def dotcatDeleteCrossSection(ProfileName: str, CrossSectionNumber: int) -> int: ...
    @staticmethod
    def dotcatDeleteShape(pShape: dotcatShape_t) -> int: ...
    @staticmethod
    def dotcatEnumerateShapes(pShapeEnumerator: dotcatInteropShapeEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportAddProfileItem(pNewName: dotcatProfileName_t, pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportBoltAssemblyToFile(pBoltItemExport: dotcatBoltItemExport_t) -> int: ...
    @staticmethod
    def dotcatExportCopyProfileItem(pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    @staticmethod
    def dotcatExportCreateSavePoint() -> int: ...
    @staticmethod
    def dotcatExportCustomComponentItemToFile(pComponentItem: dotcatComponentName_t, ExportFile: str) -> int: ...
    @staticmethod
    def dotcatExportDeleteMaterialItem(pMaterialItem: dotcatMaterialItem_t) -> int: ...
    @staticmethod
    def dotcatExportDeleteProfileItem(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportDeleteUserParametricProfileItem(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportDeleteUserPropertyItem(pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    @staticmethod
    def dotcatExportEnumerateBoltLengths(pBoltEnumerator: dotcatBoltLengthEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportEnumerateBolts(pBoltEnumerator: dotcatBoltItemEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportEnumerateComponents(pComponentEnumerator: dotcatComponentItemEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportEnumerateMaterials(pMaterialEnumerator: dotcatMaterialItemEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportEnumeratePrinters(pPrinterEnumerator: dotcatPrinterItemEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportEnumerateProfiles(pProfileEnumerator: dotcatProfileItemEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportEnumerateUserProperties(pUserPropertyEnumerator: dotcatUserPropertyItemEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportFinalizeImportProfilesFromFolder(item: dotcatImportItem_t) -> int: ...
    @staticmethod
    def dotcatExportFinalizeImportProfilesFromFolderWithoutSave(item: dotcatImportItem_t) -> int: ...
    @staticmethod
    def dotcatExportGetParametricProfilePrefixFromSubtype(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportGetParametricProfileTypeByPrefix(pProfilePrefix: str, rProfileType: int) -> int: ...
    @staticmethod
    def dotcatExportGetProfileCrossSection(pCrossSection: dotcatCrossSection_t) -> int: ...
    @staticmethod
    def dotcatExportGetProfileType(pProfileName: str, rProfileType: int) -> int: ...
    @staticmethod
    def dotcatExportGetTranslatedOptionLabels(userPropertyOption2: dotcatUserPropertyOption2_t) -> int: ...
    @staticmethod
    def dotcatExportImportBoltAssembliesFromFolder(Path: str) -> int: ...
    @staticmethod
    def dotcatExportImportCustomComponentsFromPath(Path: str) -> int: ...
    @staticmethod
    def dotcatExportImportCustomComponentsFromPathWithUpdateCheck(Path: str, ForcedUpdate: bool) -> int: ...
    @staticmethod
    def dotcatExportImportLibraryProfilesFromFolder(Path: str) -> int: ...
    @staticmethod
    def dotcatExportImportMaterialsFromFolder(Path: str) -> int: ...
    @staticmethod
    def dotcatExportImportMeshesFromFolder(Path: str) -> int: ...
    @staticmethod
    def dotcatExportImportParametricProfilesFromFolder(Path: str) -> int: ...
    @staticmethod
    def dotcatExportImportRebarsFromFolder(Path: str) -> int: ...
    @staticmethod
    def dotcatExportInitializeImportProfilesFromFolder(item: dotcatImportItem_t) -> int: ...
    @staticmethod
    def dotcatExportInsertMaterialItem(materialItem: dotcatMaterialItem_t) -> int: ...
    @staticmethod
    def dotcatExportInsertUserPropertyItem(pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    @staticmethod
    def dotcatExportMaterialExists(pMaterialItem: dotcatMaterialItem_t) -> int: ...
    @staticmethod
    def dotcatExportMaterialItemToFile(pMaterialItem: dotcatMaterialItem_t, ExportFile: str) -> int: ...
    @staticmethod
    def dotcatExportMaterialNameMaxLength() -> int: ...
    @staticmethod
    def dotcatExportMeshToFile(pMeshItemExport: dotcatMeshItemExport_t) -> int: ...
    @staticmethod
    def dotcatExportModifyMaterialItem(materialItem: dotcatMaterialItem_t) -> int: ...
    @staticmethod
    def dotcatExportModifyProfileItem(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportModifyUserPropertyItem(pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    @staticmethod
    def dotcatExportProfileItemProperties(pProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    @staticmethod
    def dotcatExportProfileItemToFile(pProfileItem: dotcatProfileItem_t, ExportFile: str) -> int: ...
    @staticmethod
    def dotcatExportProfileItemsToFile(profileNames: dotcatProfileNames_t, path: str, fileName: str) -> int: ...
    @staticmethod
    def dotcatExportProfileTreeToFile(pProfileTreePath: dotcatProfileTreePath_t, ExportFile: str) -> int: ...
    @staticmethod
    def dotcatExportRebarToFile(pRebarItemExport: dotcatRebarItemExport_t) -> int: ...
    @staticmethod
    def dotcatExportRenameProfileItem(pNewName: dotcatProfileName_t, pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportRollbackToSavePoint() -> int: ...
    @staticmethod
    def dotcatExportSaveProfileDatabase() -> int: ...
    @staticmethod
    def dotcatExportSaveProfileDatabaseNew() -> int: ...
    @staticmethod
    def dotcatExportSelectMaterialItem(pMaterialItem: dotcatMaterialItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectParametricProfileItemByPrefix(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectParametricProfileItemByProfileName(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectParametricProfileItemByTypeAndSubType(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectProfileItem(pProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectProfileItemByTypeAndSubType(ProfileItemType: int, ProfileItemSubType: int, CrossSectionNumber: int, rProfileItem: dotcatProfileItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectProfileItemSubTypes(pProfileItem: dotcatProfileItem_t, pProfileItemSubTypeEnumerator: dotcatProfileItemSubTypeEnumerator_t) -> int: ...
    @staticmethod
    def dotcatExportSelectUserPropertyItem(pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    @staticmethod
    def dotcatExportSelectUserPropertyItemObjectTypes(pUserPropertyItemObjectTypes: dotcatUserPropertyItemObjectTypes_t) -> int: ...
    @staticmethod
    def dotcatExportShapeItemToFile(pShapeItem: dotcatShape_t, ExportFile: str) -> int: ...
    @staticmethod
    def dotcatExportUserPropertyItemObjectTypeOperation(pObjectTypeUserPropertyItemOperation: dotcatUserPropertyItemObjectTypeOperation_t) -> int: ...
    @staticmethod
    def dotcatGetProfileItemCrossSection(ProfileName: str, isParametric: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    @staticmethod
    def dotcatGetProfileItemPropertiesByTypeAndSubType(Type: int, SubType: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    @staticmethod
    def dotcatGetShapeByGuid(shape: dotcatShape_t, shapeGuid: str) -> int: ...
    @staticmethod
    def dotcatImportShape(pEntry: dotcatShapeImport_t, pShape: dotcatShape_t) -> int: ...
    @staticmethod
    def dotcatInsertShape(pInput: dotcatShape_t, pResultShape: dotcatShape_t, AllowGeoDuplicates: bool) -> int: ...
    @staticmethod
    def dotcatModifyCrossSection(ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    @staticmethod
    def dotcatModifyProfileItemProperties(ProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    @staticmethod
    def dotcatModifyShape(pInput: dotcatShape_t, pResultShape: dotcatShape_t) -> int: ...
    @staticmethod
    def dotcatRenameShape(pShape: dotcatShape_t, Name: str) -> int: ...
    @staticmethod
    def dotcatSelectShape(pShape: dotcatShape_t) -> int: ...
    @staticmethod
    def dotcatSetEquivalentType(ProfileName: str, CrossSectionNumber: int, EquivalentType: int) -> int: ...
    @staticmethod
    def dotcatShapeExists(GeoHash: str) -> int: ...
    @staticmethod
    def dotcatShapeExistsByName(Name: str) -> int: ...
    @staticmethod
    def dotcatShapeLocation(Name: str) -> int: ...

class CDelegateWrapper(MarshalByRefObject):
    """.NET: Tekla.Structures.CatalogInternal.CDelegateWrapper"""
    def __init__(self, *args) -> None: ...
    def AddCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def CleanAndModifyShape(self, pInput: dotcatShape_t, cleaningParams: dotcatShapeCleanParams_t, pIsSolid: bool) -> int: ...
    def CleanAndModifyShapeByName(self, name: str, cleaningParams: dotcatShapeCleanParams_t, isSolid: bool) -> int: ...
    def DeleteCrossSection(self, ProfileName: str, CrossSectionNumber: int) -> int: ...
    def DeleteShape(self, pShape: dotcatShape_t) -> int: ...
    def EnumerateShapes(self, pShapeEnumerator: dotcatShapeEnumerator_t) -> int: ...
    def ExportAddProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportBoltAssemblyToFile(self, pBoltItemExport: dotcatBoltItemExport_t) -> int: ...
    def ExportConvertFabricatorProfilesAndMaterialsToTS(self, FabricatorDataFilePaths: dotcatFabricatorDataFilePaths_t) -> int: ...
    def ExportCopyProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportCreateSavePoint(self, ) -> bool: ...
    def ExportCustomComponentItemToFile(self, pComponentItem: dotcatComponentName_t, ExportFile: str) -> int: ...
    def ExportDeleteMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportDeleteProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserParametricProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportEnumerateBoltLengths(self, Grade: str, Size: float, BoltLengths: List) -> int: ...
    def ExportEnumerateBolts(self, pBoltEnumerator: dotcatBoltItemEnumerator_t) -> int: ...
    def ExportEnumerateComponents(self, pComponentEnumerator: dotcatComponentItemEnumerator_t) -> int: ...
    def ExportEnumerateMaterials(self, pMaterialEnumerator: dotcatMaterialItemEnumerator_t) -> int: ...
    def ExportEnumeratePrinters(self, pPrinterEnumerator: dotcatPrinterItemEnumerator_t) -> int: ...
    def ExportEnumerateProfiles(self, pProfileEnumerator: dotcatProfileItemEnumerator_t) -> int: ...
    def ExportEnumerateUserProperties(self, pUserPropertyEnumerator: dotcatUserPropertyItemEnumerator_t) -> int: ...
    def ExportFinalizeImportProfilesFromFolder(self, pConflicts: List) -> int: ...
    def ExportFinalizeImportProfilesFromFolderWithoutSave(self, pConflicts: List) -> bool: ...
    def ExportFinishList(self, ) -> List: ...
    def ExportGetModelPath(self, Path: str) -> int: ...
    def ExportGetParametricProfilePrefixFromSubtype(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportGetParametricProfileTypeByPrefix(self, pProfilePrefix: str, rProfileType: int) -> int: ...
    def ExportGetProfileCrossSection(self, pCrossSection: dotcatCrossSection_t) -> int: ...
    def ExportGetProfileType(self, pProfileName: str, rProfileType: int) -> int: ...
    def ExportGetTranslatedOptionLabels(self, userPropertyOption2: dotcatUserPropertyOption2_t) -> int: ...
    def ExportImportBoltAssembliesFromFolder(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPath(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPathWithUpdateCheck(self, Path: str, ForcedUpdate: bool) -> int: ...
    def ExportImportLibraryProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportMaterialsFromFolder(self, Path: str) -> int: ...
    def ExportImportMeshesFromFolder(self, Path: str) -> int: ...
    def ExportImportParametricProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportRebarsFromFolder(self, Path: str) -> int: ...
    def ExportInitializeImportProfilesFromFolder(self, item: dotcatImportItem_t, pConflicts: List) -> int: ...
    def ExportInsertMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportInsertUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportMaterialExists(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportMaterialItemToFile(self, pMaterialItem: dotcatMaterialItem_t, ExportFile: str) -> int: ...
    def ExportMaterialNameMaxLength(self, ) -> int: ...
    def ExportMeshToFile(self, pMeshItemExport: dotcatMeshItemExport_t) -> int: ...
    def ExportModifyMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportModifyProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportModifyUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportProfileItemProperties(self, pProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ExportProfileItemToFile(self, pProfileItem: dotcatProfileItem_t, ExportFile: str) -> int: ...
    def ExportProfileItemsToFile(self, profileNames: dotcatProfileNames_t, path: str, fileName: str) -> int: ...
    def ExportProfileTreeToFile(self, pProfileTreePath: dotcatProfileTreePath_t, ExportFile: str) -> int: ...
    def ExportRebarToFile(self, pRebarItemExport: dotcatRebarItemExport_t) -> int: ...
    def ExportRenameProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportRollbackToSavePoint(self, ) -> bool: ...
    def ExportSaveProfileDatabase(self, ) -> int: ...
    def ExportSaveProfileDatabaseNew(self, ) -> int: ...
    def ExportSelectMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportSelectParametricProfileItemByPrefix(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByProfileName(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByTypeAndSubType(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemByTypeAndSubType(self, ProfileItemType: int, ProfileItemSubType: int, CrossSectionNumber: int, rProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemSubTypes(self, pProfileItem: dotcatProfileItem_t, pProfileItemSubTypeEnumerator: dotcatProfileItemSubTypeEnumerator_t) -> int: ...
    def ExportSelectUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportSelectUserPropertyItemObjectTypes(self, pUserPropertyItemObjectTypes: dotcatUserPropertyItemObjectTypes_t) -> int: ...
    def ExportShapeItemToFile(self, pShapeItem: dotcatShape_t, ExportFile: str) -> int: ...
    def ExportUserPropertyItemObjectTypeOperation(self, pUserPropertyItemObjectTypeOperation: dotcatUserPropertyItemObjectTypeOperation_t) -> int: ...
    def GetProfileItemCrossSection(self, ProfileName: str, isParametric: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetProfileItemPropertiesByTypeAndSubType(self, Type: int, SubType: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetShapeByGuid(self, shape: dotcatShape_t, shapeGuid: str) -> int: ...
    def ImportShape(self, pEntry: dotcatShapeImport_t, pShape: dotcatShape_t) -> int: ...
    def InsertShape(self, pInput: dotcatShape_t, pResultShape: dotcatShape_t, AllowGeoDuplicates: bool) -> int: ...
    def ModifyCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def ModifyProfileItemProperties(self, ProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ModifyShape(self, pInput: dotcatShape_t, pResultShape: dotcatShape_t) -> int: ...
    def RenameShape(self, input: dotcatShape_t, Name: str) -> int: ...
    def SelectShape(self, pShape: dotcatShape_t) -> int: ...
    def SetEquivalentType(self, ProfileName: str, CrossSectionNumber: int, EquivalentType: int) -> int: ...
    def ShapeExists(self, GeoHash: str) -> int: ...
    def ShapeExistsByName(self, Name: str) -> int: ...
    def ShapeLocation(self, Name: str) -> int: ...

class CatalogInternalOperation:
    """.NET: Tekla.Structures.CatalogInternal.CatalogInternalOperation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddProfileItem(profileItem: ProfileItem, newName: str) -> bool: ...
    @staticmethod
    def CreateSavePoint() -> bool: ...
    @staticmethod
    def DeleteMultiCSProfile(multiCsProfileItem: ParametricProfileItem) -> bool: ...
    @staticmethod
    def DeleteSketchedProfile(sketchedProfileItem: ParametricProfileItem) -> bool: ...
    @staticmethod
    def GetProfileItemCrossSection(profileName: str, isParametric: bool, profileItemCrossSection: ProfileItemCrossSection) -> bool: ...
    @staticmethod
    def GetProfileItemProperties(profileName: str, crossSectionNumber: int, parametersType: ProfileItemParametersTypeEnum, isParametric: bool) -> IList: ...
    @staticmethod
    def GetProfileItemPropertiesByTypeAndSubType(type: int, subType: int, profileItemProperties: List) -> bool: ...
    @staticmethod
    def ImportCustomComponentsFromPathWithUpdateCheck(Path: str, ForcedUpdate: bool) -> bool: ...
    @staticmethod
    def IsValidUnusedProfileName(profileName: str) -> bool: ...
    @staticmethod
    def ModifyProfileItemProperties(profileName: str, crossSectionNumber: int, parametersType: ProfileItemParametersTypeEnum, profileItemParameters: IList) -> bool: ...
    @staticmethod
    def RenameProfileItem(profileItem: ProfileItem, newName: str) -> bool: ...
    @staticmethod
    def RollbackToSavePoint() -> bool: ...
    @staticmethod
    def SaveProfileDatabaseNew() -> bool: ...
    @staticmethod
    def SelectProfileItemByTypeAndSubType(profileItem: ProfileItem, profileItemTypeEnum: ProfileItemTypeEnum, profileItemSubTypeEnum: ProfileItemSubTypeEnum, crossSectionNumber: int) -> bool: ...

class ConflictHandler:
    """.NET: Tekla.Structures.CatalogInternal.ConflictHandler"""
    def __init__(self, *args) -> None: ...
    Conflicts: List
    def dotFinalizeImportProfilesFromFolder(self, ) -> bool: ...
    def dotFinalizeImportProfilesFromFolderWithoutSave(self, ) -> bool: ...
    def dotInitializeImportProfilesFromFolder(self, path: str) -> bool: ...

class ConflictItem:
    """.NET: Tekla.Structures.CatalogInternal.ConflictItem"""
    def __init__(self, *args) -> None: ...
    Identifier: str
    ItemType: str
    State: StateEnum
    Action: ActionEnum

class DelegateFake(GenericDelegateFake):
    """.NET: Tekla.Structures.CatalogInternal.DelegateFake"""
    def __init__(self, *args) -> None: ...
    ...

class DotNetProxy:
    """.NET: Tekla.Structures.CatalogInternal.DotNetProxy"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Run(param: str) -> int: ...

class EventHandler:
    """.NET: Tekla.Structures.CatalogInternal.EventHandler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def OnEvent(param: str) -> int: ...

class GenericDelegateFake:
    """.NET: Tekla.Structures.CatalogInternal.GenericDelegateFake`1"""
    def __init__(self, *args) -> None: ...
    def AddCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def CleanAndModifyShape(self, pInput: dotcatShape_t, cleaningParams: dotcatShapeCleanParams_t, pIsSolid: bool) -> int: ...
    def CleanAndModifyShapeByName(self, name: str, cleaningParams: dotcatShapeCleanParams_t, isSolid: bool) -> int: ...
    def DeleteCrossSection(self, ProfileName: str, CrossSectionNumber: int) -> int: ...
    def DeleteShape(self, vo: dotcatShape_t) -> int: ...
    def EnumerateShapes(self, pShapeEnumerator: dotcatShapeEnumerator_t) -> int: ...
    def ExportAddProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportBoltAssemblyToFile(self, pBoltItemExport: dotcatBoltItemExport_t) -> int: ...
    def ExportConvertFabricatorProfilesAndMaterialsToTS(self, DataFilePaths: dotcatFabricatorDataFilePaths_t) -> int: ...
    def ExportCopyProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportCreateSavePoint(self, ) -> bool: ...
    def ExportCustomComponentItemToFile(self, pComponentItem: dotcatComponentName_t, ExportFile: str) -> int: ...
    def ExportDeleteMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportDeleteProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserParametricProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportEnumerateBoltLengths(self, Grade: str, Size: float, BoltLengths: List) -> int: ...
    def ExportEnumerateBolts(self, pBoltEnumerator: dotcatBoltItemEnumerator_t) -> int: ...
    def ExportEnumerateComponents(self, pComponentEnumerator: dotcatComponentItemEnumerator_t) -> int: ...
    def ExportEnumerateMaterials(self, pMaterialEnumerator: dotcatMaterialItemEnumerator_t) -> int: ...
    def ExportEnumeratePrinters(self, pPrinterEnumerator: dotcatPrinterItemEnumerator_t) -> int: ...
    def ExportEnumerateProfiles(self, pProfileEnumerator: dotcatProfileItemEnumerator_t) -> int: ...
    def ExportEnumerateUserProperties(self, pUserPropertyEnumerator: dotcatUserPropertyItemEnumerator_t) -> int: ...
    def ExportFinalizeImportProfilesFromFolder(self, pConflicts: List) -> int: ...
    def ExportFinalizeImportProfilesFromFolderWithoutSave(self, pConflicts: List) -> bool: ...
    def ExportFinishList(self, ) -> List: ...
    def ExportGetModelPath(self, Path: str) -> int: ...
    def ExportGetParametricProfilePrefixFromSubtype(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportGetParametricProfileTypeByPrefix(self, pProfilePrefix: str, rProfileType: int) -> int: ...
    def ExportGetProfileCrossSection(self, pCrossSection: dotcatCrossSection_t) -> int: ...
    def ExportGetProfileType(self, pProfileName: str, rProfileType: int) -> int: ...
    def ExportGetTranslatedOptionLabels(self, userPropertyOption2: dotcatUserPropertyOption2_t) -> int: ...
    def ExportImportBoltAssembliesFromFolder(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPath(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPathWithUpdateCheck(self, Path: str, ForcedUpdate: bool) -> int: ...
    def ExportImportLibraryProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportMaterialsFromFolder(self, Path: str) -> int: ...
    def ExportImportMeshesFromFolder(self, Path: str) -> int: ...
    def ExportImportParametricProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportRebarsFromFolder(self, Path: str) -> int: ...
    def ExportInitializeImportProfilesFromFolder(self, item: dotcatImportItem_t, pConflicts: List) -> int: ...
    def ExportInsertMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportInsertUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportMaterialExists(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportMaterialItemToFile(self, pMaterialItem: dotcatMaterialItem_t, ExportFile: str) -> int: ...
    def ExportMaterialNameMaxLength(self, ) -> int: ...
    def ExportMeshToFile(self, pMeshItemExport: dotcatMeshItemExport_t) -> int: ...
    def ExportModifyMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportModifyProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportModifyUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportProfileItemProperties(self, pProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ExportProfileItemToFile(self, pProfileItem: dotcatProfileItem_t, ExportFile: str) -> int: ...
    def ExportProfileItemsToFile(self, profileNames: dotcatProfileNames_t, path: str, fileName: str) -> int: ...
    def ExportProfileTreeToFile(self, pProfileTreePath: dotcatProfileTreePath_t, ExportFile: str) -> int: ...
    def ExportRebarToFile(self, pRebarItemExport: dotcatRebarItemExport_t) -> int: ...
    def ExportRenameProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportRollbackToSavePoint(self, ) -> bool: ...
    def ExportSaveProfileDatabase(self, ) -> int: ...
    def ExportSaveProfileDatabaseNew(self, ) -> int: ...
    def ExportSelectMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportSelectParametricProfileItemByPrefix(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByProfileName(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByTypeAndSubType(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemByTypeAndSubType(self, ProfileItemType: int, ProfileItemSubType: int, CrossSectionNumber: int, rProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemSubTypes(self, pProfileItem: dotcatProfileItem_t, pProfileItemSubTypeEnumerator: dotcatProfileItemSubTypeEnumerator_t) -> int: ...
    def ExportSelectUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportSelectUserPropertyItemObjectTypes(self, pUserPropertyItemObjectTypes: dotcatUserPropertyItemObjectTypes_t) -> int: ...
    def ExportShapeItemToFile(self, pShapeItem: dotcatShape_t, ExportFile: str) -> int: ...
    def ExportUserPropertyItemObjectTypeOperation(self, pUserPropertyItemObjectTypeOperation: dotcatUserPropertyItemObjectTypeOperation_t) -> int: ...
    def GetProfileItemCrossSection(self, ProfileName: str, isParemetric: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetProfileItemPropertiesByTypeAndSubType(self, Type: int, SubType: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetShapeByGuid(self, shape: dotcatShape_t, shapeGuid: str) -> int: ...
    def ImportShape(self, entry: dotcatShapeImport_t, shape: dotcatShape_t) -> int: ...
    def InsertShape(self, input: dotcatShape_t, pResultShape: dotcatShape_t, AllowGeoDuplicates: bool) -> int: ...
    def ModifyCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def ModifyProfileItemProperties(self, ProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ModifyShape(self, input: dotcatShape_t, result: dotcatShape_t) -> int: ...
    def RenameShape(self, input: dotcatShape_t, Name: str) -> int: ...
    def SelectShape(self, vo: dotcatShape_t) -> int: ...
    def SetEquivalentType(self, ProfileName: str, CrossSectionNumber: int, EquivalentType: int) -> int: ...
    def ShapeExists(self, geohash: str) -> int: ...
    def ShapeExistsByName(self, name: str) -> int: ...
    def ShapeLocation(self, Name: str) -> int: ...

class ICDelegate:
    """.NET: Tekla.Structures.CatalogInternal.ICDelegate"""
    def __init__(self, *args) -> None: ...
    def AddCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def CleanAndModifyShape(self, pInput: dotcatShape_t, cleaningParams: dotcatShapeCleanParams_t, pIsSolid: bool) -> int: ...
    def CleanAndModifyShapeByName(self, name: str, cleaningParams: dotcatShapeCleanParams_t, isSolid: bool) -> int: ...
    def DeleteCrossSection(self, ProfileName: str, CrossSectionNumber: int) -> int: ...
    def DeleteShape(self, vo: dotcatShape_t) -> int: ...
    def EnumerateShapes(self, pShapeEnumerator: dotcatShapeEnumerator_t) -> int: ...
    def ExportAddProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportBoltAssemblyToFile(self, pBoltItemExport: dotcatBoltItemExport_t) -> int: ...
    def ExportConvertFabricatorProfilesAndMaterialsToTS(self, FabricatorDataFilePaths: dotcatFabricatorDataFilePaths_t) -> int: ...
    def ExportCopyProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportCreateSavePoint(self, ) -> bool: ...
    def ExportCustomComponentItemToFile(self, pComponentItem: dotcatComponentName_t, ExportFile: str) -> int: ...
    def ExportDeleteMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportDeleteProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserParametricProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportDeleteUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportEnumerateBoltLengths(self, Grade: str, Size: float, BoltLengths: List) -> int: ...
    def ExportEnumerateBolts(self, pBoltEnumerator: dotcatBoltItemEnumerator_t) -> int: ...
    def ExportEnumerateComponents(self, pComponentEnumerator: dotcatComponentItemEnumerator_t) -> int: ...
    def ExportEnumerateMaterials(self, pMaterialEnumerator: dotcatMaterialItemEnumerator_t) -> int: ...
    def ExportEnumeratePrinters(self, pPrinterEnumerator: dotcatPrinterItemEnumerator_t) -> int: ...
    def ExportEnumerateProfiles(self, pProfileEnumerator: dotcatProfileItemEnumerator_t) -> int: ...
    def ExportEnumerateUserProperties(self, pUserPropertyEnumerator: dotcatUserPropertyItemEnumerator_t) -> int: ...
    def ExportFinalizeImportProfilesFromFolder(self, pConflicts: List) -> int: ...
    def ExportFinalizeImportProfilesFromFolderWithoutSave(self, pConflicts: List) -> bool: ...
    def ExportFinishList(self, ) -> List: ...
    def ExportGetModelPath(self, Path: str) -> int: ...
    def ExportGetParametricProfilePrefixFromSubtype(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportGetParametricProfileTypeByPrefix(self, pProfilePrefix: str, rProfileType: int) -> int: ...
    def ExportGetProfileCrossSection(self, pCrossSection: dotcatCrossSection_t) -> int: ...
    def ExportGetProfileType(self, pProfileName: str, rProfileType: int) -> int: ...
    def ExportGetTranslatedOptionLabels(self, userPropertyOption2: dotcatUserPropertyOption2_t) -> int: ...
    def ExportImportBoltAssembliesFromFolder(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPath(self, Path: str) -> int: ...
    def ExportImportCustomComponentsFromPathWithUpdateCheck(self, Path: str, ForcedUpdate: bool) -> int: ...
    def ExportImportLibraryProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportMaterialsFromFolder(self, Path: str) -> int: ...
    def ExportImportMeshesFromFolder(self, Path: str) -> int: ...
    def ExportImportParametricProfilesFromFolder(self, Path: str) -> int: ...
    def ExportImportRebarsFromFolder(self, Path: str) -> int: ...
    def ExportInitializeImportProfilesFromFolder(self, item: dotcatImportItem_t, pConflicts: List) -> int: ...
    def ExportInsertMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportInsertUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportMaterialExists(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportMaterialItemToFile(self, pMaterialItem: dotcatMaterialItem_t, ExportFile: str) -> int: ...
    def ExportMaterialNameMaxLength(self, ) -> int: ...
    def ExportMeshToFile(self, pMeshItemExport: dotcatMeshItemExport_t) -> int: ...
    def ExportModifyMaterialItem(self, materialItem: dotcatMaterialItem_t) -> int: ...
    def ExportModifyProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportModifyUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportProfileItemProperties(self, pProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ExportProfileItemToFile(self, pProfileItem: dotcatProfileItem_t, ExportFile: str) -> int: ...
    def ExportProfileItemsToFile(self, profileNames: dotcatProfileNames_t, path: str, fileName: str) -> int: ...
    def ExportProfileTreeToFile(self, pProfileTreePath: dotcatProfileTreePath_t, ExportFile: str) -> int: ...
    def ExportRebarToFile(self, pRebarItemExport: dotcatRebarItemExport_t) -> int: ...
    def ExportRenameProfileItem(self, pProfileItem: dotcatProfileItem_t, pNewName: dotcatProfileName_t) -> int: ...
    def ExportRollbackToSavePoint(self, ) -> bool: ...
    def ExportSaveProfileDatabase(self, ) -> int: ...
    def ExportSaveProfileDatabaseNew(self, ) -> int: ...
    def ExportSelectMaterialItem(self, pMaterialItem: dotcatMaterialItem_t) -> int: ...
    def ExportSelectParametricProfileItemByPrefix(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByProfileName(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectParametricProfileItemByTypeAndSubType(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItem(self, pProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemByTypeAndSubType(self, ProfileItemType: int, ProfileItemSubType: int, CrossSectionNumber: int, rProfileItem: dotcatProfileItem_t) -> int: ...
    def ExportSelectProfileItemSubTypes(self, pProfileItem: dotcatProfileItem_t, pProfileItemSubTypeEnumerator: dotcatProfileItemSubTypeEnumerator_t) -> int: ...
    def ExportSelectUserPropertyItem(self, pUserPropertyItem: dotcatUserPropertyItem_t) -> int: ...
    def ExportSelectUserPropertyItemObjectTypes(self, pUserPropertyItemObjectTypes: dotcatUserPropertyItemObjectTypes_t) -> int: ...
    def ExportShapeItemToFile(self, pShapeItem: dotcatShape_t, ExportFile: str) -> int: ...
    def ExportUserPropertyItemObjectTypeOperation(self, pUserPropertyItemObjectTypeOperation: dotcatUserPropertyItemObjectTypeOperation_t) -> int: ...
    def GetProfileItemCrossSection(self, ProfileName: str, isParametric: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetProfileItemPropertiesByTypeAndSubType(self, Type: int, SubType: int, CrossSection: dotcatProfileItemCrossSection_t) -> int: ...
    def GetShapeByGuid(self, shape: dotcatShape_t, shapeGuid: str) -> int: ...
    def ImportShape(self, entry: dotcatShapeImport_t, shape: dotcatShape_t) -> int: ...
    def InsertShape(self, input: dotcatShape_t, pResultShape: dotcatShape_t, AllowGeoDuplicates: bool) -> int: ...
    def ModifyCrossSection(self, ProfileName: str, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> int: ...
    def ModifyProfileItemProperties(self, ProfileItemProperties: dotcatProfileItemPropertiesEnumerator_s) -> int: ...
    def ModifyShape(self, input: dotcatShape_t, result: dotcatShape_t) -> int: ...
    def RenameShape(self, input: dotcatShape_t, Name: str) -> int: ...
    def SelectShape(self, vo: dotcatShape_t) -> int: ...
    def SetEquivalentType(self, ProfileName: str, CrossSectionNumber: int, EquivalentType: int) -> int: ...
    def ShapeExists(self, geohash: str) -> int: ...
    def ShapeExistsByName(self, Name: str) -> int: ...
    def ShapeLocation(self, Name: str) -> int: ...

class ImportEntry:
    """.NET: Tekla.Structures.CatalogInternal.ImportEntry"""
    def __init__(self, *args) -> None: ...
    FolderPath: str
    EntryFileName: str
    CoordinateSystem: CoordinateSystem
    Overwrite: bool
    CreateCustomPart: bool
    ScalingFactor: float

class ImportFromArchive(ImportEntry):
    """.NET: Tekla.Structures.CatalogInternal.ImportFromArchive"""
    def __init__(self, *args) -> None: ...
    FolderPath: str
    EntryFileName: str
    CoordinateSystem: CoordinateSystem
    Overwrite: bool
    CreateCustomPart: bool
    ScalingFactor: float

class ImportFromGeometry(ImportEntry):
    """.NET: Tekla.Structures.CatalogInternal.ImportFromGeometry"""
    def __init__(self, *args) -> None: ...
    GeometryIdentifier: str
    ShapeName: str
    CreateCustomPart: bool
    FolderPath: str
    EntryFileName: str
    CoordinateSystem: CoordinateSystem
    Overwrite: bool
    ScalingFactor: float

class ImportFromMetadata(ImportEntry):
    """.NET: Tekla.Structures.CatalogInternal.ImportFromMetadata"""
    def __init__(self, *args) -> None: ...
    FolderPath: str
    EntryFileName: str
    CoordinateSystem: CoordinateSystem
    Overwrite: bool
    CreateCustomPart: bool
    ScalingFactor: float
    def GetSchema(self, ) -> str: ...

class ImportResult:
    """.NET: Tekla.Structures.CatalogInternal.ImportResult"""
    def __init__(self, *args) -> None: ...
    ...

class MeshItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.MeshItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class RebarHandler:
    """.NET: Tekla.Structures.CatalogInternal.RebarHandler"""
    def __init__(self, *args) -> None: ...
    Instance: RebarHandler
    @staticmethod
    def ApplyNewRebarSize(grade: str, oldSize: str, newSize: str, radiuses: ArrayList, startHook: RebarHookData, endHook: RebarHookData) -> bool: ...
    def GetAvailableDiameters(self, rebar: Reinforcement) -> IList: ...
    def GetAvailableRadiuses(self, rebar: Reinforcement) -> IList: ...
    @staticmethod
    def GetCatalogItem(grade: str, size: str, radius: float) -> RebarItem: ...
    def GetMeshItems(self, ) -> IEnumerable: ...
    @staticmethod
    def GetOverhangRight(totalDistance: float, unitDistance: float) -> float: ...
    @staticmethod
    def GetRebarItemsFromFile(FilePath: str) -> List: ...
    @staticmethod
    def SetMeshSizeAndOverhangs(item: MeshItem) -> None: ...

class RebarItemComparer:
    """.NET: Tekla.Structures.CatalogInternal.RebarItemComparer"""
    def __init__(self, *args) -> None: ...
    def Equals(self, rebarItem1: RebarItem, rebarItem2: RebarItem) -> bool: ...
    def GetHashCode(self, obj: RebarItem) -> int: ...

class RebarItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.RebarItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class Remoter:
    """.NET: Tekla.Structures.CatalogInternal.Remoter"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def DisposeService() -> None: ...
    @staticmethod
    def InitializeSandBox() -> bool: ...

class ShapeHandler:
    """.NET: Tekla.Structures.CatalogInternal.ShapeHandler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddMetadataKeyVal(guid: str, key: str, value: ShapeMetadata) -> bool: ...
    @staticmethod
    def AppendMetadata(guid: str, keyValPairs: IList) -> bool: ...
    @staticmethod
    def CleanAndModifyByName(name: str, cleaningParams: dotcatShapeCleanParams_t, isSolid: bool) -> bool: ...
    @staticmethod
    def CountShapeInstances() -> Dictionary: ...
    @staticmethod
    def DeleteMetadata(guid: str, metadataKey: str) -> bool: ...
    @staticmethod
    def ExistsByBrep(brep: FacetedBrep) -> bool: ...
    @staticmethod
    def ExistsByFingerprint(fingerprint: str) -> bool: ...
    @staticmethod
    def ExistsByName(Name: str) -> bool: ...
    @staticmethod
    def GetAllMetadataKeys(guid: str) -> List: ...
    @staticmethod
    def GetAllShapeMetadata(guid: str) -> List: ...
    @staticmethod
    def GetHandlePoints(guid: str) -> IList: ...
    @staticmethod
    def GetMetadata(guid: str, key: str) -> ShapeMetadata: ...
    @staticmethod
    def GetShapeByGuid(shapeGuid: str) -> ShapeItem: ...
    @staticmethod
    def GetShapeLocation(shapeName: str) -> ShapeLocation: ...
    @staticmethod
    def GetShapesWithMatchingGeometryFingerprint(fingerprintToFind: str) -> List: ...
    @staticmethod
    def Import(entry: ImportEntry) -> ShapeItem: ...
    @staticmethod
    def ImportOrGet(entry: ImportEntry) -> ShapeItem: ...
    @staticmethod
    def InsertShapeAllowGeometricDuplicates(inputShape: ShapeItem) -> bool: ...
    @staticmethod
    def TryImport(entry: ImportEntry, shapeItem: ShapeItem) -> ImportResult: ...
    @staticmethod
    def UpdateMetadataKeyVal(guid: str, key: str, newValue: ShapeMetadata) -> bool: ...

class ShapeLocation:
    """.NET: Tekla.Structures.CatalogInternal.ShapeLocation"""
    def __init__(self, *args) -> None: ...
    ...

class ShapeMetadata:
    """.NET: Tekla.Structures.CatalogInternal.ShapeMetadata"""
    def __init__(self, *args) -> None: ...
    Value: object
    Type: ShapeMetadataTypeEnum
    Label: str
    Description: str
    @staticmethod
    def ConvertStringListToShapeMetadata(metadataAsStringList: List) -> ShapeMetadata: ...
    @staticmethod
    def ConvertStringMatadataToShapeMetadata(metadatasStringList: List) -> List: ...
    def ConvertToStringList(self, ) -> List: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...

class dotCrossSectionPoint_t:
    """.NET: Tekla.Structures.CatalogInternal.dotCrossSectionPoint_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotExtrema_t:
    """.NET: Tekla.Structures.CatalogInternal.dotExtrema_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, boundingBox: AABB) -> None: ...
    def ToStruct(self, boundingBox: AABB) -> None: ...

class dotcatBoltItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatBoltItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatBoltItemExport_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatBoltItemExport_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatBoltLengthEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatBoltLengthEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatBoltName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatBoltName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatClientId_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatClientId_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatComponentDescription_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatComponentDescription_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatComponentItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatComponentItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatComponentName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatComponentName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatConflictItem_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatConflictItem_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatCrossSection_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatCrossSection_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatFabricatorDataFilePaths_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatFabricatorDataFilePaths_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatFingerprint_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatFingerprint_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatGeometryHash_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatGeometryHash_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatGuid_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatGuid_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatImportItem_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatImportItem_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatInteropShapeEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatInteropShapeEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatMaterialItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatMaterialItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatMaterialItem_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatMaterialItem_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatMaterialName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatMaterialName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatMeshItemExport_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatMeshItemExport_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatPrinterDevice_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatPrinterDevice_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatPrinterExtension_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatPrinterExtension_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatPrinterItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatPrinterItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatPrinterName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatPrinterName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemCrossSection_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemCrossSection_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemParameter_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemParameter_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemPropertiesEnumerator_s:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemPropertiesEnumerator_s"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemSubTypeBitmap_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemSubTypeBitmap_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemSubTypeEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemSubTypeEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemSubTypeLabel_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemSubTypeLabel_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItemSubTypeParameterString_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItemSubTypeParameterString_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileItem_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileItem_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileNames_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileNames_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatProfileTreePath_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatProfileTreePath_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatRebarItemExport_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatRebarItemExport_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatShapeCleanParams_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatShapeCleanParams_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatShapeEnumData_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatShapeEnumData_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatShapeEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatShapeEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatShapeImport_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatShapeImport_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatShapeName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatShapeName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatShape_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatShape_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyItemEnumerator_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyItemEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyItemObjectTypeOperation_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyItemObjectTypeOperation_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyItemObjectTypes_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyItemObjectTypes_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyItem_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyItem_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyName_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyOption2_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyOption2_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotcatUserPropertyOption_t:
    """.NET: Tekla.Structures.CatalogInternal.dotcatUserPropertyOption_t"""
    def __init__(self, *args) -> None: ...
    ...
