# Auto-generated — Tekla 2026 — Tekla.Structures.Catalogs

class AttributeConfiguration:
    """.NET: Tekla.Structures.Catalogs.AttributeConfiguration"""
    def __init__(self, *args) -> None: ...
    ...

class BoltItem:
    """.NET: Tekla.Structures.Catalogs.BoltItem"""
    def __init__(self, *args) -> None: ...
    Standard: str
    Type: BoltItemTypeEnum
    Size: float
    Lengths: List
    def ExportBoltStandard(self, filename: str) -> bool: ...

class BoltItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.BoltItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: BoltItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class BoltName:
    """.NET: Tekla.Structures.Catalogs.BoltName"""
    def __init__(self, *args) -> None: ...
    Name: str

class BrepType:
    """.NET: Tekla.Structures.Catalogs.BrepType"""
    def __init__(self, *args) -> None: ...
    ...

class CatalogHandler:
    """.NET: Tekla.Structures.Catalogs.CatalogHandler"""
    def __init__(self, *args) -> None: ...
    def ExportProfileItems(self, profileNames: IList, path: str, fileName: str) -> bool: ...
    def GetBoltItems(self, ) -> BoltItemEnumerator: ...
    def GetComponentItems(self, ) -> ComponentItemEnumerator: ...
    def GetConnectionStatus(self, ) -> bool: ...
    def GetDrawingItems(self, ) -> DrawingItemEnumerator: ...
    def GetLibraryProfileItems(self, ) -> ProfileItemEnumerator: ...
    def GetMaterialItems(self, ) -> MaterialItemEnumerator: ...
    def GetMaterialMarketSizes(self, ) -> MaterialMarketSizesItemEnumerator: ...
    def GetMeshItems(self, ) -> MeshItemEnumerator: ...
    def GetParametricProfileItems(self, ) -> ProfileItemEnumerator: ...
    def GetPrinterItems(self, ) -> PrinterItemEnumerator: ...
    def GetProfileItems(self, ) -> ProfileItemEnumerator: ...
    def GetRebarItems(self, ) -> RebarItemEnumerator: ...
    def GetShapeItems(self, ) -> ShapeItemEnumerator: ...
    @staticmethod
    def GetSteelFinishItems() -> IEnumerable: ...
    def GetUserPropertyItems(self, objectType: CatalogObjectTypeEnum) -> UserPropertyItemEnumerator: ...
    def ImportBoltItems(self, path: str) -> bool: ...
    def ImportCustomComponentItems(self, path: str) -> bool: ...
    def ImportDrawingItems(self, path: str) -> bool: ...
    def ImportLibraryProfileItems(self, path: str) -> bool: ...
    def ImportMaterialItems(self, path: str) -> bool: ...
    def ImportMeshItems(self, path: str) -> bool: ...
    def ImportParametricProfileItems(self, path: str) -> bool: ...
    def ImportRebarItems(self, path: str) -> bool: ...
    def ImportShapeItems(self, path: str) -> bool: ...
    def ImportShapeItemsFromGeometryFiles(self, path: str) -> bool: ...
    def SaveProfileDatabase(self, ) -> bool: ...

class CatalogItemEnumeratorInitializationException(Exception):
    """.NET: Tekla.Structures.Catalogs.CatalogItemEnumeratorInitializationException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CatalogObjectTypeEnum:
    """.NET: Tekla.Structures.Catalogs.CatalogObjectTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class ComponentItem:
    """.NET: Tekla.Structures.Catalogs.ComponentItem"""
    def __init__(self, *args) -> None: ...
    UIName: str
    Name: str
    Type: ComponentTypeEnum
    Number: int
    AttributeFileExtension: str
    def Export(self, filename: str) -> bool: ...
    def GetVersion(self, version: int) -> bool: ...
    def Select(self, name: str, number: int, type: ComponentTypeEnum) -> bool: ...

class ComponentItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.ComponentItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: ComponentItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class CrossSection:
    """.NET: Tekla.Structures.Catalogs.CrossSection"""
    def __init__(self, *args) -> None: ...
    Profile: ProfileName
    Location: float
    Length: float
    HighAccuracy: bool
    OuterSurface: List
    OuterSurfacePoints: List
    InnerSurfaces: List
    InnerSurfacePoints: List
    def GetInnerContours(self, ) -> List: ...
    def GetOuterContour(self, ) -> Polycurve: ...
    def Select(self, HighAccuracy: bool, Location: float, Length: float) -> bool: ...

class CrossSectionPoint(Point):
    """.NET: Tekla.Structures.Catalogs.CrossSectionPoint"""
    def __init__(self, *args) -> None: ...
    Chamfer: Chamfer

class DrawingItem:
    """.NET: Tekla.Structures.Catalogs.DrawingItem"""
    def __init__(self, *args) -> None: ...
    Name: str
    Files: List
    Type: DrawingTypes
    def Export(self, filename: str) -> bool: ...
    def Select(self, Name: str) -> bool: ...

class DrawingItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.DrawingItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: DrawingItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class FabricatorProfilesAndMaterials:
    """.NET: Tekla.Structures.Catalogs.FabricatorProfilesAndMaterials"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ConvertSourceFile(profilesFilePath: str, dimensionsFilePath: str) -> bool: ...

class FinishItem:
    """.NET: Tekla.Structures.Catalogs.FinishItem"""
    def __init__(self, *args) -> None: ...
    Abbreviation: str
    Description: str
    def ToString(self, ) -> str: ...

class LibraryProfileItem(ProfileItem):
    """.NET: Tekla.Structures.Catalogs.LibraryProfileItem"""
    def __init__(self, *args) -> None: ...
    aProfileItemAnalysisParameters: ArrayList
    aProfileItemUserParameters: ArrayList
    ProfileName: str
    ProfileItemType: ProfileItemTypeEnum
    ProfileItemSubType: ProfileItemSubTypeEnum
    aProfileItemParameters: ArrayList
    ParameterString: str
    NumberOfCrossSections: int
    aProfileItemCrossSections: ArrayList
    ProfileItemCrossSections: IList
    IsSketchedUserParametric: bool
    IsCLBProfile: bool
    IsHardcodedProfile: bool
    IsMultiCrossSectionUserParametric: bool
    def Copy(self, newName: str) -> bool: ...
    def Delete(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, profileName: str) -> bool: ...

class MaterialItem:
    """.NET: Tekla.Structures.Catalogs.MaterialItem"""
    def __init__(self, *args) -> None: ...
    MaterialName: str
    AliasName1: str
    AliasName2: str
    AliasName3: str
    Type: MaterialItemTypeEnum
    ProfileDensity: float
    PlateDensity: float
    ModulusOfElasticity: float
    PoissonsRatio: float
    ThermalDilatation: float
    DesignCode: int
    def Delete(self, ) -> bool: ...
    def Export(self, filename: str) -> bool: ...
    def Insert(self, ) -> bool: ...
    @staticmethod
    def MaterialNameMaxLength() -> int: ...
    def Modify(self, ) -> bool: ...
    def Select(self, materialName: str) -> bool: ...

class MaterialItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.MaterialItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: MaterialItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class MaterialMarketSizesItem:
    """.NET: Tekla.Structures.Catalogs.MaterialMarketSizesItem"""
    def __init__(self, *args) -> None: ...
    MaterialName: str
    MarketSizes: list

class MaterialMarketSizesItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.MaterialMarketSizesItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: MaterialMarketSizesItem
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class MaterialName:
    """.NET: Tekla.Structures.Catalogs.MaterialName"""
    def __init__(self, *args) -> None: ...
    Name: str

class MeshItem:
    """.NET: Tekla.Structures.Catalogs.MeshItem"""
    def __init__(self, *args) -> None: ...
    Grade: str
    Name: str
    DiameterLongitudinal: str
    DistanceLongitudinal: str
    Length: float
    MinimumOverlappingLongitudinal: float
    MaximumOverlappingLongitudinal: float
    LeftOverhangLongitudinal: float
    RightOverhangLongitudinal: float
    DiameterCross: str
    DistanceCross: str
    Width: float
    MinimumOverlappingCross: float
    MaximumOverlappingCross: float
    LeftOverhangCross: float
    RightOverhangCross: float
    def Export(self, filename: str) -> bool: ...
    def Select(self, MeshName: str, MeshGrade: str) -> bool: ...

class MeshItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.MeshItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: MeshItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...
    @staticmethod
    def SelectMeshItem(Name: str, Grade: str) -> MeshItem: ...

class ParametricProfileItem(ProfileItem):
    """.NET: Tekla.Structures.Catalogs.ParametricProfileItem"""
    def __init__(self, *args) -> None: ...
    ProfilePrefix: str
    ProfileItemType: ProfileItemTypeEnum
    ProfileItemSubType: ProfileItemSubTypeEnum
    aProfileItemParameters: ArrayList
    ParameterString: str
    NumberOfCrossSections: int
    aProfileItemCrossSections: ArrayList
    ProfileItemCrossSections: IList
    IsSketchedUserParametric: bool
    IsCLBProfile: bool
    IsHardcodedProfile: bool
    IsMultiCrossSectionUserParametric: bool
    def CreateProfileString(self, ) -> str: ...
    @staticmethod
    def GetParametricProfilePrefix(Subtype: int) -> str: ...
    def Select(self, ProfileName: str) -> bool: ...
    def SelectByPrefix(self, ProfilePrefix: str) -> bool: ...
    def SelectByProfileName(self, ProfileName: str) -> bool: ...
    def SelectByTypeAndSubtype(self, profileName: str, type: ProfileItemTypeEnum, subtype: ProfileItemSubTypeEnum) -> bool: ...

class PrinterItem:
    """.NET: Tekla.Structures.Catalogs.PrinterItem"""
    def __init__(self, *args) -> None: ...
    Name: str
    Device: str
    Extension: str
    PrintAreaWidth: float
    PrintAreaHeigth: float

class PrinterItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.PrinterItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: PrinterItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class ProfileItem:
    """.NET: Tekla.Structures.Catalogs.ProfileItem"""
    def __init__(self, *args) -> None: ...
    ProfileItemType: ProfileItemTypeEnum
    ProfileItemSubType: ProfileItemSubTypeEnum
    aProfileItemParameters: ArrayList
    ParameterString: str
    NumberOfCrossSections: int
    aProfileItemCrossSections: ArrayList
    ProfileItemCrossSections: IList
    IsSketchedUserParametric: bool
    IsCLBProfile: bool
    IsHardcodedProfile: bool
    IsMultiCrossSectionUserParametric: bool
    def AddCrossSection(self, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> bool: ...
    def DeleteCrossSection(self, CrossSectionNumber: int) -> bool: ...
    def Export(self, filename: str) -> bool: ...
    def GetCrossSection(self, RelativeLocation: float) -> CrossSection: ...
    def GetHighAccuracyCrossSection(self, RelativeLocation: float) -> CrossSection: ...
    @staticmethod
    def GetProfileItemSubTypes(profileItem: ProfileItem, typeEnum: ProfileItemTypeEnum) -> List: ...
    def IsProfileUserDefined(self, ) -> bool: ...
    def IsProfileUserParametric(self, ) -> bool: ...
    def ModifyCrossSection(self, CrossSectionNumber: int, Location: float, Type: int, SubType: int) -> bool: ...
    def ModifyProfileItemAnalysisParameter(self, value: ProfileItemParameter) -> bool: ...
    def ModifyProfileItemParameter(self, value: ProfileItemParameter) -> bool: ...
    def ModifyProfileItemUserParameter(self, value: ProfileItemParameter) -> bool: ...
    def Select(self, ) -> bool: ...
    def SelectCrossSections(self, ) -> bool: ...
    def SetEquivalentType(self, CrossSectionNumber: int, EquivalentType: int) -> bool: ...

class ProfileItemCrossSection:
    """.NET: Tekla.Structures.Catalogs.ProfileItemCrossSection"""
    def __init__(self, *args) -> None: ...
    CrossSectionNumber: int
    Number: int
    CrossSectionLocation: float
    Location: float
    ProfileType: int
    ProfileSubType: int
    EquivalentType: int
    NumberOfProfileItemParameters: int
    ProfileItemParameters: IList
    NumberOfProfileItemAnalysisParameters: int
    ProfileItemAnalysisParameters: IList
    NumberOfProfileItemUserParameters: int
    ProfileItemUserParameters: IList
    def AddProfileItemAnalysisParamter(self, property: str, alblString: str, symbol: str, value: object, ParameterUnitType: ParameterUnitTypeEnum, crossSectionNumber: int) -> None: ...
    def AddProfileItemParamter(self, property: str, alblString: str, symbol: str, value: object, ParameterUnitType: ParameterUnitTypeEnum, crossSectionNumber: int) -> None: ...
    def AddProfileItemUserParamter(self, property: str, alblString: str, symbol: str, value: object, ParameterUnitType: ParameterUnitTypeEnum, crossSectionNumber: int) -> None: ...

class ProfileItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.ProfileItemEnumerator"""
    def __init__(self, *args) -> None: ...
    SelectInstances: bool
    Current: ProfileItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class ProfileItemParameter:
    """.NET: Tekla.Structures.Catalogs.ProfileItemParameter"""
    def __init__(self, *args) -> None: ...
    Property: str
    AlblString: str
    Value: float
    IntegerValue: int
    StringValue: str
    Symbol: str
    ParameterUnitType: ParameterUnitTypeEnum
    CrossSectionNumber: int

class ProfileItemSubType:
    """.NET: Tekla.Structures.Catalogs.ProfileItemSubType"""
    def __init__(self, *args) -> None: ...
    SubTypeId: ProfileItemSubTypeEnum
    Label: str
    ParameterString: str
    BitmapName: str

class ProfileName:
    """.NET: Tekla.Structures.Catalogs.ProfileName"""
    def __init__(self, *args) -> None: ...
    Name: str

class RebarHeaderItem:
    """.NET: Tekla.Structures.Catalogs.RebarHeaderItem"""
    def __init__(self, *args) -> None: ...
    PropertyName: str
    Name: str
    Type: str
    Units: str

class RebarItem:
    """.NET: Tekla.Structures.Catalogs.RebarItem"""
    def __init__(self, *args) -> None: ...
    Grade: str
    Size: str
    Usage: str
    BendRadius: float
    Code: str
    NominalDiameter: float
    ActualDiameter: float
    WeightPerLenght: float
    CrossSectionArea: float
    HookRadius90Degrees: float
    HookLength90Degrees: float
    HookRadius135Degrees: float
    HookLength135Degrees: float
    HookRadius180Degrees: float
    HookLength180Degrees: float
    LapLength: float
    CrankStraightLength: float
    CrankedLengthType: str
    CrankedLength: float
    CrankExtraOffset: float
    ExtraPointShortening: float
    CurveTolerance: float
    MaxRadiusRequiringBending: float
    def Delete(self, ) -> bool: ...
    def Export(self, filename: str) -> bool: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, OriginalGrade: str, OriginalSize: str, OriginalUsage: str) -> bool: ...
    def Select(self, Grade: str, Diameter: float, BendRadius: float, UseNominalDiameter: bool) -> bool: ...

class RebarItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.RebarItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: RebarItem
    @staticmethod
    def DeleteRebarItem(rebarItem: RebarItem) -> bool: ...
    @staticmethod
    def GetRebarHeaderItems() -> List: ...
    def GetSize(self, ) -> int: ...
    @staticmethod
    def InsertRebarItem(rebarItem: RebarItem) -> bool: ...
    @staticmethod
    def ModifyRebarItem(rebarItem: RebarItem, originalRebarItem: RebarItem) -> bool: ...
    def MoveNext(self, ) -> bool: ...
    @staticmethod
    def RebarItemExists(rebarItem: RebarItem) -> bool: ...
    def Reset(self, ) -> None: ...
    @staticmethod
    def SelectRebarItem(Grade: str, Size: str, Usage: str, Code: str) -> RebarItem: ...

class ShapeItem:
    """.NET: Tekla.Structures.Catalogs.ShapeItem"""
    def __init__(self, *args) -> None: ...
    Name: str
    Guid: str
    GeometryGuid: str
    GeometryHash: str
    Extrema: AABB
    IsSolid: bool
    ShapeFacetedBrep: FacetedBrep
    UpAxis: ShapeUpAxis
    Fingerprint: str
    BrepType: BrepType
    HandlePoints: List
    def CleanAndModify(self, isSolid: bool) -> bool: ...
    def Delete(self, ) -> bool: ...
    def DeleteMetadata(self, key: str) -> bool: ...
    def Export(self, filename: str) -> bool: ...
    def GetAllMetadataKeys(self, ) -> List: ...
    def GetInstanceCount(self, ) -> int: ...
    def GetMetadata(self, key: str, type: ShapeMetadataTypeEnum, value: object, label: str, description: str) -> bool: ...
    def Insert(self, ) -> bool: ...
    def InsertOrGetGuidsOfShapesWithMatchingGeometry(self, existingShapeGuids: List) -> bool: ...
    def InsertUsingNormals(self, ) -> bool: ...
    def InsertUsingNormalsAllowDuplicates(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Rename(self, newName: str) -> bool: ...
    def Select(self, name: str) -> bool: ...
    def SetHandlePoints(self, HandlePoints: List) -> bool: ...
    def SetMetadata(self, key: str, type: ShapeMetadataTypeEnum, value: object, label: str, description: str) -> bool: ...

class ShapeItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.ShapeItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: ShapeItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class ShapeMetadataTypeEnum:
    """.NET: Tekla.Structures.Catalogs.ShapeMetadataTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class ShapeUpAxis:
    """.NET: Tekla.Structures.Catalogs.ShapeUpAxis"""
    def __init__(self, *args) -> None: ...
    ...

class UserPropertyFieldTypeEnum:
    """.NET: Tekla.Structures.Catalogs.UserPropertyFieldTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class UserPropertyItem:
    """.NET: Tekla.Structures.Catalogs.UserPropertyItem"""
    def __init__(self, *args) -> None: ...
    Name: str
    Type: PropertyTypeEnum
    FieldType: UserPropertyFieldTypeEnum
    Level: UserPropertyLevelEnum
    AffectsNumbering: bool
    Unique: bool
    Visibility: UserPropertyVisibilityEnum
    def AddToObjectType(self, objectType: CatalogObjectTypeEnum) -> bool: ...
    def Delete(self, ) -> bool: ...
    def GetDefaultValue(self, DefaultValue: int) -> bool: ...
    def GetLabel(self, translated: bool) -> str: ...
    def GetObjectTypes(self, objectTypes: List) -> bool: ...
    def GetOptions(self, IntOptions: List, translatedLabels: bool) -> bool: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def RemoveFromObjectType(self, objectType: CatalogObjectTypeEnum) -> bool: ...
    def Select(self, ) -> bool: ...
    def SetDefaultValue(self, DefaultValue: int) -> bool: ...
    def SetLabel(self, label: str) -> None: ...
    def SetOptions(self, IntOptions: List) -> bool: ...

class UserPropertyItemEnumerator:
    """.NET: Tekla.Structures.Catalogs.UserPropertyItemEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: UserPropertyItem
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class UserPropertyLevelEnum:
    """.NET: Tekla.Structures.Catalogs.UserPropertyLevelEnum"""
    def __init__(self, *args) -> None: ...
    ...

class UserPropertyName:
    """.NET: Tekla.Structures.Catalogs.UserPropertyName"""
    def __init__(self, *args) -> None: ...
    Name: str

class UserPropertyOption:
    """.NET: Tekla.Structures.Catalogs.UserPropertyOption"""
    def __init__(self, *args) -> None: ...
    IntValue: int
    DoubleValue: float
    StringValue: str
    OptionLabel: str
    OptionLabelTranslated: str

class UserPropertyVisibilityEnum:
    """.NET: Tekla.Structures.Catalogs.UserPropertyVisibilityEnum"""
    def __init__(self, *args) -> None: ...
    ...
