# Auto-generated — Tekla 2026 — Tekla.Structures.Datatype

class Angle:
    """.NET: Tekla.Structures.Datatype.Angle"""
    def __init__(self, *args) -> None: ...
    CurrentUnitType: UnitType
    DecimalPlaces: int
    Degrees: float
    Radians: float
    CurrentUnitValue: float
    def CompareTo(self, other: Angle) -> int: ...
    def Equals(self, other: Angle) -> bool: ...
    @staticmethod
    def FromCurrentUnit(angle: float) -> Angle: ...
    @staticmethod
    def FromDegrees(degrees: float) -> Angle: ...
    @staticmethod
    def FromRadians(radians: float) -> Angle: ...
    @staticmethod
    def Parse(text: str, formatProvider: IFormatProvider, unitType: UnitType) -> Angle: ...
    def ToString(self, format: str, formatProvider: IFormatProvider, angleUnit: UnitType) -> str: ...
    @staticmethod
    def TryParse(text: str, formatProvider: IFormatProvider, unitType: UnitType, result: Angle) -> bool: ...

class AngleList:
    """.NET: Tekla.Structures.Datatype.AngleList"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Parse(text: str, formatProvider: IFormatProvider, unitType: UnitType) -> List: ...
    @staticmethod
    def ToString(angleList: IEnumerable, format: str, formatProvider: IFormatProvider, angleUnit: UnitType) -> str: ...

class Boolean:
    """.NET: Tekla.Structures.Datatype.Boolean"""
    def __init__(self, *args) -> None: ...
    Value: bool
    def GetSchema(self, ) -> XmlSchema: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class BooleanConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.BooleanConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class Constants:
    """.NET: Tekla.Structures.Datatype.Constants"""
    def __init__(self, *args) -> None: ...
    ...

class Distance:
    """.NET: Tekla.Structures.Datatype.Distance"""
    def __init__(self, *args) -> None: ...
    CurrentUnitType: UnitType
    UseUnitsInDecimalString: bool
    UseFractionalFormat: bool
    Millimeters: float
    Value: float
    def CompareTo(self, other: Distance) -> int: ...
    def ConvertTo(self, unitType: UnitType) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def FromDecimalString(text: str, formatProvider: IFormatProvider, unitType: UnitType) -> Distance: ...
    @staticmethod
    def FromFractionalFeetAndInchesString(text: str, formatProvider: IFormatProvider, unitType: UnitType) -> Distance: ...
    def GetHashCode(self, ) -> int: ...
    def GetSchema(self, ) -> XmlSchema: ...
    def GetXmlElement(self, reader: XmlReader) -> None: ...
    @staticmethod
    def Parse(text: str, formatProvider: IFormatProvider, unitType: UnitType) -> Distance: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToDecimalString(self, format: str, formatProvider: IFormatProvider, unitType: UnitType) -> str: ...
    def ToFractionalFeetAndInchesString(self, formatProvider: IFormatProvider) -> str: ...
    def ToFractionalInchesString(self, formatProvider: IFormatProvider) -> str: ...
    def ToString(self, format: str, formatProvider: IFormatProvider, unitType: UnitType) -> str: ...
    @staticmethod
    def TryParse(text: str, formatProvider: IFormatProvider, defaultUnitType: UnitType, result: Distance) -> bool: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class DistanceConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.DistanceConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class DistanceList:
    """.NET: Tekla.Structures.Datatype.DistanceList"""
    def __init__(self, *args) -> None: ...
    Item: Distance
    Count: int
    IsReadOnly: bool
    def Add(self, item: Distance) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: Distance) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetSchema(self, ) -> XmlSchema: ...
    def IndexOf(self, item: Distance) -> int: ...
    def Insert(self, index: int, item: Distance) -> None: ...
    @staticmethod
    def Parse(input: str, formatProvider: IFormatProvider, defaultUnitType: UnitType) -> DistanceList: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def Remove(self, item: Distance) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def ToArray(self, ) -> list: ...
    def ToString(self, format: str, formatProvider: IFormatProvider, unitType: UnitType) -> str: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class DistanceListConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.DistanceListConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class Double:
    """.NET: Tekla.Structures.Datatype.Double"""
    def __init__(self, *args) -> None: ...
    Value: float
    def CompareTo(self, other: float) -> int: ...
    def Equals(self, Obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetSchema(self, ) -> XmlSchema: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToString(self, ) -> str: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class DoubleConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.DoubleConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class Enum:
    """.NET: Tekla.Structures.Datatype.Enum`1"""
    def __init__(self, *args) -> None: ...
    Value: E
    def GetSchema(self, ) -> XmlSchema: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class EnumConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.EnumConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class IDataType:
    """.NET: Tekla.Structures.Datatype.IDataType"""
    def __init__(self, *args) -> None: ...
    ...

class IDoubleDataType:
    """.NET: Tekla.Structures.Datatype.IDoubleDataType"""
    def __init__(self, *args) -> None: ...
    Value: float

class IIntDataType:
    """.NET: Tekla.Structures.Datatype.IIntDataType"""
    def __init__(self, *args) -> None: ...
    Value: int

class IStringDataType:
    """.NET: Tekla.Structures.Datatype.IStringDataType"""
    def __init__(self, *args) -> None: ...
    Value: str

class Integer:
    """.NET: Tekla.Structures.Datatype.Integer"""
    def __init__(self, *args) -> None: ...
    Value: int
    def Equals(self, Obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetSchema(self, ) -> XmlSchema: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToString(self, ) -> str: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class IntegerConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.IntegerConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...

class Settings:
    """.NET: Tekla.Structures.Datatype.Settings"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetValue(name: str) -> object: ...
    @staticmethod
    def SetValue(name: str, value: object) -> None: ...
    @staticmethod
    def TryGetValue(name: str, obj: object) -> bool: ...

class SettingsProxy(MarshalByRefObject):
    """.NET: Tekla.Structures.Datatype.SettingsProxy"""
    def __init__(self, *args) -> None: ...
    def GetValue(self, name: str) -> object: ...
    def SetValue(self, name: str, value: object) -> None: ...
    def TryGetValue(self, name: str, obj: object) -> bool: ...

class String:
    """.NET: Tekla.Structures.Datatype.String"""
    def __init__(self, *args) -> None: ...
    Value: str
    def Equals(self, Obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetSchema(self, ) -> XmlSchema: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToString(self, ) -> str: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...

class StringConverter(TypeConverter):
    """.NET: Tekla.Structures.Datatype.StringConverter"""
    def __init__(self, *args) -> None: ...
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object) -> object: ...
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: object, destinationType: Type) -> object: ...
