# Auto-generated — Tekla 2026 — Tekla.Structures.DialogInternal

class AreWeUnitTesting:
    """.NET: Tekla.Structures.DialogInternal.AreWeUnitTesting"""
    def __init__(self, *args) -> None: ...
    Value: bool

class CDelegateSetter:
    """.NET: Tekla.Structures.DialogInternal.CDelegateSetter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def SetInstanceForUnitTesting(cdelegate: ICDelegate) -> None: ...

class DelegateFake(GenericDelegateFake):
    """.NET: Tekla.Structures.DialogInternal.DelegateFake"""
    def __init__(self, *args) -> None: ...
    ...

class GenericDelegateFake:
    """.NET: Tekla.Structures.DialogInternal.GenericDelegateFake`1"""
    def __init__(self, *args) -> None: ...
    def DisplayHtmlHelpTopic(self, pHelpTopic: str) -> bool: ...
    def ExportAddAkitForm(self, akitForm: IAkitForm) -> int: ...
    def ExportAddAttribute(self, Attribute: dotdiaAttributeDefinition_t) -> int: ...
    def ExportAddAttributeToStack(self, Name: str, Value: dotdiaAttributeValue_t) -> int: ...
    def ExportAddExternalWindow(self, Name: str, Handle: IntPtr) -> int: ...
    def ExportConvertFromCurrentUnits(self, Profile: dotdiaProfile_t) -> int: ...
    def ExportConvertToCurrentUnits(self, Profile: dotdiaProfile_t) -> int: ...
    def ExportFindAttributeFile(self, pFileName: str, FullFilePath: str) -> int: ...
    def ExportGetActiveDialog(self, Name: str) -> int: ...
    def ExportGetAttributeFileName(self, Name: str) -> int: ...
    def ExportGetCB(self, ) -> int: ...
    def ExportGetDialogValue(self, Name: str, Value: dotdiaAttributeValue_t) -> int: ...
    def ExportGetMainFrameHandle(self, Ptr: int) -> int: ...
    def ExportGetModelPath(self, Path: str) -> int: ...
    def ExportGetSettings(self, Settings: dotdiaSettings_t) -> int: ...
    def ExportGetUnitDecimals(self, UnitType: dotdiaUnitTypes_e) -> int: ...
    def ExportModifyCB(self, ) -> int: ...
    def ExportRegisterDialog(self, Name: str) -> int: ...
    def ExportRemoveAkitForm(self, akitForm: IAkitForm) -> int: ...
    def ExportRemoveExternalWindow(self, Name: str, Handle: IntPtr) -> int: ...
    def ExportSetActiveDialog(self, Name: str) -> int: ...
    def ExportSetDialogToggles(self, ToggleValue: int) -> int: ...
    def ExportSetDialogValue(self, Name: str, Value: dotdiaAttributeValue_t) -> int: ...
    def ExportStoreAppliedValues(self, dialogName: str) -> int: ...
    def ExportUnitOperation(self, pOperation: dotUnitOperation_t) -> int: ...
    def FreeDialogOwnerHandle(self, Handle: IntPtr) -> bool: ...
    def LoadAttributeFileNameToDialogAndApply(self, pAttributeFileName: str, pDialogName: str) -> bool: ...
    def LoadAttributeFileNameToDialogAndModify(self, pAttributeFileName: str, pDialogName: str) -> bool: ...
    def ProcessValueChangedEvent(self, Handle: IntPtr, Parameter: str) -> bool: ...
    def RegisterObjectDialogAttributeCallback(self, AttributeCB: RebarAttibuteCallback_t) -> bool: ...
    def RegisterProfileObjectDialogAttributeCallback(self, AttributeCB: ProfileAttributeCallback_t) -> bool: ...
    def RegisterShapeObjectDialogAttributeCallback(self, AttributeCB: ShapeAttibuteCallback_t) -> bool: ...

class ICDelegate:
    """.NET: Tekla.Structures.DialogInternal.ICDelegate"""
    def __init__(self, *args) -> None: ...
    def DisplayHtmlHelpTopic(self, pHelpTopic: str) -> bool: ...
    def ExportAddAkitForm(self, akitForm: IAkitForm) -> int: ...
    def ExportAddAttribute(self, Attribute: dotdiaAttributeDefinition_t) -> int: ...
    def ExportAddAttributeToStack(self, Name: str, Value: dotdiaAttributeValue_t) -> int: ...
    def ExportAddExternalWindow(self, Name: str, Handle: IntPtr) -> int: ...
    def ExportConvertFromCurrentUnits(self, Profile: dotdiaProfile_t) -> int: ...
    def ExportConvertToCurrentUnits(self, Profile: dotdiaProfile_t) -> int: ...
    def ExportFindAttributeFile(self, pFileName: str, FullFilePath: str) -> int: ...
    def ExportGetActiveDialog(self, Name: str) -> int: ...
    def ExportGetAttributeFileName(self, Name: str) -> int: ...
    def ExportGetCB(self, ) -> int: ...
    def ExportGetDialogValue(self, Name: str, Value: dotdiaAttributeValue_t) -> int: ...
    def ExportGetMainFrameHandle(self, Ptr: int) -> int: ...
    def ExportGetModelPath(self, Path: str) -> int: ...
    def ExportGetSettings(self, Settings: dotdiaSettings_t) -> int: ...
    def ExportGetUnitDecimals(self, UnitType: dotdiaUnitTypes_e) -> int: ...
    def ExportModifyCB(self, ) -> int: ...
    def ExportRegisterDialog(self, Name: str) -> int: ...
    def ExportRemoveAkitForm(self, akitForm: IAkitForm) -> int: ...
    def ExportRemoveExternalWindow(self, Name: str, Handle: IntPtr) -> int: ...
    def ExportSetActiveDialog(self, Name: str) -> int: ...
    def ExportSetDialogToggles(self, ToggleValue: int) -> int: ...
    def ExportSetDialogValue(self, Name: str, Value: dotdiaAttributeValue_t) -> int: ...
    def ExportStoreAppliedValues(self, dialogName: str) -> int: ...
    def ExportUnitOperation(self, pOperation: dotUnitOperation_t) -> int: ...
    def FreeDialogOwnerHandle(self, handle: IntPtr) -> bool: ...
    def LoadAttributeFileNameToDialogAndApply(self, pAttributeFileName: str, pDialogName: str) -> bool: ...
    def LoadAttributeFileNameToDialogAndModify(self, pAttributeFileName: str, pDialogName: str) -> bool: ...
    def ProcessValueChangedEvent(self, handle: IntPtr, parameter: str) -> bool: ...
    def RegisterObjectDialogAttributeCallback(self, attributeCB: RebarAttibuteCallback_t) -> bool: ...
    def RegisterProfileObjectDialogAttributeCallback(self, attributeCB: ProfileAttributeCallback_t) -> bool: ...
    def RegisterShapeObjectDialogAttributeCallback(self, attributeCB: ShapeAttibuteCallback_t) -> bool: ...

class IDialogOwner:
    """.NET: Tekla.Structures.DialogInternal.IDialogOwner"""
    def __init__(self, *args) -> None: ...
    def OnValueChanged(self, data: object) -> None: ...

class NativeDialogOwner:
    """.NET: Tekla.Structures.DialogInternal.NativeDialogOwner"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def OnValueChanged(self, data: object) -> None: ...

class ProfileAttributeCallback_t:
    """.NET: Tekla.Structures.DialogInternal.ProfileAttributeCallback_t"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, handle: IntPtr, profile: str, flag: int, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, handle: IntPtr, profile: str, flag: int) -> bool: ...

class ProfileAttributeRequestArgs(EventArgs):
    """.NET: Tekla.Structures.DialogInternal.ProfileAttributeRequestArgs"""
    def __init__(self, *args) -> None: ...
    Attributes: ProfileAttributes

class ProfileAttributeRequestHandler:
    """.NET: Tekla.Structures.DialogInternal.ProfileAttributeRequestHandler"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class ProfileAttributes:
    """.NET: Tekla.Structures.DialogInternal.ProfileAttributes"""
    def __init__(self, *args) -> None: ...
    Profile: str
    SelectedCallback: Action
    ClosedCallback: Action

class ProfileDialogOwner:
    """.NET: Tekla.Structures.DialogInternal.ProfileDialogOwner"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def OnValueChanged(self, attributes: ProfileAttributes) -> None: ...

class RebarAttibuteCallback_t:
    """.NET: Tekla.Structures.DialogInternal.RebarAttibuteCallback_t"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, handle: IntPtr, size: str, grade: str, radius: float, usage: int, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, handle: IntPtr, size: str, grade: str, radius: float, usage: int) -> bool: ...

class RebarAttibuteRequestHandler:
    """.NET: Tekla.Structures.DialogInternal.RebarAttibuteRequestHandler"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class RebarAttributeRequestArgs(EventArgs):
    """.NET: Tekla.Structures.DialogInternal.RebarAttributeRequestArgs"""
    def __init__(self, *args) -> None: ...
    Attributes: RebarAttributes

class RebarAttributes:
    """.NET: Tekla.Structures.DialogInternal.RebarAttributes"""
    def __init__(self, *args) -> None: ...
    Size: str
    Grade: str
    BendingRadius: float
    Usage: int
    SelectedCallback: Action
    ClosedCallback: Action

class RebarDialogOwner:
    """.NET: Tekla.Structures.DialogInternal.RebarDialogOwner"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def OnValueChanged(self, attributes: RebarAttributes) -> None: ...

class Remoter:
    """.NET: Tekla.Structures.DialogInternal.Remoter"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def DisposeService() -> None: ...
    @staticmethod
    def InitializeSandBox() -> bool: ...

class ShapeAttibuteCallback_t:
    """.NET: Tekla.Structures.DialogInternal.ShapeAttibuteCallback_t"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, handle: IntPtr, shape: str, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, handle: IntPtr, shape: str) -> bool: ...

class ShapeAttibuteRequestHandler:
    """.NET: Tekla.Structures.DialogInternal.ShapeAttibuteRequestHandler"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class ShapeAttributeRequestArgs(EventArgs):
    """.NET: Tekla.Structures.DialogInternal.ShapeAttributeRequestArgs"""
    def __init__(self, *args) -> None: ...
    Attributes: ShapeAttributes

class ShapeAttributes:
    """.NET: Tekla.Structures.DialogInternal.ShapeAttributes"""
    def __init__(self, *args) -> None: ...
    Shape: str
    SelectedCallback: Action
    ClosedCallback: Action

class ShapeDialogOwner:
    """.NET: Tekla.Structures.DialogInternal.ShapeDialogOwner"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def OnValueChanged(self, attributes: ShapeAttributes) -> None: ...

class UnitHelper:
    """.NET: Tekla.Structures.DialogInternal.UnitHelper"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def FormatDoubleUnitValue(value: float, type: dotdiaUnitTypes_e, includeLabel: bool) -> str: ...
    @staticmethod
    def GetUnitDecimals(type: dotdiaUnitTypes_e) -> Nullable: ...
    @staticmethod
    def GetUnitLabel(type: dotdiaUnitTypes_e) -> str: ...
    @staticmethod
    def ParseDoubleUnitValue(stringValue: str, type: dotdiaUnitTypes_e) -> Nullable: ...
    @staticmethod
    def SetUnitDecimals(type: dotdiaUnitTypes_e, count: int) -> Nullable: ...

class UnitOperationEnum:
    """.NET: Tekla.Structures.DialogInternal.UnitOperationEnum"""
    def __init__(self, *args) -> None: ...
    ...

class dotUnitOperation_t:
    """.NET: Tekla.Structures.DialogInternal.dotUnitOperation_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotdiaAttributeDataType_e:
    """.NET: Tekla.Structures.DialogInternal.dotdiaAttributeDataType_e"""
    def __init__(self, *args) -> None: ...
    ...

class dotdiaAttributeDefinition_t:
    """.NET: Tekla.Structures.DialogInternal.dotdiaAttributeDefinition_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotdiaAttributeValue_t:
    """.NET: Tekla.Structures.DialogInternal.dotdiaAttributeValue_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotdiaProfile_t:
    """.NET: Tekla.Structures.DialogInternal.dotdiaProfile_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotdiaSettings_t:
    """.NET: Tekla.Structures.DialogInternal.dotdiaSettings_t"""
    def __init__(self, *args) -> None: ...
    ...
