# Auto-generated — Tekla 2026 — Tekla.Structures.DrawingInternal

class AreWeUnitTesting:
    """.NET: Tekla.Structures.DrawingInternal.AreWeUnitTesting"""
    def __init__(self, *args) -> None: ...
    Value: bool

class AssociativityCommandEnum:
    """.NET: Tekla.Structures.DrawingInternal.AssociativityCommandEnum"""
    def __init__(self, *args) -> None: ...
    ...

class AssociativityManager:
    """.NET: Tekla.Structures.DrawingInternal.AssociativityManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ConfirmViewAssociativityHide() -> None: ...
    @staticmethod
    def GetDimensionEndPointRules(dimension: StraightDimension) -> IList: ...
    @staticmethod
    def GetDimensionStartPointRules(dimension: StraightDimension) -> IList: ...
    @staticmethod
    def GetViewPossibleObjects(viewId: Identifier) -> IList: ...
    @staticmethod
    def GetViewPreferredRuleObject(viewId: Identifier) -> int: ...
    @staticmethod
    def GetViewRules(viewId: Identifier) -> IList: ...
    @staticmethod
    def IsExperimentalAllowed() -> bool: ...
    @staticmethod
    def SetViewPreferredRuleObject(viewId: Identifier, preferredObjectId: int) -> None: ...
    @staticmethod
    def SetViewPreferredRuleObjectByGuid(viewId: Identifier, objectGuid: str) -> None: ...
    @staticmethod
    def TryCreateFilterDimensionRuleFromSelectedDimensions() -> IList: ...
    @staticmethod
    def TryGetAllDimensionPointAssociations(dimensionId: int, rules: IList) -> bool: ...
    @staticmethod
    def TryGetDimensionEndPointAssociations(dimensionId: int, rules: IList) -> bool: ...
    @staticmethod
    def TryGetDimensionEndPointLocation(dimensionId: int, screenX: int, screenY: int) -> bool: ...
    @staticmethod
    def TryGetDimensionRebarOrBoltAssociations(dimensionId: int, rules: IList) -> bool: ...
    @staticmethod
    def TryGetDimensionStartPointAssociations(dimensionId: int, rules: IList) -> bool: ...
    @staticmethod
    def TryGetDimensionStartPointLocation(dimensionId: int, screenX: int, screenY: int) -> bool: ...
    @staticmethod
    def TryGetDimensionZeroPointAssociations(dimensionId: int, rules: IList) -> bool: ...
    @staticmethod
    def TryGetSectionLocation(sectionId: int, screenX: int, screenY: int) -> bool: ...
    @staticmethod
    def TryGetViewLocation(viewId: int, screenX: int, screenY: int) -> bool: ...

class AssociativityPointTypeEnum:
    """.NET: Tekla.Structures.DrawingInternal.AssociativityPointTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class AssociativityRule(DrawingObject):
    """.NET: Tekla.Structures.DrawingInternal.AssociativityRule"""
    def __init__(self, *args) -> None: ...
    Follow: Followable
    Rotation: Followable
    Rules: List
    UpdateMode: AssociativityUpdateMode
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def AddRule(self, rule: FitRule) -> bool: ...
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def RemoveRule(self, rule: FitRule) -> bool: ...
    def Select(self, ) -> bool: ...

class CDelegateSetter:
    """.NET: Tekla.Structures.DrawingInternal.CDelegateSetter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ResetInstance() -> None: ...
    @staticmethod
    def SetInstanceForUnitTesting(cdelegate: ICDelegate) -> None: ...

class CloningManager:
    """.NET: Tekla.Structures.DrawingInternal.CloningManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CloneView(targetViewId: int, sourceViewId: int, sourceDrawingId: int) -> None: ...
    @staticmethod
    def GetViewMatchingScore(targetViewId: int, sourceViewId: int, sourceDrawingId: int) -> float: ...
    @staticmethod
    def SetPartialCloningSettings(settings: str) -> None: ...

class CommitMessage:
    """.NET: Tekla.Structures.DrawingInternal.CommitMessage"""
    def __init__(self, *args) -> None: ...
    ...

class DatabaseObjectExtensions:
    """.NET: Tekla.Structures.DrawingInternal.DatabaseObjectExtensions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetIdentifier(databaseObject: DatabaseObject) -> Identifier: ...
    @staticmethod
    def GetViewIdentifier(databaseObject: DatabaseObject) -> Identifier: ...

class DelegateFake(GenericDelegateFake):
    """.NET: Tekla.Structures.DrawingInternal.DelegateFake"""
    def __init__(self, *args) -> None: ...
    ...

class DisplayableAssociativityRule:
    """.NET: Tekla.Structures.DrawingInternal.DisplayableAssociativityRule"""
    def __init__(self, *args) -> None: ...
    Rule: PointAssociativityRule
    PointType: AssociationType
    MainModelObjectIdentifier: Identifier
    SecondaryModelObjectIdentifier: Identifier

class DocumentManagerController(MarshalByRefObject):
    """.NET: Tekla.Structures.DrawingInternal.DocumentManagerController"""
    def __init__(self, *args) -> None: ...
    GetSelectedDrawingGuidsFunc: Func
    GetVisibleDrawingIdsFunc: Func
    SetSelectedDrawingsFunc: Action
    def GetSelectedDrawingGuids(self, ) -> IEnumerable: ...
    def GetVisibleDrawingIds(self, ) -> IEnumerable: ...
    def SetSelectedDrawings(self, drawingIds: IEnumerable) -> None: ...
    def ShowWindow(self, ) -> None: ...
    def UpdateDocumentManager(self, newDrawingIsNotNull: bool, newId: int, newType: int, oldDrawingIsNotNull: bool, oldId: int, oldType: int) -> None: ...

class DotNetDrawingProxy:
    """.NET: Tekla.Structures.DrawingInternal.DotNetDrawingProxy"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Run(Param: str) -> int: ...

class DrawingChecker:
    """.NET: Tekla.Structures.DrawingInternal.DrawingChecker"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def DrawingCheckerFetchCurrentDrawingErrors(CheckType: DrawingCheckerType) -> IList: ...

class DrawingCheckerType:
    """.NET: Tekla.Structures.DrawingInternal.DrawingCheckerType"""
    def __init__(self, *args) -> None: ...
    ...

class DrawingConversions:
    """.NET: Tekla.Structures.DrawingInternal.DrawingConversions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetDrawingRuntimeIdFromFilename(drawingFilename: str) -> int: ...

class DrawingExtensions:
    """.NET: Tekla.Structures.DrawingInternal.DrawingExtensions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CachedModify(drawing: Drawing) -> bool: ...
    @staticmethod
    def CachedSelect(drawing: Drawing) -> bool: ...
    @staticmethod
    def DbOperation(drawing: Drawing, operationType: QueryTypeEnum, OverrideTrackingSource: Nullable) -> bool: ...
    @staticmethod
    def GetDgGuid(drawing: Drawing) -> Guid: ...
    @staticmethod
    def GetDrawingCloningSourceData(drawing: Drawing) -> Tuple: ...
    @staticmethod
    def GetPlotFileName(drawing: Drawing, includeRevisionInfo: bool) -> str: ...
    @staticmethod
    def GetPlotFileNameExt(drawing: Drawing, includeRevisionInfo: IncludeRevisionMarkEnum) -> str: ...
    @staticmethod
    def IsDrawingNumberingUpToDate(drawing: Drawing) -> bool: ...

class EditMode:
    """.NET: Tekla.Structures.DrawingInternal.EditMode"""
    def __init__(self, *args) -> None: ...
    ...

class EventHandlerWrapper(MarshalByRefObject):
    """.NET: Tekla.Structures.DrawingInternal.EventHandlerWrapper"""
    def __init__(self, *args) -> None: ...
    def AddListener(self, EventListener: IUIEvents) -> None: ...
    def RemoveListener(self, EventListener: IUIEvents) -> None: ...

class GenericDelegateFake:
    """.NET: Tekla.Structures.DrawingInternal.GenericDelegateFake`1"""
    def __init__(self, *args) -> None: ...
    def ExportAddToMasterDrawingCatalog(self, ) -> int: ...
    def ExportAngleDimensionAttributesHandler(self, AngleDimAttr: dotGrAngleDimensionAttributes_t) -> int: ...
    def ExportAngleDimensionHandler(self, pAngleDimension: dotGrAngleDimension_t) -> int: ...
    def ExportArcHandler(self, pArc: dotGrArc_t) -> int: ...
    def ExportArePoursShownInDrawing(self, ) -> int: ...
    def ExportAssociativityHandler(self, pHandler: dotGrAssociativityHandler_t) -> int: ...
    def ExportAssociativityRuleHandler(self, pAssociativity: dotGrAssociativity_t) -> ReturnValuesEnum: ...
    def ExportAutomationHandler(self, pAutomation: dotGrAutomation_t) -> int: ...
    def ExportBoltAttributesHandler(self, pBoltAttributes: dotGrBoltAttributes_t) -> int: ...
    def ExportBoltHandler(self, pBolt: dotGrBolt_t) -> int: ...
    def ExportCircleHandler(self, pCircle: dotGrCircle_t) -> int: ...
    def ExportCloningHandler(self, pHandler: dotGrCloningHandler_t) -> int: ...
    def ExportClosedGraphicObjectAttributesHandler(self, pClosedGraphicObjectAttributes: dotGrClosedGraphicObjectAttributes_t, ObjectType: int) -> int: ...
    def ExportCloudHandler(self, pCloud: dotGrCloud_t) -> int: ...
    def ExportConnectionHandler(self, pConnection: dotGrConnection_t) -> int: ...
    def ExportCopySelectedDrawingsToNewSheet(self, ) -> int: ...
    def ExportCurvedDimensionOrthogonalHandler(self, CurvedDimension: dotGrCurvedDimensionOrthogonal_t) -> int: ...
    def ExportCurvedDimensionRadialHandler(self, CurvedDimension: dotGrCurvedDimensionRadial_t) -> int: ...
    def ExportCurvedDimensionSetOrthogonalAttributesHandler(self, CurvedDimAttr: dotGrCurvedDimensionSetOrthogonalAttributes_t) -> int: ...
    def ExportCurvedDimensionSetOrthogonalHandler(self, CurvedDimensionSet: dotGrCurvedDimensionSetOrthogonal_t) -> int: ...
    def ExportCurvedDimensionSetRadialAttributesHandler(self, CurvedDimAttr: dotGrCurvedDimensionSetRadialAttributes_t) -> int: ...
    def ExportCurvedDimensionSetRadialHandler(self, CurvedDimensionSet: dotGrCurvedDimensionSetRadial_t) -> int: ...
    def ExportDeleteSelectedDrawings(self, ) -> int: ...
    def ExportDetailMarkAttributesHandler(self, pDetailMarkAttributes: dotGrDetailMarkAttributes_t) -> int: ...
    def ExportDetailMarkHandler(self, pDetailMark: dotGrDetailMark_t) -> ReturnValuesEnum: ...
    def ExportDimensionLinkHandler(self, DimensionLink: dotGrDimensionLink_t) -> int: ...
    def ExportDisplayDrawingCloningDialog(self, ) -> int: ...
    def ExportDisplayDrawingPropertiesDialog(self, ) -> int: ...
    def ExportDisplayDrawingUdaDialog(self, ) -> int: ...
    def ExportDisplayRevisionDialog(self, ) -> int: ...
    def ExportDisplaySnapshotDialogByFileName(self, fileName: str) -> int: ...
    def ExportDisplaySnapshotsDialog(self, ) -> int: ...
    def ExportDisplaySnapshotsDialogByGuid(self, guid: str) -> int: ...
    def ExportDoubleListHandler(self, pDoubleList: dotGrDoubleList_t) -> int: ...
    def ExportDrawingCheckerFetchCurrentDrawingErrors(self, CheckType: int, dimensionsThatArentAssociated: List) -> int: ...
    def ExportDrawingHandler(self, pDrawing: dotGrDrawingAttributes_t) -> ReturnValuesEnum: ...
    def ExportDrawingHandlerHandler(self, pHandler: dotGrDrawingHandler_t) -> int: ...
    def ExportDrawingObjectSelectorHandler(self, selectorData: dotDrawingObjectSelector_t) -> ReturnValuesEnum: ...
    def ExportEdgeChamferAttributesHandler(self, pEdgeChamferAttributes: dotGrEdgeChamferAttributes_t) -> int: ...
    def ExportEdgeChamferHandler(self, pEdgeChamfer: dotGrEdgeChamfer_t) -> int: ...
    def ExportEmbeddedObjectAttributesHandler(self, pEmbeddedObjectAttributes: dotGrEmbeddedObjectAttributes_t) -> ReturnValuesEnum: ...
    def ExportEmbeddedObjectHandler(self, pEmbeddedObject: dotGrEmbeddedObject_t) -> ReturnValuesEnum: ...
    def ExportEnumerateCustomLineTypes(self, pDotCustomLineTypes: dotGrCustomLineTypes_t) -> ReturnValuesEnum: ...
    def ExportEnumerateObjects(self, pEnumerator: dotEnumerator_t) -> int: ...
    def ExportFilterDrawingListByParts(self, ) -> int: ...
    def ExportGetARGBFromColorIndex(self, ColorIndex: int, ARGB: dotARGBColor_t) -> int: ...
    def ExportGetAllColorPaletteFiles(self, DotClientId: dotClientId_t) -> int: ...
    def ExportGetChangedDrawingForUpdatedEvent(self, pDrawingAttributes: dotGrDrawingAttributes_t) -> int: ...
    def ExportGetColorIndexFromARGB(self, ARGB: dotARGBColor_t) -> int: ...
    def ExportGetColorIndexFromSaveFormat(self, SaveFormat: str) -> int: ...
    def ExportGetDocumentManagerController(self, documentManagerController: IDocumentManagerController) -> int: ...
    def ExportGetDotType(self, pModelObject: dotGrDrawingObject_t) -> int: ...
    def ExportGetDrawingExportFileName(self, drawingId: int, drawingFileName: str, formatString: str, includeRevisionInfo: bool, allowNameWithoutVariables: bool, fullFileName: bool, exportFileName: str) -> int: ...
    def ExportGetDrawingExportFileNameExt(self, drawingId: int, drawingFileName: str, formatString: str, includeRevisionInfo: int, allowNameWithoutVariables: bool, fullFileName: bool, exportFileName: str) -> int: ...
    def ExportGetDrawingReadyForIssuingChangeEvent(self, drawingGuid: str) -> bool: ...
    def ExportGetDrawingToObjectMapping(self, DotClientId: dotClientId_t) -> bool: ...
    def ExportGetDrawingsBySelectedParts(self, DotClientId: dotClientId_t, ignoreFilters: bool, ignoreGADrawings: bool) -> int: ...
    def ExportGetEditMode(self, ) -> EditMode: ...
    def ExportGetIdsForDrawingsNeedingNumbering(self, DotClientId: dotClientId_t) -> int: ...
    def ExportGetNextModelObjectIdentifier(self, modelObjectId: int, drawingId: int) -> int: ...
    def ExportGetNumberOfNonUpToDateObjectsAndPours(self, ) -> int: ...
    def ExportGetPluginInputById(self, PluginId: int, pInput: dotPluginInput_t) -> int: ...
    def ExportGetSaveFormatFromColorIndex(self, ColorIndex: int, SaveFormat: str) -> int: ...
    def ExportGetSnapshotFromDatabase(self, Enumerator: dotEnumerator_t, SerializedObjects: List, SelectInstances: bool) -> int: ...
    def ExportGridAttributesHandler(self, pGridAttributes: dotGrGridAttributes_t) -> int: ...
    def ExportGridHandler(self, pGrid: dotGrGrid_t) -> int: ...
    def ExportGridLineAttributesHandler(self, pGridLineAttributes: dotGrGridLineAttributes_t) -> int: ...
    def ExportGridLineHandler(self, pGridLine: dotGrGridLine_t) -> int: ...
    def ExportHatchLineAttributesHandler(self, pHatchLineAttributes: dotGrHatchLineAttributes_t) -> int: ...
    def ExportHatchLineHandler(self, pHatchLine: dotGrHatchLine_t) -> int: ...
    def ExportHighlightCutInView(self, ModelId: int, SectionViewId: int, ContextViewId: int) -> int: ...
    def ExportHighlightGridLine(self, GridLineId: int) -> int: ...
    def ExportHighlightPartInView(self, ModelId: int, ViewId: int) -> int: ...
    def ExportIntListHandler(self, pIntList: dotGrIntList_t) -> int: ...
    def ExportIsStandardColor(self, ColorIndex: int) -> int: ...
    def ExportLayoutHandler(self, pHandler: dotGrLayoutHandler_t) -> int: ...
    def ExportLeaderLineHandler(self, pLeaderLine: dotGrLeaderLine_t) -> ReturnValuesEnum: ...
    def ExportLevelMarkAttributesHandler(self, pLevelMarkAttributes: dotGrLevelMarkAttributes_t) -> int: ...
    def ExportLevelMarkHandler(self, pLevelMark: dotGrLevelMark_t) -> ReturnValuesEnum: ...
    def ExportLineHandler(self, pLine: dotGrLine_t) -> int: ...
    def ExportLinkAttributesHandler(self, pLinkAttributes: dotGrLinkAttributes_t) -> ReturnValuesEnum: ...
    def ExportLinkHandler(self, pLink: dotGrLink_t) -> ReturnValuesEnum: ...
    def ExportMarkAttributesHandler(self, pMarkBaseAttributes: dotGrMarkBaseAttributes_t) -> int: ...
    def ExportMarkElementListHandler(self, pElementList: dotGrElementList_t) -> ReturnValuesEnum: ...
    def ExportMarkHandler(self, pMarkBase: dotGrMarkBase_t) -> ReturnValuesEnum: ...
    def ExportMarkLearningHandler(self, pHandler: dotGrMarkLearningHandler_t) -> int: ...
    def ExportMarkListingHandler(self, pHandler: dotGrMarkListingHandler_t) -> int: ...
    def ExportModelDatabaseUserPropertyHandler(self, pProperty: dotGrUserProperty_t) -> ReturnValuesEnum: ...
    def ExportNumberDrawings(self, ) -> int: ...
    def ExportOpenGraphicObjectAttributesHandler(self, pOpenGraphicObjectAttributes: dotGrOpenGraphicObjectAttributes_t, ObjectType: int) -> int: ...
    def ExportOperationHandler(self, pHandler: dotGrOperationHandler_t) -> int: ...
    def ExportPartAttributesHandler(self, pPartAttributes: dotGrPartAttributes_t) -> int: ...
    def ExportPartHandler(self, pPart: dotGrPart_t) -> int: ...
    def ExportPickerCommandHandler(self, pPickerCommand: dotGrPickerCommand_t) -> ReturnValuesEnum: ...
    def ExportPickerHandler(self, pickerData: dotDrawingUIPickerWrapper_t) -> ReturnValuesEnum: ...
    def ExportPluginHandler(self, Plugin: dotGrPlugin_t, Filename: str, Applyvalues: bool) -> ReturnValuesEnum: ...
    def ExportPluginQueueHandler(self, pPluginQueue: dotGrPluginQueue_t) -> ReturnValuesEnum: ...
    def ExportPointListHandler(self, pPointList: dotGrPointList_t) -> int: ...
    def ExportPolygonHandler(self, pPolygon: dotGrPolygon_t) -> int: ...
    def ExportPolylineHandler(self, pPolyline: dotGrPolyline_t) -> int: ...
    def ExportPourAttributesHandler(self, pPourAttributes: dotGrPourAttributes_t) -> int: ...
    def ExportPourBreakAttributesHandler(self, pPourBreakAttributes: dotGrPourBreakAttributes_t) -> ReturnValuesEnum: ...
    def ExportPourBreakHandler(self, pPourBreak: dotGrPourBreak_t) -> ReturnValuesEnum: ...
    def ExportPourHandler(self, pPour: dotGrPour_t) -> int: ...
    def ExportPrintDrawingHandler(self, pPrintDrawing: dotGrPrintDrawing_t) -> int: ...
    def ExportRadiusDimensionAttributesHandler(self, RadiusDimAttr: dotGrRadiusDimensionAttributes_t) -> int: ...
    def ExportRadiusDimensionHandler(self, pRadiusDimension: dotGrRadiusDimension_t) -> int: ...
    def ExportRecreateSelectedDrawings(self, ) -> int: ...
    def ExportRectangleHandler(self, pRectangle: dotGrRectangle_t) -> int: ...
    def ExportRectangularCloudHandler(self, pRectangularCloud: dotGrRectangularCloud_t) -> int: ...
    def ExportReferenceModelAttributesHandler(self, pReferenceModelAttributes: dotGrReferenceModelAttributes_t) -> ReturnValuesEnum: ...
    def ExportReferenceModelHandler(self, pReferenceModel: dotGrReferenceModel_t) -> ReturnValuesEnum: ...
    def ExportRefreshColorMode(self, ) -> int: ...
    def ExportReinforcementBaseAttributesHandler(self, ReinforcementBaseAttributes: dotGrReinforcementBaseAttributes_t) -> ReturnValuesEnum: ...
    def ExportReinforcementHandler(self, pReinforcement: dotGrReinforcementBase_t) -> ReturnValuesEnum: ...
    def ExportReinforcementSetGroupGetModelIdentifiers(self, pIdentifiers: dotGrReinforcementSetGroupIdentifiers_t, modelIds: List) -> ReturnValuesEnum: ...
    def ExportSectionMarkAttributesHandler(self, pSectionMarkAttributes: dotGrSectionMarkAttributes_t) -> ReturnValuesEnum: ...
    def ExportSectionMarkHandler(self, pSectionMark: dotGrSectionMark_t) -> ReturnValuesEnum: ...
    def ExportSelectPartsByDrawings(self, ) -> int: ...
    def ExportSetColorRgb(self, color: int, red: int, green: int, blue: int) -> int: ...
    def ExportSetDocumentManagerController(self, documentManagerController: IDocumentManagerController) -> int: ...
    def ExportSetDrawingPlotDateById(self, drawingId: int) -> int: ...
    def ExportSetPenWidth(self, color: int, penWidth: int) -> int: ...
    def ExportShowAssociativityPinPushed(self, DrawingObjectId: int, IsStartPoint: int) -> int: ...
    def ExportShowAssociativityPinUnpushed(self, DrawingObjectId: int, IsStartPoint: int) -> int: ...
    def ExportShowColorPalette(self, color: int, hWndOwner: IntPtr) -> int: ...
    def ExportShowColorPaletteForHatchBackground(self, color: int, hWndOwner: IntPtr) -> int: ...
    def ExportSignalDocumentManagerClosed(self, ) -> int: ...
    def ExportSignalDrawingSelectionChanged(self, ) -> int: ...
    def ExportStraightDimensionHandler(self, StraightDimension: dotGrStraightDimension_t) -> int: ...
    def ExportStraightDimensionSetAttributesHandler(self, StraightDimensionSetAttributes: dotGrStraightDimensionSetAttributes_t) -> int: ...
    def ExportStraightDimensionSetExcludePartsAccordingToFilter(self, drawingObject: dotGrDrawingObject_t) -> int: ...
    def ExportStraightDimensionSetHandler(self, StraightDimensionSet: dotGrStraightDimensionSet_t) -> int: ...
    def ExportStringListHandler(self, pStringList: dotGrStringList_t) -> int: ...
    def ExportSurfacingAttributesHandler(self, pSurfacingAttributes: dotGrSurfacingAttributes_t) -> int: ...
    def ExportSurfacingHandler(self, pSurfacing: dotGrSurfacing_t) -> int: ...
    def ExportSymbolAttributesHandler(self, pSymbolAttributes: dotGrSymbolAttributes_t) -> int: ...
    def ExportSymbolHandler(self, pSymbol: dotGrSymbol_t) -> ReturnValuesEnum: ...
    def ExportTextAttributesHandler(self, pTextAttributes: dotGrTextAttributes_t) -> int: ...
    def ExportTextFileAttributesHandler(self, pTextFileAttributes: dotGrTextFileAttributes_t) -> ReturnValuesEnum: ...
    def ExportTextFileHandler(self, pTextFile: dotGrTextFile_t) -> ReturnValuesEnum: ...
    def ExportTextHandler(self, pText: dotGrText_t) -> ReturnValuesEnum: ...
    def ExportTryOpenDrawing(self, drawingId: int) -> int: ...
    def ExportUnhighlightCutInView(self, ViewId: int) -> int: ...
    def ExportUnhighlightGridLine(self, GridLineId: int) -> int: ...
    def ExportUnhighlightPartInView(self, ModelId: int, ViewId: int) -> int: ...
    def ExportUpdateSelectedDrawingMarks(self, ) -> int: ...
    def ExportUpdateSelectedDrawings(self, ) -> int: ...
    def ExportUserPropertyHandler(self, pProperty: dotGrUserProperty_t) -> ReturnValuesEnum: ...
    def ExportViewAttributesHandler(self, pViewAttributes: dotGrViewAttributes_t) -> int: ...
    def ExportViewCommandHandler(self, pViewCommand: dotGrViewCommand_t) -> ReturnValuesEnum: ...
    def ExportViewHandler(self, pView: dotGrView_t) -> ReturnValuesEnum: ...
    def ExportWeldAttributesHandler(self, pAttributes: dotGrWeldAttributes_t) -> ReturnValuesEnum: ...
    def ExportWeldHandler(self, pWeld: dotGrWeld_t) -> ReturnValuesEnum: ...
    def ExportWeldMarkAttributesHandler(self, pAttributes: dotGrWeldMarkAttributes_t) -> int: ...
    def ExportWeldMarkHandler(self, pWeldMark: dotGrWeldMark_t) -> int: ...
    def GetDrawingRuntimeIdFromFilename(self, drawingFilename: str) -> int: ...
    def GetDrawingViewVisibilityFilterValue(self, drawingViewId: int, drawingViewVisibilityFilterValue: str) -> bool: ...
    def GetRaiseReadWindowsNamesByViewIds(self, modelViewId: int, drawingViewId: int) -> bool: ...
    def GetSheet(self, ) -> ContainerView: ...
    def ImportDoubleListHandler(self, pDoubleList: dotGrDoubleList_t) -> int: ...
    def ImportIntListHandler(self, pIntList: dotGrIntList_t) -> int: ...
    def ImportMarkElementListHandler(self, pElementList: dotGrElementList_t) -> int: ...
    def ImportPointListHandler(self, pPointList: dotGrPointList_t) -> int: ...
    def ImportStringListHandler(self, pStringList: dotGrStringList_t) -> int: ...
    def LoadAttributeFileNameToDialogAndApply(self, pAttributeFileName: str, pDialogName: str) -> bool: ...
    def LoadAttributeFileNameToDialogAndModify(self, pAttributeFileName: str, pDialogName: str) -> bool: ...

class ICDelegate:
    """.NET: Tekla.Structures.DrawingInternal.ICDelegate"""
    def __init__(self, *args) -> None: ...
    def ExportAddToMasterDrawingCatalog(self, ) -> int: ...
    def ExportAngleDimensionAttributesHandler(self, AngleDimAttr: dotGrAngleDimensionAttributes_t) -> int: ...
    def ExportAngleDimensionHandler(self, pAngleDimension: dotGrAngleDimension_t) -> int: ...
    def ExportArcHandler(self, pArc: dotGrArc_t) -> int: ...
    def ExportArePoursShownInDrawing(self, ) -> int: ...
    def ExportAssociativityHandler(self, pHandler: dotGrAssociativityHandler_t) -> int: ...
    def ExportAssociativityRuleHandler(self, pAssociativity: dotGrAssociativity_t) -> ReturnValuesEnum: ...
    def ExportAutomationHandler(self, pAutomation: dotGrAutomation_t) -> int: ...
    def ExportBoltAttributesHandler(self, pBoltAttributes: dotGrBoltAttributes_t) -> int: ...
    def ExportBoltHandler(self, pBolt: dotGrBolt_t) -> int: ...
    def ExportCircleHandler(self, pCircle: dotGrCircle_t) -> int: ...
    def ExportCloningHandler(self, pHandler: dotGrCloningHandler_t) -> int: ...
    def ExportClosedGraphicObjectAttributesHandler(self, pClosedGraphicObjectAttributes: dotGrClosedGraphicObjectAttributes_t, ObjectType: int) -> int: ...
    def ExportCloudHandler(self, pCloud: dotGrCloud_t) -> int: ...
    def ExportConnectionHandler(self, pConnection: dotGrConnection_t) -> int: ...
    def ExportCopySelectedDrawingsToNewSheet(self, ) -> int: ...
    def ExportCurvedDimensionOrthogonalHandler(self, CurvedDimension: dotGrCurvedDimensionOrthogonal_t) -> int: ...
    def ExportCurvedDimensionRadialHandler(self, CurvedDimension: dotGrCurvedDimensionRadial_t) -> int: ...
    def ExportCurvedDimensionSetOrthogonalAttributesHandler(self, CurvedDimAttr: dotGrCurvedDimensionSetOrthogonalAttributes_t) -> int: ...
    def ExportCurvedDimensionSetOrthogonalHandler(self, CurvedDimensionSet: dotGrCurvedDimensionSetOrthogonal_t) -> int: ...
    def ExportCurvedDimensionSetRadialAttributesHandler(self, CurvedDimAttr: dotGrCurvedDimensionSetRadialAttributes_t) -> int: ...
    def ExportCurvedDimensionSetRadialHandler(self, CurvedDimensionSet: dotGrCurvedDimensionSetRadial_t) -> int: ...
    def ExportDeleteSelectedDrawings(self, ) -> int: ...
    def ExportDetailMarkAttributesHandler(self, pDetailMarkAttributes: dotGrDetailMarkAttributes_t) -> int: ...
    def ExportDetailMarkHandler(self, pDetailMark: dotGrDetailMark_t) -> ReturnValuesEnum: ...
    def ExportDimensionLinkHandler(self, DimensionLink: dotGrDimensionLink_t) -> int: ...
    def ExportDisplayDrawingCloningDialog(self, ) -> int: ...
    def ExportDisplayDrawingPropertiesDialog(self, ) -> int: ...
    def ExportDisplayDrawingUdaDialog(self, ) -> int: ...
    def ExportDisplayRevisionDialog(self, ) -> int: ...
    def ExportDisplaySnapshotDialogByFileName(self, fileName: str) -> int: ...
    def ExportDisplaySnapshotsDialog(self, ) -> int: ...
    def ExportDisplaySnapshotsDialogByGuid(self, guid: str) -> int: ...
    def ExportDoubleListHandler(self, pDoubleList: dotGrDoubleList_t) -> int: ...
    def ExportDrawingCheckerFetchCurrentDrawingErrors(self, CheckType: int, dimensionsThatArentAssociated: List) -> int: ...
    def ExportDrawingHandler(self, pDrawing: dotGrDrawingAttributes_t) -> ReturnValuesEnum: ...
    def ExportDrawingHandlerHandler(self, pHandler: dotGrDrawingHandler_t) -> int: ...
    def ExportDrawingObjectSelectorHandler(self, selectorData: dotDrawingObjectSelector_t) -> ReturnValuesEnum: ...
    def ExportEdgeChamferAttributesHandler(self, pEdgeChamferAttributes: dotGrEdgeChamferAttributes_t) -> int: ...
    def ExportEdgeChamferHandler(self, pEdgeChamfer: dotGrEdgeChamfer_t) -> int: ...
    def ExportEmbeddedObjectAttributesHandler(self, pEmbeddedObjectAttributes: dotGrEmbeddedObjectAttributes_t) -> ReturnValuesEnum: ...
    def ExportEmbeddedObjectHandler(self, pEmbeddedObject: dotGrEmbeddedObject_t) -> ReturnValuesEnum: ...
    def ExportEnumerateCustomLineTypes(self, pDotCustomLineTypes: dotGrCustomLineTypes_t) -> ReturnValuesEnum: ...
    def ExportEnumerateObjects(self, pEnumerator: dotEnumerator_t) -> int: ...
    def ExportFilterDrawingListByParts(self, ) -> int: ...
    def ExportGetARGBFromColorIndex(self, ColorIndex: int, ARGB: dotARGBColor_t) -> int: ...
    def ExportGetAllColorPaletteFiles(self, DotClientId: dotClientId_t) -> int: ...
    def ExportGetChangedDrawingForUpdatedEvent(self, pDrawingAttributes: dotGrDrawingAttributes_t) -> int: ...
    def ExportGetColorIndexFromARGB(self, ARGB: dotARGBColor_t) -> int: ...
    def ExportGetColorIndexFromSaveFormat(self, SaveFormat: str) -> int: ...
    def ExportGetDocumentManagerController(self, documentManagerController: IDocumentManagerController) -> int: ...
    def ExportGetDotType(self, pModelObject: dotGrDrawingObject_t) -> int: ...
    def ExportGetDrawingExportFileName(self, drawingId: int, drawingFileName: str, formatString: str, includeRevisionInfo: bool, allowNameWithoutVariables: bool, fullFileName: bool, exportFileName: str) -> int: ...
    def ExportGetDrawingExportFileNameExt(self, drawingId: int, drawingFileName: str, formatString: str, includeRevisionInfo: int, allowNameWithoutVariables: bool, fullFileName: bool, exportFileName: str) -> int: ...
    def ExportGetDrawingReadyForIssuingChangeEvent(self, drawingGuid: str) -> bool: ...
    def ExportGetDrawingToObjectMapping(self, DotClientId: dotClientId_t) -> bool: ...
    def ExportGetDrawingsBySelectedParts(self, DotClientId: dotClientId_t, ignoreFilters: bool, ignoreGADrawings: bool) -> int: ...
    def ExportGetEditMode(self, ) -> EditMode: ...
    def ExportGetIdsForDrawingsNeedingNumbering(self, DotClientId: dotClientId_t) -> int: ...
    def ExportGetNextModelObjectIdentifier(self, modelObjectId: int, drawingId: int) -> int: ...
    def ExportGetNumberOfNonUpToDateObjectsAndPours(self, ) -> int: ...
    def ExportGetPluginInputById(self, PluginId: int, pInput: dotPluginInput_t) -> int: ...
    def ExportGetSaveFormatFromColorIndex(self, ColorIndex: int, SaveFormat: str) -> int: ...
    def ExportGetSnapshotFromDatabase(self, Enumerator: dotEnumerator_t, SerializedObjects: List, SelectInstances: bool) -> int: ...
    def ExportGridAttributesHandler(self, pGridAttributes: dotGrGridAttributes_t) -> int: ...
    def ExportGridHandler(self, pGrid: dotGrGrid_t) -> int: ...
    def ExportGridLineAttributesHandler(self, pGridLineAttributes: dotGrGridLineAttributes_t) -> int: ...
    def ExportGridLineHandler(self, pGridLine: dotGrGridLine_t) -> int: ...
    def ExportHatchLineAttributesHandler(self, pHatchLineAttributes: dotGrHatchLineAttributes_t) -> int: ...
    def ExportHatchLineHandler(self, pHatchLine: dotGrHatchLine_t) -> int: ...
    def ExportHighlightCutInView(self, ModelId: int, SectionViewId: int, ContextViewId: int) -> int: ...
    def ExportHighlightGridLine(self, GridLineId: int) -> int: ...
    def ExportHighlightPartInView(self, ModelId: int, ViewId: int) -> int: ...
    def ExportIntListHandler(self, pIntList: dotGrIntList_t) -> int: ...
    def ExportIsStandardColor(self, ColorIndex: int) -> int: ...
    def ExportLayoutHandler(self, pHandler: dotGrLayoutHandler_t) -> int: ...
    def ExportLeaderLineHandler(self, pLeaderLine: dotGrLeaderLine_t) -> ReturnValuesEnum: ...
    def ExportLevelMarkAttributesHandler(self, pLevelMarkAttributes: dotGrLevelMarkAttributes_t) -> int: ...
    def ExportLevelMarkHandler(self, pLevelMark: dotGrLevelMark_t) -> ReturnValuesEnum: ...
    def ExportLineHandler(self, pLine: dotGrLine_t) -> int: ...
    def ExportLinkAttributesHandler(self, pLinkAttributes: dotGrLinkAttributes_t) -> ReturnValuesEnum: ...
    def ExportLinkHandler(self, pLink: dotGrLink_t) -> ReturnValuesEnum: ...
    def ExportMarkAttributesHandler(self, pMarkBaseAttributes: dotGrMarkBaseAttributes_t) -> int: ...
    def ExportMarkElementListHandler(self, pElementList: dotGrElementList_t) -> ReturnValuesEnum: ...
    def ExportMarkHandler(self, pMarkBase: dotGrMarkBase_t) -> ReturnValuesEnum: ...
    def ExportMarkLearningHandler(self, pHandler: dotGrMarkLearningHandler_t) -> int: ...
    def ExportMarkListingHandler(self, pHandler: dotGrMarkListingHandler_t) -> int: ...
    def ExportModelDatabaseUserPropertyHandler(self, pProperty: dotGrUserProperty_t) -> ReturnValuesEnum: ...
    def ExportNumberDrawings(self, ) -> int: ...
    def ExportOpenGraphicObjectAttributesHandler(self, pOpenGraphicObjectAttributes: dotGrOpenGraphicObjectAttributes_t, ObjectType: int) -> int: ...
    def ExportOperationHandler(self, pHandler: dotGrOperationHandler_t) -> int: ...
    def ExportPartAttributesHandler(self, pPartAttributes: dotGrPartAttributes_t) -> int: ...
    def ExportPartHandler(self, pPart: dotGrPart_t) -> int: ...
    def ExportPickerCommandHandler(self, pPickerCommand: dotGrPickerCommand_t) -> ReturnValuesEnum: ...
    def ExportPickerHandler(self, pickerData: dotDrawingUIPickerWrapper_t) -> ReturnValuesEnum: ...
    def ExportPluginHandler(self, Plugin: dotGrPlugin_t, Filename: str, Applyvalues: bool) -> ReturnValuesEnum: ...
    def ExportPluginQueueHandler(self, pPluginQueue: dotGrPluginQueue_t) -> ReturnValuesEnum: ...
    def ExportPointListHandler(self, pPointList: dotGrPointList_t) -> int: ...
    def ExportPolygonHandler(self, pPolygon: dotGrPolygon_t) -> int: ...
    def ExportPolylineHandler(self, pPolyline: dotGrPolyline_t) -> int: ...
    def ExportPourAttributesHandler(self, pPourAttributes: dotGrPourAttributes_t) -> int: ...
    def ExportPourBreakAttributesHandler(self, pPourBreakAttributes: dotGrPourBreakAttributes_t) -> ReturnValuesEnum: ...
    def ExportPourBreakHandler(self, pPourBreak: dotGrPourBreak_t) -> ReturnValuesEnum: ...
    def ExportPourHandler(self, pPour: dotGrPour_t) -> int: ...
    def ExportPrintDrawingHandler(self, pPrintDrawing: dotGrPrintDrawing_t) -> int: ...
    def ExportRadiusDimensionAttributesHandler(self, RadiusDimAttr: dotGrRadiusDimensionAttributes_t) -> int: ...
    def ExportRadiusDimensionHandler(self, pRadiusDimension: dotGrRadiusDimension_t) -> int: ...
    def ExportRecreateSelectedDrawings(self, ) -> int: ...
    def ExportRectangleHandler(self, pRectangle: dotGrRectangle_t) -> int: ...
    def ExportRectangularCloudHandler(self, pRectangularCloud: dotGrRectangularCloud_t) -> int: ...
    def ExportReferenceModelAttributesHandler(self, pReferenceModelAttributes: dotGrReferenceModelAttributes_t) -> ReturnValuesEnum: ...
    def ExportReferenceModelHandler(self, pReferenceModel: dotGrReferenceModel_t) -> ReturnValuesEnum: ...
    def ExportRefreshColorMode(self, ) -> int: ...
    def ExportReinforcementBaseAttributesHandler(self, ReinforcementBaseAttributes: dotGrReinforcementBaseAttributes_t) -> ReturnValuesEnum: ...
    def ExportReinforcementHandler(self, pReinforcement: dotGrReinforcementBase_t) -> ReturnValuesEnum: ...
    def ExportReinforcementSetGroupGetModelIdentifiers(self, pIdentifiers: dotGrReinforcementSetGroupIdentifiers_t, modelIds: List) -> ReturnValuesEnum: ...
    def ExportSectionMarkAttributesHandler(self, pSectionMarkAttributes: dotGrSectionMarkAttributes_t) -> ReturnValuesEnum: ...
    def ExportSectionMarkHandler(self, pSectionMark: dotGrSectionMark_t) -> ReturnValuesEnum: ...
    def ExportSelectPartsByDrawings(self, ) -> int: ...
    def ExportSetColorRgb(self, color: int, red: int, green: int, blue: int) -> int: ...
    def ExportSetDocumentManagerController(self, documentManagerController: IDocumentManagerController) -> int: ...
    def ExportSetDrawingPlotDateById(self, drawingId: int) -> int: ...
    def ExportSetPenWidth(self, color: int, penWidth: int) -> int: ...
    def ExportShowAssociativityPinPushed(self, DrawingObjectId: int, IsStartPoint: int) -> int: ...
    def ExportShowAssociativityPinUnpushed(self, DrawingObjectId: int, IsStartPoint: int) -> int: ...
    def ExportShowColorPalette(self, color: int, hWndOwner: IntPtr) -> int: ...
    def ExportShowColorPaletteForHatchBackground(self, color: int, hWndOwner: IntPtr) -> int: ...
    def ExportSignalDocumentManagerClosed(self, ) -> int: ...
    def ExportSignalDrawingSelectionChanged(self, ) -> int: ...
    def ExportStraightDimensionHandler(self, StraightDimension: dotGrStraightDimension_t) -> int: ...
    def ExportStraightDimensionSetAttributesHandler(self, StraightDimensionSetAttributes: dotGrStraightDimensionSetAttributes_t) -> int: ...
    def ExportStraightDimensionSetExcludePartsAccordingToFilter(self, drawingObject: dotGrDrawingObject_t) -> int: ...
    def ExportStraightDimensionSetHandler(self, StraightDimensionSet: dotGrStraightDimensionSet_t) -> int: ...
    def ExportStringListHandler(self, pStringList: dotGrStringList_t) -> int: ...
    def ExportSurfacingAttributesHandler(self, pSurfacingAttributes: dotGrSurfacingAttributes_t) -> int: ...
    def ExportSurfacingHandler(self, pSurfacing: dotGrSurfacing_t) -> int: ...
    def ExportSymbolAttributesHandler(self, pSymbolAttributes: dotGrSymbolAttributes_t) -> int: ...
    def ExportSymbolHandler(self, pSymbol: dotGrSymbol_t) -> ReturnValuesEnum: ...
    def ExportTextAttributesHandler(self, pTextAttributes: dotGrTextAttributes_t) -> int: ...
    def ExportTextFileAttributesHandler(self, pTextFileAttributes: dotGrTextFileAttributes_t) -> ReturnValuesEnum: ...
    def ExportTextFileHandler(self, pTextFile: dotGrTextFile_t) -> ReturnValuesEnum: ...
    def ExportTextHandler(self, pText: dotGrText_t) -> ReturnValuesEnum: ...
    def ExportTryOpenDrawing(self, drawingId: int) -> int: ...
    def ExportUnhighlightCutInView(self, ViewId: int) -> int: ...
    def ExportUnhighlightGridLine(self, GridLineId: int) -> int: ...
    def ExportUnhighlightPartInView(self, ModelId: int, ViewId: int) -> int: ...
    def ExportUpdateSelectedDrawingMarks(self, ) -> int: ...
    def ExportUpdateSelectedDrawings(self, ) -> int: ...
    def ExportUserPropertyHandler(self, pProperty: dotGrUserProperty_t) -> ReturnValuesEnum: ...
    def ExportViewAttributesHandler(self, pViewAttributes: dotGrViewAttributes_t) -> int: ...
    def ExportViewCommandHandler(self, pViewCommand: dotGrViewCommand_t) -> ReturnValuesEnum: ...
    def ExportViewHandler(self, pView: dotGrView_t) -> ReturnValuesEnum: ...
    def ExportWeldAttributesHandler(self, pAttributes: dotGrWeldAttributes_t) -> ReturnValuesEnum: ...
    def ExportWeldHandler(self, pWeld: dotGrWeld_t) -> ReturnValuesEnum: ...
    def ExportWeldMarkAttributesHandler(self, pWeldMarkAttributes: dotGrWeldMarkAttributes_t) -> int: ...
    def ExportWeldMarkHandler(self, pWeldMark: dotGrWeldMark_t) -> int: ...
    def GetDrawingRuntimeIdFromFilename(self, drawingFilename: str) -> int: ...
    def GetDrawingViewVisibilityFilterValue(self, drawingViewId: int, drawingViewVisibilityFilterValue: str) -> bool: ...
    def GetRaiseReadWindowsNamesByViewIds(self, modelViewId: int, drawingViewId: int) -> bool: ...
    def ImportDoubleListHandler(self, pDoubleList: dotGrDoubleList_t) -> int: ...
    def ImportIntListHandler(self, pIntList: dotGrIntList_t) -> int: ...
    def ImportMarkElementListHandler(self, pElementList: dotGrElementList_t) -> int: ...
    def ImportPointListHandler(self, pPointList: dotGrPointList_t) -> int: ...
    def ImportStringListHandler(self, pStringList: dotGrStringList_t) -> int: ...
    def LoadAttributeFileNameToDialogAndApply(self, pAttributeFileName: str, pDialogName: str) -> bool: ...
    def LoadAttributeFileNameToDialogAndModify(self, pAttributeFileName: str, pDialogName: str) -> bool: ...

class IDocumentManagerController:
    """.NET: Tekla.Structures.DrawingInternal.IDocumentManagerController"""
    def __init__(self, *args) -> None: ...
    def GetSelectedDrawingGuids(self, ) -> IEnumerable: ...
    def GetVisibleDrawingIds(self, ) -> IEnumerable: ...
    def SetSelectedDrawings(self, drawingIds: IEnumerable) -> None: ...
    def ShowWindow(self, ) -> None: ...
    def UpdateDocumentManager(self, newDrawingIsNotNull: bool, newId: int, newType: int, oldDrawingIsNotNull: bool, oldId: int, oldType: int) -> None: ...

class IEventHandler:
    """.NET: Tekla.Structures.DrawingInternal.IEventHandler"""
    def __init__(self, *args) -> None: ...
    def AddListener(self, EventListener: IUIEvents) -> None: ...
    def RemoveListener(self, EventListener: IUIEvents) -> None: ...

class ISyncWrapper:
    """.NET: Tekla.Structures.DrawingInternal.ISyncWrapper"""
    def __init__(self, *args) -> None: ...
    def Sync(self, ) -> None: ...

class InternalOnlyAttribute(Attribute):
    """.NET: Tekla.Structures.DrawingInternal.InternalOnlyAttribute"""
    def __init__(self, *args) -> None: ...
    TypeId: object

class LayoutManager:
    """.NET: Tekla.Structures.DrawingInternal.LayoutManager"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ClearUndoLog() -> None: ...
    @staticmethod
    def CloseEditor() -> None: ...
    @staticmethod
    def CreateLayout(Name: str, Sizes: IEnumerable) -> bool: ...
    @staticmethod
    def DoCommit(LayoutMode: bool) -> None: ...
    @staticmethod
    def DoesLayoutExist(name: str) -> bool: ...
    @staticmethod
    def DoesTableLayoutExist(name: str) -> bool: ...
    @staticmethod
    def GetAvailableLayouts() -> List: ...
    @staticmethod
    def GetDrawingFoldmark() -> Tuple: ...
    @staticmethod
    def GetDrawingFrames() -> List: ...
    @staticmethod
    def GetDrawingSize() -> Tuple: ...
    @staticmethod
    def GetDrawingSizes(layoutName: str) -> IList: ...
    @staticmethod
    def HiddenTableVisibility() -> bool: ...
    @staticmethod
    def InLocalChangesState() -> bool: ...
    @staticmethod
    def IsLayoutEditorOpenedFromModelMode() -> bool: ...
    @staticmethod
    def ModifyDrawingSize(newSizeId: int, currentSizes: IEnumerable) -> int: ...
    @staticmethod
    def OpenEditor() -> None: ...
    @staticmethod
    def RefreshUI() -> None: ...
    @staticmethod
    def RepairDrawingSizes() -> None: ...
    @staticmethod
    def ResetDrawingSize(drawingSizeId: int) -> None: ...
    @staticmethod
    def ResetLayout(layoutName: str, CurrentSizes: IEnumerable) -> int: ...
    @staticmethod
    def SetDrawingFoldmark(foldMark: Tuple) -> None: ...
    @staticmethod
    def SetDrawingFrames(frames: IEnumerable) -> None: ...
    @staticmethod
    def SetDrawingSizes(newSizes: IEnumerable, currentSizeId: int) -> bool: ...
    @staticmethod
    def SetHiddenTableVisibility(Visibility: bool) -> None: ...
    @staticmethod
    def SetNameVisibility(Visibility: bool) -> None: ...
    @staticmethod
    def ShouldOpenActiveLayout() -> bool: ...
    @staticmethod
    def ShowSaveDialog() -> None: ...
    @staticmethod
    def TableNameVisibility() -> bool: ...
    @staticmethod
    def ZoomToLayout() -> None: ...

class LayoutOptionEnum:
    """.NET: Tekla.Structures.DrawingInternal.LayoutOptionEnum"""
    def __init__(self, *args) -> None: ...
    ...

class LayoutOptionTypeEnum:
    """.NET: Tekla.Structures.DrawingInternal.LayoutOptionTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class LayoutOptions:
    """.NET: Tekla.Structures.DrawingInternal.LayoutOptions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetDrawingTypeAllowed(drawingType: int) -> bool: ...
    @staticmethod
    def GetOptionDouble(option: LayoutOptionEnum) -> float: ...
    @staticmethod
    def GetOptionInt(option: LayoutOptionEnum) -> int: ...
    @staticmethod
    def GetOptionStr(option: LayoutOptionEnum) -> str: ...
    @staticmethod
    def GetOptionType(option: LayoutOptionEnum) -> LayoutOptionTypeEnum: ...
    @staticmethod
    def SetDrawingTypeAllowed(drawingType: int, Allowed: bool) -> None: ...
    @staticmethod
    def SetOption(option: LayoutOptionEnum, newValue: int) -> None: ...

class LayoutTable:
    """.NET: Tekla.Structures.DrawingInternal.LayoutTable"""
    def __init__(self, *args) -> None: ...
    Name: str
    RefTableId: int
    Scale: float
    XOffset: float
    YOffset: float
    TableLayoutId: int
    TableCorner: int
    RefCorner: int
    Id: int
    FileName: str
    OverlapVithViews: bool
    Angle: float
    TableType: int
    Flags: int
    OriginalTableId: int
    OriginalDbId: int
    def Delete(self, ) -> bool: ...
    def GetDecoratedName(self, ) -> str: ...
    def GetDrawingNames(self, ) -> List: ...
    def HasLocalInstance(self, ) -> bool: ...
    def Insert(self, PickedPoint: Point) -> bool: ...
    def IsTableDwg(self, ) -> bool: ...
    def IsTableKeyplan(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...
    def SetTableDwgDxf(self, ) -> None: ...
    def SetTableKeyPlan(self, ) -> None: ...
    def ToString(self, ) -> str: ...

class MarkLearning:
    """.NET: Tekla.Structures.DrawingInternal.MarkLearning"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CountModelObjectTypes(drawingId: int, viewId: int) -> Dictionary: ...
    @staticmethod
    def CountModelObjectTypesFromCurrentDrawing(viewId: int) -> Dictionary: ...
    @staticmethod
    def GetMarkContent(markId: int) -> ContainerElement: ...
    @staticmethod
    def GetViewAttributes(drawingId: int, viewId: int) -> Dictionary: ...
    @staticmethod
    def GetViewAttributesFromCurrentDrawing(viewId: int) -> Dictionary: ...
    @staticmethod
    def ListDrawingModelObjectsInView(drawingId: int, viewId: int) -> Dictionary: ...

class MarkLearningCommandEnum:
    """.NET: Tekla.Structures.DrawingInternal.MarkLearningCommandEnum"""
    def __init__(self, *args) -> None: ...
    ...

class MarkListing:
    """.NET: Tekla.Structures.DrawingInternal.MarkListing"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetMenuName(currentMenuName: str) -> bool: ...
    @staticmethod
    def TryGetMarks(modelObjectId: int, viewIds: IList, marksIds: IList) -> bool: ...

class Operation:
    """.NET: Tekla.Structures.DrawingInternal.Operation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddDimensioningRuleAndModify(view: View, filter: str, operation: str, property: str) -> bool: ...
    @staticmethod
    def AddObjectsToViewAndModify(view: View, objects: List) -> bool: ...
    @staticmethod
    def AddToMasterDrawingCatalog() -> bool: ...
    @staticmethod
    def ArePoursShownInDrawing() -> bool: ...
    @staticmethod
    def CopySelectedDrawingsToNewSheet() -> bool: ...
    @staticmethod
    def CreateViewWithoutLoadingAttributes(identifier: Identifier, viewIdentifier: Identifier, drawingIdentifier: Identifier) -> View: ...
    @staticmethod
    def DeleteSelectedDrawings() -> bool: ...
    @staticmethod
    def DisplayDrawingCloningDialog() -> bool: ...
    @staticmethod
    def DisplayDrawingPropertiesDialog() -> bool: ...
    @staticmethod
    def DisplayDrawingUdaDialog() -> bool: ...
    @staticmethod
    def DisplayRevisionDialog() -> bool: ...
    @staticmethod
    def DisplaySnapshotDialogByFileName(fileName: str) -> bool: ...
    @staticmethod
    def DisplaySnapshotsDialog() -> bool: ...
    @staticmethod
    def DisplaySnapshotsDialogByGuid(guid: str) -> bool: ...
    @staticmethod
    def FillSelectedDrawings(Param: str) -> str: ...
    @staticmethod
    def FillVisibleDrawings(Param: str) -> str: ...
    @staticmethod
    def FilterDrawingListByParts() -> bool: ...
    @staticmethod
    def GetAllColorPaletteFilePaths() -> List: ...
    @staticmethod
    def GetCachedDrawing(drawingId: Identifier) -> Drawing: ...
    @staticmethod
    def GetDocumentManagerController(documentManagerController: IDocumentManagerController) -> bool: ...
    @staticmethod
    def GetDrawing(drawingId: Identifier) -> Drawing: ...
    @staticmethod
    def GetDrawingObject(id: Identifier, drawingIdentifier: Identifier) -> DrawingObject: ...
    @staticmethod
    def GetDrawingToObjectMapping(drawings: IEnumerable) -> IEnumerable: ...
    @staticmethod
    def GetDrawingViewVisibilityFilterValue(drawingViewId: int, drawingViewVisibilityFilterValue: str) -> bool: ...
    @staticmethod
    def GetDrawingsBySelectedParts(ignoreFilters: bool, ignoreGADrawings: bool) -> IEnumerable: ...
    @staticmethod
    def GetEditMode() -> EditMode: ...
    @staticmethod
    def GetNextModelObjectIdentifier(drawingId: int) -> Identifier: ...
    @staticmethod
    def GetNumberOfNonUpToDateObjectsAndPours() -> int: ...
    @staticmethod
    def HighlightCutInView(ModelId: int, SectionViewId: int, ContextViewId: int) -> int: ...
    @staticmethod
    def HighlightGridLine(GridLineId: int) -> int: ...
    @staticmethod
    def HighlightPartInView(ModelId: int, ViewId: int) -> int: ...
    @staticmethod
    def NumberDrawings() -> bool: ...
    @staticmethod
    def RaiseReadWindowsNamesByViewIds(modelViewId: int, drawingViewId: int) -> bool: ...
    @staticmethod
    def RecreateSelectedDrawings() -> bool: ...
    @staticmethod
    def RefreshColorMode() -> bool: ...
    @staticmethod
    def Select(drawingObjects: ArrayList, suppressCallbacks: bool) -> bool: ...
    @staticmethod
    def SelectPartsByDrawings() -> int: ...
    @staticmethod
    def SetColorRgb(color: int, red: int, green: int, blue: int) -> bool: ...
    @staticmethod
    def SetDocumentManagerController(documentManagerController: IDocumentManagerController) -> bool: ...
    @staticmethod
    def SetDocumentManagerSelectedDrawing(Param: str) -> str: ...
    @staticmethod
    def SetDocumentManagerSelectedDrawings(drawingIds: IEnumerable) -> str: ...
    @staticmethod
    def SetDrawingPlotDateById(drawingId: int) -> bool: ...
    @staticmethod
    def SetPenWidth(color: int, penWidth: int) -> bool: ...
    @staticmethod
    def ShowAssociativityPinPushed(DrawingObjectId: int, IsStartPoint: int) -> int: ...
    @staticmethod
    def ShowAssociativityPinUnpushed(DrawingObjectId: int, IsStartPoint: int) -> int: ...
    @staticmethod
    def ShowDocumentManagerWindow(Param: str) -> str: ...
    @staticmethod
    def SignalDocumentManagerClosed() -> bool: ...
    @staticmethod
    def SignalDrawingSelectionChanged() -> bool: ...
    @staticmethod
    def TryOpenDrawing(drawingId: int) -> bool: ...
    @staticmethod
    def UnhighlightCutInView(ViewId: int) -> int: ...
    @staticmethod
    def UnhighlightGridLine(GridLineId: int) -> int: ...
    @staticmethod
    def UnhighlightPartInView(ModelId: int, ViewId: int) -> int: ...
    @staticmethod
    def UpdateDocumentManager(param: str) -> str: ...
    @staticmethod
    def UpdateSelectedDrawingMarks() -> bool: ...
    @staticmethod
    def UpdateSelectedDrawings() -> bool: ...

class PluginOperation:
    """.NET: Tekla.Structures.DrawingInternal.PluginOperation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def WaitInPluginQueue() -> bool: ...

class PointAssociativityRule:
    """.NET: Tekla.Structures.DrawingInternal.PointAssociativityRule"""
    def __init__(self, *args) -> None: ...
    RuleId: int
    PointType: AssociativityPointTypeEnum
    PointIndex: int
    ObjectId1: Identifier
    PlaneName1: str
    ObjectId2: Identifier
    PlaneName2: str
    ObjectId3: Identifier
    PlaneName3: str
    IsCenterBased: bool

class PropertyType:
    """.NET: Tekla.Structures.DrawingInternal.PropertyType"""
    def __init__(self, *args) -> None: ...
    ...

class QueryTypeEnum:
    """.NET: Tekla.Structures.DrawingInternal.QueryTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class Remoter:
    """.NET: Tekla.Structures.DrawingInternal.Remoter"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def DisposeService() -> None: ...
    @staticmethod
    def InitializeSandBox() -> bool: ...

class ReturnValuesEnum:
    """.NET: Tekla.Structures.DrawingInternal.ReturnValuesEnum"""
    def __init__(self, *args) -> None: ...
    ...

class RevisionMark(DrawingObject):
    """.NET: Tekla.Structures.DrawingInternal.RevisionMark"""
    def __init__(self, *args) -> None: ...
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, objectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ScopedCDelegateSetter:
    """.NET: Tekla.Structures.DrawingInternal.ScopedCDelegateSetter"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class SyncHandler:
    """.NET: Tekla.Structures.DrawingInternal.SyncHandler"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, ) -> None: ...

class SyncWrapper(MarshalByRefObject):
    """.NET: Tekla.Structures.DrawingInternal.SyncWrapper"""
    def __init__(self, *args) -> None: ...
    def Sync(self, ) -> None: ...

class TSDrawingColorHandler:
    """.NET: Tekla.Structures.DrawingInternal.TSDrawingColorHandler"""
    def __init__(self, *args) -> None: ...
    StandardColorInfo: List
    StandardColors: BidirectionalDictionary
    StandardColorNames: List
    @staticmethod
    def GetAsTrueColor(inputColor: DrawingColors) -> TeklaDrawingColor: ...
    @staticmethod
    def GetColorIndexFromRGB(red: int, green: int, blue: int) -> int: ...
    @staticmethod
    def GetColorIndexFromSaveFormat(saveFormat: str) -> int: ...
    @staticmethod
    def GetColorIndexFromSystemDrawingColor(color: Color) -> int: ...
    @staticmethod
    def GetSaveFormatFromColorIndex(colorIndex: int) -> str: ...
    @staticmethod
    def GetStandardColorEnums() -> List: ...
    @staticmethod
    def GetStandardColorNames() -> List: ...
    @staticmethod
    def GetStandardColors() -> List: ...
    @staticmethod
    def IsStandardColor(colorIndex: int) -> bool: ...
    @staticmethod
    def TryGetRGBFromColorIndex(colorIndex: int, red: int, green: int, blue: int) -> bool: ...
    @staticmethod
    def TryGetSystemDrawingColor(colorIndex: int, color: Color) -> bool: ...

class TableLayout:
    """.NET: Tekla.Structures.DrawingInternal.TableLayout"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AreEqualInSizes(firstSize: int, secondSize: int) -> bool: ...
    @staticmethod
    def GetAllTemplates() -> List: ...
    @staticmethod
    def GetCurrentTables() -> List: ...
    @staticmethod
    def GetMarginsAndSpaces(marginH: float, marginV: float, spaceH: float, spaceV: float) -> None: ...
    @staticmethod
    def GetSelectedTables() -> List: ...
    @staticmethod
    def IsValid() -> bool: ...
    @staticmethod
    def ModifyMarginsAndSpaces(marginH: float, marginV: float, spaceH: float, spaceV: float) -> None: ...
    @staticmethod
    def Save(usedSizeIds: List) -> bool: ...
    @staticmethod
    def SaveAs(name: str, usedSizeIds: List) -> bool: ...
    @staticmethod
    def SelectTable(table: LayoutTable) -> None: ...
    @staticmethod
    def TryGetTranslatedSpecialTableStrings(keyplan: str, dwgDxf: str) -> None: ...
    @staticmethod
    def UnselectTables() -> None: ...

class dak_dndeffect_t:
    """.NET: Tekla.Structures.DrawingInternal.dak_dndeffect_t"""
    def __init__(self, *args) -> None: ...
    ...

class dak_eventtype_t:
    """.NET: Tekla.Structures.DrawingInternal.dak_eventtype_t"""
    def __init__(self, *args) -> None: ...
    ...

class dak_modifier_t:
    """.NET: Tekla.Structures.DrawingInternal.dak_modifier_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotARGBColor_t:
    """.NET: Tekla.Structures.DrawingInternal.dotARGBColor_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotClientId_t:
    """.NET: Tekla.Structures.DrawingInternal.dotClientId_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotDrawingObjectSelector_t:
    """.NET: Tekla.Structures.DrawingInternal.dotDrawingObjectSelector_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotDrawingUIPickerWrapper_t:
    """.NET: Tekla.Structures.DrawingInternal.dotDrawingUIPickerWrapper_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotDrawingUIPicker_t:
    """.NET: Tekla.Structures.DrawingInternal.dotDrawingUIPicker_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotEnumerator_t:
    """.NET: Tekla.Structures.DrawingInternal.dotEnumerator_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrAngleDimensionAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrAngleDimensionAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: AngleDimensionAttributes) -> None: ...
    def ToStruct(self, attributes: AngleDimensionAttributes) -> None: ...

class dotGrAngleDimension_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrAngleDimension_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, angleDimension: AngleDimension) -> None: ...
    def ToStruct(self, angleDimension: AngleDimension) -> None: ...

class dotGrArcAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrArcAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, arcAttributes: ArcAttributes) -> None: ...
    def ToStruct(self, arcAttributes: ArcAttributes) -> None: ...

class dotGrArc_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrArc_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, arc: Arc) -> None: ...
    def ToStruct(self, arc: Arc) -> None: ...

class dotGrArrowheadAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrArrowheadAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ArrowheadAttributes) -> None: ...
    def ToStruct(self, attributes: ArrowheadAttributes) -> None: ...

class dotGrAssociativityHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrAssociativityHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrAssociativity_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrAssociativity_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: AttributesBase) -> None: ...
    def ToStruct(self, Attributes: AttributesBase) -> None: ...

class dotGrAutomation_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrAutomation_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrBoltAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrBoltAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, boltAttributes: BoltAttributes) -> None: ...
    def ToStruct(self, boltAttributes: BoltAttributes) -> None: ...

class dotGrBolt_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrBolt_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Bolt: Bolt) -> None: ...
    def ToStruct(self, Bolt: Bolt) -> None: ...

class dotGrCircleAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCircleAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, CircleAttributes: CircleAttributes) -> None: ...
    def ToStruct(self, CircleAttributes: CircleAttributes) -> None: ...

class dotGrCircle_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCircle_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Circle: Circle) -> None: ...
    def ToStruct(self, Circle: Circle) -> None: ...

class dotGrCloningHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCloningHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrClosedGraphicObjectAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrClosedGraphicObjectAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, ClosedGraphicObject: ClosedGraphicObjectAttributes) -> None: ...
    def ToStruct(self, ClosedGraphicObject: ClosedGraphicObjectAttributes) -> None: ...

class dotGrClosedGraphicObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrClosedGraphicObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, ClosedGraphicObject: ClosedGraphicObject) -> None: ...
    def ToStruct(self, ClosedGraphicObject: ClosedGraphicObject) -> None: ...

class dotGrCloudAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCloudAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, CloudAttributes: CloudAttributes) -> None: ...
    def ToStruct(self, CloudAttributes: CloudAttributes) -> None: ...

class dotGrCloudBase_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCloudBase_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, cloudBase: CloudBase) -> None: ...
    def ToStruct(self, cloudBase: CloudBase) -> None: ...

class dotGrCloud_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCloud_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, cloud: Cloud) -> None: ...
    def ToStruct(self, cloud: Cloud) -> None: ...

class dotGrCombinedDimensionAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCombinedDimensionAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: CombinedDimensionAttributes) -> None: ...
    def ToStruct(self, attributes: CombinedDimensionAttributes) -> None: ...

class dotGrConnection_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrConnection_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, part: Connection) -> None: ...
    def ToStruct(self, part: Connection) -> None: ...

class dotGrCurvedDimensionOrthogonal_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionOrthogonal_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, CurvedDimension: CurvedDimensionOrthogonal) -> None: ...
    def ToStruct(self, CurvedDimension: CurvedDimensionOrthogonal) -> None: ...

class dotGrCurvedDimensionRadial_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionRadial_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, CurvedDimension: CurvedDimensionRadial) -> None: ...
    def ToStruct(self, CurvedDimension: CurvedDimensionRadial) -> None: ...

class dotGrCurvedDimensionSetBaseAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionSetBaseAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: CurvedDimensionSetBaseAttributes) -> None: ...
    def ToStruct(self, attributes: CurvedDimensionSetBaseAttributes) -> None: ...

class dotGrCurvedDimensionSetOrthogonalAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionSetOrthogonalAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: CurvedDimensionSetOrthogonalAttributes) -> None: ...
    def ToStruct(self, attributes: CurvedDimensionSetOrthogonalAttributes) -> None: ...

class dotGrCurvedDimensionSetOrthogonal_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionSetOrthogonal_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, CurvedDimension: CurvedDimensionSetOrthogonal) -> None: ...
    def ToStruct(self, CurvedDimension: CurvedDimensionSetOrthogonal) -> None: ...

class dotGrCurvedDimensionSetRadialAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionSetRadialAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: CurvedDimensionSetRadialAttributes) -> None: ...
    def ToStruct(self, attributes: CurvedDimensionSetRadialAttributes) -> None: ...

class dotGrCurvedDimensionSetRadial_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCurvedDimensionSetRadial_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, CurvedDimension: CurvedDimensionSetRadial) -> None: ...
    def ToStruct(self, CurvedDimension: CurvedDimensionSetRadial) -> None: ...

class dotGrCustomLineTypes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrCustomLineTypes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, ) -> None: ...
    def ToStruct(self, ) -> None: ...

class dotGrDakDoubleList_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDakDoubleList_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrDakEvent_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDakEvent_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrDatabaseObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDatabaseObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, databaseObject: DatabaseObject) -> None: ...
    def ToStruct(self, databaseObject: DatabaseObject) -> None: ...

class dotGrDate_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDate_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Date: DateTime) -> None: ...

class dotGrDetailMarkAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDetailMarkAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: DetailMarkAttributes) -> None: ...
    def ToStruct(self, Attributes: DetailMarkAttributes) -> None: ...

class dotGrDetailMarkTagsAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDetailMarkTagsAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: DetailMarkTagsAttributes) -> None: ...
    def ToStruct(self, attributes: DetailMarkTagsAttributes) -> None: ...

class dotGrDetailMark_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDetailMark_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, detailMark: DetailMark) -> None: ...
    def ToStruct(self, detailMark: DetailMark) -> None: ...

class dotGrDimensionBase_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionBase_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, dimension: DimensionBase) -> None: ...
    def ToStruct(self, dimension: DimensionBase) -> None: ...

class dotGrDimensionExaggerationAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionExaggerationAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: DimensionExaggerationAttributes) -> None: ...
    def ToStruct(self, attributes: DimensionExaggerationAttributes) -> None: ...

class dotGrDimensionFormatAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionFormatAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: DimensionFormatAttributes) -> None: ...
    def ToStruct(self, attributes: DimensionFormatAttributes) -> None: ...

class dotGrDimensionLink_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionLink_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Link: DimensionLink) -> None: ...
    def ToStruct(self, Link: DimensionLink) -> None: ...

class dotGrDimensionPlacingAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionPlacingAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: DimensionPlacingAttributes) -> None: ...
    def ToStruct(self, attributes: DimensionPlacingAttributes) -> None: ...

class dotGrDimensionSetBaseAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionSetBaseAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: DimensionSetBaseAttributes) -> None: ...
    def ToStruct(self, attributes: DimensionSetBaseAttributes) -> None: ...

class dotGrDimensionSetBase_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionSetBase_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, dimension: DimensionSetBase) -> None: ...
    def ToStruct(self, dimension: DimensionSetBase) -> None: ...

class dotGrDimensionTextAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDimensionTextAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: DimensionTextAttributes) -> None: ...
    def ToStruct(self, attributes: DimensionTextAttributes) -> None: ...

class dotGrDoubleList_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDoubleList_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, doubleList: List) -> None: ...
    def ToStruct(self, doubleList: List) -> None: ...

class dotGrDrawingAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDrawingAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Drawing: Drawing) -> None: ...
    def ToStruct(self, Drawing: Drawing) -> None: ...

class dotGrDrawingHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDrawingHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrDrawingObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrDrawingObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, drawingObject: DrawingObject) -> None: ...
    def ToStruct(self, drawingObject: DrawingObject) -> None: ...

class dotGrEdgeChamferAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrEdgeChamferAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, chamferAttributes: EdgeChamferAttributes) -> None: ...
    def ToStruct(self, chamferAttributes: EdgeChamferAttributes) -> None: ...

class dotGrEdgeChamfer_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrEdgeChamfer_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, chamfer: EdgeChamfer) -> None: ...
    def ToStruct(self, chamfer: EdgeChamfer) -> None: ...

class dotGrElementList_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrElementList_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrElement_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrElement_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrEmbeddedObjectAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrEmbeddedObjectAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, EmbeddedObjectAttributes: EmbeddedObjectAttributes) -> None: ...
    def ToStruct(self, EmbeddedObjectAttributes: EmbeddedObjectAttributes) -> None: ...

class dotGrEmbeddedObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrEmbeddedObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, obj: EmbeddedObjectBase) -> None: ...
    def ToStruct(self, obj: EmbeddedObjectBase) -> None: ...

class dotGrFontAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrFontAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: FontAttributes) -> None: ...
    def ToStruct(self, attributes: FontAttributes) -> None: ...

class dotGrFrame_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrFrame_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Frame: Frame) -> None: ...
    def ToStruct(self, Frame: Frame) -> None: ...

class dotGrGraphicObjectAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGraphicObjectAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, graphicObjectAttributes: GraphicObjectAttributes) -> None: ...
    def ToStruct(self, graphicObjectAttributes: GraphicObjectAttributes) -> None: ...

class dotGrGraphicObjectHatchAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGraphicObjectHatchAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: GraphicObjectHatchAttributes) -> None: ...
    def ToStruct(self, attributes: GraphicObjectHatchAttributes) -> None: ...

class dotGrGraphicObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGraphicObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, graphicObject: GraphicObject) -> None: ...
    def ToStruct(self, graphicObject: GraphicObject) -> None: ...

class dotGrGridAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGridAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, grid: GridAttributes) -> None: ...
    def ToStruct(self, grid: GridAttributes) -> None: ...

class dotGrGridLabel_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGridLabel_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, gridLabel: GridLabel) -> None: ...
    def ToStruct(self, gridLabel: GridLabel) -> None: ...

class dotGrGridLineAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGridLineAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, gridLine: GridLineAttributes) -> None: ...
    def ToStruct(self, gridLine: GridLineAttributes) -> None: ...

class dotGrGridLine_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGridLine_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, gridLine: GridLine) -> None: ...
    def ToStruct(self, gridLine: GridLine) -> None: ...

class dotGrGrid_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrGrid_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, grid: Grid) -> None: ...
    def ToStruct(self, grid: Grid) -> None: ...

class dotGrHatchAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrHatchAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: HatchAttributes) -> None: ...
    def ToStruct(self, attributes: HatchAttributes) -> None: ...

class dotGrHatchLineAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrHatchLineAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, HatchLineAttributes: HatchLineAttributes) -> None: ...
    def ToStruct(self, HatchLineAttributes: HatchLineAttributes) -> None: ...

class dotGrHatchLine_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrHatchLine_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, hatchLine: HatchLine) -> None: ...
    def ToStruct(self, hatchLine: HatchLine) -> None: ...

class dotGrHideable_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrHideable_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pObject: Hideable) -> None: ...
    def ToStruct(self, pObject: Hideable) -> None: ...

class dotGrIntList_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrIntList_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, intList: List) -> None: ...
    def ToStruct(self, intList: List) -> None: ...

class dotGrLayTable_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLayTable_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Table: LayoutTable) -> None: ...
    def ToStruct(self, Table: LayoutTable) -> None: ...

class dotGrLayoutAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLayoutAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: LayoutAttributes) -> None: ...
    def ToStruct(self, attributes: LayoutAttributes) -> None: ...

class dotGrLayoutHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLayoutHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrLeaderLine_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLeaderLine_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, LeaderLine: LeaderLine) -> None: ...
    def ToStruct(self, LeaderLine: LeaderLine) -> None: ...

class dotGrLevelMarkAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLevelMarkAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: LevelMarkAttributes) -> None: ...
    def ToStruct(self, Attributes: LevelMarkAttributes) -> None: ...

class dotGrLevelMark_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLevelMark_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, levelmark: LevelMark) -> None: ...
    def ToStruct(self, levelmark: LevelMark) -> None: ...

class dotGrLineAttributesStruct_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLineAttributesStruct_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, lineAttributes: LineAttributes) -> None: ...
    def ToStruct(self, lineAttributes: LineAttributes) -> None: ...

class dotGrLineAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLineAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: LineTypeAttributes) -> None: ...
    def ToStruct(self, attributes: LineTypeAttributes) -> None: ...

class dotGrLineTypes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLineTypes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, lineTypes: LineTypes) -> None: ...
    def ToStruct(self, lineTypes: LineTypes) -> None: ...

class dotGrLine_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLine_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, line: Line) -> None: ...
    def ToStruct(self, line: Line) -> None: ...

class dotGrLinkAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLinkAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, obj: LinkAttributes) -> None: ...
    def ToStruct(self, obj: LinkAttributes) -> None: ...

class dotGrLink_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrLink_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, obj: HyperLink) -> None: ...
    def ToStruct(self, obj: HyperLink) -> None: ...

class dotGrMarkBaseAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrMarkBaseAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: MarkBaseAttributes) -> None: ...
    def ToStruct(self, attributes: MarkBaseAttributes) -> None: ...

class dotGrMarkBase_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrMarkBase_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, mark: MarkBase) -> None: ...
    def ToStruct(self, mark: MarkBase) -> None: ...

class dotGrMarkLearningHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrMarkLearningHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrMarkListingHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrMarkListingHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrModelObjectHatchAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrModelObjectHatchAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ModelObjectHatchAttributes) -> None: ...
    def ToStruct(self, attributes: ModelObjectHatchAttributes) -> None: ...

class dotGrModelObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrModelObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pObject: ModelObject) -> None: ...
    def ToStruct(self, pObject: ModelObject) -> None: ...

class dotGrModelViewCreation_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrModelViewCreation_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrOpenGraphicObjectAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrOpenGraphicObjectAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, openGraphicObject: OpenGraphicObjectAttributes) -> None: ...
    def ToStruct(self, openGraphicObject: OpenGraphicObjectAttributes) -> None: ...

class dotGrOpenGraphicObject_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrOpenGraphicObject_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, openGraphicObject: OpenGraphicObject) -> None: ...
    def ToStruct(self, openGraphicObject: OpenGraphicObject) -> None: ...

class dotGrOperationHandler_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrOperationHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrPartAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPartAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, partAttributes: PartAttributes) -> None: ...
    def ToStruct(self, partAttributes: PartAttributes) -> None: ...

class dotGrPart_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPart_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, part: Part) -> None: ...
    def ToStruct(self, part: Part) -> None: ...

class dotGrPath_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPath_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, path: str) -> None: ...
    def ToStruct(self, path: str) -> None: ...

class dotGrPickerCommand_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPickerCommand_t"""
    def __init__(self, *args) -> None: ...
    def GetIsInteractivePicker(self, ) -> bool: ...
    def ToStruct(self, ) -> None: ...

class dotGrPlacingAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPlacingAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: PlacingAttributes) -> None: ...
    def ToStruct(self, attributes: PlacingAttributes) -> None: ...

class dotGrPlacingDirectionAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPlacingDirectionAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: PlacingDirectionAttributes) -> None: ...
    def ToStruct(self, attributes: PlacingDirectionAttributes) -> None: ...

class dotGrPlacingDistanceAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPlacingDistanceAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: PlacingDistanceAttributes) -> None: ...
    def ToStruct(self, attributes: PlacingDistanceAttributes) -> None: ...

class dotGrPlacingQuarterAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPlacingQuarterAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: PlacingQuarterAttributes) -> None: ...
    def ToStruct(self, attributes: PlacingQuarterAttributes) -> None: ...

class dotGrPlacing_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPlacing_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, PlacingBase: PlacingBase) -> None: ...
    def ToStruct(self, PlacingBase: PlacingBase, preferredPlacingTypeBase: PreferredPlacingTypeBase) -> None: ...

class dotGrPluginQueue_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPluginQueue_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrPlugin_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPlugin_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, plugin: Plugin) -> None: ...
    def ToStruct(self, plugin: Plugin) -> None: ...

class dotGrPointList_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPointList_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pointList: List) -> None: ...
    def ToStruct(self, pointList: List) -> None: ...

class dotGrPolygonAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPolygonAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, PolygonAttributes: PolygonAttributes) -> None: ...
    def ToStruct(self, PolygonAttributes: PolygonAttributes) -> None: ...

class dotGrPolygon_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPolygon_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, polygon: Polygon) -> None: ...
    def ToStruct(self, polygon: Polygon) -> None: ...

class dotGrPolylineAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPolylineAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, polylineAttributes: PolylineAttributes) -> None: ...
    def ToStruct(self, polylineAttributes: PolylineAttributes) -> None: ...

class dotGrPolyline_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPolyline_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, polyline: Polyline) -> None: ...
    def ToStruct(self, polyline: Polyline) -> None: ...

class dotGrPourAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPourAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pourAttributes: PourAttributes) -> None: ...
    def ToStruct(self, pourAttributes: PourAttributes) -> None: ...

class dotGrPourBreakAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPourBreakAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pourBreakAttributes: PourBreakAttributes) -> None: ...
    def ToStruct(self, pourBreakAttributes: PourBreakAttributes) -> None: ...

class dotGrPourBreak_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPourBreak_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pourBreak: PourBreak) -> None: ...
    def ToStruct(self, pourBreak: PourBreak) -> None: ...

class dotGrPour_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPour_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pour: PourObject) -> None: ...
    def ToStruct(self, pour: PourObject) -> None: ...

class dotGrPreferredPlacingType_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPreferredPlacingType_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Placing: PreferredPlacingTypeBase) -> None: ...
    def ToStruct(self, preferredPlacingType: PreferredPlacingTypeBase) -> None: ...

class dotGrPrintAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPrintAttributes_t"""
    def __init__(self, *args) -> None: ...
    def ToStruct(self, attributes: PrintAttributes, FileName: str) -> None: ...

class dotGrPrintDrawing_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrPrintDrawing_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrRadiusDimensionAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrRadiusDimensionAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: RadiusDimensionAttributes) -> None: ...
    def ToStruct(self, attributes: RadiusDimensionAttributes) -> None: ...

class dotGrRadiusDimension_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrRadiusDimension_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, RadiusDimension: RadiusDimension) -> None: ...
    def ToStruct(self, RadiusDimension: RadiusDimension) -> None: ...

class dotGrRectangleAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrRectangleAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, RectangleAttributes: RectangleAttributes) -> None: ...
    def ToStruct(self, RectangleAttributes: RectangleAttributes) -> None: ...

class dotGrRectangle_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrRectangle_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, rectangle: Rectangle) -> None: ...
    def ToStruct(self, rectangle: Rectangle) -> None: ...

class dotGrRectangularCloudAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrRectangularCloudAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, RectangularCloudAttributes: RectangularCloudAttributes) -> None: ...
    def ToStruct(self, RectangularCloudAttributes: RectangularCloudAttributes) -> None: ...

class dotGrRectangularCloud_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrRectangularCloud_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, rectangularCloud: RectangularCloud) -> None: ...
    def ToStruct(self, rectangularCloud: RectangularCloud) -> None: ...

class dotGrReferenceModelAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrReferenceModelAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attr: ReferenceModelAttributes) -> None: ...
    def ToStruct(self, attr: ReferenceModelAttributes) -> None: ...

class dotGrReferenceModel_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrReferenceModel_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, model: ReferenceModel) -> None: ...
    def ToStruct(self, model: ReferenceModel) -> None: ...

class dotGrReinforcementBaseAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrReinforcementBaseAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, reinforcementAttributes: ReinforcementBaseAttributes) -> None: ...
    def ToStruct(self, reinforcementAttributes: ReinforcementBaseAttributes) -> None: ...

class dotGrReinforcementBase_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrReinforcementBase_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, reinforcement: ReinforcementBase) -> None: ...
    def ToStruct(self, reinforcement: ReinforcementBase) -> None: ...

class dotGrReinforcementSetGroupIdentifiers_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrReinforcementSetGroupIdentifiers_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrSectionMarkAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSectionMarkAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: SectionMarkAttributes) -> None: ...
    def ToStruct(self, Attributes: SectionMarkAttributes) -> None: ...

class dotGrSectionMarkSymbol_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSectionMarkSymbol_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, MarkSymbol: SectionMarkSymbol) -> None: ...
    def ToStruct(self, MarkSymbol: SectionMarkSymbol) -> None: ...

class dotGrSectionMarkTagAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSectionMarkTagAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: SectionMarkTagAttributes) -> None: ...
    def ToStruct(self, attributes: SectionMarkTagAttributes) -> None: ...

class dotGrSectionMarkTagsAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSectionMarkTagsAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: SectionMarkTagsAttributes) -> None: ...
    def ToStruct(self, attributes: SectionMarkTagsAttributes) -> None: ...

class dotGrSectionMark_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSectionMark_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, sectionMark: SectionMark) -> None: ...
    def ToStruct(self, sectionMark: SectionMark) -> None: ...

class dotGrSheet_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSheet_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrSize_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSize_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Size: Size) -> None: ...
    def ToStruct(self, Size: Size) -> None: ...

class dotGrSnapSettings_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSnapSettings_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrStraightDimensionAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrStraightDimensionAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, straightDimensionAttributes: StraightDimensionAttributes) -> None: ...
    def ToStruct(self, straightDimensionAttributes: StraightDimensionAttributes) -> None: ...

class dotGrStraightDimensionSetAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrStraightDimensionSetAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: StraightDimensionSetAttributes) -> None: ...
    def ToStruct(self, attributes: StraightDimensionSetAttributes) -> None: ...

class dotGrStraightDimensionSet_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrStraightDimensionSet_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, straightDimension: StraightDimensionSet) -> None: ...
    def ToStruct(self, straightDimension: StraightDimensionSet) -> None: ...

class dotGrStraightDimension_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrStraightDimension_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, straightDimension: StraightDimension) -> None: ...
    def ToStruct(self, straightDimension: StraightDimension) -> None: ...

class dotGrStringList_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrStringList_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, stringList: List) -> None: ...
    def ToStruct(self, stringList: List) -> None: ...

class dotGrString_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrString_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, String: str) -> None: ...
    def ToStruct(self, String: str) -> None: ...

class dotGrSurfacingAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSurfacingAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, SurfacingAttributes: SurfacingAttributes) -> None: ...
    def ToStruct(self, SurfacingAttributes: SurfacingAttributes) -> None: ...

class dotGrSurfacing_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSurfacing_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Surfacing: Surfacing) -> None: ...
    def ToStruct(self, Surfacing: Surfacing) -> None: ...

class dotGrSymbolAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSymbolAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: SymbolAttributes) -> None: ...
    def ToStruct(self, Attributes: SymbolAttributes) -> None: ...

class dotGrSymbol_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrSymbol_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, symbol: Symbol) -> None: ...
    def ToStruct(self, symbol: Symbol) -> None: ...

class dotGrTextAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrTextAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: TextAttributes) -> None: ...
    def ToStruct(self, Attributes: TextAttributes) -> None: ...

class dotGrTextFileAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrTextFileAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, ObjectAttributes: TextFileAttributes) -> None: ...
    def ToStruct(self, ObjectAttributes: TextFileAttributes) -> None: ...

class dotGrTextFile_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrTextFile_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, obj: TextFile) -> None: ...
    def ToStruct(self, obj: TextFile) -> None: ...

class dotGrText_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrText_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, pText: Text) -> None: ...
    def ToStruct(self, pText: Text) -> None: ...

class dotGrUnitAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrUnitAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: UnitAttributes) -> None: ...
    def ToStruct(self, attributes: UnitAttributes) -> None: ...

class dotGrUserProperty_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrUserProperty_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrViewAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewAttributes_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrViewCommand_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewCommand_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrViewMarkBasicSymbolAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewMarkBasicSymbolAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ViewMarkBasicSymbolAttributes) -> None: ...
    def ToStruct(self, attributes: ViewMarkBasicSymbolAttributes) -> None: ...

class dotGrViewMarkBasicTagAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewMarkBasicTagAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ViewMarkBasicTagAttributes) -> None: ...
    def ToStruct(self, attributes: ViewMarkBasicTagAttributes) -> None: ...

class dotGrViewMarkSymbolAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewMarkSymbolAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ViewMarkSymbolAttributes) -> None: ...
    def ToStruct(self, attributes: ViewMarkSymbolAttributes) -> None: ...

class dotGrViewMarkTagAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewMarkTagAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ViewMarkTagAttributes) -> None: ...
    def ToStruct(self, attributes: ViewMarkTagAttributes) -> None: ...

class dotGrViewMarkTagsAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewMarkTagsAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: ViewMarkTagsAttributes) -> None: ...
    def ToStruct(self, attributes: ViewMarkTagsAttributes) -> None: ...

class dotGrViewRotation_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewRotation_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGrViewShorteningAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrViewShorteningAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Attributes: ViewShorteningAttributes) -> None: ...
    def ToStruct(self, attributes: ViewShorteningAttributes) -> None: ...

class dotGrView_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrView_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, view: View) -> None: ...
    def ToStruct(self, view: View) -> None: ...

class dotGrWeldAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrWeldAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, weldAttributes: WeldAttributes) -> None: ...
    def ToStruct(self, weldAttributes: WeldAttributes) -> None: ...

class dotGrWeldMarkAttributes_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrWeldMarkAttributes_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, attributes: WeldMarkAttributes) -> None: ...
    def ToStruct(self, attributes: WeldMarkAttributes) -> None: ...

class dotGrWeldMark_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrWeldMark_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Mark: WeldMark) -> None: ...
    def ToStruct(self, Mark: WeldMark) -> None: ...

class dotGrWeld_t:
    """.NET: Tekla.Structures.DrawingInternal.dotGrWeld_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, weld: Weld) -> None: ...
    def ToStruct(self, weld: Weld) -> None: ...

class dotLblMergeParam_t:
    """.NET: Tekla.Structures.DrawingInternal.dotLblMergeParam_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotLblPullOutParam_t:
    """.NET: Tekla.Structures.DrawingInternal.dotLblPullOutParam_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotMarkListingCommand_e:
    """.NET: Tekla.Structures.DrawingInternal.dotMarkListingCommand_e"""
    def __init__(self, *args) -> None: ...
    ...

class dotOBB_t:
    """.NET: Tekla.Structures.DrawingInternal.dotOBB_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, obb: OBB) -> None: ...
    def ToStruct(self, obb: OBB) -> None: ...

class dotPluginInput_t:
    """.NET: Tekla.Structures.DrawingInternal.dotPluginInput_t"""
    def __init__(self, *args) -> None: ...
    ...

class grDrawingCreationMethod_e:
    """.NET: Tekla.Structures.DrawingInternal.grDrawingCreationMethod_e"""
    def __init__(self, *args) -> None: ...
    ...

class grDrawingCreationSource_e:
    """.NET: Tekla.Structures.DrawingInternal.grDrawingCreationSource_e"""
    def __init__(self, *args) -> None: ...
    ...
