# Auto-generated — Tekla 2026 — Tekla.Structures.Forming

class DeformingType:
    """.NET: Tekla.Structures.Forming.DeformingType"""
    def __init__(self, *args) -> None: ...
    ...

class FoldingType:
    """.NET: Tekla.Structures.Forming.FoldingType"""
    def __init__(self, *args) -> None: ...
    ...

class FormingStates:
    """.NET: Tekla.Structures.Forming.FormingStates"""
    def __init__(self, *args) -> None: ...
    Deforming: DeformingType
    Folding: FoldingType
    Wrapping: WrappingType
    def Clone(self, ) -> object: ...

class WrappingType:
    """.NET: Tekla.Structures.Forming.WrappingType"""
    def __init__(self, *args) -> None: ...
    ...
