# Auto-generated — Tekla 2026 — Tekla.Structures.Geometry3d

class AABB:
    """.NET: Tekla.Structures.Geometry3d.AABB"""
    def __init__(self, *args) -> None: ...
    MinPoint: Point
    MaxPoint: Point
    def Collide(self, Other: AABB) -> bool: ...
    def GetCenterPoint(self, ) -> Point: ...
    def GetCornerPoints(self, ) -> list: ...
    def IsInside(self, Point: Point) -> bool: ...

class Arc:
    """.NET: Tekla.Structures.Geometry3d.Arc"""
    def __init__(self, *args) -> None: ...
    Length: float
    StartPoint: Point
    EndPoint: Point
    CenterPoint: Point
    ArcMiddlePoint: Point
    Normal: Vector
    Angle: float
    Radius: float
    StartTangent: Vector
    StartDirection: Vector
    def Clone(self, ) -> ICurve: ...
    def Equals(self, other: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...

class CoordinateSystem:
    """.NET: Tekla.Structures.Geometry3d.CoordinateSystem"""
    def __init__(self, *args) -> None: ...
    Origin: Point
    AxisX: Vector
    AxisY: Vector

class Distance:
    """.NET: Tekla.Structures.Geometry3d.Distance"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def PointToLine(Point: Point, Line: Line) -> float: ...
    @staticmethod
    def PointToLineSegment(Point: Point, LineSegment: LineSegment) -> float: ...
    @staticmethod
    def PointToPlane(Point: Point, Plane: GeometricPlane) -> float: ...
    @staticmethod
    def PointToPoint(Point1: Point, Point2: Point) -> float: ...

class FacetedBrep:
    """.NET: Tekla.Structures.Geometry3d.FacetedBrep"""
    def __init__(self, *args) -> None: ...
    Faces: ICollection
    InnerWires: IDictionary
    OuterWires: list
    GetEdges: IList
    Vertices: IList
    def CheckForTwoManifold(self, ) -> bool: ...
    def GetInnerFace(self, faceIndex: int) -> list: ...
    def GetInnerFaceCount(self, faceIndex: int) -> int: ...
    def GetOuterFace(self, faceIndex: int) -> list: ...

class FacetedBrepFace:
    """.NET: Tekla.Structures.Geometry3d.FacetedBrepFace"""
    def __init__(self, *args) -> None: ...
    HasHoles: bool
    Holes: IList
    IsReadOnly: bool
    VerticeIndexes: IList
    Vertices: IList

class FacetedBrepFaceHole:
    """.NET: Tekla.Structures.Geometry3d.FacetedBrepFaceHole"""
    def __init__(self, *args) -> None: ...
    Count: int
    IsReadOnly: bool
    VerticeIndexes: IList
    Vertices: IList

class FacetedBrepWithNormals(FacetedBrep):
    """.NET: Tekla.Structures.Geometry3d.FacetedBrepWithNormals"""
    def __init__(self, *args) -> None: ...
    Normals: list
    Faces: ICollection
    InnerWires: IDictionary
    OuterWires: list
    GetEdges: IList
    Vertices: IList

class GeometricPlane:
    """.NET: Tekla.Structures.Geometry3d.GeometricPlane"""
    def __init__(self, *args) -> None: ...
    Origin: Point
    Normal: Vector
    def GetNormal(self, ) -> Vector: ...

class GeometryConstants:
    """.NET: Tekla.Structures.Geometry3d.GeometryConstants"""
    def __init__(self, *args) -> None: ...
    ...

class IBoundingVolume:
    """.NET: Tekla.Structures.Geometry3d.IBoundingVolume"""
    def __init__(self, *args) -> None: ...
    ...

class ICurve:
    """.NET: Tekla.Structures.Geometry3d.ICurve"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Length: float
    def Clone(self, ) -> ICurve: ...

class IndirectPolymeshEdge:
    """.NET: Tekla.Structures.Geometry3d.IndirectPolymeshEdge"""
    def __init__(self, *args) -> None: ...
    EdgeType: PolymeshEdgeTypeEnum
    StartPoint: int
    EndPoint: int
    ShellIndex: int

class Intersection:
    """.NET: Tekla.Structures.Geometry3d.Intersection"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def LineSegmentToObb(lineSegment: LineSegment, obb: OBB) -> LineSegment: ...
    @staticmethod
    def LineSegmentToPlane(lineSegment: LineSegment, plane: GeometricPlane) -> Point: ...
    @staticmethod
    def LineToLine(line1: Line, line2: Line) -> LineSegment: ...
    @staticmethod
    def LineToObb(line: Line, obb: OBB) -> LineSegment: ...
    @staticmethod
    def LineToPlane(line: Line, plane: GeometricPlane) -> Point: ...
    @staticmethod
    def PlaneToPlane(plane1: GeometricPlane, plane2: GeometricPlane) -> Line: ...

class Line:
    """.NET: Tekla.Structures.Geometry3d.Line"""
    def __init__(self, *args) -> None: ...
    Origin: Point
    Direction: Vector

class LineSegment:
    """.NET: Tekla.Structures.Geometry3d.LineSegment"""
    def __init__(self, *args) -> None: ...
    Point1: Point
    Point2: Point
    StartPoint: Point
    EndPoint: Point
    def Clone(self, ) -> ICurve: ...
    def Equals(self, o: object) -> bool: ...
    def GetDirectionVector(self, ) -> Vector: ...
    def GetHashCode(self, ) -> int: ...
    def Length(self, ) -> float: ...

class Matrix:
    """.NET: Tekla.Structures.Geometry3d.Matrix"""
    def __init__(self, *args) -> None: ...
    Item: float
    def GetTranspose(self, ) -> Matrix: ...
    def ToString(self, ) -> str: ...
    def Transform(self, p: Point) -> Point: ...
    def Transpose(self, ) -> None: ...

class MatrixFactory:
    """.NET: Tekla.Structures.Geometry3d.MatrixFactory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ByCoordinateSystems(CoordSys1: CoordinateSystem, CoordSys2: CoordinateSystem) -> Matrix: ...
    @staticmethod
    def FromCoordinateSystem(CoordSys: CoordinateSystem) -> Matrix: ...
    @staticmethod
    def Rotate(Angle: float, Axis: Vector) -> Matrix: ...
    @staticmethod
    def ToCoordinateSystem(CoordSys: CoordinateSystem) -> Matrix: ...

class OBB:
    """.NET: Tekla.Structures.Geometry3d.OBB"""
    def __init__(self, *args) -> None: ...
    Center: Point
    Axis0: Vector
    Axis1: Vector
    Axis2: Vector
    Extent0: float
    Extent1: float
    Extent2: float
    def ClosestPointTo(self, point: Point) -> Point: ...
    def ComputeVertices(self, ) -> list: ...
    def DistanceTo(self, point: Point) -> float: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IntersectionPointsWith(self, line: Line) -> list: ...
    def IntersectionWith(self, line: Line) -> LineSegment: ...
    def Intersects(self, obb: OBB) -> bool: ...
    def SetAxis(self, axis0: Vector, axis1: Vector, axis2: Vector) -> None: ...
    def SetExtent(self, extent0: float, extent1: float, extent2: float) -> None: ...
    def ShortestSegmentTo(self, line: Line) -> LineSegment: ...

class Parallel:
    """.NET: Tekla.Structures.Geometry3d.Parallel"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def LineSegmentToLineSegment(LineSegment1: LineSegment, LineSegment2: LineSegment, Tolerance: float) -> bool: ...
    @staticmethod
    def LineSegmentToPlane(LineSegment: LineSegment, Plane: GeometricPlane, Tolerance: float) -> bool: ...
    @staticmethod
    def LineToLine(Line1: Line, Line2: Line, Tolerance: float) -> bool: ...
    @staticmethod
    def LineToPlane(Line: Line, Plane: GeometricPlane, Tolerance: float) -> bool: ...
    @staticmethod
    def PlaneToPlane(Plane1: GeometricPlane, Plane2: GeometricPlane, Tolerance: float) -> bool: ...
    @staticmethod
    def VectorToPlane(Vector: Vector, Plane: GeometricPlane, Tolerance: float) -> bool: ...
    @staticmethod
    def VectorToVector(Vector1: Vector, Vector2: Vector, Tolerance: float) -> bool: ...

class Point:
    """.NET: Tekla.Structures.Geometry3d.Point"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AreEqual(Point1: Point, Point2: Point) -> bool: ...
    def CompareTo(self, obj: object) -> int: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, cultureInfo: CultureInfo) -> str: ...
    def Translate(self, X: float, Y: float, Z: float) -> None: ...
    def Zero(self, ) -> None: ...

class PolyLine:
    """.NET: Tekla.Structures.Geometry3d.PolyLine"""
    def __init__(self, *args) -> None: ...
    Points: ArrayList
    def Equals(self, O: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def Length(self, ) -> float: ...

class Polycurve:
    """.NET: Tekla.Structures.Geometry3d.Polycurve"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Length: float
    def Clone(self, ) -> ICurve: ...
    def Equals(self, other: ICurve) -> bool: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class PolycurveGeometryBuilder:
    """.NET: Tekla.Structures.Geometry3d.PolycurveGeometryBuilder"""
    def __init__(self, *args) -> None: ...
    def Append(self, arc: Arc) -> PolycurveGeometryBuilder: ...
    def AppendArc(self, middlePoint: Point, endPoint: Point) -> PolycurveGeometryBuilder: ...
    def AppendSegment(self, endPoint: Point) -> PolycurveGeometryBuilder: ...
    def AppendTangentArc(self, endPoint: Point) -> PolycurveGeometryBuilder: ...
    def AppendTangentSegment(self, length: float) -> PolycurveGeometryBuilder: ...
    def GetPolycurve(self, ) -> Polycurve: ...
    def Prepend(self, arc: Arc) -> PolycurveGeometryBuilder: ...
    def PrependArc(self, startPoint: Point, middlePoint: Point) -> PolycurveGeometryBuilder: ...
    def PrependSegment(self, startPoint: Point) -> PolycurveGeometryBuilder: ...
    def PrependTangentArc(self, startPoint: Point) -> PolycurveGeometryBuilder: ...
    def PrependTangentSegment(self, length: float) -> PolycurveGeometryBuilder: ...
    def Replace(self, index: int, arc: Arc) -> PolycurveGeometryBuilder: ...

class PolymeshEdgeTypeEnum:
    """.NET: Tekla.Structures.Geometry3d.PolymeshEdgeTypeEnum"""
    def __init__(self, *args) -> None: ...
    ...

class Projection:
    """.NET: Tekla.Structures.Geometry3d.Projection"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def LineSegmentToPlane(LineSegment: LineSegment, Plane: GeometricPlane) -> LineSegment: ...
    @staticmethod
    def LineToPlane(Line: Line, Plane: GeometricPlane) -> Line: ...
    @staticmethod
    def PointToLine(Point: Point, Line: Line) -> Point: ...
    @staticmethod
    def PointToPlane(Point: Point, Plane: GeometricPlane) -> Point: ...

class Vector(Point):
    """.NET: Tekla.Structures.Geometry3d.Vector"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Cross(Vector1: Vector, Vector2: Vector) -> Vector: ...
    @staticmethod
    def Dot(Vector1: Vector, Vector2: Vector) -> float: ...
    def GetAngleBetween(self, Vector: Vector) -> float: ...
    def GetLength(self, ) -> float: ...
    def GetNormal(self, ) -> Vector: ...
    def Normalize(self, NewLength: float) -> float: ...
    def ToString(self, ) -> str: ...
