# Auto-generated — Tekla 2026 — Tekla.Structures.PluginsInternal

class DelegateFake(GenericDelegateFake):
    """.NET: Tekla.Structures.PluginsInternal.DelegateFake"""
    def __init__(self, *args) -> None: ...
    ...

class DelegateProxy:
    """.NET: Tekla.Structures.PluginsInternal.DelegateProxy"""
    def __init__(self, *args) -> None: ...
    Delegate: ICDelegate
    @staticmethod
    def DeactivateInterface(Param: str) -> int: ...

class GenericDelegateFake:
    """.NET: Tekla.Structures.PluginsInternal.GenericDelegateFake`1"""
    def __init__(self, *args) -> None: ...
    def DrawingExportAddPlugin(self, pPluginDefinition: dotPluginDefinition_t) -> int: ...
    def DrawingExportCurrentDefineInputClientId(self, pInput: dotPluginClient_t) -> int: ...
    def DrawingExportDefineInputCompleted(self, pInput: dotPluginClient_t) -> int: ...
    def DrawingExportGetPluginInput(self, pInput: dotPluginInput_t) -> int: ...
    def DrawingExportPluginRunCompleted(self, pInput: dotPluginClient_t) -> int: ...
    def DrawingExportSetPluginInput(self, pInput: dotPluginInput_t) -> int: ...
    def ExportAddPlugin(self, pPluginDefinition: dotPluginDefinition_t, pConnectionType: dotConnectionType_t) -> int: ...
    def ExportExecutePluginResult(self, ExecuteResult: int) -> int: ...
    def ExportGetConnectionCode(self, ConnectionCode: dotConnectionCode_t) -> int: ...
    def ExportGetInput(self, pInput: dotPluginInput_t) -> int: ...
    def ExportGetPluginBaseDirectory(self, pPluginBaseDirectory: dotPluginBaseDirectory_t) -> int: ...
    def ExportGetPluginDoubleAttributes(self, pInput: dotPluginAttributesDouble_t) -> int: ...
    def ExportGetPluginId(self, ) -> int: ...
    def ExportGetPluginIntAttributes(self, pInput: dotPluginAttributesInt_t) -> int: ...
    def ExportGetPluginName(self, pPluginName: dotPluginName_t) -> int: ...
    def ExportGetPluginStringAttributes(self, pInput: dotPluginAttributesString_t) -> int: ...
    def ExportSetConnectionCode(self, ConnectionCode: dotConnectionCode_t) -> int: ...
    def ExportSetInput(self, pInput: dotPluginInput_t) -> int: ...
    def ExportSetPluginResult(self, Result: int) -> int: ...
    def ExportSignalInputEnded(self, ) -> int: ...

class ICDelegate:
    """.NET: Tekla.Structures.PluginsInternal.ICDelegate"""
    def __init__(self, *args) -> None: ...
    def DrawingExportAddPlugin(self, pPluginDefinition: dotPluginDefinition_t) -> int: ...
    def DrawingExportCurrentDefineInputClientId(self, pInput: dotPluginClient_t) -> int: ...
    def DrawingExportDefineInputCompleted(self, pInput: dotPluginClient_t) -> int: ...
    def DrawingExportGetPluginInput(self, pInput: dotPluginInput_t) -> int: ...
    def DrawingExportPluginRunCompleted(self, pInput: dotPluginClient_t) -> int: ...
    def DrawingExportSetPluginInput(self, pInput: dotPluginInput_t) -> int: ...
    def ExportAddPlugin(self, pPluginDefinition: dotPluginDefinition_t, pConnectionType: dotConnectionType_t) -> int: ...
    def ExportExecutePluginResult(self, ExecuteResult: int) -> int: ...
    def ExportGetConnectionCode(self, ConnectionCode: dotConnectionCode_t) -> int: ...
    def ExportGetInput(self, pInput: dotPluginInput_t) -> int: ...
    def ExportGetPluginBaseDirectory(self, pPluginBaseDirectory: dotPluginBaseDirectory_t) -> int: ...
    def ExportGetPluginDoubleAttributes(self, pInput: dotPluginAttributesDouble_t) -> int: ...
    def ExportGetPluginId(self, ) -> int: ...
    def ExportGetPluginIntAttributes(self, pInput: dotPluginAttributesInt_t) -> int: ...
    def ExportGetPluginName(self, pPluginName: dotPluginName_t) -> int: ...
    def ExportGetPluginStringAttributes(self, pInput: dotPluginAttributesString_t) -> int: ...
    def ExportSetConnectionCode(self, ConnectionCode: dotConnectionCode_t) -> int: ...
    def ExportSetInput(self, pInput: dotPluginInput_t) -> int: ...
    def ExportSetPluginResult(self, Result: int) -> int: ...
    def ExportSignalInputEnded(self, ) -> int: ...

class Remoter:
    """.NET: Tekla.Structures.PluginsInternal.Remoter"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def DisposeService() -> None: ...
    @staticmethod
    def GetConnectionStatus() -> bool: ...
    @staticmethod
    def InitializeSandBox() -> bool: ...
