# Auto-generated — Tekla 2026 — Tekla.Structures.RemotingHelper

class GenericDelegateProxy:
    """.NET: Tekla.Structures.RemotingHelper.GenericDelegateProxy`2"""
    def __init__(self, *args) -> None: ...
    Delegate: I

class IReturnStrategy:
    """.NET: Tekla.Structures.RemotingHelper.IReturnStrategy"""
    def __init__(self, *args) -> None: ...
    def Return(self, ) -> T: ...

class RaiseNotImplementedStrategy:
    """.NET: Tekla.Structures.RemotingHelper.RaiseNotImplementedStrategy"""
    def __init__(self, *args) -> None: ...
    def Return(self, ) -> T: ...

class ReturnDefaultStrategy:
    """.NET: Tekla.Structures.RemotingHelper.ReturnDefaultStrategy"""
    def __init__(self, *args) -> None: ...
    def Return(self, ) -> T: ...
