# Auto-generated — Tekla 2026 — Tekla.Structures.Solid

class Edge:
    """.NET: Tekla.Structures.Solid.Edge"""
    def __init__(self, *args) -> None: ...
    Type: EdgeTypeEnum
    StartPoint: Point
    EndPoint: Point
    def Clone(self, ) -> object: ...

class EdgeEnumerator:
    """.NET: Tekla.Structures.Solid.EdgeEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: object
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Face:
    """.NET: Tekla.Structures.Solid.Face"""
    def __init__(self, *args) -> None: ...
    Normal: Vector
    OriginPartId: Identifier
    def GetLoopEnumerator(self, ) -> LoopEnumerator: ...

class FaceEnumerator:
    """.NET: Tekla.Structures.Solid.FaceEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Face
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class ISolid:
    """.NET: Tekla.Structures.Solid.ISolid"""
    def __init__(self, *args) -> None: ...
    MinimumPoint: Point
    MaximumPoint: Point
    def GetEdgeEnumerator(self, ) -> EdgeEnumerator: ...
    def GetFaceEnumerator(self, ) -> FaceEnumerator: ...

class Loop:
    """.NET: Tekla.Structures.Solid.Loop"""
    def __init__(self, *args) -> None: ...
    def GetVertexEnumerator(self, ) -> VertexEnumerator: ...

class LoopEnumerator:
    """.NET: Tekla.Structures.Solid.LoopEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Loop
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class Shell:
    """.NET: Tekla.Structures.Solid.Shell"""
    def __init__(self, *args) -> None: ...
    def GetEdgeEnumerator(self, ) -> EdgeEnumerator: ...
    def GetFaceEnumerator(self, ) -> FaceEnumerator: ...

class ShellEnumerator:
    """.NET: Tekla.Structures.Solid.ShellEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: object
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class VertexEnumerator:
    """.NET: Tekla.Structures.Solid.VertexEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Point
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...
