# Auto-generated — Tekla 2026 — Tekla.Structures.Model.History

class ModelHistory:
    """.NET: Tekla.Structures.Model.History.ModelHistory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetCurrentModificationStamp() -> ModificationStamp: ...
    @staticmethod
    def GetDeletedObjects(ModStamp: ModificationStamp) -> ModelObjectEnumerator: ...
    @staticmethod
    def GetDeletedObjectsWithType(ModStamp: ModificationStamp, Enum: ModelObjectEnum) -> ModelObjectEnumerator: ...
    @staticmethod
    def GetLocalChanges() -> ModificationInfo: ...
    @staticmethod
    def GetModifications(Name: str, ObjectTypes: IEnumerable, PrevStamp: ModificationStamp) -> ModificationInfo: ...
    @staticmethod
    def GetModifiedObjects(ModStamp: ModificationStamp) -> ModelObjectEnumerator: ...
    @staticmethod
    def GetModifiedObjectsWithType(ModStamp: ModificationStamp, Enum: ModelObjectEnum) -> ModelObjectEnumerator: ...
    @staticmethod
    def GetNotSharedObjects() -> ModelObjectEnumerator: ...
    @staticmethod
    def TakeModifications(Name: str, ObjectTypes: IEnumerable, PrevStamp: ModificationStamp) -> ModificationInfo: ...
    @staticmethod
    def UpdateModificationStampToLatest(modificationStampKey: str) -> None: ...

class ModificationInfo:
    """.NET: Tekla.Structures.Model.History.ModificationInfo"""
    def __init__(self, *args) -> None: ...
    ...

class ModificationStamp:
    """.NET: Tekla.Structures.Model.History.ModificationStamp"""
    def __init__(self, *args) -> None: ...
    LocalStamp: int
    ServerStamp: int
    Guid: str

class ModifiedObjectInfo:
    """.NET: Tekla.Structures.Model.History.ModifiedObjectInfo"""
    def __init__(self, *args) -> None: ...
    ...
