# Auto-generated — Tekla 2026 — Tekla.Structures.Model.Operations

class GuidConversion:
    """.NET: Tekla.Structures.Model.Operations.GuidConversion"""
    def __init__(self, *args) -> None: ...
    def GetGuidMapping(self, ) -> Dictionary: ...
    def GetNewGuid(self, oldGuid: Guid) -> Guid: ...

class Operation:
    """.NET: Tekla.Structures.Model.Operations.Operation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AddToPourUnit(inputPourUnit: PourUnit, objectsToBeAdded: List) -> bool: ...
    @staticmethod
    def CalculatePourUnits() -> bool: ...
    @staticmethod
    def Combine(ObjectToCombineTo: Beam, ObjectToBeCombined: Beam) -> Beam: ...
    @staticmethod
    def ConvertPartToItem(originalPart: Part, newItem: Brep) -> bool: ...
    @staticmethod
    def CopyObject(Object: ModelObject, StartCoordinateSystem: CoordinateSystem, EndCoordinateSystem: CoordinateSystem) -> ModelObject: ...
    @staticmethod
    def CopyObjectMirror(modelObject: ModelObject, x: float, y: float, angle: float) -> ModelObject: ...
    @staticmethod
    def CreateBentPlateByFaces(part1: Part, face1: IList, part2: Part, face2: IList, bendShape: BendShape) -> BentPlate: ...
    @staticmethod
    def CreateBentPlateByParts(part1: Part, part2: Part, bendShape: BendShape) -> BentPlate: ...
    @staticmethod
    def CreateConicalBentPlateByFaces(part1: Part, face1: IList, part2: Part, face2: IList, largestRadius: float, halfAperture: float) -> BentPlate: ...
    @staticmethod
    def CreateConicalBentPlateByPartsAndAperture(part1: Part, part2: Part, largestRadius: float, halfAperture: float) -> BentPlate: ...
    @staticmethod
    def CreateConicalBentPlateByPartsAndTwoRadiuses(part1: Part, part2: Part, firstRadius: float, secondRadius: float) -> BentPlate: ...
    @staticmethod
    def CreateDGNv8Export(FileName: str, Folder: str, BasePoint: ExportBasePoint, BasePointGuid: str, ObjectColoring: str, ExportLayersAs: str, OnlyFromSelectedObjects: bool) -> bool: ...
    @staticmethod
    def CreateIFC2x3Export(fullPathAndFileName: str, exportViewType: IFC2x3ExportViewTypeEnum, attributesOverridesFileNames: IEnumerable, additionalPropertySetFileName: str, locationByValue: ExportBasePoint, layersNamesAsPartNames: bool, useViewColors: bool, flags: IFC2x3ExportFlags, basePointGuid: str) -> bool: ...
    @staticmethod
    def CreateIFC4ExportFromAll(fullPathAndFileName: str, exportViewType: IFCExportViewTypeEnum, exportVersion: IFCExportVersionEnum, attributesOverridesFileNames: IEnumerable, propertySets: IEnumerable, locationByValue: ExportBasePoint, exportLayersAsValue: str, objectColoring: str, flags: IFCExportFlags, basePointGuid: str) -> bool: ...
    @staticmethod
    def CreateIFC4ExportFromSelected(fullPathAndFileName: str, exportViewType: IFCExportViewTypeEnum, exportVersion: IFCExportVersionEnum, attributesOverridesFileNames: IEnumerable, propertySets: IEnumerable, locationByValue: ExportBasePoint, exportLayersAsValue: str, objectColoring: str, flags: IFCExportFlags, basePointGuid: str) -> bool: ...
    @staticmethod
    def CreateIFC4ExportFromSelectedAndTheirAssemblies(fullPathAndFileName: str, exportViewType: IFCExportViewTypeEnum, exportVersion: IFCExportVersionEnum, attributesOverridesFileNames: IEnumerable, propertySets: IEnumerable, locationByValue: ExportBasePoint, exportLayersAsValue: str, objectColoring: str, flags: IFCExportFlags, basePointGuid: str) -> bool: ...
    @staticmethod
    def CreateMISFileFromAll(MISType: MISExportTypeEnum, FileName: str) -> bool: ...
    @staticmethod
    def CreateMISFileFromSelected(MISType: MISExportTypeEnum, FileName: str) -> bool: ...
    @staticmethod
    def CreateNCFilesByPartId(NCFileSettings: str, DestinationFolder: str, PartID: Identifier, DstvOutput: str, CreatePopMarks: bool, PopMarkSettingsFileName: str, CreateContourMarking: bool, ContourMarkingSettingsFileName: str) -> bool: ...
    @staticmethod
    def CreateNCFilesFromAll(NCFileSettings: str, DestinationFolder: str, CreatePopMarks: bool, PopMarkSettingsFileName: str, CreateContourMarking: bool, ContourMarkingSettingsFileName: str) -> bool: ...
    @staticmethod
    def CreateNCFilesFromSelected(NCFileSettings: str, DestinationFolder: str, CreatePopMarks: bool, PopMarkSettingsFileName: str, CreateContourMarking: bool, ContourMarkingSettingsFileName: str) -> bool: ...
    @staticmethod
    def CreateReport(parameters: ReportParameters) -> bool: ...
    @staticmethod
    def CreateReportFromAll(TemplateName: str, FileName: str, Title1: str, Title2: str, Title3: str) -> bool: ...
    @staticmethod
    def CreateReportFromSelected(TemplateName: str, FileName: str, Title1: str, Title2: str, Title3: str) -> bool: ...
    @staticmethod
    def CreateShapeFromGeometry(originalPart: Part) -> str: ...
    @staticmethod
    def DisplayPrintReportDialog(FileName: str) -> bool: ...
    @staticmethod
    def DisplayPrompt(Message: str) -> bool: ...
    @staticmethod
    def DisplayReport(FileName: str) -> bool: ...
    @staticmethod
    def ExplodeBentPlate(bentPlate: BentPlate) -> bool: ...
    @staticmethod
    def Freeze(rebarSet: RebarSet, value: bool) -> bool: ...
    @staticmethod
    def GetHandlePoints(guid: str) -> List: ...
    @staticmethod
    def GetSimilarNumberedObjects(ObjectToCompare: ModelObject) -> List: ...
    @staticmethod
    def Group(RebarList: IEnumerable) -> RebarGroup: ...
    @staticmethod
    def Highlight(ModelObjects: List) -> bool: ...
    @staticmethod
    def IsMacroRunning() -> bool: ...
    @staticmethod
    def IsModelAutoSaved(ModelFolder: str) -> bool: ...
    @staticmethod
    def IsNumberingAllowed() -> bool: ...
    @staticmethod
    def IsNumberingUpToDate(InputModelObject: ModelObject) -> bool: ...
    @staticmethod
    def IsNumberingUpToDateAll() -> bool: ...
    @staticmethod
    def MoveObject(Object: ModelObject, StartCoordinateSystem: CoordinateSystem, EndCoordinateSystem: CoordinateSystem) -> bool: ...
    @staticmethod
    def MoveObjectMirror(modelObject: ModelObject, x: float, y: float, angle: float) -> bool: ...
    @staticmethod
    def ObjectMatchesToFilter(ModelObject: ModelObject, FilterName: str) -> bool: ...
    @staticmethod
    def Open(ModelFolder: str, OpenAutoSaved: bool) -> bool: ...
    @staticmethod
    def RemoveFromPourUnit(objectsToBeRemoved: List) -> bool: ...
    @staticmethod
    def RunMacro(FileName: str) -> bool: ...
    @staticmethod
    def SaveAsWebModel(Filename: str) -> bool: ...
    @staticmethod
    def SaveSelectedAsWebModel(Filename: str) -> bool: ...
    @staticmethod
    def SetHandlePoints(guid: str, HandlePoints: List) -> bool: ...
    @staticmethod
    def ShowOnlySelected(UnselectedMode: UnselectedModeEnum) -> None: ...
    @staticmethod
    def Split(Object: Beam, SplitPoint: Point) -> Beam: ...
    @staticmethod
    def SplitSlab(PartId: int, Polymesh: FacetedBrep) -> bool: ...
    @staticmethod
    def Ungrouping(Reinforcement: RebarGroup) -> ModelObjectEnumerator: ...
