# Auto-generated — Tekla 2026 — Tekla.Structures.Model.PointCloudDataServices

class PointCloudDataServices:
    """.NET: Tekla.Structures.Model.PointCloudDataServices.PointCloudDataServices"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetPointCloudUrlAsync(project: TCProject, pointCloud: TCPointCloud) -> Task: ...
    @staticmethod
    def GetProjectsWithPointCloudsAsync() -> Task: ...

class TCPointCloud:
    """.NET: Tekla.Structures.Model.PointCloudDataServices.TCPointCloud"""
    def __init__(self, *args) -> None: ...
    ...

class TCProject:
    """.NET: Tekla.Structures.Model.PointCloudDataServices.TCProject"""
    def __init__(self, *args) -> None: ...
    ...
