# Auto-generated — Tekla 2026 — Tekla.Structures.Model.UI

class ClipBox:
    """.NET: Tekla.Structures.Model.UI.ClipBox"""
    def __init__(self, *args) -> None: ...
    ClipPlanes: List
    View: View
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...

class ClipPlane:
    """.NET: Tekla.Structures.Model.UI.ClipPlane"""
    def __init__(self, *args) -> None: ...
    ClipPlaneID: int
    Location: Point
    UpVector: Vector
    View: View
    IsBorderVisible: bool
    IsScissorVisible: bool
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...

class ClipPlaneCollection:
    """.NET: Tekla.Structures.Model.UI.ClipPlaneCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    IsSynchronized: bool
    SyncRoot: object
    def CopyTo(self, array: Array, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class Color:
    """.NET: Tekla.Structures.Model.UI.Color"""
    def __init__(self, *args) -> None: ...
    Red: float
    Green: float
    Blue: float
    Transparency: float

class GraphicPolyLine:
    """.NET: Tekla.Structures.Model.UI.GraphicPolyLine"""
    def __init__(self, *args) -> None: ...
    PolyLine: PolyLine
    Color: Color
    Width: int
    Type: LineType

class GraphicsDrawer:
    """.NET: Tekla.Structures.Model.UI.GraphicsDrawer"""
    def __init__(self, *args) -> None: ...
    def DrawLineSegment(self, Point1: Point, Point2: Point, Color: Color) -> bool: ...
    def DrawMeshLines(self, Mesh: Mesh, Color: Color) -> bool: ...
    def DrawMeshSurface(self, Mesh: Mesh, Color: Color) -> bool: ...
    def DrawPolyLine(self, GraphicPolyLine: GraphicPolyLine) -> int: ...
    def DrawText(self, Location: Point, Text: str, Color: Color) -> bool: ...
    def DrawTextToView(self, Location: Point, Text: str, Color: Color, View: View) -> int: ...
    def RemoveTemporaryGraphicsObject(self, GraphicObjectID: int) -> None: ...
    def RemoveTemporaryGraphicsObjects(self, GraphicObjectIDs: IEnumerable) -> None: ...

class Mesh:
    """.NET: Tekla.Structures.Model.UI.Mesh"""
    def __init__(self, *args) -> None: ...
    Points: ArrayList
    Triangles: ArrayList
    Lines: ArrayList
    def AddLine(self, Index1: int, Index2: int) -> None: ...
    def AddPoint(self, Point: Point) -> int: ...
    def AddTriangle(self, Index1: int, Index2: int, Index3: int) -> None: ...

class ModelObjectSelector:
    """.NET: Tekla.Structures.Model.UI.ModelObjectSelector"""
    def __init__(self, *args) -> None: ...
    def GetObjectsByBoundingBox(self, MinPoint: Point, MaxPoint: Point, View: View) -> ModelObjectEnumerator: ...
    def GetSelectedObjects(self, ) -> ModelObjectEnumerator: ...
    def Select(self, ModelObjects: ArrayList, ShowDimensions: bool) -> bool: ...

class ModelObjectVisualization:
    """.NET: Tekla.Structures.Model.UI.ModelObjectVisualization"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ClearAllTemporaryStates() -> bool: ...
    @staticmethod
    def ClearTemporaryStates(modelObjects: List) -> bool: ...
    @staticmethod
    def GetAllTemporaryColored() -> IEnumerable: ...
    @staticmethod
    def GetRepresentation(modelObject: ModelObject, color: Color) -> bool: ...
    @staticmethod
    def GetTempRepresentation(modelObject: ModelObject) -> Color: ...
    @staticmethod
    def SetTemporaryState(modelObjects: List, color: Color) -> bool: ...
    @staticmethod
    def SetTemporaryStateForAll(color: Color) -> bool: ...
    @staticmethod
    def SetTransparency(modelObjects: List, transparency: TemporaryTransparency) -> bool: ...
    @staticmethod
    def SetTransparencyForAll(transparency: TemporaryTransparency) -> bool: ...
    @staticmethod
    def SetVisibility(modelObjects: List, Visible: Nullable) -> bool: ...
    @staticmethod
    def UnhideParts() -> None: ...

class ModelViewEnumerator:
    """.NET: Tekla.Structures.Model.UI.ModelViewEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: View
    Count: int
    CurrentViewId: int
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class PickInput:
    """.NET: Tekla.Structures.Model.UI.PickInput"""
    def __init__(self, *args) -> None: ...
    Count: int
    IsSynchronized: bool
    SyncRoot: object
    def CopyTo(self, array: Array, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class Picker:
    """.NET: Tekla.Structures.Model.UI.Picker"""
    def __init__(self, *args) -> None: ...
    def PickFace(self, Prompt: str) -> PickInput: ...
    def PickLine(self, Prompt: str) -> ArrayList: ...
    def PickObject(self, Enum: PickObjectEnum, Prompt: str) -> ModelObject: ...
    def PickObjects(self, Enum: PickObjectsEnum, Prompt: str) -> ModelObjectEnumerator: ...
    def PickPoint(self, Prompt: str, ReferencePoint: Point) -> Point: ...
    def PickPoints(self, Enum: PickPointEnum, Prompt: str) -> ArrayList: ...

class SnapshotSettings:
    """.NET: Tekla.Structures.Model.UI.SnapshotSettings"""
    def __init__(self, *args) -> None: ...
    ...

class TemporaryTransparency:
    """.NET: Tekla.Structures.Model.UI.TemporaryTransparency"""
    def __init__(self, *args) -> None: ...
    ...

class View:
    """.NET: Tekla.Structures.Model.UI.View"""
    def __init__(self, *args) -> None: ...
    CurrentRepresentation: str
    Identifier: Identifier
    ViewCoordinateSystem: CoordinateSystem
    DisplayCoordinateSystem: CoordinateSystem
    Name: str
    WorkArea: AABB
    ViewDepthUp: float
    ViewDepthDown: float
    ViewProjection: ViewProjectionType
    DisplayType: DisplayOrientationType
    ViewRendering: ViewRenderingType
    ViewFilter: str
    SharedView: bool
    VisibilitySettings: ViewVisibilitySettings
    def CreateSnapshot(self, filePath: str, snapshotSettings: SnapshotSettings, overwrite: bool) -> bool: ...
    def Delete(self, ) -> bool: ...
    def GetClipPlanes(self, ) -> ClipPlaneCollection: ...
    def Insert(self, ) -> bool: ...
    def IsPerspectiveViewProjection(self, ) -> bool: ...
    def IsVisible(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ViewCamera:
    """.NET: Tekla.Structures.Model.UI.ViewCamera"""
    def __init__(self, *args) -> None: ...
    Location: Point
    DirectionVector: Vector
    UpVector: Vector
    FieldOfView: float
    ZoomFactor: float
    View: View
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ViewHandler:
    """.NET: Tekla.Structures.Model.UI.ViewHandler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetActiveView() -> View: ...
    @staticmethod
    def GetAllViews() -> ModelViewEnumerator: ...
    @staticmethod
    def GetPermanentViews() -> ModelViewEnumerator: ...
    @staticmethod
    def GetSelectedViews() -> ModelViewEnumerator: ...
    @staticmethod
    def GetTemporaryViews() -> ModelViewEnumerator: ...
    @staticmethod
    def GetVisibleViews() -> ModelViewEnumerator: ...
    @staticmethod
    def HideView(view: View) -> bool: ...
    @staticmethod
    def RedrawView(view: View) -> bool: ...
    @staticmethod
    def RedrawWorkplane() -> bool: ...
    @staticmethod
    def SetActiveView(view: View) -> bool: ...
    @staticmethod
    def SetRepresentation(Representation: str) -> bool: ...
    @staticmethod
    def ShowView(view: View) -> bool: ...
    @staticmethod
    def ZoomToBoundingBox(view: View, B: AABB) -> bool: ...

class ViewVisibilitySettings:
    """.NET: Tekla.Structures.Model.UI.ViewVisibilitySettings"""
    def __init__(self, *args) -> None: ...
    PointsVisible: bool
    PartsVisible: bool
    BoltsVisible: bool
    BoltHolesVisible: bool
    WeldsVisible: bool
    ConstructionPlanesVisible: bool
    RebarsVisible: bool
    SurfaceTreatmentsVisible: bool
    PoursVisible: bool
    PourBreaksVisible: bool
    LoadsVisible: bool
    CutsVisible: bool
    FittingsVisible: bool
    ComponentsVisible: bool
    GridsVisible: bool
    ConstructionLinesVisible: bool
    ReferenceObjectsVisible: bool
    BuildingVisible: bool
    PointsVisibleInComponents: bool
    PartsVisibleInComponents: bool
    BoltsVisibleInComponents: bool
    BoltHolesVisibleInComponents: bool
    WeldsVisibleInComponents: bool
    ConstructionPlanesVisibleInComponents: bool
    RebarsVisibleInComponents: bool
    CutsVisibleInComponents: bool
    FittingsVisibleInComponents: bool
    ComponentsVisibleInComponents: bool
