# Auto-generated — Tekla 2026 — FlatBuffers

class ByteBuffer:
    """.NET: FlatBuffers.ByteBuffer"""
    def __init__(self, *args) -> None: ...
    Length: int
    Data: list
    Position: int
    def Get(self, index: int) -> int: ...
    def GetDouble(self, index: int) -> float: ...
    def GetFloat(self, index: int) -> float: ...
    def GetInt(self, index: int) -> int: ...
    def GetLong(self, index: int) -> int: ...
    def GetSbyte(self, index: int) -> int: ...
    def GetShort(self, index: int) -> int: ...
    def GetUint(self, index: int) -> int: ...
    def GetUlong(self, index: int) -> int: ...
    def GetUshort(self, index: int) -> int: ...
    def Put(self, offset: int, value: int) -> None: ...
    def PutByte(self, offset: int, value: int, count: int) -> None: ...
    def PutDouble(self, offset: int, value: float) -> None: ...
    def PutFloat(self, offset: int, value: float) -> None: ...
    def PutInt(self, offset: int, value: int) -> None: ...
    def PutLong(self, offset: int, value: int) -> None: ...
    def PutSbyte(self, offset: int, value: int) -> None: ...
    def PutShort(self, offset: int, value: int) -> None: ...
    def PutUint(self, offset: int, value: int) -> None: ...
    def PutUlong(self, offset: int, value: int) -> None: ...
    def PutUshort(self, offset: int, value: int) -> None: ...
    def Reset(self, ) -> None: ...
    @staticmethod
    def ReverseBytes(input: int) -> int: ...

class FlatBufferBuilder:
    """.NET: FlatBuffers.FlatBufferBuilder"""
    def __init__(self, *args) -> None: ...
    ForceDefaults: bool
    Offset: int
    DataBuffer: ByteBuffer
    def AddBool(self, o: int, x: bool, d: bool) -> None: ...
    def AddByte(self, o: int, x: int, d: int) -> None: ...
    def AddDouble(self, o: int, x: float, d: float) -> None: ...
    def AddFloat(self, o: int, x: float, d: float) -> None: ...
    def AddInt(self, o: int, x: int, d: int) -> None: ...
    def AddLong(self, o: int, x: int, d: int) -> None: ...
    def AddOffset(self, o: int, x: int, d: int) -> None: ...
    def AddSbyte(self, o: int, x: int, d: int) -> None: ...
    def AddShort(self, o: int, x: int, d: int) -> None: ...
    def AddStruct(self, voffset: int, x: int, d: int) -> None: ...
    def AddUint(self, o: int, x: int, d: int) -> None: ...
    def AddUlong(self, o: int, x: int, d: int) -> None: ...
    def AddUshort(self, o: int, x: int, d: int) -> None: ...
    def Clear(self, ) -> None: ...
    def CreateString(self, s: str) -> StringOffset: ...
    def CreateVectorOfTables(self, offsets: list) -> VectorOffset: ...
    def EndObject(self, ) -> int: ...
    def EndVector(self, ) -> VectorOffset: ...
    def Finish(self, rootTable: int, fileIdentifier: str) -> None: ...
    def Nested(self, obj: int) -> None: ...
    def NotNested(self, ) -> None: ...
    def Pad(self, size: int) -> None: ...
    def Prep(self, size: int, additionalBytes: int) -> None: ...
    def PutBool(self, x: bool) -> None: ...
    def PutByte(self, x: int) -> None: ...
    def PutDouble(self, x: float) -> None: ...
    def PutFloat(self, x: float) -> None: ...
    def PutInt(self, x: int) -> None: ...
    def PutLong(self, x: int) -> None: ...
    def PutSbyte(self, x: int) -> None: ...
    def PutShort(self, x: int) -> None: ...
    def PutUint(self, x: int) -> None: ...
    def PutUlong(self, x: int) -> None: ...
    def PutUshort(self, x: int) -> None: ...
    def Required(self, table: int, field: int) -> None: ...
    def SizedByteArray(self, ) -> list: ...
    def Slot(self, voffset: int) -> None: ...
    def StartObject(self, numfields: int) -> None: ...
    def StartVector(self, elemSize: int, count: int, alignment: int) -> None: ...

class FlatBufferConstants:
    """.NET: FlatBuffers.FlatBufferConstants"""
    def __init__(self, *args) -> None: ...
    ...

class IFlatbufferObject:
    """.NET: FlatBuffers.IFlatbufferObject"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Offset:
    """.NET: FlatBuffers.Offset`1"""
    def __init__(self, *args) -> None: ...
    ...

class StringOffset:
    """.NET: FlatBuffers.StringOffset"""
    def __init__(self, *args) -> None: ...
    ...

class Struct:
    """.NET: FlatBuffers.Struct"""
    def __init__(self, *args) -> None: ...
    ...

class Table:
    """.NET: FlatBuffers.Table"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    @staticmethod
    def CompareStrings(offset_1: int, offset_2: int, bb: ByteBuffer) -> int: ...
    @staticmethod
    def __has_identifier(bb: ByteBuffer, ident: str) -> bool: ...
    @staticmethod
    def __indirect(offset: int, bb: ByteBuffer) -> int: ...
    @staticmethod
    def __offset(vtableOffset: int, offset: int, bb: ByteBuffer) -> int: ...
    def __string(self, offset: int) -> str: ...
    def __union(self, offset: int) -> T: ...
    def __vector(self, offset: int) -> int: ...
    def __vector_as_arraysegment(self, offset: int) -> Nullable: ...
    def __vector_len(self, offset: int) -> int: ...

class VectorOffset:
    """.NET: FlatBuffers.VectorOffset"""
    def __init__(self, *args) -> None: ...
    ...
