# Auto-generated — Tekla 2026 — RenderCommand

class Command:
    """.NET: RenderCommand.Command"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    CmdType: Commands
    @staticmethod
    def AddCmd(builder: FlatBufferBuilder, cmdOffset: int) -> None: ...
    @staticmethod
    def AddCmdType(builder: FlatBufferBuilder, cmdType: Commands) -> None: ...
    def Cmd(self, ) -> Nullable: ...
    @staticmethod
    def CreateCommand(builder: FlatBufferBuilder, cmd_type: Commands, cmdOffset: int) -> Offset: ...
    @staticmethod
    def EndCommand(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def FinishCommandBuffer(builder: FlatBufferBuilder, offset: Offset) -> None: ...
    @staticmethod
    def GetRootAsCommand(_bb: ByteBuffer, obj: Command) -> Command: ...
    @staticmethod
    def StartCommand(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Command: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Commands:
    """.NET: RenderCommand.Commands"""
    def __init__(self, *args) -> None: ...
    ...

class Delete:
    """.NET: RenderCommand.Delete"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Guid: str
    Schema: str
    @staticmethod
    def AddGuid(builder: FlatBufferBuilder, guidOffset: StringOffset) -> None: ...
    @staticmethod
    def AddSchema(builder: FlatBufferBuilder, schemaOffset: StringOffset) -> None: ...
    @staticmethod
    def CreateDelete(builder: FlatBufferBuilder, guidOffset: StringOffset, schemaOffset: StringOffset) -> Offset: ...
    @staticmethod
    def EndDelete(builder: FlatBufferBuilder) -> Offset: ...
    def GetGuidBytes(self, ) -> Nullable: ...
    @staticmethod
    def GetRootAsDelete(_bb: ByteBuffer, obj: Delete) -> Delete: ...
    def GetSchemaBytes(self, ) -> Nullable: ...
    @staticmethod
    def StartDelete(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Delete: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class DeleteAll:
    """.NET: RenderCommand.DeleteAll"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Schema: str
    @staticmethod
    def AddSchema(builder: FlatBufferBuilder, schemaOffset: StringOffset) -> None: ...
    @staticmethod
    def CreateDeleteAll(builder: FlatBufferBuilder, schemaOffset: StringOffset) -> Offset: ...
    @staticmethod
    def EndDeleteAll(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsDeleteAll(_bb: ByteBuffer, obj: DeleteAll) -> DeleteAll: ...
    def GetSchemaBytes(self, ) -> Nullable: ...
    @staticmethod
    def StartDeleteAll(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> DeleteAll: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Render:
    """.NET: RenderCommand.Render"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Guid: str
    Schema: str
    Data: Nullable
    @staticmethod
    def AddData(builder: FlatBufferBuilder, dataOffset: Offset) -> None: ...
    @staticmethod
    def AddGuid(builder: FlatBufferBuilder, guidOffset: StringOffset) -> None: ...
    @staticmethod
    def AddSchema(builder: FlatBufferBuilder, schemaOffset: StringOffset) -> None: ...
    @staticmethod
    def CreateRender(builder: FlatBufferBuilder, guidOffset: StringOffset, schemaOffset: StringOffset, dataOffset: Offset) -> Offset: ...
    @staticmethod
    def EndRender(builder: FlatBufferBuilder) -> Offset: ...
    def GetGuidBytes(self, ) -> Nullable: ...
    @staticmethod
    def GetRootAsRender(_bb: ByteBuffer, obj: Render) -> Render: ...
    def GetSchemaBytes(self, ) -> Nullable: ...
    @staticmethod
    def StartRender(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Render: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...
