# Auto-generated — Tekla 2026 — RenderData

class Color:
    """.NET: RenderData.Color"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Red: int
    Green: int
    Blue: int
    Alpha: int
    @staticmethod
    def AddAlpha(builder: FlatBufferBuilder, Alpha: int) -> None: ...
    @staticmethod
    def AddBlue(builder: FlatBufferBuilder, Blue: int) -> None: ...
    @staticmethod
    def AddGreen(builder: FlatBufferBuilder, Green: int) -> None: ...
    @staticmethod
    def AddRed(builder: FlatBufferBuilder, Red: int) -> None: ...
    @staticmethod
    def CreateColor(builder: FlatBufferBuilder, Red: int, Green: int, Blue: int, Alpha: int) -> Offset: ...
    @staticmethod
    def EndColor(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsColor(_bb: ByteBuffer, obj: Color) -> Color: ...
    @staticmethod
    def StartColor(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Color: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Data:
    """.NET: RenderData.Data"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    ColorsLength: int
    FacesLength: int
    LinesLength: int
    PolylinesLength: int
    PointsLength: int
    TextsLength: int
    @staticmethod
    def AddColors(builder: FlatBufferBuilder, colorsOffset: VectorOffset) -> None: ...
    @staticmethod
    def AddFaces(builder: FlatBufferBuilder, facesOffset: VectorOffset) -> None: ...
    @staticmethod
    def AddLines(builder: FlatBufferBuilder, linesOffset: VectorOffset) -> None: ...
    @staticmethod
    def AddPoints(builder: FlatBufferBuilder, pointsOffset: VectorOffset) -> None: ...
    @staticmethod
    def AddPolylines(builder: FlatBufferBuilder, polylinesOffset: VectorOffset) -> None: ...
    @staticmethod
    def AddTexts(builder: FlatBufferBuilder, textsOffset: VectorOffset) -> None: ...
    def Colors(self, j: int) -> Nullable: ...
    @staticmethod
    def CreateColorsVector(builder: FlatBufferBuilder, data: list) -> VectorOffset: ...
    @staticmethod
    def CreateData(builder: FlatBufferBuilder, colorsOffset: VectorOffset, facesOffset: VectorOffset, linesOffset: VectorOffset, polylinesOffset: VectorOffset, pointsOffset: VectorOffset, textsOffset: VectorOffset) -> Offset: ...
    @staticmethod
    def CreateFacesVector(builder: FlatBufferBuilder, data: list) -> VectorOffset: ...
    @staticmethod
    def CreateLinesVector(builder: FlatBufferBuilder, data: list) -> VectorOffset: ...
    @staticmethod
    def CreatePointsVector(builder: FlatBufferBuilder, data: list) -> VectorOffset: ...
    @staticmethod
    def CreatePolylinesVector(builder: FlatBufferBuilder, data: list) -> VectorOffset: ...
    @staticmethod
    def CreateTextsVector(builder: FlatBufferBuilder, data: list) -> VectorOffset: ...
    @staticmethod
    def EndData(builder: FlatBufferBuilder) -> Offset: ...
    def Faces(self, j: int) -> Nullable: ...
    @staticmethod
    def FinishDataBuffer(builder: FlatBufferBuilder, offset: Offset) -> None: ...
    @staticmethod
    def GetRootAsData(_bb: ByteBuffer, obj: Data) -> Data: ...
    def Lines(self, j: int) -> Nullable: ...
    def Points(self, j: int) -> Nullable: ...
    def Polylines(self, j: int) -> Nullable: ...
    @staticmethod
    def StartColorsVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    @staticmethod
    def StartData(builder: FlatBufferBuilder) -> None: ...
    @staticmethod
    def StartFacesVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    @staticmethod
    def StartLinesVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    @staticmethod
    def StartPointsVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    @staticmethod
    def StartPolylinesVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    @staticmethod
    def StartTextsVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    def Texts(self, j: int) -> Nullable: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Data: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Face:
    """.NET: RenderData.Face"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    PosLength: int
    Colorindex: int
    @staticmethod
    def AddColorindex(builder: FlatBufferBuilder, colorindex: int) -> None: ...
    @staticmethod
    def AddPos(builder: FlatBufferBuilder, posOffset: VectorOffset) -> None: ...
    @staticmethod
    def CreateFace(builder: FlatBufferBuilder, posOffset: VectorOffset, colorindex: int) -> Offset: ...
    @staticmethod
    def EndFace(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsFace(_bb: ByteBuffer, obj: Face) -> Face: ...
    def Pos(self, j: int) -> Nullable: ...
    @staticmethod
    def StartFace(builder: FlatBufferBuilder) -> None: ...
    @staticmethod
    def StartPosVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Face: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Line:
    """.NET: RenderData.Line"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Start: Nullable
    End: Nullable
    Colorindex: int
    Width: LineWidth
    @staticmethod
    def AddColorindex(builder: FlatBufferBuilder, colorindex: int) -> None: ...
    @staticmethod
    def AddEnd(builder: FlatBufferBuilder, endOffset: Offset) -> None: ...
    @staticmethod
    def AddStart(builder: FlatBufferBuilder, startOffset: Offset) -> None: ...
    @staticmethod
    def AddWidth(builder: FlatBufferBuilder, Width: LineWidth) -> None: ...
    @staticmethod
    def EndLine(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsLine(_bb: ByteBuffer, obj: Line) -> Line: ...
    @staticmethod
    def StartLine(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Line: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class LineWidth:
    """.NET: RenderData.LineWidth"""
    def __init__(self, *args) -> None: ...
    ...

class Point:
    """.NET: RenderData.Point"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Pos: Nullable
    @staticmethod
    def AddPos(builder: FlatBufferBuilder, posOffset: Offset) -> None: ...
    @staticmethod
    def EndPoint(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsPoint(_bb: ByteBuffer, obj: Point) -> Point: ...
    @staticmethod
    def StartPoint(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Point: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class PolyLine:
    """.NET: RenderData.PolyLine"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    PosLength: int
    Colorindex: int
    Width: LineWidth
    @staticmethod
    def AddColorindex(builder: FlatBufferBuilder, colorindex: int) -> None: ...
    @staticmethod
    def AddPos(builder: FlatBufferBuilder, posOffset: VectorOffset) -> None: ...
    @staticmethod
    def AddWidth(builder: FlatBufferBuilder, Width: LineWidth) -> None: ...
    @staticmethod
    def CreatePolyLine(builder: FlatBufferBuilder, posOffset: VectorOffset, colorindex: int, Width: LineWidth) -> Offset: ...
    @staticmethod
    def EndPolyLine(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsPolyLine(_bb: ByteBuffer, obj: PolyLine) -> PolyLine: ...
    def Pos(self, j: int) -> Nullable: ...
    @staticmethod
    def StartPolyLine(builder: FlatBufferBuilder) -> None: ...
    @staticmethod
    def StartPosVector(builder: FlatBufferBuilder, numElems: int) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> PolyLine: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Text:
    """.NET: RenderData.Text"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    Pos: Nullable
    Textstr: str
    Size: float
    Colorindex: int
    @staticmethod
    def AddColorindex(builder: FlatBufferBuilder, colorindex: int) -> None: ...
    @staticmethod
    def AddPos(builder: FlatBufferBuilder, posOffset: Offset) -> None: ...
    @staticmethod
    def AddSize(builder: FlatBufferBuilder, size: float) -> None: ...
    @staticmethod
    def AddTextstr(builder: FlatBufferBuilder, textstrOffset: StringOffset) -> None: ...
    @staticmethod
    def EndText(builder: FlatBufferBuilder) -> Offset: ...
    @staticmethod
    def GetRootAsText(_bb: ByteBuffer, obj: Text) -> Text: ...
    def GetTextstrBytes(self, ) -> Nullable: ...
    @staticmethod
    def StartText(builder: FlatBufferBuilder) -> None: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Text: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...

class Vec3:
    """.NET: RenderData.Vec3"""
    def __init__(self, *args) -> None: ...
    ByteBuffer: ByteBuffer
    X: float
    Y: float
    Z: float
    @staticmethod
    def CreateVec3(builder: FlatBufferBuilder, X: float, Y: float, Z: float) -> Offset: ...
    def __assign(self, _i: int, _bb: ByteBuffer) -> Vec3: ...
    def __init(self, _i: int, _bb: ByteBuffer) -> None: ...
