# Auto-generated — Tekla 2026 — Render

class Color:
    """.NET: Render.Color"""
    def __init__(self, *args) -> None: ...
    ...

class Face:
    """.NET: Render.Face"""
    def __init__(self, *args) -> None: ...
    def Add(self, p: Point) -> None: ...

class Line:
    """.NET: Render.Line"""
    def __init__(self, *args) -> None: ...
    ...

class Point:
    """.NET: Render.Point"""
    def __init__(self, *args) -> None: ...
    ...

class Polyline:
    """.NET: Render.Polyline"""
    def __init__(self, *args) -> None: ...
    def Add(self, p: Point) -> None: ...

class RenderContainer:
    """.NET: Render.RenderContainer"""
    def __init__(self, *args) -> None: ...
    def AddColors(self, Colors: List) -> None: ...
    def AddFaces(self, Faces: List) -> None: ...
    def AddLines(self, Lines: List) -> None: ...
    def AddPoints(self, Points: List) -> None: ...
    def AddPolylines(self, Polylines: List) -> None: ...
    def AddTexts(self, Texts: List) -> None: ...
    def Delete(self, guid: Guid) -> list: ...
    def DeleteAll(self, ) -> list: ...
    def Render(self, guid: Guid) -> list: ...

class Text:
    """.NET: Render.Text"""
    def __init__(self, *args) -> None: ...
    ...

class Width:
    """.NET: Render.Width"""
    def __init__(self, *args) -> None: ...
    ...
