# Auto-generated — Rhino 8 — Rhino.Geometry.Collections

class BrepCurveList:
    """.NET: Rhino.Geometry.Collections.BrepCurveList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Curve
    def Add(self, curve: Curve) -> int: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class BrepEdgeList:
    """.NET: Rhino.Geometry.Collections.BrepEdgeList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: BrepEdge
    def Add(self, startVertex: BrepVertex, endVertex: BrepVertex, curve3dIndex: int, subDomain: Interval, edgeTolerance: float) -> BrepEdge: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def MergeAllEdges(self, angleTolerance: float) -> int: ...
    def MergeEdge(self, edgeIndex: int, angleTolerance: float) -> int: ...
    def RemoveNakedMicroEdges(self, tolerance: float, cleanUp: bool) -> int: ...
    def SplitEdgeAtParameters(self, edgeIndex: int, edgeParameters: IEnumerable) -> int: ...
    def SplitKinkyEdge(self, edgeIndex: int, kinkToleranceRadians: float) -> bool: ...

class BrepFaceList:
    """.NET: Rhino.Geometry.Collections.BrepFaceList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: BrepFace
    HasPerFaceColors: bool
    def Add(self, surfaceIndex: int) -> BrepFace: ...
    def AddConeFace(self, vertex: BrepVertex, edge: BrepEdge, revEdge: bool) -> BrepFace: ...
    def AddRuledFace(self, edgeA: BrepEdge, revEdgeA: bool, edgeB: BrepEdge, revEdgeB: bool) -> BrepFace: ...
    def ClearPerFaceColors(self, ) -> int: ...
    def ExtractFace(self, faceIndex: int) -> Brep: ...
    def Flip(self, onlyReversedFaces: bool) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def RemoveAt(self, faceIndex: int) -> None: ...
    def RemoveSlits(self, ) -> bool: ...
    def ShrinkFaces(self, ) -> bool: ...
    def SplitBipolarFaces(self, ) -> bool: ...
    def SplitClosedFaces(self, minimumDegree: int) -> bool: ...
    def SplitFaceAtTangents(self, faceIndex: int) -> bool: ...
    def SplitFacesAtTangents(self, ) -> bool: ...
    def SplitKinkyFace(self, faceIndex: int, kinkTolerance: float) -> bool: ...
    def SplitKinkyFaces(self, kinkTolerance: float, compact: bool) -> bool: ...
    def StandardizeFaceSurface(self, faceIndex: int) -> bool: ...
    def StandardizeFaceSurfaces(self, ) -> None: ...

class BrepLoopList:
    """.NET: Rhino.Geometry.Collections.BrepLoopList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: BrepLoop
    def Add(self, loopType: BrepLoopType, face: BrepFace) -> BrepLoop: ...
    def AddOuterLoop(self, faceIndex: int) -> BrepLoop: ...
    def AddPlanarFaceLoop(self, faceIndex: int, loopType: BrepLoopType, boundaryCurves: IEnumerable) -> BrepLoop: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class BrepSurfaceList:
    """.NET: Rhino.Geometry.Collections.BrepSurfaceList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Surface
    def GetEnumerator(self, ) -> IEnumerator: ...

class BrepTrimList:
    """.NET: Rhino.Geometry.Collections.BrepTrimList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: BrepTrim
    def Add(self, edge: BrepEdge, rev3d: bool, loop: BrepLoop, curve2dIndex: int) -> BrepTrim: ...
    def AddCurveOnFace(self, face: BrepFace, edge: BrepEdge, rev3d: bool, curve2dIndex: int) -> BrepTrim: ...
    def AddSingularTrim(self, vertex: BrepVertex, loop: BrepLoop, iso: IsoStatus, curve2dIndex: int) -> BrepTrim: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def MatchEnds(self, trim0: BrepTrim, trim1: BrepTrim) -> bool: ...

class BrepVertexList:
    """.NET: Rhino.Geometry.Collections.BrepVertexList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: BrepVertex
    def Add(self, point: Point3d, vertexTolerance: float) -> BrepVertex: ...
    def AddPointOnFace(self, face: BrepFace, s: float, t: float) -> BrepVertex: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class MeshFaceList:
    """.NET: Rhino.Geometry.Collections.MeshFaceList"""
    def __init__(self, *args) -> None: ...
    Count: int
    QuadCount: int
    TriangleCount: int
    Capacity: int
    Item: MeshFace
    def AddFace(self, vertex1: int, vertex2: int, vertex3: int, vertex4: int) -> int: ...
    def AddFaces(self, faces: IEnumerable) -> list: ...
    def AdjacentFaces(self, faceIndex: int) -> list: ...
    def Clear(self, ) -> None: ...
    def ConvertNonPlanarQuadsToTriangles(self, planarTolerance: float, angleToleranceRadians: float, splitMethod: int) -> int: ...
    def ConvertQuadsToTriangles(self, ) -> bool: ...
    def ConvertTrianglesToQuads(self, angleToleranceRadians: float, minimumDiagonalLengthRatio: float) -> bool: ...
    def CullDegenerateFaces(self, ) -> int: ...
    def DeleteFaces(self, faceIndexes: IEnumerable, compact: bool) -> int: ...
    def Destroy(self, ) -> None: ...
    def ExtractDuplicateFaces(self, ) -> Mesh: ...
    def ExtractFaces(self, faceIndices: IEnumerable) -> Mesh: ...
    def GetClashingFacePairs(self, maxPairCount: int) -> list: ...
    def GetConnectedFaces(self, faceIndex: int, angleRadians: float, greaterThanAngle: bool) -> list: ...
    def GetConnectedFacesToEdges(self, startFaceIndex: int, treatNonmanifoldLikeUnwelded: bool) -> list: ...
    def GetDuplicateFaces(self, ) -> list: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetFace(self, index: int) -> MeshFace: ...
    def GetFaceAspectRatio(self, index: int) -> float: ...
    def GetFaceBoundingBox(self, faceIndex: int) -> BoundingBox: ...
    def GetFaceCenter(self, faceIndex: int) -> Point3d: ...
    def GetFaceVertices(self, faceIndex: int, a: Point3f, b: Point3f, c: Point3f, d: Point3f) -> bool: ...
    def GetTopologicalVertices(self, faceIndex: int) -> list: ...
    def GetZeroAreaFaces(self, whollyDegenerateFaces: list, partiallyDegenerateFaces: list) -> bool: ...
    def HasNakedEdges(self, faceIndex: int) -> bool: ...
    def Insert(self, index: int, face: MeshFace) -> None: ...
    def IsHidden(self, faceIndex: int) -> bool: ...
    def MergeAdjacentFaces(self, edgeIndex: int) -> bool: ...
    def RemoveAt(self, index: int, compact: bool) -> None: ...
    def RemoveZeroAreaFaces(self, fixedFaceCount: int) -> int: ...
    def SetFace(self, index: int, vertex1: int, vertex2: int, vertex3: int, vertex4: int) -> bool: ...
    def ToIntArray(self, asTriangles: bool, replacedIndices: List) -> list: ...

class MeshFaceNormalList:
    """.NET: Rhino.Geometry.Collections.MeshFaceNormalList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Vector3f
    Capacity: int
    def AddFaceNormal(self, x: float, y: float, z: float) -> int: ...
    def Clear(self, ) -> None: ...
    def ComputeFaceNormals(self, ) -> bool: ...
    def Destroy(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def SetFaceNormal(self, index: int, x: float, y: float, z: float) -> bool: ...
    def UnitizeFaceNormals(self, ) -> bool: ...

class MeshNgonList:
    """.NET: Rhino.Geometry.Collections.MeshNgonList"""
    def __init__(self, *args) -> None: ...
    Count: int
    UnsignedCount: int
    Item: MeshNgon
    def AddNgon(self, ngon: MeshNgon) -> int: ...
    def AddNgons(self, ngons: IEnumerable) -> list: ...
    def AddPlanarNgons(self, planarTolerance: float, minimumNgonVertexCount: int, minimumNgonFaceCount: int, allowHoles: bool) -> int: ...
    def Clear(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetNgon(self, index: int) -> MeshNgon: ...
    def GetNgonBoundary(self, ngonFaceIndexList: IEnumerable) -> list: ...
    def GetNgonBoundingBox(self, index: int) -> BoundingBox: ...
    def GetNgonCenter(self, index: int) -> Point3d: ...
    def GetNgonEdgeCount(self, index: int) -> int: ...
    def GetNgonOuterEdgeCount(self, index: int) -> int: ...
    def Insert(self, index: int, ngon: MeshNgon) -> None: ...
    def IsValid(self, index: int, textLog: TextLog) -> int: ...
    def NgonBoundaryVertexList(self, ngon: MeshNgon, bAppendStartPoint: bool) -> list: ...
    def NgonHasHoles(self, index: int) -> bool: ...
    def NgonIndexFromFaceIndex(self, meshFaceIndex: int) -> int: ...
    def Orientation(self, index: int, permitHoles: bool) -> int: ...
    def RemoveAllNgons(self, ) -> int: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveNgons(self, indices: IEnumerable) -> int: ...
    def ReverseOuterBoundary(self, index: int) -> None: ...
    def SetNgon(self, index: int, ngon: MeshNgon) -> None: ...

class MeshTextureCoordinateList:
    """.NET: Rhino.Geometry.Collections.MeshTextureCoordinateList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Capacity: int
    Item: Point2f
    def Add(self, s: float, t: float) -> int: ...
    def AddRange(self, textureCoordinates: list) -> bool: ...
    def Clear(self, ) -> None: ...
    def Destroy(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def NormalizeTextureCoordinates(self, ) -> bool: ...
    def ReverseTextureCoordinates(self, direction: int) -> bool: ...
    def SetTextureCoordinate(self, index: int, s: float, t: float) -> bool: ...
    def SetTextureCoordinates(self, textureCoordinates: list) -> bool: ...
    def ToFloatArray(self, ) -> list: ...
    def TransposeTextureCoordinates(self, ) -> bool: ...

class MeshTopologyEdgeList:
    """.NET: Rhino.Geometry.Collections.MeshTopologyEdgeList"""
    def __init__(self, *args) -> None: ...
    Count: int
    def CollapseEdge(self, topologyEdgeIndex: int) -> bool: ...
    def EdgeLine(self, topologyEdgeIndex: int) -> Line: ...
    def GetConnectedFaces(self, topologyEdgeIndex: int, faceOrientationMatchesEdgeDirection: list) -> list: ...
    def GetEdgeIndex(self, topologyVertex1: int, topologyVertex2: int) -> int: ...
    def GetEdgesForFace(self, faceIndex: int, sameOrientation: list) -> list: ...
    def GetTopologyVertices(self, topologyEdgeIndex: int) -> IndexPair: ...
    def IsEdgeUnwelded(self, topologyEdgeIndex: int) -> bool: ...
    def IsHidden(self, topologyEdgeIndex: int) -> bool: ...
    def IsNgonInterior(self, topologyEdgeIndex: int) -> bool: ...
    def IsSwappableEdge(self, topologyEdgeIndex: int) -> bool: ...
    def SplitEdge(self, topologyEdgeIndex: int, t: float) -> bool: ...
    def SwapEdge(self, topologyEdgeIndex: int) -> bool: ...

class MeshTopologyVertexList:
    """.NET: Rhino.Geometry.Collections.MeshTopologyVertexList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Point3f
    def ConnectedEdge(self, topologyVertexIndex: int, edgeAtVertexIndex: int) -> int: ...
    def ConnectedEdges(self, topologyVertexIndex: int) -> list: ...
    def ConnectedEdgesCount(self, topologyVertexIndex: int) -> int: ...
    def ConnectedFaces(self, topologyVertexIndex: int) -> list: ...
    def ConnectedTopologyVertices(self, topologyVertexIndex: int, sorted: bool) -> list: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndicesFromFace(self, faceIndex: int) -> list: ...
    def IsHidden(self, topologyVertexIndex: int) -> bool: ...
    def MeshVertexIndices(self, topologyVertexIndex: int) -> list: ...
    def SortEdges(self, topologyVertexIndex: int) -> bool: ...
    def TopologyVertexIndex(self, vertexIndex: int) -> int: ...

class MeshVertexColorList:
    """.NET: Rhino.Geometry.Collections.MeshVertexColorList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Color
    Tag: MappingTag
    Capacity: int
    def Add(self, red: int, green: int, blue: int) -> int: ...
    def AddRange(self, colors: IEnumerable) -> bool: ...
    def AppendColors(self, colors: list) -> bool: ...
    def Clear(self, ) -> None: ...
    def CreateMonotoneMesh(self, baseColor: Color) -> bool: ...
    def Destroy(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def SetColor(self, index: int, red: int, green: int, blue: int) -> bool: ...
    def SetColors(self, colors: list) -> bool: ...
    def ToARGBArray(self, ) -> list: ...

class MeshVertexList:
    """.NET: Rhino.Geometry.Collections.MeshVertexList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Capacity: int
    Item: Point3f
    UseDoublePrecisionVertices: bool
    def Add(self, x: float, y: float, z: float) -> int: ...
    def AddVertices(self, vertices: IEnumerable) -> None: ...
    @staticmethod
    def Align(meshes: IEnumerable, distance: float, whichVertices: IEnumerable) -> int: ...
    def Clear(self, ) -> None: ...
    def CombineIdentical(self, ignoreNormals: bool, ignoreAdditional: bool) -> bool: ...
    def CullUnused(self, ) -> int: ...
    def Destroy(self, ) -> None: ...
    def GetConnectedVertices(self, vertexIndex: int) -> list: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetTopologicalIndenticalVertices(self, vertexIndex: int) -> list: ...
    def GetVertexFaces(self, vertexIndex: int) -> list: ...
    def Hide(self, vertexIndex: int) -> None: ...
    def HideAll(self, ) -> None: ...
    def IsHidden(self, vertexIndex: int) -> bool: ...
    def Point3dAt(self, index: int) -> Point3d: ...
    def Remove(self, index: int, shrinkFaces: bool) -> bool: ...
    def SetVertex(self, index: int, x: float, y: float, z: float, updateNormals: bool) -> bool: ...
    def Show(self, vertexIndex: int) -> None: ...
    def ShowAll(self, ) -> None: ...
    def ToFloatArray(self, ) -> list: ...
    def ToPoint3dArray(self, ) -> list: ...
    def ToPoint3fArray(self, ) -> list: ...

class MeshVertexNormalList:
    """.NET: Rhino.Geometry.Collections.MeshVertexNormalList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Capacity: int
    Item: Vector3f
    def Add(self, x: float, y: float, z: float) -> int: ...
    def AddRange(self, normals: list) -> bool: ...
    def Clear(self, ) -> None: ...
    def ComputeNormals(self, ) -> bool: ...
    def Destroy(self, ) -> None: ...
    def Flip(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def SetNormal(self, index: int, x: float, y: float, z: float) -> bool: ...
    def SetNormals(self, normals: list) -> bool: ...
    def ToFloatArray(self, ) -> list: ...
    def UnitizeNormals(self, ) -> bool: ...

class MeshVertexStatusList:
    """.NET: Rhino.Geometry.Collections.MeshVertexStatusList"""
    def __init__(self, *args) -> None: ...
    Count: int
    HiddenCount: int
    Capacity: int
    Item: bool
    def Add(self, hidden: bool) -> None: ...
    def AddRange(self, values: IEnumerable) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, hidden: bool) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def Destroy(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class NurbsCurveKnotList:
    """.NET: Rhino.Geometry.Collections.NurbsCurveKnotList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: float
    IsClampedStart: bool
    IsClampedEnd: bool
    KnotStyle: KnotStyle
    def ClampEnd(self, end: CurveEnd) -> bool: ...
    def Contains(self, item: float) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def CreatePeriodicKnots(self, knotSpacing: float) -> bool: ...
    def CreateUniformKnots(self, knotSpacing: float) -> bool: ...
    def EnsurePrivateCopy(self, ) -> None: ...
    def EpsilonEquals(self, other: NurbsCurveKnotList, epsilon: float) -> bool: ...
    def IndexOf(self, item: float) -> int: ...
    def InsertKnot(self, value: float, multiplicity: int) -> bool: ...
    def KnotMultiplicity(self, index: int) -> int: ...
    def RemoveKnotAt(self, t: float) -> bool: ...
    def RemoveKnots(self, index0: int, index1: int) -> bool: ...
    def RemoveMultipleKnots(self, minimumMultiplicity: int, maximumMultiplicity: int, tolerance: float) -> int: ...
    def SuperfluousKnot(self, start: bool) -> float: ...

class NurbsCurvePointList:
    """.NET: Rhino.Geometry.Collections.NurbsCurvePointList"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: ControlPoint
    ControlPolygonLength: float
    PointSize: int
    def ChangeEndWeights(self, w0: float, w1: float) -> bool: ...
    def Contains(self, item: ControlPoint) -> bool: ...
    def ControlPolygon(self, ) -> Polyline: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def EnsurePrivateCopy(self, ) -> None: ...
    def EpsilonEquals(self, other: NurbsCurvePointList, epsilon: float) -> bool: ...
    def GetPoint(self, index: int, point: Point3d) -> bool: ...
    def GetWeight(self, index: int) -> float: ...
    def IndexOf(self, item: ControlPoint) -> int: ...
    def MakeNonRational(self, ) -> bool: ...
    def MakeRational(self, ) -> bool: ...
    def SetPoint(self, index: int, x: float, y: float, z: float, weight: float) -> bool: ...
    def SetWeight(self, index: int, weight: float) -> bool: ...
    def UVNDirectionsAt(self, index: int, uDir: Vector3d, vDir: Vector3d, nDir: Vector3d) -> bool: ...
    def ValidateSpacing(self, closeTolerance: float, stackTolerance: float, closeIndices: list, stackedIndices: list) -> bool: ...

class NurbsSurfaceKnotList:
    """.NET: Rhino.Geometry.Collections.NurbsSurfaceKnotList"""
    def __init__(self, *args) -> None: ...
    Count: int
    ClampedAtStart: bool
    ClampedAtEnd: bool
    KnotStyle: KnotStyle
    Item: float
    def CreatePeriodicKnots(self, knotSpacing: float) -> bool: ...
    def CreateUniformKnots(self, knotSpacing: float) -> bool: ...
    def EnsurePrivateCopy(self, ) -> None: ...
    def EpsilonEquals(self, other: NurbsSurfaceKnotList, epsilon: float) -> bool: ...
    def InsertKnot(self, value: float, multiplicity: int) -> bool: ...
    def KnotMultiplicity(self, index: int) -> int: ...
    def RemoveKnots(self, index0: int, index1: int) -> bool: ...
    def RemoveKnotsAt(self, u: float, v: float) -> bool: ...
    def RemoveMultipleKnots(self, minimumMultiplicity: int, maximumMultiplicity: int, tolerance: float) -> int: ...
    def SuperfluousKnot(self, start: bool) -> float: ...

class NurbsSurfacePointList:
    """.NET: Rhino.Geometry.Collections.NurbsSurfacePointList"""
    def __init__(self, *args) -> None: ...
    CountU: int
    CountV: int
    PointSize: int
    def EnsurePrivateCopy(self, ) -> None: ...
    def EpsilonEquals(self, other: NurbsSurfacePointList, epsilon: float) -> bool: ...
    def GetControlPoint(self, u: int, v: int) -> ControlPoint: ...
    def GetGrevillePoint(self, u: int, v: int) -> Point2d: ...
    def GetPoint(self, u: int, v: int, point: Point3d) -> bool: ...
    def GetWeight(self, u: int, v: int) -> float: ...
    def SetControlPoint(self, u: int, v: int, cp: ControlPoint) -> bool: ...
    def SetPoint(self, u: int, v: int, x: float, y: float, z: float, weight: float) -> bool: ...
    def SetWeight(self, u: int, v: int, weight: float) -> bool: ...
    def UVNDirectionsAt(self, u: int, v: int, uDir: Vector3d, vDir: Vector3d, nDir: Vector3d) -> bool: ...
    def ValidateSpacing(self, closeTolerance: float, stackTolerance: float, closeIndices: list, stackedIndices: list) -> bool: ...

class SubDEdgeList:
    """.NET: Rhino.Geometry.Collections.SubDEdgeList"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, tag: SubDEdgeTag, v0: SubDVertex, v1: SubDVertex) -> SubDEdge: ...
    def Find(self, id: int) -> SubDEdge: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def SetEdgeTags(self, edgeIndices: IEnumerable, tag: SubDEdgeTag) -> None: ...

class SubDFaceList:
    """.NET: Rhino.Geometry.Collections.SubDFaceList"""
    def __init__(self, *args) -> None: ...
    Count: int
    HasPerFaceColors: bool
    def ClearPerFaceColors(self, ) -> int: ...
    def Find(self, id: int) -> SubDFace: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class SubDVertexList:
    """.NET: Rhino.Geometry.Collections.SubDVertexList"""
    def __init__(self, *args) -> None: ...
    Count: int
    First: SubDVertex
    def Add(self, tag: SubDVertexTag, vertex: Point3d) -> SubDVertex: ...
    def Find(self, id: int) -> SubDVertex: ...
    def SetVertexTags(self, vertexIndices: IEnumerable, tag: SubDVertexTag) -> None: ...
