# Auto-generated — Rhino 8 — Rhino.Geometry.Intersect

class ArcArcIntersection:
    """.NET: Rhino.Geometry.Intersect.ArcArcIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class CircleCircleIntersection:
    """.NET: Rhino.Geometry.Intersect.CircleCircleIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class CurveIntersections:
    """.NET: Rhino.Geometry.Intersect.CurveIntersections"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: IntersectionEvent
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class Intersection:
    """.NET: Rhino.Geometry.Intersect.Intersection"""
    def __init__(self, *args) -> None: ...
    MeshIntersectionsTolerancesCoefficient: float
    @staticmethod
    def ArcArc(arcA: Arc, arcB: Arc, intersectionPoint1: Point3d, intersectionPoint2: Point3d) -> ArcArcIntersection: ...
    @staticmethod
    def BrepBrep(brepA: Brep, brepB: Brep, tolerance: float, joinCurves: bool, intersectionCurves: list, intersectionPoints: list) -> bool: ...
    @staticmethod
    def BrepPlane(brep: Brep, plane: Plane, tolerance: float, joinCurves: bool, intersectionCurves: list, intersectionPoints: list) -> bool: ...
    @staticmethod
    def BrepSurface(brep: Brep, surface: Surface, tolerance: float, joinCurves: bool, intersectionCurves: list, intersectionPoints: list) -> bool: ...
    @staticmethod
    def CircleCircle(circleA: Circle, circleB: Circle, intersectionPoint1: Point3d, intersectionPoint2: Point3d) -> CircleCircleIntersection: ...
    @staticmethod
    def CurveBrep(curve: Curve, brep: Brep, tolerance: float, overlapCurves: list, intersectionPoints: list, curveParameters: list) -> bool: ...
    @staticmethod
    def CurveBrepFace(curve: Curve, face: BrepFace, tolerance: float, overlapCurves: list, intersectionPoints: list) -> bool: ...
    @staticmethod
    def CurveCurve(curveA: Curve, curveB: Curve, tolerance: float, overlapTolerance: float) -> CurveIntersections: ...
    @staticmethod
    def CurveCurveValidate(curveA: Curve, curveB: Curve, tolerance: float, overlapTolerance: float, invalidIndices: list, textLog: TextLog) -> CurveIntersections: ...
    @staticmethod
    def CurveLine(curve: Curve, line: Line, tolerance: float, overlapTolerance: float) -> CurveIntersections: ...
    @staticmethod
    def CurvePlane(curve: Curve, plane: Plane, tolerance: float) -> CurveIntersections: ...
    @staticmethod
    def CurveSelf(curve: Curve, tolerance: float) -> CurveIntersections: ...
    @staticmethod
    def CurveSurface(curve: Curve, curveDomain: Interval, surface: Surface, tolerance: float, overlapTolerance: float) -> CurveIntersections: ...
    @staticmethod
    def CurveSurfaceValidate(curve: Curve, curveDomain: Interval, surface: Surface, tolerance: float, overlapTolerance: float, invalidIndices: list, textLog: TextLog) -> CurveIntersections: ...
    @staticmethod
    def LineBox(line: Line, box: BoundingBox, tolerance: float, lineParameters: Interval) -> bool: ...
    @staticmethod
    def LineCircle(line: Line, circle: Circle, t1: float, point1: Point3d, t2: float, point2: Point3d) -> LineCircleIntersection: ...
    @staticmethod
    def LineCylinder(line: Line, cylinder: Cylinder, intersectionPoint1: Point3d, intersectionPoint2: Point3d) -> LineCylinderIntersection: ...
    @staticmethod
    def LineLine(lineA: Line, lineB: Line, a: float, b: float, tolerance: float, finiteSegments: bool) -> bool: ...
    @staticmethod
    def LinePlane(line: Line, plane: Plane, lineParameter: float) -> bool: ...
    @staticmethod
    def LineSphere(line: Line, sphere: Sphere, intersectionPoint1: Point3d, intersectionPoint2: Point3d) -> LineSphereIntersection: ...
    @staticmethod
    def MeshLine(mesh: Mesh, line: Line, faceIds: list) -> list: ...
    @staticmethod
    def MeshLineSorted(mesh: Mesh, line: Line, faceIds: list) -> list: ...
    @staticmethod
    def MeshMesh(meshes: IEnumerable, tolerance: float, intersections: list, overlapsPolylines: bool, overlapsPolylinesResult: list, overlapsMesh: bool, overlapsMeshResult: Mesh, textLog: TextLog, cancel: CancellationToken, progress: IProgress) -> bool: ...
    @staticmethod
    def MeshMeshAccurate(meshA: Mesh, meshB: Mesh, tolerance: float) -> list: ...
    @staticmethod
    def MeshMeshFast(meshA: Mesh, meshB: Mesh) -> list: ...
    @staticmethod
    def MeshMeshPredicate(meshes: IEnumerable, tolerance: float, pairs: list, textLog: TextLog) -> bool: ...
    @staticmethod
    def MeshPlane(mesh: Mesh, cache: MeshIntersectionCache, plane: Plane, tolerance: float) -> list: ...
    @staticmethod
    def MeshPolyline(mesh: Mesh, curve: PolylineCurve, faceIds: list) -> list: ...
    @staticmethod
    def MeshPolylineSorted(mesh: Mesh, curve: PolylineCurve, faceIds: list) -> list: ...
    @staticmethod
    def MeshRay(mesh: Mesh, ray: Ray3d, meshFaceIndices: list) -> float: ...
    @staticmethod
    def PlaneBoundingBox(plane: Plane, boundingBox: BoundingBox, polyline: Polyline) -> bool: ...
    @staticmethod
    def PlaneCircle(plane: Plane, circle: Circle, firstCircleParameter: float, secondCircleParameter: float) -> PlaneCircleIntersection: ...
    @staticmethod
    def PlanePlane(planeA: Plane, planeB: Plane, intersectionLine: Line) -> bool: ...
    @staticmethod
    def PlanePlanePlane(planeA: Plane, planeB: Plane, planeC: Plane, intersectionPoint: Point3d) -> bool: ...
    @staticmethod
    def PlaneSphere(plane: Plane, sphere: Sphere, intersectionCircle: Circle) -> PlaneSphereIntersection: ...
    @staticmethod
    def ProjectPointsToBreps(breps: IEnumerable, points: IEnumerable, direction: Vector3d, tolerance: float) -> list: ...
    @staticmethod
    def ProjectPointsToBrepsEx(breps: IEnumerable, points: IEnumerable, direction: Vector3d, tolerance: float, indices: list) -> list: ...
    @staticmethod
    def ProjectPointsToMeshes(meshes: IEnumerable, points: IEnumerable, direction: Vector3d, tolerance: float) -> list: ...
    @staticmethod
    def ProjectPointsToMeshesEx(meshes: IEnumerable, points: IEnumerable, direction: Vector3d, tolerance: float, indices: list) -> list: ...
    @staticmethod
    def RayShoot(ray: Ray3d, geometry: IEnumerable, maxReflections: int) -> list: ...
    @staticmethod
    def SphereSphere(sphereA: Sphere, sphereB: Sphere, intersectionCircle: Circle) -> SphereSphereIntersection: ...
    @staticmethod
    def SurfaceSurface(surfaceA: Surface, surfaceB: Surface, tolerance: float, intersectionCurves: list, intersectionPoints: list) -> bool: ...

class IntersectionEvent:
    """.NET: Rhino.Geometry.Intersect.IntersectionEvent"""
    def __init__(self, *args) -> None: ...
    IsPoint: bool
    IsOverlap: bool
    PointA: Point3d
    PointA2: Point3d
    PointB: Point3d
    PointB2: Point3d
    ParameterA: float
    ParameterB: float
    OverlapA: Interval
    OverlapB: Interval
    @staticmethod
    def CompareEquivalent(eventA: IntersectionEvent, eventB: IntersectionEvent, relativePointTolerance: float, log: TextLog) -> bool: ...
    def SurfaceOverlapParameter(self, uDomain: Interval, vDomain: Interval) -> None: ...
    def SurfacePointParameter(self, u: float, v: float) -> None: ...

class LineCircleIntersection:
    """.NET: Rhino.Geometry.Intersect.LineCircleIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class LineCylinderIntersection:
    """.NET: Rhino.Geometry.Intersect.LineCylinderIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class LineSphereIntersection:
    """.NET: Rhino.Geometry.Intersect.LineSphereIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class MeshClash:
    """.NET: Rhino.Geometry.Intersect.MeshClash"""
    def __init__(self, *args) -> None: ...
    MeshA: Mesh
    MeshB: Mesh
    ClashPoint: Point3d
    ClashRadius: float
    @staticmethod
    def FindDetail(objA: RhinoObject, objB: RhinoObject, distance: float, meshType: MeshType, meshingParameters: MeshingParameters) -> list: ...
    @staticmethod
    def Search(setA: IEnumerable, setB: IEnumerable, distance: float, meshType: MeshType, meshingParameters: MeshingParameters) -> list: ...

class MeshInterference:
    """.NET: Rhino.Geometry.Intersect.MeshInterference"""
    def __init__(self, *args) -> None: ...
    IndexA: int
    IndexB: int
    HitPoints: list

class MeshIntersectionCache:
    """.NET: Rhino.Geometry.Intersect.MeshIntersectionCache"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class PlaneCircleIntersection:
    """.NET: Rhino.Geometry.Intersect.PlaneCircleIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class PlaneSphereIntersection:
    """.NET: Rhino.Geometry.Intersect.PlaneSphereIntersection"""
    def __init__(self, *args) -> None: ...
    ...

class RayShootEvent:
    """.NET: Rhino.Geometry.Intersect.RayShootEvent"""
    def __init__(self, *args) -> None: ...
    GeometryIndex: int
    BrepFaceIndex: int
    Point: Point3d

class SphereSphereIntersection:
    """.NET: Rhino.Geometry.Intersect.SphereSphereIntersection"""
    def __init__(self, *args) -> None: ...
    ...
