# Auto-generated — Tekla 2026 — Tekla.Structures.Internal

class ArcTools:
    """.NET: Tekla.Structures.Internal.ArcTools"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AreArcPointsCollinear(point1: Point, point2: Point, point3: Point) -> bool: ...
    @staticmethod
    def ConstructArc(startPoint: Point, endPoint: Point, radius: float, isLargeArc: bool) -> Arc: ...
    @staticmethod
    def GetArcAngleBy3Points(startPoint: Point, endPoint: Point, pointOnArc: Point, arcNormal: Vector) -> Angle: ...
    @staticmethod
    def GetArcCenterPointFromTangent(startPoint: Point, endPoint: Point, pointOnTangent: Point, arcNormal: Vector) -> Point: ...
    @staticmethod
    def GetArcCenterPointUsing3Points(startPoint: Point, endPoint: Point, pointOnArc: Point) -> Point: ...
    @staticmethod
    def GetArcMiddlePoint(startPoint: Point, endPoint: Point, centerPoint: Point, normal: Vector) -> Point: ...
    @staticmethod
    def GetArcNormal(startPoint: Point, endPoint: Point, pointOnArc: Point) -> Vector: ...
    @staticmethod
    def GetBulgeToWidthRatio(startPoint: Point, endPoint: Point, pointOnArc: Point) -> float: ...

class Channels:
    """.NET: Tekla.Structures.Internal.Channels"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GenerateUniqueRemotingChannel(channelMainName: str) -> str: ...

class DotAnalysisModuleManagerQuery:
    """.NET: Tekla.Structures.Internal.DotAnalysisModuleManagerQuery"""
    def __init__(self, *args) -> None: ...
    ...

class FormWrapperFunctionality(WrapperFunctionalityBase):
    """.NET: Tekla.Structures.Internal.FormWrapperFunctionality"""
    def __init__(self, *args) -> None: ...
    def Invoke0(self, method: TargetMethod0) -> TResult: ...
    def Invoke16vvvvvvvvvvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12, p13: T13, p14: T14, p15: T15, method: TargetMethod16vvvvvvvvvvvvvvvv) -> TResult: ...
    def Invoke18vvvvvvvvvvvvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12, p13: T13, p14: T14, p15: T15, p16: T16, p17: T17, method: TargetMethod18vvvvvvvvvvvvvvvvvv) -> TResult: ...
    def Invoke1r(self, p0: T0, method: TargetMethod1r) -> TResult: ...
    def Invoke1v(self, p0: T0, method: TargetMethod1v) -> TResult: ...
    def Invoke2rr(self, p0: T0, p1: T1, method: TargetMethod2rr) -> TResult: ...
    def Invoke2rv(self, p0: T0, p1: T1, method: TargetMethod2rv) -> TResult: ...
    def Invoke2vr(self, p0: T0, p1: T1, method: TargetMethod2vr) -> TResult: ...
    def Invoke2vv(self, p0: T0, p1: T1, method: TargetMethod2vv) -> TResult: ...
    def Invoke3rrr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3rrr) -> TResult: ...
    def Invoke3rrv(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3rrv) -> TResult: ...
    def Invoke3rvv(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3rvv) -> TResult: ...
    def Invoke3vrr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vrr) -> TResult: ...
    def Invoke3vvr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vvr) -> TResult: ...
    def Invoke3vvv(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vvv) -> TResult: ...
    def Invoke4rrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4rrrr) -> TResult: ...
    def Invoke4rrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4rrrv) -> TResult: ...
    def Invoke4rrvv(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4rrvv) -> TResult: ...
    def Invoke4vvrr(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4vvrr) -> TResult: ...
    def Invoke4vvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4vvvr) -> TResult: ...
    def Invoke4vvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4vvvv) -> TResult: ...
    def Invoke5rrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5rrrrr) -> TResult: ...
    def Invoke5rrvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5rrvvv) -> TResult: ...
    def Invoke5rvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5rvvvv) -> TResult: ...
    def Invoke5vvrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvrrr) -> TResult: ...
    def Invoke5vvrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvrrv) -> TResult: ...
    def Invoke5vvvrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvvrr) -> TResult: ...
    def Invoke5vvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvvvv) -> TResult: ...
    def Invoke6rrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6rrrrrr) -> TResult: ...
    def Invoke6rrrrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6rrrrrv) -> TResult: ...
    def Invoke6vrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vrrrrr) -> TResult: ...
    def Invoke6vvrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvrrrr) -> TResult: ...
    def Invoke6vvrrvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvrrvv) -> TResult: ...
    def Invoke6vvvrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvrrr) -> TResult: ...
    def Invoke6vvvvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvvvr) -> TResult: ...
    def Invoke6vvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvvvv) -> TResult: ...
    def Invoke7rrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7rrrrrrr) -> TResult: ...
    def Invoke7vrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vrrrrrr) -> TResult: ...
    def Invoke7vvrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvrrrrr) -> TResult: ...
    def Invoke7vvrrvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvrrvvv) -> TResult: ...
    def Invoke7vvvvvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvvvvvr) -> TResult: ...
    def Invoke8vvvvvvrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, method: TargetMethod8vvvvvvrv) -> TResult: ...
    def Invoke8vvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, method: TargetMethod8vvvvvvvv) -> TResult: ...
    def Invoke9rrrrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, method: TargetMethod9rrrrrrrrr) -> TResult: ...
    def Invoke9vvvvvvvrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, method: TargetMethod9vvvvvvvrv) -> TResult: ...

class IAsyncCallCompletion:
    """.NET: Tekla.Structures.Internal.IAsyncCallCompletion`1"""
    def __init__(self, *args) -> None: ...
    def OnCompleted(self, result: TResult) -> None: ...
    def OnException(self, exception: Exception) -> None: ...

class ITsInvoker:
    """.NET: Tekla.Structures.Internal.ITsInvoker"""
    def __init__(self, *args) -> None: ...
    AppDomainFriendlyName: str
    def CreateInstance(self, assemblyName: str, typeName: str, parameters: list) -> object: ...
    def CreatePermanentInstance(self, assemblyName: str, typeName: str, parameters: list) -> object: ...
    def FreePermanentInstance(self, instance: object) -> None: ...
    def GetAssemblyLocation(self, assemblyName: str) -> str: ...
    def GetMethodNames(self, assemblyName: str, typeName: str) -> list: ...
    def GetTypeNames(self, assemblyName: str) -> list: ...
    def Invoke(self, assemblyName: str, typeName: str, methodName: str, parameters: list) -> object: ...
    def InvokeMember(self, assemblyName: str, typeName: str, memberName: str, invokeFlags: BindingFlags, parameters: list) -> object: ...
    def IsSubclass(self, assemblyName: str, typeName: str, parentAssemblyName: str, parentTypeName: str) -> bool: ...
    def Load(self, assemblyName: str) -> str: ...
    def LoadFrom(self, assemblyFileName: str) -> str: ...

class MessagePump:
    """.NET: Tekla.Structures.Internal.MessagePump"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def InitializeForHeadless() -> None: ...
    @staticmethod
    def Pump(task: Task) -> bool: ...

class Plugins:
    """.NET: Tekla.Structures.Internal.Plugins"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CancelCurrentPlugin() -> int: ...
    @staticmethod
    def DefinePluginInput(SeparateThread: bool) -> bool: ...
    @staticmethod
    def GetDefaultExtensionsFolder() -> str: ...
    @staticmethod
    def GetExtensionsDirectories() -> list: ...
    @staticmethod
    def GetPluginBaseDirectory() -> str: ...
    @staticmethod
    def GetPluginFormFullName(pluginName: str, pluginFormFullName: str) -> bool: ...
    @staticmethod
    def GetPluginNameFromFormFullName(pluginFormFullName: str, pluginName: str) -> bool: ...
    @staticmethod
    def InstantiateAndSetAsCurrentPlugin(PluginName: str, CreateInvoker: CreateInvokerDelegate) -> bool: ...
    @staticmethod
    def IsConnectionPlugin(pluginName: str) -> bool: ...
    @staticmethod
    def IsDrawingPlugin(pluginName: str) -> bool: ...
    @staticmethod
    def LoadPluginAssembly(pluginAssemblyLocation: str) -> Assembly: ...
    @staticmethod
    def ResetCurrentPlugin() -> None: ...
    @staticmethod
    def Run(param: str) -> bool: ...
    @staticmethod
    def RunCurrent() -> bool: ...

class RemotingProxyFactory(MarshalByRefObject):
    """.NET: Tekla.Structures.Internal.RemotingProxyFactory"""
    def __init__(self, *args) -> None: ...
    Default: RemotingProxyFactory
    def CreateRemotingProxy(self, assemblyName: str, typeName: str) -> object: ...
    def InitializeLifetimeService(self, ) -> object: ...
    def UseInDomain(self, domain: AppDomain) -> None: ...

class RemotingProxyHelper:
    """.NET: Tekla.Structures.Internal.RemotingProxyHelper"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateNewInstance(channelName: str) -> I: ...
    @staticmethod
    def DisposeService() -> None: ...
    @staticmethod
    def IsFormWrapperRequired() -> bool: ...
    @staticmethod
    def IsTsProcess() -> bool: ...
    @staticmethod
    def SetRemotingProxyFactory(factory: RemotingProxyFactory) -> None: ...

class StructuresDataStorage(StructuresDataStorageBase):
    """.NET: Tekla.Structures.Internal.StructuresDataStorage"""
    def __init__(self, *args) -> None: ...
    def GetVariable(self, name: str) -> object: ...
    def GetVariables(self, names: list) -> IDictionary: ...

class StructuresDataStorageBase(MarshalByRefObject):
    """.NET: Tekla.Structures.Internal.StructuresDataStorageBase"""
    def __init__(self, *args) -> None: ...
    def GetVariable(self, name: str) -> object: ...
    def GetVariables(self, names: list) -> IDictionary: ...
    def InitializeLifetimeService(self, ) -> object: ...

class StructuresMetadataLoader:
    """.NET: Tekla.Structures.Internal.StructuresMetadataLoader"""
    def __init__(self, *args) -> None: ...
    ...

class SynchronizeInvokeFunctionality(WrapperFunctionalityBase):
    """.NET: Tekla.Structures.Internal.SynchronizeInvokeFunctionality"""
    def __init__(self, *args) -> None: ...
    def Invoke0(self, Method: TargetMethod0) -> TResult: ...
    def Invoke16vvvvvvvvvvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12, p13: T13, p14: T14, p15: T15, method: TargetMethod16vvvvvvvvvvvvvvvv) -> TResult: ...
    def Invoke18vvvvvvvvvvvvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12, p13: T13, p14: T14, p15: T15, p16: T16, p17: T17, method: TargetMethod18vvvvvvvvvvvvvvvvvv) -> TResult: ...
    def Invoke1r(self, P0: T0, Method: TargetMethod1r) -> TResult: ...
    def Invoke1v(self, P0: T0, Method: TargetMethod1v) -> TResult: ...
    def Invoke2rr(self, P0: T0, P1: T1, Method: TargetMethod2rr) -> TResult: ...
    def Invoke2rv(self, P0: T0, P1: T1, Method: TargetMethod2rv) -> TResult: ...
    def Invoke2vr(self, P0: T0, P1: T1, Method: TargetMethod2vr) -> TResult: ...
    def Invoke2vv(self, P0: T0, P1: T1, Method: TargetMethod2vv) -> TResult: ...
    def Invoke3rrr(self, P0: T0, P1: T1, P2: T2, Method: TargetMethod3rrr) -> TResult: ...
    def Invoke3rrv(self, P0: T0, P1: T1, P2: T2, Method: TargetMethod3rrv) -> TResult: ...
    def Invoke3rvv(self, P0: T0, P1: T1, P2: T2, Method: TargetMethod3rvv) -> TResult: ...
    def Invoke3vrr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vrr) -> TResult: ...
    def Invoke3vvr(self, P0: T0, P1: T1, P2: T2, Method: TargetMethod3vvr) -> TResult: ...
    def Invoke3vvv(self, P0: T0, P1: T1, P2: T2, Method: TargetMethod3vvv) -> TResult: ...
    def Invoke4rrrr(self, P0: T0, P1: T1, P2: T2, P3: T3, Method: TargetMethod4rrrr) -> TResult: ...
    def Invoke4rrrv(self, P0: T0, P1: T1, P2: T2, P3: T3, Method: TargetMethod4rrrv) -> TResult: ...
    def Invoke4rrvv(self, P0: T0, P1: T1, P2: T2, P3: T3, Method: TargetMethod4rrvv) -> TResult: ...
    def Invoke4vvrr(self, P0: T0, P1: T1, P2: T2, P3: T3, Method: TargetMethod4vvrr) -> TResult: ...
    def Invoke4vvvr(self, P0: T0, P1: T1, P2: T2, P3: T3, Method: TargetMethod4vvvr) -> TResult: ...
    def Invoke4vvvv(self, P0: T0, P1: T1, P2: T2, P3: T3, Method: TargetMethod4vvvv) -> TResult: ...
    def Invoke5rrrrr(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5rrrrr) -> TResult: ...
    def Invoke5rrvvv(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5rrvvv) -> TResult: ...
    def Invoke5rvvvv(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5rvvvv) -> TResult: ...
    def Invoke5vvrrr(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5vvrrr) -> TResult: ...
    def Invoke5vvrrv(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5vvrrv) -> TResult: ...
    def Invoke5vvvrr(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5vvvrr) -> TResult: ...
    def Invoke5vvvvv(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, Method: TargetMethod5vvvvv) -> TResult: ...
    def Invoke6rrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6rrrrrr) -> TResult: ...
    def Invoke6rrrrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6rrrrrv) -> TResult: ...
    def Invoke6vrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vrrrrr) -> TResult: ...
    def Invoke6vvrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvrrrr) -> TResult: ...
    def Invoke6vvrrvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvrrvv) -> TResult: ...
    def Invoke6vvvrrr(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, P5: T5, Method: TargetMethod6vvvrrr) -> TResult: ...
    def Invoke6vvvvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvvvr) -> TResult: ...
    def Invoke6vvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvvvv) -> TResult: ...
    def Invoke7rrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7rrrrrrr) -> TResult: ...
    def Invoke7vrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vrrrrrr) -> TResult: ...
    def Invoke7vvrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvrrrrr) -> TResult: ...
    def Invoke7vvrrvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvrrvvv) -> TResult: ...
    def Invoke7vvvvvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvvvvvr) -> TResult: ...
    def Invoke8vvvvvvrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, method: TargetMethod8vvvvvvrv) -> TResult: ...
    def Invoke8vvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, method: TargetMethod8vvvvvvvv) -> TResult: ...
    def Invoke9rrrrrrrrr(self, P0: T0, P1: T1, P2: T2, P3: T3, P4: T4, P5: T5, P6: T6, P7: T7, P8: T8, Method: TargetMethod9rrrrrrrrr) -> TResult: ...
    def Invoke9vvvvvvvrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, method: TargetMethod9vvvvvvvrv) -> TResult: ...

class TeklaProcessExecuter(Process):
    """.NET: Tekla.Structures.Internal.TeklaProcessExecuter"""
    def __init__(self, *args) -> None: ...
    BasePriority: int
    ExitCode: int
    HasExited: bool
    ExitTime: DateTime
    Handle: IntPtr
    SafeHandle: SafeProcessHandle
    HandleCount: int
    Id: int
    MachineName: str
    MainWindowHandle: IntPtr
    MainWindowTitle: str
    MainModule: ProcessModule
    MaxWorkingSet: IntPtr
    MinWorkingSet: IntPtr
    Modules: ProcessModuleCollection
    NonpagedSystemMemorySize: int
    NonpagedSystemMemorySize64: int
    PagedMemorySize: int
    PagedMemorySize64: int
    PagedSystemMemorySize: int
    PagedSystemMemorySize64: int
    PeakPagedMemorySize: int
    PeakPagedMemorySize64: int
    PeakWorkingSet: int
    PeakWorkingSet64: int
    PeakVirtualMemorySize: int
    PeakVirtualMemorySize64: int
    PriorityBoostEnabled: bool
    PriorityClass: ProcessPriorityClass
    PrivateMemorySize: int
    PrivateMemorySize64: int
    PrivilegedProcessorTime: TimeSpan
    ProcessName: str
    ProcessorAffinity: IntPtr
    Responding: bool
    SessionId: int
    StartInfo: ProcessStartInfo
    StartTime: DateTime
    SynchronizingObject: ISynchronizeInvoke
    Threads: ProcessThreadCollection
    TotalProcessorTime: TimeSpan
    UserProcessorTime: TimeSpan
    VirtualMemorySize: int
    VirtualMemorySize64: int
    EnableRaisingEvents: bool
    StandardInput: StreamWriter
    StandardOutput: StreamReader
    StandardError: StreamReader
    WorkingSet: int
    WorkingSet64: int
    Site: ISite
    Container: IContainer
    def Start(self, program: str, args: str) -> bool: ...

class TeklaStructuresDatabaseHelper:
    """.NET: Tekla.Structures.Internal.TeklaStructuresDatabaseHelper"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetIndexedAttributeName(attributeName: str, index: int) -> str: ...

class TeklaStructuresInfo:
    """.NET: Tekla.Structures.Internal.TeklaStructuresInfo"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetTsBuildType() -> TsBuildTypes: ...

class TsBuildTypes:
    """.NET: Tekla.Structures.Internal.TsBuildTypes"""
    def __init__(self, *args) -> None: ...
    ...

class WrapperDelegateHelper:
    """.NET: Tekla.Structures.Internal.WrapperDelegateHelper"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateDelegate(Instance: object, MethodName: str) -> T: ...

class WrapperFunctionalityBase:
    """.NET: Tekla.Structures.Internal.WrapperFunctionalityBase"""
    def __init__(self, *args) -> None: ...
    def Invoke0(self, method: TargetMethod0) -> TResult: ...
    def Invoke16vvvvvvvvvvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12, p13: T13, p14: T14, p15: T15, method: TargetMethod16vvvvvvvvvvvvvvvv) -> TResult: ...
    def Invoke18vvvvvvvvvvvvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, p9: T9, p10: T10, p11: T11, p12: T12, p13: T13, p14: T14, p15: T15, p16: T16, p17: T17, method: TargetMethod18vvvvvvvvvvvvvvvvvv) -> TResult: ...
    def Invoke1r(self, p0: T0, method: TargetMethod1r) -> TResult: ...
    def Invoke1v(self, p0: T0, method: TargetMethod1v) -> TResult: ...
    def Invoke2rr(self, p0: T0, p1: T1, method: TargetMethod2rr) -> TResult: ...
    def Invoke2rv(self, p0: T0, p1: T1, method: TargetMethod2rv) -> TResult: ...
    def Invoke2vr(self, p0: T0, p1: T1, method: TargetMethod2vr) -> TResult: ...
    def Invoke2vv(self, p0: T0, p1: T1, method: TargetMethod2vv) -> TResult: ...
    def Invoke3rrr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3rrr) -> TResult: ...
    def Invoke3rrv(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3rrv) -> TResult: ...
    def Invoke3rvv(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3rvv) -> TResult: ...
    def Invoke3vrr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vrr) -> TResult: ...
    def Invoke3vvr(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vvr) -> TResult: ...
    def Invoke3vvv(self, p0: T0, p1: T1, p2: T2, method: TargetMethod3vvv) -> TResult: ...
    def Invoke4rrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4rrrr) -> TResult: ...
    def Invoke4rrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4rrrv) -> TResult: ...
    def Invoke4rrvv(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4rrvv) -> TResult: ...
    def Invoke4vvrr(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4vvrr) -> TResult: ...
    def Invoke4vvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4vvvr) -> TResult: ...
    def Invoke4vvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, method: TargetMethod4vvvv) -> TResult: ...
    def Invoke5rrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5rrrrr) -> TResult: ...
    def Invoke5rrvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5rrvvv) -> TResult: ...
    def Invoke5rvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5rvvvv) -> TResult: ...
    def Invoke5vvrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvrrr) -> TResult: ...
    def Invoke5vvrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvrrv) -> TResult: ...
    def Invoke5vvvrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvvrr) -> TResult: ...
    def Invoke5vvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, method: TargetMethod5vvvvv) -> TResult: ...
    def Invoke6rrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6rrrrrr) -> TResult: ...
    def Invoke6rrrrrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6rrrrrv) -> TResult: ...
    def Invoke6vrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vrrrrr) -> TResult: ...
    def Invoke6vvrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvrrrr) -> TResult: ...
    def Invoke6vvrrvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvrrvv) -> TResult: ...
    def Invoke6vvvrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvrrr) -> TResult: ...
    def Invoke6vvvvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvvvr) -> TResult: ...
    def Invoke6vvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, method: TargetMethod6vvvvvv) -> TResult: ...
    def Invoke7rrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7rrrrrrr) -> TResult: ...
    def Invoke7vrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vrrrrrr) -> TResult: ...
    def Invoke7vvrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvrrrrr) -> TResult: ...
    def Invoke7vvrrvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvrrvvv) -> TResult: ...
    def Invoke7vvvvvvr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, method: TargetMethod7vvvvvvr) -> TResult: ...
    def Invoke8vvvvvvrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, method: TargetMethod8vvvvvvrv) -> TResult: ...
    def Invoke8vvvvvvvv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, method: TargetMethod8vvvvvvvv) -> TResult: ...
    def Invoke9rrrrrrrrr(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, method: TargetMethod9rrrrrrrrr) -> TResult: ...
    def Invoke9vvvvvvvrv(self, p0: T0, p1: T1, p2: T2, p3: T3, p4: T4, p5: T5, p6: T6, p7: T7, p8: T8, method: TargetMethod9vvvvvvvrv) -> TResult: ...

class dotClashCheckOptions_t:
    """.NET: Tekla.Structures.Internal.dotClashCheckOptions_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotClientId_t:
    """.NET: Tekla.Structures.Internal.dotClientId_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotComponentOptions_t:
    """.NET: Tekla.Structures.Internal.dotComponentOptions_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotConnectionCode_t:
    """.NET: Tekla.Structures.Internal.dotConnectionCode_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotConnectionType_t:
    """.NET: Tekla.Structures.Internal.dotConnectionType_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotCoordinateSystem_t:
    """.NET: Tekla.Structures.Internal.dotCoordinateSystem_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, P: CoordinateSystem) -> None: ...
    def ToStruct(self, P: CoordinateSystem) -> None: ...

class dotGetAdvancedOption_t:
    """.NET: Tekla.Structures.Internal.dotGetAdvancedOption_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotIdentifierToGUID_t:
    """.NET: Tekla.Structures.Internal.dotIdentifierToGUID_t"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetGuidByIdentifier(identifier: Identifier) -> str: ...
    @staticmethod
    def GetIdentifierByGuid(guid: str) -> Identifier: ...

class dotIdentifier_t:
    """.NET: Tekla.Structures.Internal.dotIdentifier_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, identifier: Identifier) -> None: ...
    def ToStruct(self, identifier: Identifier) -> None: ...

class dotMatrix_t:
    """.NET: Tekla.Structures.Internal.dotMatrix_t"""
    def __init__(self, *args) -> None: ...
    def FromStruct(self, Matrix: Matrix) -> None: ...
    def ToStruct(self, Matrix: Matrix) -> None: ...

class dotModuleManagerQuery_t:
    """.NET: Tekla.Structures.Internal.dotModuleManagerQuery_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginAttributesDouble_t:
    """.NET: Tekla.Structures.Internal.dotPluginAttributesDouble_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginAttributesInt_t:
    """.NET: Tekla.Structures.Internal.dotPluginAttributesInt_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginAttributesString_t:
    """.NET: Tekla.Structures.Internal.dotPluginAttributesString_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginBaseDirectory_t:
    """.NET: Tekla.Structures.Internal.dotPluginBaseDirectory_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginClient_t:
    """.NET: Tekla.Structures.Internal.dotPluginClient_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginDefinition_t:
    """.NET: Tekla.Structures.Internal.dotPluginDefinition_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginInput_t:
    """.NET: Tekla.Structures.Internal.dotPluginInput_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPluginName_t:
    """.NET: Tekla.Structures.Internal.dotPluginName_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotPoint_t:
    """.NET: Tekla.Structures.Internal.dotPoint_t"""
    def __init__(self, *args) -> None: ...
    def Equals(self, point: dotPoint_t) -> bool: ...
    def FromStruct(self, point: Point) -> None: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, ) -> str: ...
    def ToStruct(self, point: Point) -> None: ...

class dotProgramVersion_t:
    """.NET: Tekla.Structures.Internal.dotProgramVersion_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotVector_t:
    """.NET: Tekla.Structures.Internal.dotVector_t"""
    def __init__(self, *args) -> None: ...
    def Equals(self, point: dotVector_t) -> bool: ...
    def FromStruct(self, vector: Vector) -> None: ...
    def GetHashCode(self, ) -> int: ...
    def ToString(self, ) -> str: ...
    def ToStruct(self, vector: Vector) -> None: ...
