# Auto-generated — Rhino 8 — Rhino.Runtime

class AdvancedSetting:
    """.NET: Rhino.Runtime.AdvancedSetting"""
    def __init__(self, *args) -> None: ...
    ...

class AssemblyResolver:
    """.NET: Rhino.Runtime.AssemblyResolver"""
    def __init__(self, *args) -> None: ...
    CurrentDomainAssemblyResolve: ResolveEventHandler
    CurrentDomainReflectionOnlyAssemblyResolve: ResolveEventHandler
    @staticmethod
    def AddSearchFile(file: str) -> None: ...
    @staticmethod
    def AddSearchFolder(folder: str) -> None: ...

class CloudHostUtils:
    """.NET: Rhino.Runtime.CloudHostUtils"""
    def __init__(self, *args) -> None: ...
    IsEntitled: bool
    DenyReason: str
    Signature: str
    @staticmethod
    def CheckEntitlement() -> None: ...

class CommonObject:
    """.NET: Rhino.Runtime.CommonObject"""
    def __init__(self, *args) -> None: ...
    PerformCorruptionTesting: bool
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def Dispose(self, ) -> None: ...
    def EnsurePrivateCopy(self, ) -> None: ...
    @staticmethod
    def FromBase64String(archive3dm: int, opennurbs: int, base64Data: str) -> CommonObject: ...
    @staticmethod
    def FromJSON(json: str) -> CommonObject: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    def IsValidWithLog(self, log: str) -> bool: ...
    def ToJSON(self, options: SerializationOptions) -> str: ...

class CorruptGeometryException(Exception):
    """.NET: Rhino.Runtime.CorruptGeometryException"""
    def __init__(self, *args) -> None: ...
    Pointer: IntPtr
    CommonObject: CommonObject
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class DocumentCollectedException(Exception):
    """.NET: Rhino.Runtime.DocumentCollectedException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class HostUtils:
    """.NET: Rhino.Runtime.HostUtils"""
    def __init__(self, *args) -> None: ...
    RhinoAssemblyDirectory: str
    RunningAsRhinoInside: bool
    OperatingSystemEdition: str
    OperatingSystemInstallationType: str
    OperatingSystemProductName: str
    OperatingSystemVersion: str
    OperatingSystemBuildNumber: str
    RunningOnWindows: bool
    RunningOnOSX: bool
    RunningOniOS: bool
    IsPreRelease: bool
    RunningOnServer: bool
    RunningInWindowsContainer: bool
    RunningInDarkMode: bool
    DeviceName: str
    ComputerSerialNumber: str
    CurrentOSLanguage: int
    DeviceId: Guid
    RunningInMono: bool
    RunningInNetFramework: bool
    RunningInNetCore: bool
    RunningInRhino: bool
    SendDebugToCommandLine: bool
    @staticmethod
    def AutoInstallPlugInFolder(currentUser: bool) -> str: ...
    @staticmethod
    def CallFromCoreRhino(task: str) -> int: ...
    @staticmethod
    def CheckForRdk(throwOnFalse: bool, usePreviousResult: bool) -> bool: ...
    @staticmethod
    def ClearFpuExceptionStatus() -> None: ...
    @staticmethod
    def CreateCommands(pPlugIn: IntPtr, pluginAssembly: Assembly) -> int: ...
    @staticmethod
    def CreatePlugIn(pluginType: Type, printDebugMessages: bool) -> PlugIn: ...
    @staticmethod
    def DebugDumpToString(geometry: GeometryBase) -> str: ...
    @staticmethod
    def DebugString(format: str, args: list) -> None: ...
    @staticmethod
    def DescribeGeometry(geometry: GeometryBase) -> str: ...
    @staticmethod
    def DisplayOleAlerts(display: bool) -> None: ...
    @staticmethod
    def ExceptionReport(source: str, ex: Exception) -> None: ...
    @staticmethod
    def ExecuteNamedCallback(name: str, args: NamedParametersEventArgs) -> bool: ...
    @staticmethod
    def FileNameEndsWithRhinoBackupExtension(fileName: str) -> bool: ...
    @staticmethod
    def FileNameEndsWithRhinoExtension(fileName: str) -> bool: ...
    @staticmethod
    def GetAbsolutePath(relativePath: str, bRelativePathisFileName: bool, relativeTo: str, bRelativeToIsFileName: bool, pathOut: str) -> bool: ...
    @staticmethod
    def GetActivePlugInVersionFolders(currentUser: bool) -> IEnumerable: ...
    @staticmethod
    def GetAssemblySearchPaths() -> list: ...
    @staticmethod
    def GetCurrentProcessInfo(processName: str, processVersion: Version) -> None: ...
    @staticmethod
    def GetCustomComputeEndpoints() -> list: ...
    @staticmethod
    def GetPlatformService(assemblyPath: str, typeFullName: str) -> T: ...
    @staticmethod
    def GetPrinterDPI(printerName: str, horizontal: bool) -> float: ...
    @staticmethod
    def GetPrinterFormMargins(printerName: str, formName: str, portrait: bool, leftMillimeters: float, topMillimeters: float, rightMillimeters: float, bottomMillimeters: float) -> bool: ...
    @staticmethod
    def GetPrinterFormNames(printerName: str) -> list: ...
    @staticmethod
    def GetPrinterFormSize(printerName: str, formName: str, widthMillimeters: float, heightMillimeters: float) -> bool: ...
    @staticmethod
    def GetPrinterNames() -> list: ...
    @staticmethod
    def GetRhinoDotNetAssembly() -> Assembly: ...
    @staticmethod
    def GetSystemProcessorCount() -> int: ...
    @staticmethod
    def GetSystemReferenceAssemblies() -> IEnumerable: ...
    @staticmethod
    def InPlaceConstCast(geometry: GeometryBase, makeNonConst: bool) -> None: ...
    @staticmethod
    def InitializeRhinoCommon() -> None: ...
    @staticmethod
    def InitializeRhinoCommon_RDK() -> None: ...
    @staticmethod
    def InitializeZooClient() -> None: ...
    @staticmethod
    def IsManagedDll(path: str) -> bool: ...
    @staticmethod
    def IsRhinoBackupFileExtension(fileExtension: str) -> bool: ...
    @staticmethod
    def IsRhinoFileExtension(fileExtension: str) -> bool: ...
    @staticmethod
    def LoadAssemblyFrom(path: str) -> Assembly: ...
    @staticmethod
    def LoadAssemblyFromName(assemblyName: AssemblyName) -> Assembly: ...
    @staticmethod
    def LoadAssemblyFromStream(stream: Stream) -> Assembly: ...
    @staticmethod
    def LogDebugEvent(message: str) -> None: ...
    @staticmethod
    def RecordInitInstanceTime(description: str) -> None: ...
    @staticmethod
    def RegisterComputeEndpoint(endpointPath: str, t: Type) -> None: ...
    @staticmethod
    def RegisterDynamicCommand(plugin: PlugIn, cmd: Command) -> bool: ...
    @staticmethod
    def RegisterNamedCallback(name: str, callback: EventHandler) -> None: ...
    @staticmethod
    def RemoveNamedCallback(name: str) -> None: ...
    @staticmethod
    def RhinoCommonExceptionHandler(title: str, sender: object, ex: Exception) -> None: ...
    @staticmethod
    def SendLogMessageToCloudCallbackProc(msg_type: LogMessageType, pwStringClass: IntPtr, pwStringDesc: IntPtr, pwStringMessage: IntPtr) -> None: ...
    @staticmethod
    def SetInShutDown() -> None: ...
    @staticmethod
    def ShutDownRhinoCommon_RDK() -> None: ...
    @staticmethod
    def UnhandledThreadException(sender: object, e: ThreadExceptionEventArgs) -> None: ...

class IPlatformServiceLocator:
    """.NET: Rhino.Runtime.IPlatformServiceLocator"""
    def __init__(self, *args) -> None: ...
    def GetService(self, ) -> T: ...

class IShrinkWrapService:
    """.NET: Rhino.Runtime.IShrinkWrapService"""
    def __init__(self, *args) -> None: ...
    def ShrinkWrap(self, geometryBases: IEnumerable, parameters: ShrinkWrapParameters, meshingParameters: MeshingParameters, cancellationToken: CancellationToken) -> Mesh: ...

class IZooClientUtilities:
    """.NET: Rhino.Runtime.IZooClientUtilities"""
    def __init__(self, *args) -> None: ...
    LoggedInUserAvatar: Image
    LoggedInUserName: str
    UserIsLoggedIn: bool
    def AskUserForLicense(self, verify: object, parameters: ZooClientParameters) -> bool: ...
    def CheckInLicense(self, verify: object, productId: Guid) -> bool: ...
    def CheckOutLicense(self, verify: object, productId: Guid) -> bool: ...
    def ConvertLicense(self, verify: object, productId: Guid) -> bool: ...
    def DeleteLicense(self, verify: object, productId: Guid) -> bool: ...
    def Echo(self, verify: object, message: str) -> str: ...
    def GetCurrentTime(self, ) -> DateTime: ...
    def GetLicense(self, verify: object, parameters: ZooClientParameters) -> bool: ...
    def GetLicenseStatus(self, verify: object) -> list: ...
    def GetLicenseType(self, verify: object, productId: Guid) -> int: ...
    def GetOneLicenseStatus(self, verify: object, productId: Guid) -> LicenseStatus: ...
    def GetRegisteredOwnerInfo(self, verify: object, productId: Guid, registeredOwner: str, registeredOrganization: str) -> bool: ...
    def Initialize(self, verify: object) -> bool: ...
    def IsCheckOutEnabled(self, verify: object) -> bool: ...
    def LicenseOptionsHandler(self, verify: object, parameters: ZooClientParameters) -> bool: ...
    def LoginToCloudZoo(self, ) -> bool: ...
    def LogoutOfCloudZoo(self, ) -> bool: ...
    def ReturnLicense(self, verify: object, productPath: str, productId: Guid) -> bool: ...
    def ShowBuyLicenseUi(self, verify: object, productId: Guid) -> None: ...
    def ShowLicenseValidationUi(self, verify: object, cdkey: str) -> bool: ...
    def ShowRhinoExpiredMessage(self, mode: Mode, result: int) -> bool: ...

class ImportOptionsSections:
    """.NET: Rhino.Runtime.ImportOptionsSections"""
    def __init__(self, *args) -> None: ...
    ...

class Interop:
    """.NET: Rhino.Runtime.Interop"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CommandLineOptionFromNativePointer(ptrCommandLineOption: IntPtr) -> CommandLineOption: ...
    @staticmethod
    def CreateFromNativePointer(pGeometry: IntPtr) -> GeometryBase: ...
    @staticmethod
    def FileReadOptionsConstPointer(options: FileReadOptions) -> IntPtr: ...
    @staticmethod
    def FileWriteOptionsConstPointer(options: FileWriteOptions) -> IntPtr: ...
    @staticmethod
    def FontFromPointer(ptrManagedFont: IntPtr) -> Font: ...
    @staticmethod
    def FromOnBrep(source: object) -> Brep: ...
    @staticmethod
    def FromOnCurve(source: object) -> Curve: ...
    @staticmethod
    def FromOnMesh(source: object) -> Mesh: ...
    @staticmethod
    def FromOnSurface(source: object) -> Surface: ...
    @staticmethod
    def NSFontFromFont(font: Font, pointSize: float) -> IntPtr: ...
    @staticmethod
    def NativeGeometryConstPointer(geometry: GeometryBase) -> IntPtr: ...
    @staticmethod
    def NativeGeometryNonConstPointer(geometry: GeometryBase) -> IntPtr: ...
    @staticmethod
    def NativeNonConstPointer(settings: ViewCaptureSettings) -> IntPtr: ...
    @staticmethod
    def NativeRhinoDocPointer(doc: RhinoDoc) -> IntPtr: ...
    @staticmethod
    def PlugInPointer(plugin: PlugIn) -> IntPtr: ...
    @staticmethod
    def RhinoObjectConstPointer(rhinoObject: RhinoObject) -> IntPtr: ...
    @staticmethod
    def RhinoObjectFromPointer(pRhinoObject: IntPtr) -> RhinoObject: ...
    @staticmethod
    def ToIRhinoViewport(source: RhinoViewport) -> object: ...
    @staticmethod
    def ToOnBrep(source: Brep) -> object: ...
    @staticmethod
    def ToOnCurve(source: Curve) -> object: ...
    @staticmethod
    def ToOnMesh(source: Mesh) -> object: ...
    @staticmethod
    def ToOnSurface(source: Surface) -> object: ...
    @staticmethod
    def ToOnXform(source: Transform) -> object: ...
    @staticmethod
    def TryCopyFromOnArc(source: object, destination: Arc) -> bool: ...
    @staticmethod
    def TryCopyToOnArc(source: Arc, destination: object) -> bool: ...
    @staticmethod
    def ViewCaptureFromPointer(ptrViewCapture: IntPtr) -> ViewCaptureSettings: ...

class LicenseStateChangedEventArgs(EventArgs):
    """.NET: Rhino.Runtime.LicenseStateChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    CallingRhinoCommonAllowed: bool

class LicenseTypes:
    """.NET: Rhino.Runtime.LicenseTypes"""
    def __init__(self, *args) -> None: ...
    ...

class Mode:
    """.NET: Rhino.Runtime.Mode"""
    def __init__(self, *args) -> None: ...
    ...

class NamedParametersEventArgs(EventArgs):
    """.NET: Rhino.Runtime.NamedParametersEventArgs"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def Set(self, name: str, value: str) -> None: ...
    def SetWindowHandle(self, name: str, value: IntPtr) -> None: ...
    def SetWindowImageHandle(self, name: str, value: IntPtr) -> None: ...
    def TryGetArc(self, name: str, value: Arc) -> bool: ...
    def TryGetBool(self, name: str, value: bool) -> bool: ...
    def TryGetColor(self, name: str, value: Color) -> bool: ...
    def TryGetDouble(self, name: str, value: float) -> bool: ...
    def TryGetGeometry(self, name: str, values: list) -> bool: ...
    def TryGetGuid(self, name: str, value: Guid) -> bool: ...
    def TryGetGuids(self, name: str, value: list) -> bool: ...
    def TryGetInt(self, name: str, value: int) -> bool: ...
    def TryGetLine(self, name: str, value: Line) -> bool: ...
    def TryGetMeshParameters(self, name: str, value: MeshingParameters) -> bool: ...
    def TryGetObjRefs(self, name: str, value: list) -> bool: ...
    def TryGetPlane(self, name: str, plane: Plane) -> bool: ...
    def TryGetPoint(self, name: str, value: Point3d) -> bool: ...
    def TryGetPoint2i(self, name: str, value: Point) -> bool: ...
    def TryGetPoints(self, name: str, pts: list) -> bool: ...
    def TryGetRhinoObjects(self, key: str, values: list) -> bool: ...
    def TryGetString(self, name: str, value: str) -> bool: ...
    def TryGetStrings(self, name: str, value: list) -> bool: ...
    def TryGetUints(self, name: str, value: list) -> bool: ...
    def TryGetUnmangedPointer(self, name: str, value: IntPtr) -> bool: ...
    def TryGetUnsignedInt(self, name: str, value: int) -> bool: ...
    def TryGetVector(self, name: str, value: Vector3d) -> bool: ...
    def TryGetViewport(self, name: str, viewport: ViewportInfo) -> bool: ...
    def TryGetWindowHandle(self, name: str, value: IntPtr) -> bool: ...
    def TryGetWindowImageHandle(self, name: str, value: IntPtr) -> bool: ...

class NotLicensedException(Exception):
    """.NET: Rhino.Runtime.NotLicensedException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class PythonCompiledCode:
    """.NET: Rhino.Runtime.PythonCompiledCode"""
    def __init__(self, *args) -> None: ...
    def Execute(self, scope: PythonScript) -> None: ...

class PythonScript:
    """.NET: Rhino.Runtime.PythonScript"""
    def __init__(self, *args) -> None: ...
    SearchPaths: list
    Output: Action
    ScriptContextDoc: object
    ScriptContextCommand: Command
    ContextId: int
    @staticmethod
    def AddRuntimeAssembly(assembly: Assembly) -> None: ...
    def Compile(self, script: str) -> PythonCompiledCode: ...
    def ContainsVariable(self, name: str) -> bool: ...
    @staticmethod
    def Create() -> PythonScript: ...
    def CreateTextEditorControl(self, script: str, helpcallback: Action) -> object: ...
    def EvaluateExpression(self, statements: str, expression: str) -> object: ...
    def ExecuteFile(self, path: str) -> bool: ...
    def ExecuteFileInScope(self, path: str) -> bool: ...
    def ExecuteScript(self, script: str) -> bool: ...
    def GetStackTraceFromException(self, ex: Exception) -> str: ...
    def GetVariable(self, name: str) -> object: ...
    def GetVariableNames(self, ) -> IEnumerable: ...
    def RemoveVariable(self, name: str) -> None: ...
    @staticmethod
    def RuntimeAssemblies() -> list: ...
    def SetIntellisenseVariable(self, name: str, value: object) -> None: ...
    def SetVariable(self, name: str, value: object) -> None: ...
    def SetupScriptContext(self, doc: object) -> None: ...

class RdkNotLoadedException(Exception):
    """.NET: Rhino.Runtime.RdkNotLoadedException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class RiskyAction:
    """.NET: Rhino.Runtime.RiskyAction"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class Skin:
    """.NET: Rhino.Runtime.Skin"""
    def __init__(self, *args) -> None: ...
    ActiveSkin: Skin
    Settings: PersistentSettings

class TextFields:
    """.NET: Rhino.Runtime.TextFields"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Area(id: str, unitSystem: str) -> float: ...
    @staticmethod
    def BlockAttributeText(key: str, prompt: str, defaultValue: str) -> str: ...
    @staticmethod
    def BlockDescription(definitionNameOrId: str) -> str: ...
    @staticmethod
    def BlockInstanceCount(instanceDefinitionNameOrId: str) -> int: ...
    @staticmethod
    def BlockInstanceName(blockId: str) -> str: ...
    @staticmethod
    def BlockName(blockId: str) -> str: ...
    @staticmethod
    def CurveLength(id: str, unitSystem: str) -> float: ...
    @staticmethod
    def Date(dateFormat: str, languageId: str) -> str: ...
    @staticmethod
    def DateModified(dateFormat: str, languageId: str) -> str: ...
    @staticmethod
    def DetailScale(detailId: str, scaleFormat: str) -> str: ...
    @staticmethod
    def DocumentText(key: str) -> str: ...
    @staticmethod
    def FileName(options: str) -> str: ...
    @staticmethod
    def GetInstanceAttributeFields(str: str) -> list: ...
    @staticmethod
    def LayerName(layerId: str) -> str: ...
    @staticmethod
    def LayoutUserText(layoutId: str, key: str) -> str: ...
    @staticmethod
    def ModelUnits() -> str: ...
    @staticmethod
    def Notes() -> str: ...
    @staticmethod
    def NumPages() -> int: ...
    @staticmethod
    def ObjectLayer(id: str) -> str: ...
    @staticmethod
    def ObjectName(id: str) -> str: ...
    @staticmethod
    def ObjectPageName(id: str) -> str: ...
    @staticmethod
    def ObjectPageNumber(id: str) -> int: ...
    @staticmethod
    def PageHeight() -> float: ...
    @staticmethod
    def PageName(id: str) -> str: ...
    @staticmethod
    def PageNumber() -> int: ...
    @staticmethod
    def PageWidth() -> float: ...
    @staticmethod
    def PaperName() -> str: ...
    @staticmethod
    def PointCoordinate(pointId: str, axis: str) -> str: ...
    @staticmethod
    def TryFormat(text: str, doc: RhinoDoc, result: str) -> bool: ...
    @staticmethod
    def TryParse(text: str, doc: RhinoDoc, result: List) -> bool: ...
    @staticmethod
    def UserText(id: str, key: str, prompt: str, defaultValue: str) -> str: ...
    @staticmethod
    def Volume(id: str, unitSystem: str, allowOpenObjects: str) -> float: ...

class ViewCaptureWriter:
    """.NET: Rhino.Runtime.ViewCaptureWriter"""
    def __init__(self, *args) -> None: ...
    def Draw(self, constPtrPrintInfo: IntPtr, doc: RhinoDoc) -> None: ...

class ZooClientParameters:
    """.NET: Rhino.Runtime.ZooClientParameters"""
    def __init__(self, *args) -> None: ...
    ProductGuid: Guid
    LicenseGuid: Guid
    ProductTitle: str
    ProductBuildType: int
    Capabilities: LicenseCapabilities
    LicenseEntryTextMask: str
    ProductPath: str
    ParentWindow: object
    SelectedLicenseType: LicenseTypes
    OnLeaseChanged: OnLeaseChangedDelegate
    def VerifyLicenseKey(self, licenseKey: str, validationCode: str, validationCodeInstallDate: DateTime, gracePeriodExpired: bool, licenseData: LicenseData) -> ValidateResult: ...
    def VerifyPreviousVersionLicense(self, license: str, previousVersionLicense: str, errorMessage: str) -> bool: ...
