# Auto-generated — Rhino 8 — Rhino.Runtime.InProcess

class RhinoCore:
    """.NET: Rhino.Runtime.InProcess.RhinoCore"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def DoEvents(self, ) -> bool: ...
    def DoIdle(self, ) -> bool: ...
    def InvokeInHostContext(self, action: Action) -> None: ...
    def RaiseIdle(self, ) -> None: ...
    def Run(self, ) -> int: ...

class WindowStyle:
    """.NET: Rhino.Runtime.InProcess.WindowStyle"""
    def __init__(self, *args) -> None: ...
    ...
