# Auto-generated — Rhino 8 — Rhino.Runtime.InteropWrappers

class ClassArrayObjRef:
    """.NET: Rhino.Runtime.InteropWrappers.ClassArrayObjRef"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, objref: ObjRef) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class ClassArrayOnObjRef:
    """.NET: Rhino.Runtime.InteropWrappers.ClassArrayOnObjRef"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, objref: ObjRef) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, doc: RhinoDoc) -> list: ...

class ClassArrayString:
    """.NET: Rhino.Runtime.InteropWrappers.ClassArrayString"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, s: str) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class CurveSegment:
    """.NET: Rhino.Runtime.InteropWrappers.CurveSegment"""
    def __init__(self, *args) -> None: ...
    Index: int
    SubDomain: Interval
    Reversed: bool

class MeshPointDataStruct:
    """.NET: Rhino.Runtime.InteropWrappers.MeshPointDataStruct"""
    def __init__(self, *args) -> None: ...
    ...

class RhDisplayPoint:
    """.NET: Rhino.Runtime.InteropWrappers.RhDisplayPoint"""
    def __init__(self, *args) -> None: ...
    ...

class SimpleArray2dex:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArray2dex"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayArrayPoint3d:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayArrayPoint3d"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: Point3d
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def PointCountAt(self, index: int) -> int: ...
    def PolylineAt(self, index: int) -> Polyline: ...

class SimpleArrayBinaryArchiveReader:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayBinaryArchiveReader"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, reader: BinaryArchiveReader) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def Get(self, index: int) -> BinaryArchiveReader: ...
    def NonConstPointer(self, ) -> IntPtr: ...

class SimpleArrayBrepPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayBrepPointer"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, brep: Brep, asConst: bool) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayByte:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayByte"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Array(self, ) -> IntPtr: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def CopyTo(self, other: SimpleArrayByte) -> None: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayClippingPlaneObjectPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayClippingPlaneObjectPointer"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, clippingplane: ClippingPlaneObject, asConst: bool) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...

class SimpleArrayCurvePointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer"""
    def __init__(self, *args) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayDouble:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayDouble"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayExtrusionPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayExtrusionPointer"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, extrusion: Extrusion, asConst: bool) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayFloat:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayFloat"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Array(self, ) -> IntPtr: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def CopyTo(self, other: SimpleArrayFloat) -> None: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayGeometryPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayGeometryPointer"""
    def __init__(self, *args) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayGuid:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayGuid"""
    def __init__(self, *args) -> None: ...
    Item: Guid
    Count: int
    Capacity: int
    def Append(self, uuid: Guid) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayGuidPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayGuidPointer"""
    def __init__(self, *args) -> None: ...
    Item: Guid
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayHatchLinePointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayHatchLinePointer"""
    def __init__(self, *args) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...

class SimpleArrayInt:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayInt"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayIntPtr:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayIntPtr"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayInterval:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayInterval"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, interval: Interval) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayLine:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayLine"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayLinetypePointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayLinetypePointer"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayMeshFace:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayMeshFace"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayMeshPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayMeshPointer"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, mesh: Mesh, asConst: bool) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayPlane:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayPlane"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayPoint2d:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayPoint2d"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArrayPoint3d:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, pt: Point3d) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class SimpleArraySubDPointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArraySubDPointer"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, subd: SubD, asConst: bool) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArraySurfacePointer:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArraySurfacePointer"""
    def __init__(self, *args) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class SimpleArrayUint:
    """.NET: Rhino.Runtime.InteropWrappers.SimpleArrayUint"""
    def __init__(self, *args) -> None: ...
    Count: int
    UnsignedCount: int
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class StdVectorByte:
    """.NET: Rhino.Runtime.InteropWrappers.StdVectorByte"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def CopyTo(self, other: StdVectorByte) -> None: ...
    def Dispose(self, ) -> None: ...
    def Memory(self, ) -> IntPtr: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class StdVectorFloat:
    """.NET: Rhino.Runtime.InteropWrappers.StdVectorFloat"""
    def __init__(self, *args) -> None: ...
    Count: int
    def ConstPointer(self, ) -> IntPtr: ...
    def CopyTo(self, other: StdVectorFloat) -> None: ...
    def Dispose(self, ) -> None: ...
    def Memory(self, ) -> IntPtr: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class StdVectorGuid:
    """.NET: Rhino.Runtime.InteropWrappers.StdVectorGuid"""
    def __init__(self, *args) -> None: ...
    Item: Guid
    Count: int
    def Append(self, uuid: Guid) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToArray(self, ) -> list: ...

class StdVectorOfSharedPtrToMesh:
    """.NET: Rhino.Runtime.InteropWrappers.StdVectorOfSharedPtrToMesh"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, mesh: Mesh, asConst: bool) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToNonConstArray(self, ) -> list: ...

class StringHolder:
    """.NET: Rhino.Runtime.InteropWrappers.StringHolder"""
    def __init__(self, *args) -> None: ...
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def GetString(pStringHolder: IntPtr) -> str: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def ToString(self, ) -> str: ...
    def ToStringSafe(self, ) -> str: ...

class StringWrapper:
    """.NET: Rhino.Runtime.InteropWrappers.StringWrapper"""
    def __init__(self, *args) -> None: ...
    ConstPointer: IntPtr
    NonConstPointer: IntPtr
    def Dispose(self, ) -> None: ...
    @staticmethod
    def GetStringFromPointer(pConstON_wString: IntPtr) -> str: ...
    def SetString(self, s: str) -> None: ...
    @staticmethod
    def SetStringOnPointer(pON_wString: IntPtr, s: str) -> None: ...
    def ToString(self, ) -> str: ...
