# Auto-generated — Rhino 8 — Rhino.Runtime.Notifications

class ButtonType:
    """.NET: Rhino.Runtime.Notifications.ButtonType"""
    def __init__(self, *args) -> None: ...
    ...

class IAssemblyRestrictedObject:
    """.NET: Rhino.Runtime.Notifications.IAssemblyRestrictedObject"""
    def __init__(self, *args) -> None: ...
    def Editable(self, ) -> bool: ...

class Notification:
    """.NET: Rhino.Runtime.Notifications.Notification"""
    def __init__(self, *args) -> None: ...
    DateUpdated: DateTime
    AllowedAssemblies: ICollection
    MetadataCopy: IDictionary
    ButtonClicked: Action
    Item: str
    Title: str
    Description: str
    Message: str
    SeverityLevel: Severity
    CancelButtonTitle: str
    ConfirmButtonTitle: str
    AlternateButtonTitle: str
    ShowEventId: Nullable
    def Editable(self, ) -> bool: ...
    @staticmethod
    def ExecuteAssemblyProtectedCode(action: Action) -> None: ...
    def HideModal(self, ) -> None: ...
    def RemoveMetadata(self, key: str) -> bool: ...
    def ShowModal(self, ) -> None: ...
    def ToString(self, ) -> str: ...

class NotificationButtonClickedArgs(EventArgs):
    """.NET: Rhino.Runtime.Notifications.NotificationButtonClickedArgs"""
    def __init__(self, *args) -> None: ...
    Notification: Notification
    ButtonClicked: ButtonType

class NotificationCenter:
    """.NET: Rhino.Runtime.Notifications.NotificationCenter"""
    def __init__(self, *args) -> None: ...
    ...

class TrulyObservableOrderedSet:
    """.NET: Rhino.Runtime.Notifications.TrulyObservableOrderedSet`1"""
    def __init__(self, *args) -> None: ...
    Item: T
    Count: int
    IsReadOnly: bool
    def Add(self, item: T) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: T) -> int: ...
    def Insert(self, index: int, item: T) -> None: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def Sort(self, keySelector: Func, descending: bool) -> None: ...
