# Auto-generated — Tekla 2026 — Tekla.Structures.TeklaStructuresInternal

class AreWeUnitTesting:
    """.NET: Tekla.Structures.TeklaStructuresInternal.AreWeUnitTesting"""
    def __init__(self, *args) -> None: ...
    Value: bool

class AsyncCallCompletion(MarshalByRefObject):
    """.NET: Tekla.Structures.TeklaStructuresInternal.AsyncCallCompletion`1"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def FromProxy(arg0: T0, arg1: T1, arg2: T2, beginProxy: Action) -> Task: ...
    def OnCompleted(self, result: TResult) -> None: ...
    def OnException(self, exception: Exception) -> None: ...

class AtcUser:
    """.NET: Tekla.Structures.TeklaStructuresInternal.AtcUser"""
    def __init__(self, *args) -> None: ...
    Email: str
    DisplayName: str
    AccessToken: str
    IdToken: str
    TIDUniqueUserId: str

class CDelegateSetter:
    """.NET: Tekla.Structures.TeklaStructuresInternal.CDelegateSetter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ResetInstance() -> None: ...
    @staticmethod
    def SetInstanceForUnitTesting(cdelegate: ICDelegate) -> None: ...

class CDelegateSynchronized(SynchronizeInvoke):
    """.NET: Tekla.Structures.TeklaStructuresInternal.CDelegateSynchronized"""
    def __init__(self, *args) -> None: ...
    InvokeRequired: bool
    @staticmethod
    def DotAnalysisExportGetAnalysisModuleQuery(pModuleQuery: DotAnalysisModuleManagerQuery) -> int: ...
    def ExportFeatureSupportHandler(self, pArgument: dotFeatureSupportHandler_t) -> int: ...
    def ExportGetAdvancedOption(self, pArgument: dotGetAdvancedOption_t) -> int: ...
    def ExportGetAnalysisModuleQuery(self, pModuleQuery: DotAnalysisModuleManagerQuery) -> int: ...
    def ExportGetAttributeFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetCurrentProgramVersion(self, pProgramVersion: dotProgramVersion_t) -> int: ...
    def ExportGetCurrentUser(self, user: str) -> int: ...
    def ExportGetIdentifierByGUID(self, pIdentifierToGUID: dotIdentifierToGUID_t) -> int: ...
    def ExportGetModelSessionID(self, ) -> str: ...
    def ExportGetModuleQuery(self, pModuleQuery: dotModuleManagerQuery_t) -> int: ...
    def ExportGetSessionID(self, ) -> str: ...
    def ExportGetSessionLogFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetSetClashCheckOptions(self, pArgument: dotClashCheckOptions_t) -> int: ...
    def ExportGetSetComponentOptions(self, pArgument: dotComponentOptions_t) -> int: ...
    def ExportGetToolOptionValue(self, toolOptionName: str) -> int: ...
    def ExportTestingFeaturesHandler(self, pArgument: dotTestingFeaturesHandler_t) -> int: ...
    @staticmethod
    def dotExportFeatureSupportHandler(pArgument: dotFeatureSupportHandler_t) -> int: ...
    @staticmethod
    def dotExportGetAdvancedOption(pArgument: dotGetAdvancedOption_t) -> int: ...
    @staticmethod
    def dotExportGetAttributeFile(data: dotGetAttributeFile_t) -> int: ...
    @staticmethod
    def dotExportGetCurrentProgramVersion(pProgramVersion: dotProgramVersion_t) -> int: ...
    @staticmethod
    def dotExportGetCurrentUser(user: StringBuilder) -> int: ...
    @staticmethod
    def dotExportGetFabDrawingsInfoByLibraryGuid(libraryGuid: str, pDrawingsInfo: IntPtr) -> int: ...
    @staticmethod
    def dotExportGetFabricationDrawingLibraries(pLibraries: IntPtr) -> int: ...
    @staticmethod
    def dotExportGetIdentifierByGUID(pIdentifierToGUID: dotIdentifierToGUID_t) -> int: ...
    @staticmethod
    def dotExportGetModuleQuery(pModuleQuery: dotModuleManagerQuery_t) -> int: ...
    @staticmethod
    def dotExportGetSessionLogFile(data: dotGetAttributeFile_t) -> int: ...
    @staticmethod
    def dotExportGetSetClashCheckOptions(pArgument: dotClashCheckOptions_t) -> int: ...
    @staticmethod
    def dotExportGetSetComponentOptions(pArgument: dotComponentOptions_t) -> int: ...
    @staticmethod
    def dotExportGetToolOptionValue(toolOptionName: str) -> int: ...
    @staticmethod
    def dotExportTestingFeaturesHandler(pArgument: dotTestingFeaturesHandler_t) -> int: ...

class CDelegateWrapper(MarshalByRefObject):
    """.NET: Tekla.Structures.TeklaStructuresInternal.CDelegateWrapper"""
    def __init__(self, *args) -> None: ...
    def ExportFeatureSupportHandler(self, pArgument: dotFeatureSupportHandler_t) -> int: ...
    def ExportGetAdvancedOption(self, pArgument: dotGetAdvancedOption_t) -> int: ...
    def ExportGetAnalysisModuleQuery(self, pModuleQuery: DotAnalysisModuleManagerQuery) -> int: ...
    def ExportGetAttributeFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetCurrentProgramVersion(self, pProgramVersion: dotProgramVersion_t) -> int: ...
    def ExportGetCurrentUser(self, user: str) -> int: ...
    def ExportGetIdentifierByGUID(self, pIdentifierToGUID: dotIdentifierToGUID_t) -> int: ...
    def ExportGetModelSessionID(self, ) -> str: ...
    def ExportGetModuleQuery(self, pModuleQuery: dotModuleManagerQuery_t) -> int: ...
    def ExportGetSessionID(self, ) -> str: ...
    def ExportGetSessionLogFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetSetClashCheckOptions(self, pArgument: dotClashCheckOptions_t) -> int: ...
    def ExportGetSetComponentOptions(self, pArgument: dotComponentOptions_t) -> int: ...
    def ExportGetToolOptionValue(self, toolOptionName: str) -> int: ...
    def ExportTestingFeaturesHandler(self, pArgument: dotTestingFeaturesHandler_t) -> int: ...

class DelegateFake(GenericDelegateFake):
    """.NET: Tekla.Structures.TeklaStructuresInternal.DelegateFake"""
    def __init__(self, *args) -> None: ...
    ...

class DotNetProxy:
    """.NET: Tekla.Structures.TeklaStructuresInternal.DotNetProxy"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Run(Param: str) -> int: ...

class EventHandlerWrapper(MarshalByRefObject):
    """.NET: Tekla.Structures.TeklaStructuresInternal.EventHandlerWrapper"""
    def __init__(self, *args) -> None: ...
    def AddListener(self, EventListener: IEvents) -> None: ...
    def RemoveListener(self, EventListener: IEvents) -> bool: ...

class Events(MarshalByRefObject):
    """.NET: Tekla.Structures.TeklaStructuresInternal.Events"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def InitializeLifetimeService(self, ) -> object: ...
    def OnModuleManagerUpdate(self, ) -> None: ...
    def OnTeklaStructuresExit(self, EventName: str, Parameters: list) -> None: ...
    def Register(self, ) -> None: ...
    def UnRegister(self, ) -> None: ...

class FeatureSupportHandler:
    """.NET: Tekla.Structures.TeklaStructuresInternal.FeatureSupportHandler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def DbOperation(Command: dotFeatureSupportCommandEnum_e, InputParameter: str) -> str: ...

class GenericDelegateFake:
    """.NET: Tekla.Structures.TeklaStructuresInternal.GenericDelegateFake`1"""
    def __init__(self, *args) -> None: ...
    def ExportFeatureSupportHandler(self, pArgument: dotFeatureSupportHandler_t) -> int: ...
    def ExportGetAdvancedOption(self, pArgument: dotGetAdvancedOption_t) -> int: ...
    def ExportGetAnalysisModuleQuery(self, pModuleQuery: DotAnalysisModuleManagerQuery) -> int: ...
    def ExportGetAttributeFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetCurrentProgramVersion(self, pProgramVersion: dotProgramVersion_t) -> int: ...
    def ExportGetCurrentUser(self, user: str) -> int: ...
    def ExportGetIdentifierByGUID(self, pIdentifierToGUID: dotIdentifierToGUID_t) -> int: ...
    def ExportGetModelSessionID(self, ) -> str: ...
    def ExportGetModuleQuery(self, pModuleQuery: dotModuleManagerQuery_t) -> int: ...
    def ExportGetSessionID(self, ) -> str: ...
    def ExportGetSessionLogFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetSetClashCheckOptions(self, pArgument: dotClashCheckOptions_t) -> int: ...
    def ExportGetSetComponentOptions(self, pArgument: dotComponentOptions_t) -> int: ...
    def ExportGetToolOptionValue(self, toolOptionName: str) -> int: ...
    def ExportTestingFeaturesHandler(self, pArgument: dotTestingFeaturesHandler_t) -> int: ...

class ICDelegate:
    """.NET: Tekla.Structures.TeklaStructuresInternal.ICDelegate"""
    def __init__(self, *args) -> None: ...
    def ExportFeatureSupportHandler(self, pArgument: dotFeatureSupportHandler_t) -> int: ...
    def ExportGetAdvancedOption(self, pArgument: dotGetAdvancedOption_t) -> int: ...
    def ExportGetAnalysisModuleQuery(self, pModuleQuery: DotAnalysisModuleManagerQuery) -> int: ...
    def ExportGetAttributeFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetCurrentProgramVersion(self, pProgramVersion: dotProgramVersion_t) -> int: ...
    def ExportGetCurrentUser(self, user: str) -> int: ...
    def ExportGetIdentifierByGUID(self, pIdentifierToGUID: dotIdentifierToGUID_t) -> int: ...
    def ExportGetModelSessionID(self, ) -> str: ...
    def ExportGetModuleQuery(self, pModuleQuery: dotModuleManagerQuery_t) -> int: ...
    def ExportGetSessionID(self, ) -> str: ...
    def ExportGetSessionLogFile(self, data: dotGetAttributeFile_t) -> bool: ...
    def ExportGetSetClashCheckOptions(self, pArgument: dotClashCheckOptions_t) -> int: ...
    def ExportGetSetComponentOptions(self, pArgument: dotComponentOptions_t) -> int: ...
    def ExportGetToolOptionValue(self, toolOptionName: str) -> int: ...
    def ExportTestingFeaturesHandler(self, pArgument: dotTestingFeaturesHandler_t) -> int: ...

class IEventHandler:
    """.NET: Tekla.Structures.TeklaStructuresInternal.IEventHandler"""
    def __init__(self, *args) -> None: ...
    def AddListener(self, EventListener: IEvents) -> None: ...
    def RemoveListener(self, EventListener: IEvents) -> bool: ...

class IEvents:
    """.NET: Tekla.Structures.TeklaStructuresInternal.IEvents"""
    def __init__(self, *args) -> None: ...
    def OnModuleManagerUpdate(self, ) -> None: ...
    def OnTeklaStructuresExit(self, EventName: str, Parameters: list) -> None: ...
    def Register(self, ) -> None: ...
    def UnRegister(self, ) -> None: ...

class Operation:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Operation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetAtcUserAsync(askLogin: bool) -> Task: ...
    @staticmethod
    def dotExportGetAttributeFile(filename: str, locationType: SharingAttributeFileLocationType) -> str: ...
    @staticmethod
    def dotExportGetSessionLogFile() -> str: ...

class Remoter:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Remoter"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def DisposeService() -> None: ...
    @staticmethod
    def InitializeSandBox() -> bool: ...

class TeklaStructuresApplication(MarshalByRefObject):
    """.NET: Tekla.Structures.TeklaStructuresInternal.TeklaStructuresApplication"""
    def __init__(self, *args) -> None: ...
    AuthenticationAsyncCallback: Func
    def BeginAtcUserAsync(self, askLogin: bool, endCallback: IAsyncCallCompletion) -> None: ...

class TeklaStructuresSettingsHelper:
    """.NET: Tekla.Structures.TeklaStructuresInternal.TeklaStructuresSettingsHelper"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetAdvancedOptionPaths(advancedOption: str, paths: List, errorHandler: InvalidPathCallback) -> bool: ...
    @staticmethod
    def GetUnitsDecimalSettings(unitsDecimals: ModelingUnitsDecimals) -> bool: ...

class TeklaStructuresTrackingInfo:
    """.NET: Tekla.Structures.TeklaStructuresInternal.TeklaStructuresTrackingInfo"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetModelSessionID() -> str: ...
    @staticmethod
    def GetSessionID() -> str: ...

class TestingFeaturesHandler:
    """.NET: Tekla.Structures.TeklaStructuresInternal.TestingFeaturesHandler"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def DbOperation(Command: dotTestingFeaturesCommandEnum_e, InputParameter: str) -> str: ...
    @staticmethod
    def IsAvailable() -> bool: ...

class dotFeatureSupportCommandEnum_e:
    """.NET: Tekla.Structures.TeklaStructuresInternal.dotFeatureSupportCommandEnum_e"""
    def __init__(self, *args) -> None: ...
    ...

class dotFeatureSupportHandler_t:
    """.NET: Tekla.Structures.TeklaStructuresInternal.dotFeatureSupportHandler_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotGetAttributeFile_t:
    """.NET: Tekla.Structures.TeklaStructuresInternal.dotGetAttributeFile_t"""
    def __init__(self, *args) -> None: ...
    ...

class dotTestingFeaturesCommandEnum_e:
    """.NET: Tekla.Structures.TeklaStructuresInternal.dotTestingFeaturesCommandEnum_e"""
    def __init__(self, *args) -> None: ...
    ...

class dotTestingFeaturesHandler_t:
    """.NET: Tekla.Structures.TeklaStructuresInternal.dotTestingFeaturesHandler_t"""
    def __init__(self, *args) -> None: ...
    ...
