# Auto-generated — Tekla 2026 — Tekla.Structures.TeklaStructuresInternal.Filtering

class BinaryFilterExpressionToken:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.BinaryFilterExpressionToken"""
    def __init__(self, *args) -> None: ...
    FilterString: str
    BinaryFilterOperatorType: BinaryFilterOperatorType
    IsCollection: bool
    Enabled: bool

class FilterExpressionGenerator:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.FilterExpressionGenerator"""
    def __init__(self, *args) -> None: ...
    def Generate(self, FilterExpression: FilterExpression, FilterExpressionFileType: FilterExpressionFileType, FullFileName: str) -> str: ...

class FilterExpressionGeneratorFactory:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.FilterExpressionGeneratorFactory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateGenerator(FilterExpressionGeneratoryType: FilterExpressionGeneratorType) -> FilterExpressionGenerator: ...

class FilterExpressionGeneratorType:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.FilterExpressionGeneratorType"""
    def __init__(self, *args) -> None: ...
    ...

class FilterExpressionParser:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.FilterExpressionParser"""
    def __init__(self, *args) -> None: ...
    def Parse(self, FullFileName: str, Provider: IFormatProvider) -> FilterExpression: ...
    def ParseExpressionString(self, FilterString: str, Provider: IFormatProvider) -> FilterExpression: ...

class FilterExpressionParserFactory:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.FilterExpressionParserFactory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateParser(FilterExpressionParserType: FilterExpressionParserType) -> FilterExpressionParser: ...

class FilterExpressionParserType:
    """.NET: Tekla.Structures.TeklaStructuresInternal.Filtering.FilterExpressionParserType"""
    def __init__(self, *args) -> None: ...
    ...
