# Auto-generated — Tekla 2026 — Tekla.Structures.TeklaStructuresInternal.MateriaClient

class Asset:
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.Asset"""
    def __init__(self, *args) -> None: ...
    Uri: str
    Name: str

class ConnectionChangedEventArgs(EventArgs):
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.ConnectionChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    Connected: bool
    Disconnected: bool
    Busy: bool

class GraphComputeEventArgs(EventArgs):
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.GraphComputeEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class GraphParameter:
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.GraphParameter"""
    def __init__(self, *args) -> None: ...
    def ToString(self, ) -> str: ...

class IGraph:
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.IGraph"""
    def __init__(self, *args) -> None: ...
    Asset: Asset
    def GetParameterList(self, ) -> List: ...
    def GetTrimBimToFile(self, path: str) -> Task: ...
    def SetParameterList(self, graphParameters: List) -> None: ...

class IMateriaClientAdapter:
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.IMateriaClientAdapter"""
    def __init__(self, *args) -> None: ...
    def Connect(self, ) -> Task: ...
    def Disconnect(self, ) -> None: ...
    def IsConnectionActive(self, ) -> bool: ...
    def LoadGraph(self, asset: Asset, graphParameters: List) -> Task: ...
    def SearchAssets(self, StringSearch: str) -> Task: ...

class MateriaClientAdapter:
    """.NET: Tekla.Structures.TeklaStructuresInternal.MateriaClient.MateriaClientAdapter"""
    def __init__(self, *args) -> None: ...
    Instance: IMateriaClientAdapter
    def Connect(self, ) -> Task: ...
    def Disconnect(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def IsConnectionActive(self, ) -> bool: ...
    def LoadGraph(self, asset: Asset, graphParameters: List) -> Task: ...
    def SearchAssets(self, StringSearch: str) -> Task: ...
