# Auto-generated — Rhino 8 — Rhino.DocObjects.SnapShots

class SnapShotsClient:
    """.NET: Rhino.DocObjects.SnapShots.SnapShotsClient"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    SerialNumber: int
    def AnimateDocument(self, doc: RhinoDoc, dPos: float, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> bool: ...
    def AnimateObject(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, dPos: float, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> bool: ...
    def AnimationStart(self, doc: RhinoDoc, iFrames: int) -> None: ...
    def AnimationStop(self, doc: RhinoDoc) -> bool: ...
    @staticmethod
    def ApplicationCategory() -> str: ...
    def Category(self, ) -> str: ...
    def ClientId(self, ) -> Guid: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def DocumentCategory() -> str: ...
    def ExtendBoundingBoxForDocumentAnimation(self, doc: RhinoDoc, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader, bbox: BoundingBox) -> None: ...
    def ExtendBoundingBoxForObjectAnimation(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader, bbox: BoundingBox) -> None: ...
    def IsCurrentModelStateInAnySnapshot(self, doc: RhinoDoc, doc_object: RhinoObject, archive: BinaryArchiveReader, archive_array: SimpleArrayBinaryArchiveReader, text_log: TextLog) -> bool: ...
    @staticmethod
    def LayersCategory() -> str: ...
    @staticmethod
    def LightsCategory() -> str: ...
    def Name(self, ) -> str: ...
    def ObjectTransformNotification(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive: BinaryArchiveReader) -> bool: ...
    @staticmethod
    def ObjectsCategory() -> str: ...
    def PlugInId(self, ) -> Guid: ...
    def PrepareForDocumentAnimation(self, doc: RhinoDoc, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> bool: ...
    def PrepareForObjectAnimation(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive_start: BinaryArchiveReader, archive_stop: BinaryArchiveReader) -> bool: ...
    @staticmethod
    def RegisterSnapShotClient(client: SnapShotsClient) -> bool: ...
    @staticmethod
    def RenderingCategory() -> str: ...
    def RestoreDocument(self, doc: RhinoDoc, archive: BinaryArchiveReader) -> bool: ...
    def RestoreObject(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive: BinaryArchiveReader) -> bool: ...
    def SaveDocument(self, doc: RhinoDoc, archive: BinaryArchiveWriter) -> bool: ...
    def SaveObject(self, doc: RhinoDoc, doc_object: RhinoObject, transform: Transform, archive: BinaryArchiveWriter) -> bool: ...
    def SnapshotRestored(self, doc: RhinoDoc) -> None: ...
    def SupportsAnimation(self, ) -> bool: ...
    def SupportsDocument(self, ) -> bool: ...
    def SupportsObject(self, doc_object: RhinoObject) -> bool: ...
    def SupportsObjects(self, ) -> bool: ...
    @staticmethod
    def ViewsCategory() -> str: ...
