# Auto-generated — Rhino 8 — Rhino.DocObjects.Tables

class BitmapTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.BitmapTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Item: BitmapEntry
    Document: RhinoDoc
    Count: int
    def AddBitmap(self, bitmapFilename: str, replaceExisting: bool) -> int: ...
    def Delete(self, item: BitmapEntry) -> bool: ...
    def DeleteBitmap(self, bitmapFilename: str) -> bool: ...
    def ExportToFile(self, index: int, path: str) -> bool: ...
    def ExportToFiles(self, directoryPath: str, overwrite: int) -> int: ...
    def Find(self, name: str, createFile: bool, fileName: str) -> BitmapEntry: ...
    def FindIndex(self, index: int) -> BitmapEntry: ...

class DimStyleTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.DimStyleTable"""
    def __init__(self, *args) -> None: ...
    BuiltInStyles: list
    Item: DimensionStyle
    CurrentIndex: int
    CurrentId: Guid
    CurrentDimensionStyle: DimensionStyle
    Current: DimensionStyle
    ComponentType: ModelComponentType
    Document: RhinoDoc
    Count: int
    def Add(self, dimstyle: DimensionStyle, reference: bool) -> int: ...
    def Delete(self, index: int, quiet: bool) -> bool: ...
    def Find(self, name: str, ignoreDeleted: bool) -> DimensionStyle: ...
    def FindIndex(self, index: int) -> DimensionStyle: ...
    def FindName(self, name: str) -> DimensionStyle: ...
    def FindRoot(self, styleId: Guid, ignoreDeleted: bool) -> DimensionStyle: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetUnusedStyleName(self, rootName: str) -> str: ...
    def Modify(self, newSettings: DimensionStyle, dimstyleIndex: int, quiet: bool) -> bool: ...
    def SetCurrent(self, index: int, quiet: bool) -> bool: ...
    def SetCurrentDimensionStyleIndex(self, index: int, quiet: bool) -> bool: ...

class DimStyleTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.DimStyleTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: DimStyleTableEventType
    Index: int
    NewState: DimensionStyle
    OldState: DimensionStyle

class DimStyleTableEventType:
    """.NET: Rhino.DocObjects.Tables.DimStyleTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class FontTable:
    """.NET: Rhino.DocObjects.Tables.FontTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    CurrentIndex: int
    Item: Font
    def FindOrCreate(self, face: str, bold: bool, italic: bool, template_style: DimensionStyle) -> int: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class GroupTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.GroupTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Item: Group
    Document: RhinoDoc
    Count: int
    def Add(self, groupName: str, objectIds: IEnumerable) -> int: ...
    def AddToGroup(self, groupIndex: int, objectId: Guid) -> bool: ...
    def ChangeGroupName(self, groupIndex: int, newName: str) -> bool: ...
    def Delete(self, groupIndex: int) -> bool: ...
    def Find(self, groupName: str, ignoreDeletedGroups: bool) -> int: ...
    def FindIndex(self, index: int) -> Group: ...
    def FindName(self, name: str) -> Group: ...
    def FindNameHash(self, nameHash: NameHash) -> Group: ...
    def GroupMembers(self, groupIndex: int) -> list: ...
    def GroupName(self, groupIndex: int) -> str: ...
    def GroupNames(self, ignoreDeletedGroups: bool) -> list: ...
    def GroupObjectCount(self, groupIndex: int) -> int: ...
    def Hide(self, groupIndex: int) -> int: ...
    def IsDeleted(self, groupIndex: int) -> bool: ...
    def Lock(self, groupIndex: int) -> int: ...
    def RemapObjects(self, rhinoObjects: IEnumerable, indexMap: Dictionary) -> int: ...
    def Show(self, groupIndex: int) -> int: ...
    def Undelete(self, groupIndex: int) -> bool: ...
    def Unlock(self, groupIndex: int) -> int: ...

class GroupTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.GroupTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: GroupTableEventType
    GroupIndex: int
    NewState: Group
    OldState: Group

class GroupTableEventType:
    """.NET: Rhino.DocObjects.Tables.GroupTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class HatchPatternTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.HatchPatternTable"""
    def __init__(self, *args) -> None: ...
    Item: HatchPattern
    CurrentHatchPatternIndex: int
    ComponentType: ModelComponentType
    Document: RhinoDoc
    Count: int
    def Add(self, pattern: HatchPattern) -> int: ...
    def Delete(self, item: HatchPattern, quiet: bool) -> bool: ...
    def Find(self, name: str, ignoreDeleted: bool) -> int: ...
    def FindIndex(self, index: int) -> HatchPattern: ...
    def FindName(self, name: str) -> HatchPattern: ...
    def FindNameHash(self, nameHash: NameHash) -> HatchPattern: ...
    def Modify(self, hatchPattern: HatchPattern, hatchPatternIndex: int, quiet: bool) -> bool: ...
    def Rename(self, item: HatchPattern, hatchPatternName: str) -> bool: ...

class HatchPatternTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.HatchPatternTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: HatchPatternTableEventType
    HatchPatternIndex: int
    NewState: HatchPattern
    OldState: HatchPattern

class HatchPatternTableEventType:
    """.NET: Rhino.DocObjects.Tables.HatchPatternTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class InstanceDefinitionTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.InstanceDefinitionTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    ActiveCount: int
    ComponentType: ModelComponentType
    Item: InstanceDefinition
    def Add(self, name: str, description: str, url: str, urlTag: str, basePoint: Point3d, geometry: IEnumerable, attributes: IEnumerable) -> int: ...
    def Compact(self, ignoreUndoReferences: bool) -> None: ...
    def Delete(self, idefIndex: int, deleteReferences: bool, quiet: bool) -> bool: ...
    def DestroySourceArchive(self, definition: InstanceDefinition, quiet: bool) -> bool: ...
    def Find(self, instanceDefinitionName: str, ignoreDeletedInstanceDefinitions: bool) -> InstanceDefinition: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetList(self, ignoreDeleted: bool) -> list: ...
    def GetUnusedInstanceDefinitionName(self, root: str, defaultSuffix: int) -> str: ...
    def InstanceDefinitionIndex(self, instanceId: Guid, ignoreDeletedInstanceDefinitions: bool) -> int: ...
    def MakeSourcePathRelative(self, idef: InstanceDefinition, relative: bool, quiet: bool) -> bool: ...
    def Modify(self, idef: InstanceDefinition, newName: str, newDescription: str, newUrl: str, newUrlTag: str, quiet: bool) -> bool: ...
    def ModifyGeometry(self, idefIndex: int, newGeometry: IEnumerable, newAttributes: IEnumerable) -> bool: ...
    def ModifySourceArchive(self, idefIndex: int, sourceArchive: str, updateType: InstanceDefinitionUpdateType, quiet: bool) -> bool: ...
    def Purge(self, idefIndex: int) -> bool: ...
    def RefreshLinkedBlock(self, definition: InstanceDefinition) -> bool: ...
    def Undelete(self, idefIndex: int) -> bool: ...
    def UndoModify(self, idefIndex: int) -> bool: ...
    def UpdateLinkedInstanceDefinition(self, idefIndex: int, filename: str, updateNestedLinks: bool, quiet: bool) -> bool: ...

class InstanceDefinitionTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.InstanceDefinitionTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: InstanceDefinitionTableEventType
    InstanceDefinitionIndex: int
    NewState: InstanceDefinition
    OldState: InstanceDefinitionGeometry

class InstanceDefinitionTableEventType:
    """.NET: Rhino.DocObjects.Tables.InstanceDefinitionTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class LayerTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.LayerTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    ActiveCount: int
    Item: Layer
    CurrentLayerIndex: int
    CurrentLayer: Layer
    ComponentType: ModelComponentType
    def Add(self, layerName: str, layerColor: Color) -> int: ...
    def AddPath(self, layerPath: str, layerColor: Color) -> int: ...
    def AddReferenceLayer(self, layer: Layer) -> int: ...
    def CreateLayer(self, newLayer: Layer, layerType: LayerType, worksessionReferenceModelSerialNumber: int, linkedInstanceDefinitionSerialNumber: int) -> int: ...
    def Delete(self, layerIndex: int, quiet: bool) -> bool: ...
    def Duplicate(self, layerIndex: int, duplicateObjects: bool, duplicateSublayers: bool) -> list: ...
    def Find(self, parentId: Guid, layerName: str, ignoreDeletedLayers: bool) -> int: ...
    def FindByFullPath(self, layerPath: str, ignoreDeletedLayers: bool) -> int: ...
    def FindIndex(self, index: int) -> Layer: ...
    def FindName(self, layerName: str, startIndex: int) -> Layer: ...
    def FindNameHash(self, nameHash: NameHash) -> Layer: ...
    def FindNext(self, index: int, layerName: str, ignoreDeletedLayers: bool) -> int: ...
    def ForceLayerVisible(self, layerId: Guid) -> bool: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetSelected(self, layerIndices: List) -> bool: ...
    def GetSorted(self, ) -> list: ...
    def GetUnusedLayerName(self, ignoreDeleted: bool) -> str: ...
    def Modify(self, newSettings: Layer, layerIndex: int, quiet: bool) -> bool: ...
    def Purge(self, layerIndex: int, quiet: bool) -> bool: ...
    def Select(self, layerIndices: IEnumerable, bDeselect: bool) -> bool: ...
    def SetCurrentLayerIndex(self, layerIndex: int, quiet: bool) -> bool: ...
    def Sort(self, layerIndices: IEnumerable) -> None: ...
    def SortByLayerName(self, bAscending: bool) -> None: ...
    def Undelete(self, layerIndex: int) -> bool: ...
    def UndoModify(self, layerIndex: int, undoRecordSerialNumber: int) -> bool: ...

class LayerTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.LayerTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: LayerTableEventType
    LayerIndex: int
    NewState: Layer
    OldState: Layer

class LayerTableEventType:
    """.NET: Rhino.DocObjects.Tables.LayerTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class LightTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.LightTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Sun: Sun
    Skylight: Skylight
    Count: int
    ComponentType: ModelComponentType
    Item: LightObject
    def Add(self, light: Light, attributes: ObjectAttributes) -> int: ...
    def Delete(self, index: int, quiet: bool) -> bool: ...
    def Find(self, id: Guid, ignoreDeleted: bool) -> int: ...
    def FindIndex(self, index: int) -> LightObject: ...
    def FindName(self, name: str) -> LightObject: ...
    def FindNameHash(self, nameHash: NameHash) -> LightObject: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Modify(self, id: Guid, light: Light) -> bool: ...
    def Undelete(self, index: int) -> bool: ...

class LightTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.LightTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: LightTableEventType
    LightIndex: int
    NewState: LightObject
    OldState: Light

class LightTableEventType:
    """.NET: Rhino.DocObjects.Tables.LightTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class LinetypeTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.LinetypeTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    ActiveCount: int
    CurrentLinetypeIndex: int
    LinetypeScale: float
    Item: Linetype
    CurrentLinetypeSource: ObjectLinetypeSource
    CurrentLinetype: Linetype
    ContinuousLinetypeName: str
    ByLayerLinetypeName: str
    ByParentLinetypeName: str
    ComponentType: ModelComponentType
    def Add(self, name: str, segmentLengths: IEnumerable) -> int: ...
    def AddReferenceLinetype(self, linetype: Linetype) -> int: ...
    def Delete(self, index: int, quiet: bool) -> bool: ...
    def Find(self, name: str, ignoreDeletedLinetypes: bool) -> int: ...
    def FindIndex(self, index: int) -> Linetype: ...
    def FindName(self, name: str) -> Linetype: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetUnusedLinetypeName(self, ignoreDeleted: bool) -> str: ...
    def LinetypeIndexForObject(self, rhinoObject: RhinoObject) -> int: ...
    def LoadDefaultLinetypes(self, ignoreDeleted: bool) -> int: ...
    def Modify(self, linetype: Linetype, index: int, quiet: bool) -> bool: ...
    def SetCurrentLinetypeIndex(self, linetypeIndex: int, quiet: bool) -> bool: ...
    def Undelete(self, index: int) -> bool: ...
    def UndoModify(self, index: int) -> bool: ...

class LinetypeTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.LinetypeTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: LinetypeTableEventType
    LinetypeIndex: int
    NewState: Linetype
    OldState: Linetype

class LinetypeTableEventType:
    """.NET: Rhino.DocObjects.Tables.LinetypeTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class MaterialTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.MaterialTable"""
    def __init__(self, *args) -> None: ...
    Item: Material
    CurrentMaterialIndex: int
    CurrentMaterialSource: ObjectMaterialSource
    ComponentType: ModelComponentType
    Document: RhinoDoc
    Count: int
    def Add(self, material: Material, reference: bool) -> int: ...
    def Delete(self, item: Material) -> bool: ...
    def DeleteAt(self, materialIndex: int) -> bool: ...
    def Find(self, material: Material, ignoreDeletedMaterials: bool) -> int: ...
    def FindIndex(self, index: int) -> Material: ...
    def Modify(self, newSettings: Material, materialIndex: int, quiet: bool) -> bool: ...
    def ResetMaterial(self, materialIndex: int) -> bool: ...

class MaterialTableEventArgs(EventArgs):
    """.NET: Rhino.DocObjects.Tables.MaterialTableEventArgs"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    EventType: MaterialTableEventType
    Index: int
    OldSettings: Material

class MaterialTableEventType:
    """.NET: Rhino.DocObjects.Tables.MaterialTableEventType"""
    def __init__(self, *args) -> None: ...
    ...

class ModifyType:
    """.NET: Rhino.DocObjects.Tables.ModifyType"""
    def __init__(self, *args) -> None: ...
    ...

class NamedConstructionPlaneTable:
    """.NET: Rhino.DocObjects.Tables.NamedConstructionPlaneTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    Item: ConstructionPlane
    def Add(self, name: str, plane: Plane) -> int: ...
    def Delete(self, index: int) -> bool: ...
    def Find(self, name: str) -> int: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class NamedLayerStateTable:
    """.NET: Rhino.DocObjects.Tables.NamedLayerStateTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    Names: list
    def Delete(self, name: str) -> bool: ...
    def FindName(self, name: str) -> int: ...
    def Import(self, filename: str) -> int: ...
    def Rename(self, oldName: str, newName: str) -> bool: ...
    def Restore(self, name: str, properties: RestoreLayerProperties, viewportId: Guid) -> bool: ...
    def Save(self, name: str, viewportId: Guid) -> int: ...

class NamedPositionTable:
    """.NET: Rhino.DocObjects.Tables.NamedPositionTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    Ids: list
    Names: list
    def Append(self, id: Guid, objects: IEnumerable) -> bool: ...
    def Delete(self, id: Guid) -> bool: ...
    def Id(self, name: str) -> Guid: ...
    def Name(self, id: Guid) -> str: ...
    def ObjectIds(self, id: Guid) -> list: ...
    def ObjectXform(self, id: Guid, obj: RhinoObject, xform: Transform) -> bool: ...
    def Objects(self, id: Guid) -> list: ...
    def Rename(self, id: Guid, name: str) -> bool: ...
    def Restore(self, id: Guid) -> bool: ...
    def Save(self, name: str, objects: IEnumerable) -> Guid: ...
    def Update(self, id: Guid) -> bool: ...

class NamedViewTable:
    """.NET: Rhino.DocObjects.Tables.NamedViewTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    Item: ViewInfo
    Selection: list
    def Add(self, name: str, viewportId: Guid) -> int: ...
    def Delete(self, index: int) -> bool: ...
    def FindByName(self, name: str) -> int: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Rename(self, index: int, newName: str) -> bool: ...
    def Restore(self, index: int, view: RhinoView, backgroundBitmap: bool) -> bool: ...
    def RestoreAnimated(self, index: int, view: RhinoView, backgroundBitmap: bool, frames: int, frameRate: int) -> bool: ...
    def RestoreAnimatedConstantSpeed(self, index: int, viewport: RhinoViewport, units_per_frame: float, ms_delay: int) -> bool: ...
    def RestoreAnimatedConstantTime(self, index: int, viewport: RhinoViewport, frames: int, ms_delay: int) -> bool: ...
    def RestoreWithAspectRatio(self, index: int, viewport: RhinoViewport) -> bool: ...

class ObjectTable(RhinoDocCommonTable):
    """.NET: Rhino.DocObjects.Tables.ObjectTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    HistoryRecordCount: int
    BoundingBox: BoundingBox
    BoundingBoxVisible: BoundingBox
    ComponentType: ModelComponentType
    Count: int
    def Add(self, geometry: GeometryBase, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddAngularDimension(self, dimension: AngularDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddArc(self, arc: Arc, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddBox(self, box: Box, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddBrep(self, brep: Brep, attributes: ObjectAttributes, history: HistoryRecord, reference: bool, splitKinkySurfaces: bool) -> Guid: ...
    def AddCentermark(self, centermark: Centermark, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddCircle(self, circle: Circle, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportId: Guid, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddClippingPlaneSurface(self, clippingPlane: ClippingPlaneSurface, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddCurve(self, curve: Curve, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddEllipse(self, ellipse: Ellipse, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddExplodedInstancePieces(self, instance: InstanceObject, explodeNestedInstances: bool, deleteInstance: bool) -> list: ...
    def AddExtrusion(self, extrusion: Extrusion, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddHatch(self, hatch: Hatch, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddInstanceObject(self, instanceDefinitionIndex: int, instanceXform: Transform, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddLeader(self, text: str, plane: Plane, points: IEnumerable, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddLine(self, from_: Point3d, to: Point3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddLinearDimension(self, dimension: LinearDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddMesh(self, mesh: Mesh, attributes: ObjectAttributes, history: HistoryRecord, reference: bool, requireValidMesh: bool) -> Guid: ...
    def AddMorphControl(self, morphControl: MorphControl, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddOrderedPointCloud(self, xCt: int, yCt: int, zCt: int, min: Point3d, max: Point3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddOrdinateDimension(self, dimordinate: OrdinateDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddPictureFrame(self, plane: Plane, texturePath: str, asMesh: bool, width: float, height: float, selfIllumination: bool, embedBitmap: bool) -> Guid: ...
    def AddPoint(self, point: Point3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddPointCloud(self, cloud: PointCloud, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddPoints(self, points: IEnumerable, attributes: ObjectAttributes) -> RhinoList: ...
    def AddPolyline(self, points: IEnumerable, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddRadialDimension(self, dimension: RadialDimension, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddRectangle(self, rectangle: Rectangle3d, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddRhinoObject(self, meshObject: CustomMeshObject, history: HistoryRecord) -> None: ...
    def AddSphere(self, sphere: Sphere, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddSubD(self, subD: SubD, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddSurface(self, surface: Surface, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, justification: TextJustification, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AddTextDot(self, dot: TextDot, attributes: ObjectAttributes, history: HistoryRecord, reference: bool) -> Guid: ...
    def AllObjectsSince(self, runtimeSerialNumber: int) -> list: ...
    def Delete(self, objref: ObjRef, quiet: bool, ignoreModes: bool) -> bool: ...
    def DeleteGrip(self, gripId: Guid) -> bool: ...
    def DeleteGrips(self, owner: RhinoObject, gripIndices: IEnumerable) -> int: ...
    def Duplicate(self, objref: ObjRef) -> Guid: ...
    def Find(self, objectId: Guid) -> RhinoObject: ...
    def FindByCrossingWindowRegion(self, viewport: RhinoViewport, screen1: Point2d, screen2: Point2d, inside: bool, filter: ObjectType) -> list: ...
    def FindByDrawColor(self, drawColor: Color, includeLights: bool) -> list: ...
    def FindByFilter(self, filter: ObjectEnumeratorSettings) -> list: ...
    def FindByGroup(self, groupIndex: int) -> list: ...
    def FindByLayer(self, layer: Layer) -> list: ...
    def FindByObjectType(self, typeFilter: ObjectType) -> list: ...
    def FindByUserString(self, key: str, value: str, caseSensitive: bool, searchGeometry: bool, searchAttributes: bool, filter: ObjectType) -> list: ...
    def FindByWindowRegion(self, viewport: RhinoViewport, screen1: Point2d, screen2: Point2d, inside: bool, filter: ObjectType) -> list: ...
    def FindClippingPlanesForViewport(self, viewport: RhinoViewport, includeHidden: bool) -> list: ...
    def FindGeometry(self, id: Guid) -> GeometryBase: ...
    def FindId(self, id: Guid) -> RhinoObject: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetObjectIdList(self, settings: ObjectEnumeratorSettings) -> IEnumerable: ...
    def GetObjectList(self, settings: ObjectEnumeratorSettings) -> IEnumerable: ...
    def GetObjectsByType(self, settings: ObjectEnumeratorSettings) -> IEnumerable: ...
    def GetSelectedObjectCount(self, checkSubObjects: bool) -> int: ...
    def GetSelectedObjectTypes(self, ) -> ObjectType: ...
    def GetSelectedObjects(self, includeLights: bool, includeGrips: bool) -> IEnumerable: ...
    def GripUpdate(self, obj: RhinoObject, deleteOriginal: bool) -> RhinoObject: ...
    def Hide(self, objref: ObjRef, ignoreLayerMode: bool, hideGroup: str) -> bool: ...
    def InvalidateBoundingBox(self, ) -> None: ...
    def Lock(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    def ModifyAttributes(self, objref: ObjRef, newAttributes: ObjectAttributes, quiet: bool) -> bool: ...
    def ModifyRenderMaterial(self, obj: RhinoObject, material: RenderMaterial) -> bool: ...
    def ModifyTextureMapping(self, objRef: ObjRef, channel: int, mapping: TextureMapping) -> bool: ...
    def MostRecentObject(self, ) -> RhinoObject: ...
    def ObjectCount(self, filter: ObjectEnumeratorSettings) -> int: ...
    def PickObjects(self, pickContext: PickContext) -> list: ...
    def Purge(self, runtimeSerialNumber: int) -> bool: ...
    def Replace(self, objectId: Guid, geometry: GeometryBase, ignoreModes: bool) -> bool: ...
    def ReplaceInstanceObject(self, objectId: Guid, instanceDefinitionIndex: int) -> bool: ...
    def Select(self, objref: ObjRef, select: bool, syncHighlight: bool, persistentSelect: bool, ignoreGripsState: bool, ignoreLayerLocking: bool, ignoreLayerVisibility: bool) -> bool: ...
    def SelectedObjectsExist(self, objectType: ObjectType, checkSubObjects: bool) -> bool: ...
    def Show(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    def Transform(self, objref: ObjRef, xform: Transform, deleteOriginal: bool) -> Guid: ...
    def TransformWithHistory(self, objref: ObjRef, xform: Transform) -> Guid: ...
    def TryFindPoint(self, id: Guid, point: Point3d) -> bool: ...
    def Undelete(self, runtimeSerialNumber: int) -> bool: ...
    def Unlock(self, objref: ObjRef, ignoreLayerMode: bool) -> bool: ...
    def UnselectAll(self, ignorePersistentSelections: bool) -> int: ...

class RestoreLayerProperties:
    """.NET: Rhino.DocObjects.Tables.RestoreLayerProperties"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoDocCommonTable(CommonComponentTable):
    """.NET: Rhino.DocObjects.Tables.RhinoDocCommonTable`1"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    ComponentType: ModelComponentType

class RuntimeDocumentDataTable(Dictionary):
    """.NET: Rhino.DocObjects.Tables.RuntimeDocumentDataTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Comparer: IEqualityComparer
    Count: int
    Keys: KeyCollection
    Values: ValueCollection
    Item: object
    def GetValue(self, key: object, newT: Func) -> T: ...
    def TryGetValue(self, key: object) -> T: ...

class SnapshotTable:
    """.NET: Rhino.DocObjects.Tables.SnapshotTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Names: list

class StringTable:
    """.NET: Rhino.DocObjects.Tables.StringTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Count: int
    DocumentDataCount: int
    DocumentUserTextCount: int
    def Delete(self, section: str, entry: str) -> None: ...
    def GetEntryNames(self, section: str) -> list: ...
    def GetKey(self, i: int) -> str: ...
    def GetSectionNames(self, ) -> list: ...
    def GetValue(self, section: str, entry: str) -> str: ...
    def SetString(self, section: str, entry: str, value: str) -> str: ...

class ViewTable:
    """.NET: Rhino.DocObjects.Tables.ViewTable"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    ActiveView: RhinoView
    RedrawEnabled: bool
    ModelSpaceIsActive: bool
    def Add(self, title: str, projection: DefinedViewportProjection, position: Rectangle, floating: bool) -> RhinoView: ...
    def AddPageView(self, title: str, pageWidth: float, pageHeight: float) -> RhinoPageView: ...
    def DefaultViewLayout(self, ) -> None: ...
    def EnableCameraIcon(self, view: RhinoView) -> None: ...
    def EnableRedraw(self, enable: bool, redrawDocument: bool, redrawLayers: bool) -> None: ...
    def Find(self, mainViewportName: str, compareCase: bool) -> RhinoView: ...
    def FlashObjects(self, list: IEnumerable, useSelectionColor: bool) -> None: ...
    def FourViewLayout(self, useMatchingViews: bool) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetPageViews(self, ) -> list: ...
    def GetStandardRhinoViews(self, ) -> list: ...
    def GetViewList(self, includeStandardViews: bool, includePageViews: bool) -> list: ...
    def IsCameraIconVisible(self, view: RhinoView) -> bool: ...
    def Redraw(self, ) -> None: ...
    def ThreeViewLayout(self, useMatchingViews: bool) -> None: ...
