# Auto-generated — Tekla 2026 — Tekla.Structures.Filtering

class BinaryFilterExpression(FilterExpression):
    """.NET: Tekla.Structures.Filtering.BinaryFilterExpression"""
    def __init__(self, *args) -> None: ...
    IsEnable: bool

class BinaryFilterExpressionCollection(FilterExpression):
    """.NET: Tekla.Structures.Filtering.BinaryFilterExpressionCollection"""
    def __init__(self, *args) -> None: ...
    IsSynchronized: bool
    SyncRoot: object
    Count: int
    IsReadOnly: bool
    Item: BinaryFilterExpressionItem
    IsEnable: bool
    def Add(self, Item: BinaryFilterExpressionItem) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, Item: BinaryFilterExpressionItem) -> bool: ...
    def CopyTo(self, Array: list, ArrayIndex: int) -> None: ...
    def GetFirst(self, ) -> BinaryFilterExpressionItem: ...
    def GetLast(self, ) -> BinaryFilterExpressionItem: ...
    def IndexOf(self, Item: BinaryFilterExpressionItem) -> int: ...
    def Insert(self, Index: int, Item: BinaryFilterExpressionItem) -> None: ...
    def IsFirst(self, BinaryFilterExpressionItem: BinaryFilterExpressionItem) -> bool: ...
    def IsLast(self, BinaryFilterExpressionItem: BinaryFilterExpressionItem) -> bool: ...
    def Remove(self, Item: BinaryFilterExpressionItem) -> bool: ...
    def RemoveAt(self, Index: int) -> None: ...

class BinaryFilterExpressionItem(Expression):
    """.NET: Tekla.Structures.Filtering.BinaryFilterExpressionItem"""
    def __init__(self, *args) -> None: ...
    ...

class BinaryFilterOperatorType:
    """.NET: Tekla.Structures.Filtering.BinaryFilterOperatorType"""
    def __init__(self, *args) -> None: ...
    ...

class BooleanConstantFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.BooleanConstantFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class BooleanFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.BooleanFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class BooleanOperatorType:
    """.NET: Tekla.Structures.Filtering.BooleanOperatorType"""
    def __init__(self, *args) -> None: ...
    ...

class DataFilterExpression(Expression):
    """.NET: Tekla.Structures.Filtering.DataFilterExpression"""
    def __init__(self, *args) -> None: ...
    def ToString(self, ) -> str: ...

class DateTimeConstantFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.DateTimeConstantFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class DateTimeFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.DateTimeFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class DateTimeOperatorType:
    """.NET: Tekla.Structures.Filtering.DateTimeOperatorType"""
    def __init__(self, *args) -> None: ...
    ...

class Expression:
    """.NET: Tekla.Structures.Filtering.Expression"""
    def __init__(self, *args) -> None: ...
    def ToString(self, ) -> str: ...

class Filter:
    """.NET: Tekla.Structures.Filtering.Filter"""
    def __init__(self, *args) -> None: ...
    FilterExpression: FilterExpression
    def CreateFile(self, FilterExpressionFileType: FilterExpressionFileType, FullFileName: str) -> str: ...
    def ToString(self, ) -> str: ...

class FilterExpression(Expression):
    """.NET: Tekla.Structures.Filtering.FilterExpression"""
    def __init__(self, *args) -> None: ...
    IsEnable: bool

class FilterExpressionFileType:
    """.NET: Tekla.Structures.Filtering.FilterExpressionFileType"""
    def __init__(self, *args) -> None: ...
    ...

class InvalidFilterExpressionException(Exception):
    """.NET: Tekla.Structures.Filtering.InvalidFilterExpressionException"""
    def __init__(self, *args) -> None: ...
    Expression: Expression
    InvalidFilterExpressionExceptionReasonsType: InvalidFilterExpressionExceptionReasonsType
    LeftExpression: Expression
    RightExpression: Expression
    OperatorType: OperatorType
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class InvalidFilterExpressionExceptionReasonsType:
    """.NET: Tekla.Structures.Filtering.InvalidFilterExpressionExceptionReasonsType"""
    def __init__(self, *args) -> None: ...
    ...

class NumericConstantFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.NumericConstantFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class NumericFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.NumericFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class NumericOperatorType:
    """.NET: Tekla.Structures.Filtering.NumericOperatorType"""
    def __init__(self, *args) -> None: ...
    ...

class OperatorType:
    """.NET: Tekla.Structures.Filtering.OperatorType"""
    def __init__(self, *args) -> None: ...
    ...

class StringConstantFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.StringConstantFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class StringFilterExpression(DataFilterExpression):
    """.NET: Tekla.Structures.Filtering.StringFilterExpression"""
    def __init__(self, *args) -> None: ...
    ...

class StringOperatorType:
    """.NET: Tekla.Structures.Filtering.StringOperatorType"""
    def __init__(self, *args) -> None: ...
    ...
