# Auto-generated — Tekla 2026 — Tekla.Structures.Filtering.Categories

class AssemblyFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.AssemblyFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class BoltFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.BoltFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class ComponentFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.ComponentFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class ConstructionObjectFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.ConstructionObjectFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class LoadFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.LoadFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class LogicalAreaFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.LogicalAreaFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class ObjectFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.ObjectFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class ObjectTypesFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.ObjectTypesFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class PartFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.PartFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class PourBreakFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class PourObjectFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.PourObjectFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class PourUnitFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class ReferenceObjectFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.ReferenceObjectFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class ReinforcingBarFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.ReinforcingBarFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class SurfaceFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.SurfaceFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class TaskFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.TaskFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class TemplateFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.TemplateFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...

class WeldFilterExpressions:
    """.NET: Tekla.Structures.Filtering.Categories.WeldFilterExpressions"""
    def __init__(self, *args) -> None: ...
    ...
