# Auto-generated — Rhino 8 — Rhino.Render

class AddCustomUISections:
    """.NET: Rhino.Render.AddCustomUISections"""
    def __init__(self, *args) -> None: ...
    ...

class AddCustomUISectionsEventArgs(EventArgs):
    """.NET: Rhino.Render.AddCustomUISectionsEventArgs"""
    def __init__(self, *args) -> None: ...
    ExpandableContentUI: ExpandableContentUI
    EventType: Guid

class AsyncRenderContext:
    """.NET: Rhino.Render.AsyncRenderContext"""
    def __init__(self, *args) -> None: ...
    RenderWindow: RenderWindow
    RenderThread: Thread
    def Dispose(self, ) -> None: ...
    def JoinRenderThread(self, ) -> None: ...
    def StartRenderThread(self, threadStart: ThreadStart, threadName: str) -> bool: ...
    def StopRendering(self, ) -> None: ...

class CachedTextureCoordinates(CommonObject):
    """.NET: Rhino.Render.CachedTextureCoordinates"""
    def __init__(self, *args) -> None: ...
    Dim: int
    MappingId: Guid
    Count: int
    IsReadOnly: bool
    Item: Point3d
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def Contains(self, item: Point3d) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: Point3d) -> int: ...
    def TryGetAt(self, index: int, u: float, v: float, w: float) -> bool: ...

class City:
    """.NET: Rhino.Render.City"""
    def __init__(self, *args) -> None: ...
    Name: str
    Latitude: float
    Longitude: float
    TimeZone: float
    @staticmethod
    def Cities() -> int: ...
    @staticmethod
    def CityAt(index: int) -> City: ...
    @staticmethod
    def FindNearest(latitude: float, longitude: float) -> City: ...

class ComponentOrders:
    """.NET: Rhino.Render.ComponentOrders"""
    def __init__(self, *args) -> None: ...
    ...

class ContentCollectionIterator:
    """.NET: Rhino.Render.ContentCollectionIterator"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def DeleteThis(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def First(self, ) -> RenderContent: ...
    def Next(self, ) -> RenderContent: ...

class ContentUndoBlocker:
    """.NET: Rhino.Render.ContentUndoBlocker"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class ContentUndoHelper:
    """.NET: Rhino.Render.ContentUndoHelper"""
    def __init__(self, *args) -> None: ...
    def AddContent(self, content: RenderContent, parent: RenderContent) -> bool: ...
    def Dispose(self, ) -> None: ...
    def ModifyContent(self, content: RenderContent) -> bool: ...
    def TweakContent(self, content: RenderContent, parameterName: str) -> bool: ...

class ContentUuids:
    """.NET: Rhino.Render.ContentUuids"""
    def __init__(self, *args) -> None: ...
    BasicMaterialType: Guid
    BlendMaterialType: Guid
    CompositeMaterialType: Guid
    PlasterMaterialType: Guid
    MetalMaterialType: Guid
    PaintMaterialType: Guid
    PlasticMaterialType: Guid
    GemMaterialType: Guid
    GlassMaterialType: Guid
    PictureMaterialType: Guid
    DefaultMaterialInstance: Guid
    V8BlendMaterialType: Guid
    PhysicallyBasedMaterialType: Guid
    DoubleSidedMaterialType: Guid
    EmissionMaterialType: Guid
    DisplayAttributeMaterialType: Guid
    RealtimeDisplayMaterialType: Guid
    BasicEnvironmentType: Guid
    DefaultEnvironmentInstance: Guid
    Texture2DCheckerTextureType: Guid
    Texture3DCheckerTextureType: Guid
    AdvancedDotTextureType: Guid
    BitmapTextureType: Guid
    BlendTextureType: Guid
    CubeMapTextureType: Guid
    ExposureTextureType: Guid
    FBmTextureType: Guid
    GradientTextureType: Guid
    GraniteTextureType: Guid
    GridTextureType: Guid
    HDRTextureType: Guid
    EXRTextureType: Guid
    MarbleTextureType: Guid
    MaskTextureType: Guid
    NoiseTextureType: Guid
    PerlinMarbleTextureType: Guid
    PerturbingTextureType: Guid
    ProjectionChangerTextureType: Guid
    ResampleTextureType: Guid
    SingleColorTextureType: Guid
    SimpleBitmapTextureType: Guid
    StuccoTextureType: Guid
    TextureAdjustmentTextureType: Guid
    TileTextureType: Guid
    TurbulenceTextureType: Guid
    WavesTextureType: Guid
    WoodTextureType: Guid
    AddTextureType: Guid
    MultiplyTextureType: Guid
    PhysicalSkyTextureType: Guid
    HatchBumpTexture: Guid
    CrossHatchBumpTexture: Guid
    LeatherBumpTexture: Guid
    WoodBumpTexture: Guid
    SpeckleBumpTexture: Guid
    GritBumpTexture: Guid
    DotBumpTexture: Guid
    BasicMaterialCCI: Guid
    BlendMaterialCCI: Guid
    CompositeMaterialCCI: Guid
    BasicEnvironmentCCI: Guid

class ConvertibleExtensions:
    """.NET: Rhino.Render.ConvertibleExtensions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ToColor4f(variant: IConvertible) -> Color4f: ...
    @staticmethod
    def ToVector2d(variant: IConvertible) -> Vector2d: ...
    @staticmethod
    def ToVector3d(variant: IConvertible) -> Vector3d: ...

class CrcRenderHashFlags:
    """.NET: Rhino.Render.CrcRenderHashFlags"""
    def __init__(self, *args) -> None: ...
    ...

class CreatePreviewEventArgs(EventArgs):
    """.NET: Rhino.Render.CreatePreviewEventArgs"""
    def __init__(self, *args) -> None: ...
    PreviewNotifier: PreviewNotification
    Reason: CreatePreviewReason
    PreviewContent: RenderContent
    PreviewImageSize: Size
    Quality: PreviewSceneQuality
    PreviewImage: Bitmap
    Cancel: bool
    Id: int
    ContentKind: RenderContentKind
    ContentTypeId: Guid
    Environment: RenderEnvironment
    Objects: List
    Lights: List
    Viewport: ViewportInfo
    def SkipInitialisation(self, ) -> None: ...

class CreatePreviewReason:
    """.NET: Rhino.Render.CreatePreviewReason"""
    def __init__(self, *args) -> None: ...
    ...

class CreateTexture2dPreviewEventArgs(EventArgs):
    """.NET: Rhino.Render.CreateTexture2dPreviewEventArgs"""
    def __init__(self, *args) -> None: ...
    PreviewImageSize: Size
    PreviewImage: Bitmap

class CustomRenderContentAttribute(Attribute):
    """.NET: Rhino.Render.CustomRenderContentAttribute"""
    def __init__(self, *args) -> None: ...
    RenderEngineId: Guid
    ImageBased: bool
    IsLinear: bool
    IsHdrCapable: bool
    IsNormalMap: bool
    Category: str
    IsElevated: bool
    IsBuiltIn: bool
    IsPrivate: bool
    TypeId: object

class CustomRenderMeshProvider:
    """.NET: Rhino.Render.CustomRenderMeshProvider"""
    def __init__(self, *args) -> None: ...
    EdgeSofteningId: Guid
    DisplacementId: Guid
    CurvePipingId: Guid
    ShutLiningId: Guid
    ThickeningId: Guid
    Name: str
    @staticmethod
    def AllObjectsChanged(doc: RhinoDoc) -> None: ...
    def BoundingBox(self, vp: ViewportInfo, obj: RhinoObject, doc: RhinoDoc, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> BoundingBox: ...
    def BuildCustomMeshes(self, vp: ViewportInfo, objMeshes: RenderPrimitiveList, requestingPlugIn: Guid, meshType: bool) -> bool: ...
    @staticmethod
    def DocumentBasedMeshesChanged(doc: RhinoDoc) -> None: ...
    @staticmethod
    def ObjectChanged(doc: RhinoDoc, obj: RhinoObject) -> None: ...
    @staticmethod
    def RegisterProviders(assembly: Assembly, pluginId: Guid) -> None: ...
    def WillBuildCustomMeshes(self, vp: ViewportInfo, obj: RhinoObject, requestingPlugIn: Guid, preview: bool) -> bool: ...

class CustomRenderMeshProvider2(CustomRenderMeshProvider):
    """.NET: Rhino.Render.CustomRenderMeshProvider2"""
    def __init__(self, *args) -> None: ...
    Name: str
    def BoundingBox(self, vp: ViewportInfo, obj: RhinoObject, doc: RhinoDoc, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> BoundingBox: ...
    def BuildCustomMeshes(self, vp: ViewportInfo, doc: RhinoDoc, objMeshes: RenderPrimitiveList, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> bool: ...
    def WillBuildCustomMeshes(self, vp: ViewportInfo, obj: RhinoObject, doc: RhinoDoc, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> bool: ...

class Decal:
    """.NET: Rhino.Render.Decal"""
    def __init__(self, *args) -> None: ...
    CRC: int
    TextureInstanceId: Guid
    DecalMapping: DecalMapping
    Mapping: DecalMapping
    DecalProjection: DecalProjection
    Projection: DecalProjection
    MapToInside: bool
    Transparency: float
    IsVisible: bool
    Origin: Point3d
    VectorUp: Vector3d
    VectorAcross: Vector3d
    Height: float
    Radius: float
    StartLatitude: float
    EndLatitude: float
    StartLongitude: float
    EndLongitude: float
    def ConstPointer(self, ) -> IntPtr: ...
    @staticmethod
    def Create(createParams: DecalCreateParams) -> Decal: ...
    def CustomData(self, renderer: Guid) -> List: ...
    def Dispose(self, isDisposing: bool) -> None: ...
    def GetTextureMapping(self, ) -> TextureMapping: ...
    def GetUVBounds(self, min_u: float, min_v: float, max_u: float, max_v: float) -> None: ...
    def HorzSweep(self, sta: float, end: float) -> None: ...
    def NonConstPointer(self, ) -> IntPtr: ...
    def TextureRenderCRC(self, rh: TextureRenderHashFlags, lw: LinearWorkflow) -> int: ...
    def TextureRenderHash(self, flags: CrcRenderHashFlags, lw: LinearWorkflow) -> int: ...
    def TryGetColor(self, point: Point3d, normal: Vector3d, colInOut: Color4f, uvOut: Point2d) -> bool: ...
    def UVBounds(self, minUOut: float, minVOut: float, maxUOut: float, maxVOut: float) -> None: ...
    def VertSweep(self, sta: float, end: float) -> None: ...

class DecalCreateParams:
    """.NET: Rhino.Render.DecalCreateParams"""
    def __init__(self, *args) -> None: ...
    TextureInstanceId: Guid
    DecalMapping: DecalMapping
    DecalProjection: DecalProjection
    MapToInside: bool
    Transparency: float
    Origin: Point3d
    VectorUp: Vector3d
    VectorAcross: Vector3d
    Height: float
    Radius: float
    StartLatitude: float
    EndLatitude: float
    StartLongitude: float
    EndLongitude: float
    MinU: float
    MinV: float
    MaxU: float
    MaxV: float

class DecalMapping:
    """.NET: Rhino.Render.DecalMapping"""
    def __init__(self, *args) -> None: ...
    ...

class DecalProjection:
    """.NET: Rhino.Render.DecalProjection"""
    def __init__(self, *args) -> None: ...
    ...

class Decals:
    """.NET: Rhino.Render.Decals"""
    def __init__(self, *args) -> None: ...
    def Add(self, decal: Decal) -> int: ...
    def Clear(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, decal: Decal) -> bool: ...
    def RemoveAllDecals(self, ) -> None: ...

class Dithering(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.Dithering"""
    def __init__(self, *args) -> None: ...
    Method: Methods
    On: bool
    Enabled: bool
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...

class DocumentOrFreeFloatingBase(FreeFloatingBase):
    """.NET: Rhino.Render.DocumentOrFreeFloatingBase"""
    def __init__(self, *args) -> None: ...
    def BeginChange(self, cc: ChangeContexts) -> None: ...
    def EndChange(self, ) -> bool: ...

class DynamicIconUsage:
    """.NET: Rhino.Render.DynamicIconUsage"""
    def __init__(self, *args) -> None: ...
    ...

class ExtensionMethods:
    """.NET: Rhino.Render.ExtensionMethods"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ToEnvironmentMappingMode(e: EnvironmentMappingModes) -> TextureEnvironmentMappingMode: ...
    @staticmethod
    def ToSimulatedEnvironmentMappingMode(e: TextureEnvironmentMappingMode) -> EnvironmentMappingModes: ...
    @staticmethod
    def ToSimulatedTextureProjectionMode(e: TextureProjectionMode) -> ProjectionModes: ...
    @staticmethod
    def ToTextureProjectionMode(e: ProjectionModes) -> TextureProjectionMode: ...

class FilterContentByUsage:
    """.NET: Rhino.Render.FilterContentByUsage"""
    def __init__(self, *args) -> None: ...
    ...

class FreeFloatingBase:
    """.NET: Rhino.Render.FreeFloatingBase"""
    def __init__(self, *args) -> None: ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...

class GroundPlane(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.GroundPlane"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    ShadowOnly: bool
    AutoAltitude: bool
    ShowUnderside: bool
    Altitude: float
    MaterialInstanceId: Guid
    TextureOffset: Vector2d
    TextureSize: Vector2d
    TextureRotation: float
    TextureSizeLocked: bool
    TextureOffsetLocked: bool
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...

class ICurrentEnvironment:
    """.NET: Rhino.Render.ICurrentEnvironment"""
    def __init__(self, *args) -> None: ...
    ForBackground: RenderEnvironment
    ForBackground_CheckMode: RenderEnvironment
    ForLighting: RenderEnvironment
    ForReflectionAndRefraction: RenderEnvironment
    ForAnyUsage: RenderEnvironment

class ICurrentEnvironment_Get:
    """.NET: Rhino.Render.ICurrentEnvironment_Get"""
    def __init__(self, *args) -> None: ...
    ForBackground: RenderEnvironment
    ForBackground_CheckMode: RenderEnvironment
    ForLighting: RenderEnvironment
    ForReflectionAndRefraction: RenderEnvironment

class IRhRdkPreviewSceneServer_eRotationType:
    """.NET: Rhino.Render.IRhRdkPreviewSceneServer_eRotationType"""
    def __init__(self, *args) -> None: ...
    ...

class ImageFile:
    """.NET: Rhino.Render.ImageFile"""
    def __init__(self, *args) -> None: ...
    ...

class ImageFileEvent:
    """.NET: Rhino.Render.ImageFileEvent"""
    def __init__(self, *args) -> None: ...
    ...

class ImageFileEventArgs(EventArgs):
    """.NET: Rhino.Render.ImageFileEventArgs"""
    def __init__(self, *args) -> None: ...
    Event: ImageFileEvent
    FileName: str
    RenderEngine: str
    RenderEngineId: Guid
    SessionId: Guid
    EllapsedTime: int

class LightArray:
    """.NET: Rhino.Render.LightArray"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Append(self, light: Light) -> None: ...
    def Count(self, ) -> int: ...
    def Dispose(self, ) -> None: ...
    def ElementAt(self, index: int) -> Light: ...

class LightManagerSupport:
    """.NET: Rhino.Render.LightManagerSupport"""
    def __init__(self, *args) -> None: ...
    def DeleteLight(self, doc: RhinoDoc, light: Light, bUndelete: bool) -> bool: ...
    def GetLightSolo(self, doc: RhinoDoc, uuid_light: Guid) -> bool: ...
    def GetLights(self, doc: RhinoDoc, light_array: LightArray) -> None: ...
    def GroupLights(self, doc: RhinoDoc, light_array: LightArray) -> None: ...
    def LightDescription(self, doc: RhinoDoc, light: Light) -> str: ...
    def LightFromId(self, doc: RhinoDoc, uuid: Guid, light: Light) -> bool: ...
    def LightsInSoloStorage(self, doc: RhinoDoc) -> int: ...
    def ModifyLight(self, doc: RhinoDoc, light: Light) -> None: ...
    def ObjectSerialNumberFromLight(self, doc: RhinoDoc, light: Light) -> int: ...
    def OnCustomLightEvent(self, doc: RhinoDoc, le: LightMangerSupportCustomEvent, light: Light) -> None: ...
    def OnEditLight(self, doc: RhinoDoc, light_array: LightArray) -> bool: ...
    def PluginId(self, ) -> Guid: ...
    @staticmethod
    def RegisterLightManager(plugin: PlugIn) -> None: ...
    @staticmethod
    def RegisterProviders(assembly: Assembly, pluginId: Guid) -> None: ...
    def RenderEngineId(self, ) -> Guid: ...
    def SetLightSolo(self, doc: RhinoDoc, uuid_light: Guid, bSolo: bool) -> bool: ...
    def UnGroup(self, doc: RhinoDoc, light_array: LightArray) -> None: ...

class LightManagerSupportClient:
    """.NET: Rhino.Render.LightManagerSupportClient"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def DeleteLight(self, light: Light) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetLightFromId(self, uuid: Guid) -> Light: ...
    def GetLightSolo(self, light: Light) -> bool: ...
    def GetLights(self, ) -> LightArray: ...
    def GroupLights(self, lights: LightArray) -> None: ...
    def LightDescription(self, light: Light) -> str: ...
    def LightsInSoloStorage(self, ) -> int: ...
    def ModifyLight(self, light: Light) -> None: ...
    def ObjectFromLight(self, light: Light) -> RhinoObject: ...
    def OnEditLight(self, lights: LightArray) -> None: ...
    def SetLightSolo(self, light: Light, bSolo: bool) -> bool: ...
    def UnGroup(self, lights: LightArray) -> None: ...

class LightMangerSupportCustomEvent:
    """.NET: Rhino.Render.LightMangerSupportCustomEvent"""
    def __init__(self, *args) -> None: ...
    ...

class LinearWorkflow(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.LinearWorkflow"""
    def __init__(self, *args) -> None: ...
    PreProcessColors: bool
    PreProcessTextures: bool
    PostProcessFrameBuffer: bool
    PreProcessGamma: float
    PostProcessGamma: float
    PostProcessGammaOn: bool
    PostProcessGammaReciprocal: float
    Hash: int
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...

class MappingTag:
    """.NET: Rhino.Render.MappingTag"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    MappingType: TextureMappingType
    MappingCRC: int
    MeshTransform: Transform

class MetaDataProxy:
    """.NET: Rhino.Render.MetaDataProxy"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Dispose(self, ) -> None: ...
    def SetContentInstanceId(self, uuid: Guid) -> None: ...

class NamedValue:
    """.NET: Rhino.Render.NamedValue"""
    def __init__(self, *args) -> None: ...
    Name: str
    Value: object

class PhysicallyBasedMaterial:
    """.NET: Rhino.Render.PhysicallyBasedMaterial"""
    def __init__(self, *args) -> None: ...
    ...

class PixelBuffer:
    """.NET: Rhino.Render.PixelBuffer"""
    def __init__(self, *args) -> None: ...
    Buffer: IntPtr

class PreviewAppearance:
    """.NET: Rhino.Render.PreviewAppearance"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    MetaData: MetaData
    Scale: float
    SceneScale: float
    def Background(self, ) -> PreviewBackground: ...
    def Dispose(self, ) -> None: ...
    def FromMetaData(self, md: MetaData) -> None: ...
    def Geometry(self, ) -> PreviewGeometry: ...
    def Lighting(self, ) -> PreviewLighting: ...
    def RotationType(self, ) -> IRhRdkPreviewSceneServer_eRotationType: ...
    def RotationX(self, ) -> float: ...
    def RotationY(self, ) -> float: ...
    def SetRotationType(self, type: IRhRdkPreviewSceneServer_eRotationType) -> None: ...
    def SetRotationX(self, d: float) -> None: ...
    def SetRotationY(self, d: float) -> None: ...
    def SetSize(self, d: float) -> None: ...
    def Size(self, ) -> float: ...
    def ToMetaData(self, mdp: MetaDataProxy) -> None: ...

class PreviewBackground:
    """.NET: Rhino.Render.PreviewBackground"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ElementKind(self, ) -> str: ...
    def EnvironmentInstanceId(self, ) -> Guid: ...
    def SetEnvironmentInstanceId(self, guid: Guid) -> None: ...
    def SetUpPreview(self, sceneServerPointer: IntPtr, guid: Guid) -> None: ...

class PreviewGeometry:
    """.NET: Rhino.Render.PreviewGeometry"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ElementKind(self, ) -> str: ...
    def SetUpPreview(self, sceneServerPointer: IntPtr, pRenderContent: IntPtr, bCopy: bool) -> None: ...

class PreviewJobSignature:
    """.NET: Rhino.Render.PreviewJobSignature"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Compare(self, pjs: PreviewJobSignature) -> bool: ...
    def Dispose(self, ) -> None: ...
    def ImageHeight(self, ) -> int: ...
    def ImageWidth(self, ) -> int: ...

class PreviewLighting:
    """.NET: Rhino.Render.PreviewLighting"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ElementKind(self, ) -> str: ...
    def SetUpPreview(self, sceneServerPointer: IntPtr) -> None: ...

class PreviewRenderedEventArgs(EventArgs):
    """.NET: Rhino.Render.PreviewRenderedEventArgs"""
    def __init__(self, *args) -> None: ...
    PreviewJobSignature: PreviewJobSignature
    Bitmap: Bitmap
    Quality: PreviewQuality

class PreviewSceneQuality:
    """.NET: Rhino.Render.PreviewSceneQuality"""
    def __init__(self, *args) -> None: ...
    ...

class PreviewSceneServer:
    """.NET: Rhino.Render.PreviewSceneServer"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ApplyRotation(self, X: float, Y: float, type: IRhRdkPreviewSceneServer_eRotationType) -> None: ...
    def Dispose(self, ) -> None: ...
    def SetSceneScale(self, scale: float) -> None: ...

class Projection:
    """.NET: Rhino.Render.Projection"""
    def __init__(self, *args) -> None: ...
    ...

class ProxyTypes:
    """.NET: Rhino.Render.ProxyTypes"""
    def __init__(self, *args) -> None: ...
    ...

class RdkUndo:
    """.NET: Rhino.Render.RdkUndo"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def NewUndoRecord(self, ) -> RdkUndoRecord: ...

class RdkUndoRecord:
    """.NET: Rhino.Render.RdkUndoRecord"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def SetDescription(self, description: str) -> None: ...

class RealtimeDisplayMode:
    """.NET: Rhino.Render.RealtimeDisplayMode"""
    def __init__(self, *args) -> None: ...
    LinearWorkflow: LinearWorkflow
    Paused: bool
    Locked: bool
    PostEffectsOn: bool
    MaxPasses: int
    def CaptureProgress(self, ) -> float: ...
    def ComputeViewportCrc(self, view: ViewInfo) -> int: ...
    def CreateWorld(self, doc: RhinoDoc, viewInfo: ViewInfo, displayPipelineAttributes: DisplayPipelineAttributes) -> None: ...
    def DrawOpenGl(self, ) -> bool: ...
    @staticmethod
    def GetRealtimeViewport(realtimeViewport: IntPtr, create: bool) -> RealtimeDisplayMode: ...
    def GetRenderSize(self, width: int, height: int) -> None: ...
    def GetView(self, ) -> ViewInfo: ...
    def HudAllowEditMaxPasses(self, ) -> bool: ...
    def HudCustomStatusText(self, ) -> str: ...
    def HudLastRenderedPass(self, ) -> int: ...
    def HudMaximumPasses(self, ) -> int: ...
    def HudProductName(self, ) -> str: ...
    def HudRendererLocked(self, ) -> bool: ...
    def HudRendererPaused(self, ) -> bool: ...
    def HudShow(self, ) -> bool: ...
    def HudShowControls(self, ) -> bool: ...
    def HudShowCustomStatusText(self, ) -> bool: ...
    def HudShowMaxPasses(self, ) -> bool: ...
    def HudShowPasses(self, ) -> bool: ...
    def HudStartTime(self, ) -> DateTime: ...
    def IsCompleted(self, ) -> bool: ...
    def IsFrameBufferAvailable(self, view: ViewInfo) -> bool: ...
    def IsRendererStarted(self, ) -> bool: ...
    def LastRenderedPass(self, ) -> int: ...
    def OnRenderSizeChanged(self, width: int, height: int) -> bool: ...
    def OpenGlVersion(self, ) -> int: ...
    def PostConstruct(self, ) -> None: ...
    @staticmethod
    def RegisterDisplayModes(assembly: Assembly, pluginId: Guid) -> list: ...
    @staticmethod
    def RemoveRealtimeViewport(realtimeViewport: IntPtr) -> None: ...
    def SetUseDrawOpenGl(self, use: bool) -> None: ...
    def SetView(self, view: ViewInfo) -> None: ...
    def ShowCaptureProgress(self, ) -> bool: ...
    def ShutdownRenderer(self, ) -> None: ...
    def SignalRedraw(self, ) -> None: ...
    def StartRenderer(self, w: int, h: int, doc: RhinoDoc, view: ViewInfo, viewportInfo: ViewportInfo, forCapture: bool, renderWindow: RenderWindow) -> bool: ...
    @staticmethod
    def UnregisterDisplayModes(assembly: Assembly, pluginId: Guid) -> None: ...
    def UseFastDraw(self, ) -> bool: ...

class RealtimeDisplayModeClassInfo:
    """.NET: Rhino.Render.RealtimeDisplayModeClassInfo"""
    def __init__(self, *args) -> None: ...
    Name: str
    GUID: Guid
    DrawOpenGl: bool
    RealtimeDisplayModeType: Type
    DontRegisterAttributesOnStart: bool
    RequiredDisplayTechnology: DisplayTechnology

class RenderChannels(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.RenderChannels"""
    def __init__(self, *args) -> None: ...
    Mode: Modes
    CustomList: list
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...

class RenderContent:
    """.NET: Rhino.Render.RenderContent"""
    def __init__(self, *args) -> None: ...
    Fields: FieldDictionary
    CppPointer: IntPtr
    TypeName: str
    TypeDescription: str
    DisplayName: str
    Name: str
    Notes: str
    Tags: str
    ChildSlotDisplayName: str
    Category: str
    Id: Guid
    TypeId: Guid
    GroupId: Guid
    RenderHash: int
    TopLevel: bool
    Hidden: bool
    IsHiddenByAutoDelete: bool
    CanBeEdited: bool
    IsDefaultInstance: bool
    ProxyType: ProxyTypes
    Parent: RenderContent
    FirstChild: RenderContent
    NextSibling: RenderContent
    TopLevelParent: RenderContent
    Document: RhinoDoc
    DocumentOwner: RhinoDoc
    DocumentRegistered: RhinoDoc
    DocumentAssoc: RhinoDoc
    Xml: str
    IsLocked: bool
    ChildSlotName: str
    FilesToEmbed: IEnumerable
    Filename: str
    Styles: RenderContentStyles
    def AddAutomaticUserInterfaceSection(self, caption: str, id: int) -> bool: ...
    def AddChild(self, renderContent: RenderContent, childSlotName: str) -> bool: ...
    @staticmethod
    def AddPersistentRenderContent(document: RhinoDoc, renderContent: RenderContent) -> bool: ...
    def AddUserInterfaceSection(self, classType: Type, caption: str, createExpanded: bool, createVisible: bool) -> UserInterfaceSection: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def BeginCreateDynamicFields(self, automatic: bool) -> None: ...
    def BindParameterToField(self, parameterName: str, childSlotName: str, field: Field, setEvent: ChangeContexts) -> None: ...
    def ChangeChild(self, oldContent: RenderContent, newContent: RenderContent) -> bool: ...
    def ChildSlotAmount(self, childSlotName: str) -> float: ...
    def ChildSlotNameFromParamName(self, paramName: str) -> str: ...
    def ChildSlotOn(self, childSlotName: str) -> bool: ...
    def ConvertUnits(self, from_: UnitSystem, to: UnitSystem) -> None: ...
    @staticmethod
    def Create(type: Guid, parent: RenderContent, childSlotName: str, flags: ShowContentChooserFlags, doc: RhinoDoc) -> RenderContent: ...
    def CreateDynamicField(self, internalName: str, localName: str, englishName: str, value: object, minValue: object, maxValue: object, sectionId: int) -> bool: ...
    def DeleteAllChildren(self, changeContexts: ChangeContexts) -> None: ...
    def DeleteChild(self, childSlotName: str, changeContexts: ChangeContexts) -> bool: ...
    def Dispose(self, ) -> None: ...
    def DynamicIcon(self, size: Size, bitmap: Bitmap, usage: DynamicIconUsage) -> bool: ...
    def Edit(self, ) -> RenderContent: ...
    def EndChange(self, ) -> None: ...
    def EndCreateDynamicFields(self, ) -> None: ...
    def Factory(self, ) -> ContentFactory: ...
    def FindChild(self, childSlotName: str) -> RenderContent: ...
    def ForDisplay(self, ) -> RenderContent: ...
    @staticmethod
    def FromId(document: RhinoDoc, id: Guid) -> RenderContent: ...
    @staticmethod
    def FromXml(xml: str, doc: RhinoDoc) -> RenderContent: ...
    @staticmethod
    def GenerateQuickContentPreview(lw: LinearWorkflow, c: RenderContent, width: int, height: int, psc: PreviewSceneServer, bSuppressLocalMapping: bool, reason: int, result: Result) -> Bitmap: ...
    @staticmethod
    def GenerateRenderContentPreview(lwf: LinearWorkflow, c: RenderContent, width: int, height: int, bSuppressLocalMapping: bool, pjs: PreviewJobSignature, pa: PreviewAppearance, result: PreviewRenderResult) -> Bitmap: ...
    def GetChildSlotParameter(self, contentParameterName: str, extraRequirementParameter: str) -> object: ...
    def GetEmbeddedFilesList(self, ) -> list: ...
    def GetExtraRequirementParameter(self, contentParameterName: str, extraRequirementParameter: str) -> object: ...
    def GetParameter(self, parameterName: str) -> object: ...
    def GetUiHash(self, ) -> int: ...
    def GetUnderlyingInstances(self, collection: RenderContentCollection) -> bool: ...
    def Icon(self, size: Size, bitmap: Bitmap) -> bool: ...
    def Initialize(self, ) -> bool: ...
    def IsCompatible(self, renderEngineId: Guid) -> bool: ...
    def IsContentTypeAcceptableAsChild(self, type: Guid, childSlotName: str) -> bool: ...
    def IsFactoryProductAcceptableAsChild(self, kindId: Guid, factoryKind: str, childSlotName: str) -> bool: ...
    def IsReference(self, ) -> bool: ...
    def IsRenderHashCached(self, ) -> bool: ...
    @staticmethod
    def LoadFromFile(filename: str) -> RenderContent: ...
    def MakeCopy(self, ) -> RenderContent: ...
    def MakeGroupInstance(self, ) -> RenderContent: ...
    def MatchData(self, oldContent: RenderContent) -> MatchDataResult: ...
    def NewPreviewSceneServer(self, ssd: SceneServerData) -> PreviewSceneServer: ...
    def OpenInEditor(self, ) -> bool: ...
    def OpenInModalEditor(self, ) -> bool: ...
    def ParamNameFromChildSlotName(self, childSlotName: str) -> str: ...
    @staticmethod
    def RegisterContent(assembly: Assembly, pluginId: Guid) -> list: ...
    def RenderHashExclude(self, flags: CrcRenderHashFlags, excludeParameterNames: str, lw: LinearWorkflow) -> int: ...
    def Replace(self, newcontent: RenderContent) -> bool: ...
    def SaveToFile(self, filename: str, embedFilesChoice: EmbedFilesChoice) -> bool: ...
    def SetChild(self, renderContent: RenderContent, childSlotName: str, changeContexts: ChangeContexts) -> bool: ...
    def SetChildSlotAmount(self, childSlotName: str, amount: float, cc: ChangeContexts) -> None: ...
    def SetChildSlotOn(self, childSlotName: str, bOn: bool, cc: ChangeContexts) -> None: ...
    def SetChildSlotParameter(self, contentParameterName: str, extraRequirementParameter: str, value: object, sc: ExtraRequirementsSetContexts) -> bool: ...
    def SetExtraRequirementParameter(self, contentParameterName: str, extraRequirementParameter: str, value: object, sc: ExtraRequirementsSetContexts) -> bool: ...
    def SetIsRenderHashRecursive(self, recursive: bool) -> None: ...
    def SetName(self, name: str, renameEvents: bool, ensureNameUnique: bool) -> None: ...
    def SetParameter(self, parameterName: str, value: object, changeContext: ChangeContexts) -> bool: ...
    def SetRenderHash(self, hash: int) -> None: ...
    @staticmethod
    def ShowContentInstanceBrowser(doc: RhinoDoc, instance_id: Guid, kinds: RenderContentKind, buttons: ContentInstanceBrowserButtons) -> bool: ...
    def SmartUngroupRecursive(self, ) -> bool: ...
    def Ungroup(self, ) -> bool: ...
    def UngroupRecursive(self, ) -> bool: ...
    def Uninitialize(self, ) -> None: ...
    def UseCount(self, ) -> int: ...
    def VirtualIcon(self, size: Size, bitmap: Bitmap) -> bool: ...

class RenderContentChangeReason:
    """.NET: Rhino.Render.RenderContentChangeReason"""
    def __init__(self, *args) -> None: ...
    ...

class RenderContentChangedEventArgs(RenderContentEventArgs):
    """.NET: Rhino.Render.RenderContentChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    ChangeContext: ChangeContexts
    OldContent: RenderContent
    Content: RenderContent
    Document: RhinoDoc
    Reason: RenderContentChangeReason
    EnvironmentUsage: Usage
    EnvironmentUsageEx: EnvironmentUsage

class RenderContentCollection:
    """.NET: Rhino.Render.RenderContentCollection"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Add(self, collection: RenderContentCollection) -> None: ...
    def Append(self, content: RenderContent) -> None: ...
    def Clear(self, ) -> None: ...
    def ContentAt(self, index: int) -> RenderContent: ...
    def ContentNeedsPreviewThumbnail(self, c: RenderContent, includeChildren: bool) -> bool: ...
    def Count(self, ) -> int: ...
    def Dispose(self, ) -> None: ...
    def Find_Sel(self, uuid: Guid) -> RenderContent: ...
    def FirstTag(self, ) -> str: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetFilterContentByUsage(self, ) -> FilterContentByUsage: ...
    def GetForcedVaries(self, ) -> bool: ...
    def GetSearchPattern(self, ) -> str: ...
    def Iterator(self, ) -> ContentCollectionIterator: ...
    def NextTag(self, ) -> str: ...
    def Remove(self, collection: RenderContentCollection) -> None: ...
    def Set(self, collection: RenderContentCollection) -> None: ...
    def SetForcedVaries(self, b: bool) -> None: ...
    def SetSearchPattern(self, pattern: str) -> None: ...

class RenderContentEventArgs(EventArgs):
    """.NET: Rhino.Render.RenderContentEventArgs"""
    def __init__(self, *args) -> None: ...
    Content: RenderContent
    Document: RhinoDoc
    Reason: RenderContentChangeReason
    EnvironmentUsage: Usage
    EnvironmentUsageEx: EnvironmentUsage

class RenderContentFieldChangedEventArgs(RenderContentChangedEventArgs):
    """.NET: Rhino.Render.RenderContentFieldChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    FieldName: str
    ChangeContext: ChangeContexts
    OldContent: RenderContent
    Content: RenderContent
    Document: RhinoDoc
    Reason: RenderContentChangeReason
    EnvironmentUsage: Usage
    EnvironmentUsageEx: EnvironmentUsage

class RenderContentKind:
    """.NET: Rhino.Render.RenderContentKind"""
    def __init__(self, *args) -> None: ...
    ...

class RenderContentKindList:
    """.NET: Rhino.Render.RenderContentKindList"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Add(self, kind: RenderContentKind) -> None: ...
    def Contains(self, kind: RenderContentKind) -> bool: ...
    def Count(self, ) -> int: ...
    def Dispose(self, ) -> None: ...
    def SingleKind(self, ) -> RenderContentKind: ...

class RenderContentManager:
    """.NET: Rhino.Render.RenderContentManager"""
    def __init__(self, *args) -> None: ...
    UserRenderContentPath: str
    @staticmethod
    def RestoreRenderContent() -> bool: ...

class RenderContentSerializer:
    """.NET: Rhino.Render.RenderContentSerializer"""
    def __init__(self, *args) -> None: ...
    FileExtension: str
    ContentType: RenderContentKind
    ContentKind: RenderContentKind
    CanRead: bool
    CanWrite: bool
    EnglishDescription: str
    LocalDescription: str
    def CanLoadMultiple(self, ) -> bool: ...
    def LoadMultiple(self, doc: RhinoDoc, fileNames: IEnumerable, contentKind: RenderContentKind, flags: LoadMultipleFlags) -> bool: ...
    def Read(self, pathToFile: str) -> RenderContent: ...
    def RegisterSerializer(self, id: Guid) -> bool: ...
    def ReportContentAndFile(self, renderContent: RenderContent, pathToFile: str, flags: int) -> None: ...
    def ReportDeferredContentAndFile(self, renderContent: RenderContent, pathToFile: str, flags: int) -> None: ...
    def Write(self, pathToFile: str, renderContent: RenderContent, previewArgs: CreatePreviewEventArgs) -> bool: ...

class RenderContentStyles:
    """.NET: Rhino.Render.RenderContentStyles"""
    def __init__(self, *args) -> None: ...
    ...

class RenderContentType:
    """.NET: Rhino.Render.RenderContentType"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    InternalName: str
    RenderEngineId: Guid
    PlugInId: Guid
    def Dispose(self, ) -> None: ...
    @staticmethod
    def GetAllAvailableTypes() -> list: ...
    @staticmethod
    def NewContentFromTypeId(typeId: Guid, doc: RhinoDoc) -> RenderContent: ...
    def NewRenderContent(self, ) -> RenderContent: ...

class RenderEndEventArgs(EventArgs):
    """.NET: Rhino.Render.RenderEndEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class RenderEnvironment(RenderContent):
    """.NET: Rhino.Render.RenderEnvironment"""
    def __init__(self, *args) -> None: ...
    CurrentEnvironment: RenderEnvironment
    TextureChildSlotName: str
    Fields: FieldDictionary
    CppPointer: IntPtr
    TypeName: str
    TypeDescription: str
    DisplayName: str
    Name: str
    Notes: str
    Tags: str
    ChildSlotDisplayName: str
    Category: str
    Id: Guid
    TypeId: Guid
    GroupId: Guid
    RenderHash: int
    TopLevel: bool
    Hidden: bool
    IsHiddenByAutoDelete: bool
    CanBeEdited: bool
    IsDefaultInstance: bool
    ProxyType: ProxyTypes
    Parent: RenderContent
    FirstChild: RenderContent
    NextSibling: RenderContent
    TopLevelParent: RenderContent
    Document: RhinoDoc
    DocumentOwner: RhinoDoc
    DocumentRegistered: RhinoDoc
    DocumentAssoc: RhinoDoc
    Xml: str
    IsLocked: bool
    ChildSlotName: str
    FilesToEmbed: IEnumerable
    Filename: str
    Styles: RenderContentStyles
    @staticmethod
    def NewBasicEnvironment(environment: SimulatedEnvironment, doc: RhinoDoc) -> RenderEnvironment: ...
    def SimulateEnvironment(self, simulation: SimulatedEnvironment, isForDataOnly: bool) -> None: ...

class RenderEnvironmentTable:
    """.NET: Rhino.Render.RenderEnvironmentTable"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: RenderEnvironment
    def Add(self, c: RenderEnvironment) -> bool: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self, ) -> None: ...
    def Find(self, id: Guid) -> RenderEnvironment: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, c: RenderEnvironment) -> bool: ...

class RenderMaterial(RenderContent):
    """.NET: Rhino.Render.RenderMaterial"""
    def __init__(self, *args) -> None: ...
    PlasterMaterialGuid: Guid
    PlasticMaterialGuid: Guid
    PaintMaterialGuid: Guid
    GlassMaterialGuid: Guid
    GemMaterialGuid: Guid
    MetalMaterialGuid: Guid
    PictureMaterialGuid: Guid
    DefaultPreviewGeometryType: PreviewGeometryType
    DefaultPreviewBackgroundType: PreviewBackgroundType
    DefaultPreviewSize: float
    SmellsLikePlaster: bool
    SmellsLikePaint: bool
    SmellsLikeMetal: bool
    SmellsLikePlastic: bool
    SmellsLikeGem: bool
    SmellsLikeGlass: bool
    SmellsLikeTexturedPlaster: bool
    SmellsLikeTexturedPaint: bool
    SmellsLikeTexturedMetal: bool
    SmellsLikeTexturedPlastic: bool
    SmellsLikeTexturedGem: bool
    SmellsLikeTexturedGlass: bool
    Fields: FieldDictionary
    CppPointer: IntPtr
    TypeName: str
    TypeDescription: str
    DisplayName: str
    Name: str
    Notes: str
    Tags: str
    ChildSlotDisplayName: str
    Category: str
    Id: Guid
    TypeId: Guid
    GroupId: Guid
    RenderHash: int
    TopLevel: bool
    Hidden: bool
    IsHiddenByAutoDelete: bool
    CanBeEdited: bool
    IsDefaultInstance: bool
    ProxyType: ProxyTypes
    Parent: RenderContent
    FirstChild: RenderContent
    NextSibling: RenderContent
    TopLevelParent: RenderContent
    Document: RhinoDoc
    DocumentOwner: RhinoDoc
    DocumentRegistered: RhinoDoc
    DocumentAssoc: RhinoDoc
    Xml: str
    IsLocked: bool
    ChildSlotName: str
    FilesToEmbed: IEnumerable
    Filename: str
    Styles: RenderContentStyles
    def AssignTo(self, objrefs: IEnumerable, sfc: AssignToSubFaceChoices, bc: AssignToBlockChoices, bInteractive: bool) -> bool: ...
    def ConvertToPhysicallyBased(self, tg: TextureGeneration) -> PhysicallyBasedMaterial: ...
    @staticmethod
    def CreateBasicMaterial(material: Material, doc: RhinoDoc) -> RenderMaterial: ...
    @staticmethod
    def CreateImportedMaterial(material: Material, doc: RhinoDoc, reference: bool) -> RenderMaterial: ...
    @staticmethod
    def FromMaterial(material: Material, doc: RhinoDoc) -> RenderMaterial: ...
    def GetTextureAmountFromUsage(self, slot: StandardChildSlots) -> float: ...
    def GetTextureFromUsage(self, slot: StandardChildSlots) -> RenderTexture: ...
    def GetTextureOnFromUsage(self, slot: StandardChildSlots) -> bool: ...
    def HandleTexturedValue(self, slotname: str, tc: TexturedValue) -> bool: ...
    @staticmethod
    def ImportMaterialAndAssignToLayers(doc: RhinoDoc, file: str, layer_indices: IEnumerable) -> bool: ...
    def SimulateMaterial(self, simulation: Material, tg: TextureGeneration) -> None: ...
    def SimulatedMaterial(self, tg: TextureGeneration) -> Material: ...
    @staticmethod
    def SlotFromTextureType(tt: TextureType) -> StandardChildSlots: ...
    def TextureChildSlotName(self, slot: StandardChildSlots) -> str: ...
    @staticmethod
    def TextureTypeFromSlot(slot: StandardChildSlots) -> TextureType: ...
    def ToMaterial(self, tg: TextureGeneration) -> Material: ...

class RenderMaterialTable:
    """.NET: Rhino.Render.RenderMaterialTable"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: RenderMaterial
    def Add(self, c: RenderMaterial) -> bool: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self, ) -> None: ...
    def Find(self, id: Guid) -> RenderMaterial: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, c: RenderMaterial) -> bool: ...

class RenderPanelType:
    """.NET: Rhino.Render.RenderPanelType"""
    def __init__(self, *args) -> None: ...
    ...

class RenderPanels:
    """.NET: Rhino.Render.RenderPanels"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def FromRenderSessionId(plugIn: PlugIn, panelType: Type, renderSessionId: Guid) -> object: ...
    def RegisterPanel(self, plugin: PlugIn, renderPanelType: RenderPanelType, panelType: Type, renderEngineId: Guid, caption: str, alwaysShow: bool, initialShow: bool, pos: ExtraSidePanePosition) -> None: ...

class RenderPipeline:
    """.NET: Rhino.Render.RenderPipeline"""
    def __init__(self, *args) -> None: ...
    RenderSessionId: Guid
    ConfirmationSeconds: int
    PlugIn: PlugIn
    def CloseWindow(self, ) -> bool: ...
    def CommandResult(self, ) -> Result: ...
    def Dispose(self, ) -> None: ...
    def GetRenderWindow(self, viewportInfo: ViewportInfo, fromRenderViewSource: bool, region: Rectangle) -> RenderWindow: ...
    def GetRenderWindowFromRenderViewSource(self, fromRenderViewSource: bool) -> RenderWindow: ...
    @staticmethod
    def LocalizeRenderReturnCode(rc: RenderReturnCode) -> str: ...
    def PauseRendering(self, ) -> None: ...
    def Render(self, ) -> RenderReturnCode: ...
    @staticmethod
    def RenderSize(doc: RhinoDoc, fromRenderSources: bool) -> Size: ...
    def RenderWindow(self, view: RhinoView, rect: Rectangle, inWindow: bool) -> RenderReturnCode: ...
    def ResumeRendering(self, ) -> None: ...
    def SaveImage(self, fileName: str, saveAlpha: bool) -> bool: ...
    def SetAsyncRenderContext(self, aRC: AsyncRenderContext) -> None: ...
    def SupportsPause(self, ) -> bool: ...

class RenderPlugInInfo:
    """.NET: Rhino.Render.RenderPlugInInfo"""
    def __init__(self, *args) -> None: ...
    Name: str
    PlugInId: Guid

class RenderPlugInList(List):
    """.NET: Rhino.Render.RenderPlugInList"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    Item: RenderPlugInInfo

class RenderPrimitive:
    """.NET: Rhino.Render.RenderPrimitive"""
    def __init__(self, *args) -> None: ...
    RhinoObject: RhinoObject
    PrimitiveType: RenderPrimitiveType
    InstanceTransform: Transform
    RenderMaterial: RenderMaterial
    BoundingBox: BoundingBox
    def Dispose(self, ) -> None: ...
    def Mesh(self, ) -> Mesh: ...
    def TryGetBox(self, box: Box) -> bool: ...
    def TryGetCone(self, cone: Cone, truncation: Plane) -> bool: ...
    def TryGetPlane(self, plane: PlaneSurface) -> bool: ...
    def TryGetSphere(self, sphere: Sphere) -> bool: ...

class RenderPrimitiveList:
    """.NET: Rhino.Render.RenderPrimitiveList"""
    def __init__(self, *args) -> None: ...
    UseObjectsMappingChannels: bool
    Count: int
    RhinoObject: RhinoObject
    def Add(self, mesh: Mesh, material: RenderMaterial, t: Transform) -> None: ...
    def AutoDeleteMaterialsOn(self, ) -> bool: ...
    def AutoDeleteMeshesOn(self, ) -> bool: ...
    def Clear(self, ) -> None: ...
    def ConvertMeshesToTriangles(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetInstanceTransform(self, index: int) -> Transform: ...
    def Material(self, index: int) -> RenderMaterial: ...
    def Mesh(self, index: int) -> Mesh: ...
    def MeshInstance(self, index: int, instance_transform: Transform) -> Mesh: ...
    def PrimitiveType(self, index: int) -> RenderPrimitiveType: ...
    def SetInstanceTransform(self, index: int, xform: Transform) -> None: ...
    def ToMaterialArray(self, ) -> list: ...
    def ToMeshArray(self, ) -> list: ...
    def TryGetBox(self, index: int, box: Box) -> bool: ...
    def TryGetCone(self, index: int, cone: Cone, truncation: Plane) -> bool: ...
    def TryGetPlane(self, index: int, plane: PlaneSurface) -> bool: ...
    def TryGetSphere(self, index: int, sphere: Sphere) -> bool: ...

class RenderPrimitiveType:
    """.NET: Rhino.Render.RenderPrimitiveType"""
    def __init__(self, *args) -> None: ...
    ...

class RenderPropertyChangedEvent(EventArgs):
    """.NET: Rhino.Render.RenderPropertyChangedEvent"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    Context: int

class RenderSettings(CommonObject):
    """.NET: Rhino.Render.RenderSettings"""
    def __init__(self, *args) -> None: ...
    AmbientLight: Color
    BackgroundColorTop: Color
    BackgroundColorBottom: Color
    UseHiddenLights: bool
    DepthCue: bool
    FlatShade: bool
    RenderBackfaces: bool
    RenderPoints: bool
    RenderCurves: bool
    RenderIsoparams: bool
    RenderMeshEdges: bool
    RenderAnnotations: bool
    AntialiasLevel: AntialiasLevel
    UseViewportSize: bool
    ScaleBackgroundToFit: bool
    TransparentBackground: bool
    ImageUnitSystem: UnitSystem
    ImageDpi: float
    ImageSize: Size
    ShadowmapLevel: int
    BackgroundStyle: BackgroundStyle
    LinearWorkflow: LinearWorkflow
    Dithering: Dithering
    RenderChannels: RenderChannels
    GroundPlane: GroundPlane
    SafeFrame: SafeFrame
    Skylight: Skylight
    Sun: Sun
    PostEffects: PostEffectCollection
    NamedView: str
    Snapshot: str
    SpecificViewport: str
    RenderSource: RenderingSources
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def Duplicate(self, ) -> RenderSettings: ...
    def RenderEnvironment(self, usage: EnvironmentUsage, purpose: EnvironmentPurpose) -> RenderEnvironment: ...
    def RenderEnvironmentId(self, usage: EnvironmentUsage, purpose: EnvironmentPurpose) -> Guid: ...
    def RenderEnvironmentOverride(self, usage: EnvironmentUsage) -> bool: ...
    def SetRenderEnvironment(self, usage: EnvironmentUsage, env: RenderEnvironment) -> None: ...
    def SetRenderEnvironmentId(self, usage: EnvironmentUsage, guid: Guid) -> None: ...
    def SetRenderEnvironmentOverride(self, usage: EnvironmentUsage, on: bool) -> None: ...

class RenderSourceView:
    """.NET: Rhino.Render.RenderSourceView"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetViewInfo(self, ) -> ViewInfo: ...

class RenderTabs:
    """.NET: Rhino.Render.RenderTabs"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def FromRenderSessionId(plugIn: PlugIn, tabType: Type, renderSessionId: Guid) -> object: ...
    def RegisterTab(self, plugin: PlugIn, tabType: Type, renderEngineId: Guid, caption: str, icon: Icon) -> None: ...
    @staticmethod
    def SessionIdFromTab(tab: object) -> Guid: ...
    @staticmethod
    def SidePaneUiIdFromTab(tab: object) -> Guid: ...

class RenderTexture(RenderContent):
    """.NET: Rhino.Render.RenderTexture"""
    def __init__(self, *args) -> None: ...
    RenderHashWithoutLocalMapping: int
    RenderHashWithoutLocalMappingOrLinearWorkflow: int
    LocalMappingTransform: Transform
    PixelSize2: Nullable
    Fields: FieldDictionary
    CppPointer: IntPtr
    TypeName: str
    TypeDescription: str
    DisplayName: str
    Name: str
    Notes: str
    Tags: str
    ChildSlotDisplayName: str
    Category: str
    Id: Guid
    TypeId: Guid
    GroupId: Guid
    RenderHash: int
    TopLevel: bool
    Hidden: bool
    IsHiddenByAutoDelete: bool
    CanBeEdited: bool
    IsDefaultInstance: bool
    ProxyType: ProxyTypes
    Parent: RenderContent
    FirstChild: RenderContent
    NextSibling: RenderContent
    TopLevelParent: RenderContent
    Document: RhinoDoc
    DocumentOwner: RhinoDoc
    DocumentRegistered: RhinoDoc
    DocumentAssoc: RhinoDoc
    Xml: str
    IsLocked: bool
    ChildSlotName: str
    FilesToEmbed: IEnumerable
    Filename: str
    Styles: RenderContentStyles
    def CreateEvaluator(self, evaluatorFlags: TextureEvaluatorFlags) -> TextureEvaluator: ...
    def GenerateTextureSimulation(self, bitmap: Bitmap, ef: TextureEvaluatorFlags) -> bool: ...
    def GetDisplayInViewport(self, ) -> bool: ...
    def GetEnvironmentMappingMode(self, ) -> TextureEnvironmentMappingMode: ...
    @staticmethod
    def GetEnvironmentMappingProjection(mode: TextureEnvironmentMappingMode, reflectionVector: Vector3d, u: float, v: float) -> bool: ...
    def GetInternalEnvironmentMappingMode(self, ) -> TextureEnvironmentMappingMode: ...
    def GetLocalMappingType(self, ) -> eLocalMappingType: ...
    def GetMappingChannel(self, ) -> int: ...
    def GetOffset(self, ) -> Vector3d: ...
    def GetOffsetLocked(self, ) -> bool: ...
    def GetPreviewIn3D(self, ) -> bool: ...
    def GetPreviewLocalMapping(self, ) -> bool: ...
    @staticmethod
    def GetProceduralAaltonenNoiseArrayPointer() -> IntPtr: ...
    @staticmethod
    def GetProceduralAaltonenNoiseArraySize() -> int: ...
    @staticmethod
    def GetProceduralImpulseNoiseArrayPointer() -> IntPtr: ...
    @staticmethod
    def GetProceduralImpulseNoiseArraySize() -> int: ...
    @staticmethod
    def GetProceduralPerlinNoiseArrayPointer() -> IntPtr: ...
    @staticmethod
    def GetProceduralPerlinNoiseArraySize() -> int: ...
    @staticmethod
    def GetProceduralVcNoiseArrayPointer() -> IntPtr: ...
    @staticmethod
    def GetProceduralVcNoiseArraySize() -> int: ...
    def GetProjectionMode(self, ) -> TextureProjectionMode: ...
    def GetRepeat(self, ) -> Vector3d: ...
    def GetRepeatLocked(self, ) -> bool: ...
    def GetRotation(self, ) -> Vector3d: ...
    @staticmethod
    def GetWcsBoxMapping(worldXyz: Point3d, normal: Vector3d) -> Point3d: ...
    def GetWrapType(self, ) -> TextureWrapType: ...
    def GraphInfo(self, tgi: TextureGraphInfo) -> None: ...
    def IsHdrCapable(self, ) -> bool: ...
    def IsImageBased(self, ) -> bool: ...
    def IsLinear(self, ) -> bool: ...
    def IsNormalMap(self, ) -> bool: ...
    @staticmethod
    def NewBitmapTexture(texture: SimulatedTexture, doc: RhinoDoc) -> RenderTexture: ...
    def PixelSize(self, u: int, v: int, w: int) -> None: ...
    def SaveAsImage(self, FullPath: str, width: int, height: int, depth: int) -> bool: ...
    def SetDisplayInViewport(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def SetEnvironmentMappingMode(self, value: TextureEnvironmentMappingMode, changeContext: ChangeContexts) -> None: ...
    def SetGraphInfo(self, tgi: TextureGraphInfo) -> None: ...
    def SetMappingChannel(self, value: int, changeContext: ChangeContexts) -> None: ...
    def SetOffset(self, value: Vector3d, changeContext: ChangeContexts) -> None: ...
    def SetOffsetLocked(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def SetPreviewIn3D(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def SetPreviewLocalMapping(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def SetProjectionMode(self, value: TextureProjectionMode, changeContext: ChangeContexts) -> None: ...
    def SetRepeat(self, value: Vector3d, changeContext: ChangeContexts) -> None: ...
    def SetRepeatLocked(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def SetRotation(self, value: Vector3d, changeContext: ChangeContexts) -> None: ...
    def SetWrapType(self, value: TextureWrapType, changeContext: ChangeContexts) -> None: ...
    def SimulateTexture(self, simulation: SimulatedTexture, tg: TextureGeneration, size: int, obj: RhinoObject) -> None: ...
    def SimulatedTexture(self, tg: TextureGeneration, size: int, obj: RhinoObject) -> SimulatedTexture: ...

class RenderTextureTable:
    """.NET: Rhino.Render.RenderTextureTable"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: RenderTexture
    def Add(self, c: RenderTexture) -> bool: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self, ) -> None: ...
    def Find(self, id: Guid) -> RenderTexture: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Remove(self, c: RenderTexture) -> bool: ...

class RenderWindow:
    """.NET: Rhino.Render.RenderWindow"""
    def __init__(self, *args) -> None: ...
    SessionId: Guid
    def AddChannel(self, channel: StandardChannels) -> bool: ...
    def AddWireframeChannel(self, doc: RhinoDoc, viewport: ViewportInfo, size: Size, region: Rectangle) -> bool: ...
    @staticmethod
    def ChannelId(ch: StandardChannels) -> Guid: ...
    @staticmethod
    def Create(szSize: Size) -> RenderWindow: ...
    def Dispose(self, ) -> None: ...
    def EndAsyncRender(self, successCode: RenderSuccessCode) -> None: ...
    @staticmethod
    def FromSessionId(sessionId: Guid) -> RenderWindow: ...
    def GetAdjust(self, ) -> ImageAdjust: ...
    def GetBitmap(self, ) -> Bitmap: ...
    def GetRequestedRenderChannels(self, ) -> list: ...
    def GetRequestedRenderChannelsAsStandardChannels(self, ) -> list: ...
    def Invalidate(self, ) -> None: ...
    def InvalidateArea(self, rect: Rectangle) -> None: ...
    def IsChannelAvailable(self, id: Guid) -> bool: ...
    def IsChannelShown(self, id: Guid) -> bool: ...
    def OpenChannel(self, id: StandardChannels) -> Channel: ...
    def RegisterPostEffectExecutionControl(self, ec: PostEffectExecutionControl) -> None: ...
    def SaveDibAsBitmap(self, filename: str) -> None: ...
    def SaveRenderImageAs(self, filename: str, renderEngineGuid: Guid, saveAlpha: bool) -> None: ...
    def SetAdjust(self, imageAdjust: ImageAdjust) -> None: ...
    def SetIsRendering(self, is_rendering: bool) -> None: ...
    def SetProgress(self, text: str, progress: float) -> None: ...
    def SetRGBAChannelColors(self, size: Size, colors: list) -> None: ...
    def SetRenderOutputRect(self, rect: Rectangle) -> None: ...
    def SetSize(self, size: Size) -> None: ...
    def SetView(self, view: ViewInfo) -> None: ...
    def Size(self, ) -> Size: ...
    @staticmethod
    def StandardChannelForGuid(id: Guid) -> StandardChannels: ...

class RenderWindowClonedEventArgs(EventArgs):
    """.NET: Rhino.Render.RenderWindowClonedEventArgs"""
    def __init__(self, *args) -> None: ...
    OldSessionId: Guid
    NewSessionId: Guid
    OldRenderWindow: RenderWindow
    NewRenderWindow: RenderWindow

class SafeFrame(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.SafeFrame"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    PerspectiveOnly: bool
    FieldsOn: bool
    LiveFrameOn: bool
    ActionFrameOn: bool
    ActionFrameLinked: bool
    ActionFrameXScale: float
    ActionFrameYScale: float
    TitleFrameOn: bool
    TitleFrameLinked: bool
    TitleFrameXScale: float
    TitleFrameYScale: float
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...

class SceneServerData:
    """.NET: Rhino.Render.SceneServerData"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Dispose(self, ) -> None: ...

class SceneServerDataUsage:
    """.NET: Rhino.Render.SceneServerDataUsage"""
    def __init__(self, *args) -> None: ...
    ...

class SimulatedEnvironment:
    """.NET: Rhino.Render.SimulatedEnvironment"""
    def __init__(self, *args) -> None: ...
    BackgroundColor: Color
    BackgroundImage: SimulatedTexture
    BackgroundProjection: BackgroundProjections
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def ProjectionFromString(projection: str) -> BackgroundProjections: ...
    @staticmethod
    def StringFromProjection(projection: BackgroundProjections) -> str: ...

class SimulatedTexture:
    """.NET: Rhino.Render.SimulatedTexture"""
    def __init__(self, *args) -> None: ...
    BitmapSize: int
    LocalMappingTransform: Transform
    Filename: str
    OriginalFilename: str
    Repeat: Vector2d
    Offset: Vector2d
    Rotation: float
    Repeating: bool
    MappingChannel: int
    ProjectionMode: ProjectionModes
    HasTransparentColor: bool
    TransparentColor: Color4f
    TransparentColorSensitivity: float
    Filtered: bool
    def ConstPointer(self, ) -> IntPtr: ...
    def Dispose(self, ) -> None: ...
    def MetersToUnits(self, doc: RhinoDoc, units: float) -> float: ...
    def SetMappingChannelAndProjectionMode(self, pm: ProjectionModes, mappingChannel: int, emm: EnvironmentMappingModes) -> None: ...
    def Texture(self, ) -> Texture: ...
    def UnitsToMeters(self, doc: RhinoDoc, units: float) -> float: ...

class Skylight(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.Skylight"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    ShadowIntensity: float
    CustomEnvironmentOn: bool
    CustomEnvironment: Guid
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...

class Sun(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.Sun"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    ManualControl: bool
    ManualControlOn: bool
    Accuracy: Accuracies
    SkylightOn: bool
    DaylightSaving: bool
    DaylightSavingOn: bool
    DaylightSavingMinutes: int
    TimeZone: float
    North: float
    Intensity: float
    Vector: Vector3d
    Light: Light
    Azimuth: float
    Altitude: float
    Latitude: float
    Longitude: float
    Hash: int
    @staticmethod
    def AltitudeFromValues(latitude: float, longitude: float, timezoneHours: float, daylightMinutes: int, when: DateTime, hours: float, fast: bool) -> float: ...
    @staticmethod
    def ColorFromAltitude(altitudeDegrees: float) -> Color: ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetDateTime(self, kind: DateTimeKind) -> DateTime: ...
    @staticmethod
    def Here(latitude: float, longitude: float) -> bool: ...
    @staticmethod
    def JulianDay(timezoneHours: float, daylightMinutes: int, when: DateTime, hours: float) -> float: ...
    def SetDateTime(self, time: DateTime, kind: DateTimeKind) -> None: ...
    def SetPosition(self, when: DateTime, latitudeDegrees: float, longitudeDegrees: float) -> None: ...
    def ShowDialog(self, ) -> None: ...
    @staticmethod
    def SunDirection(latitude: float, longitude: float, when: DateTime) -> Vector3d: ...
    @staticmethod
    def TwilightZone() -> float: ...

class SupportOptions:
    """.NET: Rhino.Render.SupportOptions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AlwaysShowSunPreview() -> bool: ...
    @staticmethod
    def AutoSaveKeepAmount() -> int: ...
    @staticmethod
    def AutoSaveRenderings() -> bool: ...
    @staticmethod
    def CheckSupportFilesBeforeRendering() -> bool: ...
    @staticmethod
    def CombineEditors() -> bool: ...
    @staticmethod
    def CustomLibraryPath() -> str: ...
    @staticmethod
    def CustomPaths() -> str: ...
    @staticmethod
    def DarkPreviewCheckerColor() -> int: ...
    @staticmethod
    def EnablePreviewJobLog() -> bool: ...
    @staticmethod
    def FileExplorer_CustomPath() -> str: ...
    @staticmethod
    def FileExplorer_CustomPathList() -> str: ...
    @staticmethod
    def FileExplorer_InitialLocation() -> RdkInitialLocation: ...
    @staticmethod
    def FileExplorer_InitialLocationCustomFolder() -> str: ...
    @staticmethod
    def FileExplorer_LastNavigatedLocation() -> str: ...
    @staticmethod
    def FileExplorer_SetCustomPath(path: str) -> None: ...
    @staticmethod
    def FileExplorer_SetCustomPathList(path: str) -> None: ...
    @staticmethod
    def FileExplorer_SetInitialLocation(l: RdkInitialLocation) -> None: ...
    @staticmethod
    def FileExplorer_SetInitialLocationCustomFolder(path: str) -> None: ...
    @staticmethod
    def FileExplorer_SetLastNavigatedLocation(folder: str) -> None: ...
    @staticmethod
    def FileExplorer_SetShowCustom(b: bool) -> None: ...
    @staticmethod
    def FileExplorer_SetShowDocuments(b: bool) -> None: ...
    @staticmethod
    def FileExplorer_SetShowRenderContent(b: bool) -> None: ...
    @staticmethod
    def FileExplorer_SetUseDefaultLocation(b: bool) -> None: ...
    @staticmethod
    def FileExplorer_ShowCustom() -> bool: ...
    @staticmethod
    def FileExplorer_ShowDocuments() -> bool: ...
    @staticmethod
    def FileExplorer_ShowRenderContent() -> bool: ...
    @staticmethod
    def FileExplorer_UseDefaultLocation() -> bool: ...
    @staticmethod
    def HarvestContentParameters() -> bool: ...
    @staticmethod
    def LabelFormatLoc() -> int: ...
    @staticmethod
    def LabelFormatUtc() -> int: ...
    @staticmethod
    def LastNavigatedLocation() -> str: ...
    @staticmethod
    def LibrariesInitialLocation() -> RdkInitialLocation: ...
    @staticmethod
    def LibrariesInitialLocationCustomFolder() -> str: ...
    @staticmethod
    def Libraries_CustomPath() -> str: ...
    @staticmethod
    def Libraries_CustomPathList() -> str: ...
    @staticmethod
    def Libraries_InitialLocation() -> RdkInitialLocation: ...
    @staticmethod
    def Libraries_InitialLocationCustomFolder() -> str: ...
    @staticmethod
    def Libraries_LastNavigatedLocation() -> str: ...
    @staticmethod
    def Libraries_SetCustomPath(path: str) -> None: ...
    @staticmethod
    def Libraries_SetCustomPathList(path: str) -> None: ...
    @staticmethod
    def Libraries_SetInitialLocation(l: RdkInitialLocation) -> None: ...
    @staticmethod
    def Libraries_SetInitialLocationCustomFolder(path: str) -> None: ...
    @staticmethod
    def Libraries_SetLastNavigatedLocation(folder: str) -> None: ...
    @staticmethod
    def Libraries_SetShowCustom(b: bool) -> None: ...
    @staticmethod
    def Libraries_SetShowDocuments(b: bool) -> None: ...
    @staticmethod
    def Libraries_SetShowRenderContent(b: bool) -> None: ...
    @staticmethod
    def Libraries_SetUseDefaultLocation(b: bool) -> None: ...
    @staticmethod
    def Libraries_ShowCustom() -> bool: ...
    @staticmethod
    def Libraries_ShowDocuments() -> bool: ...
    @staticmethod
    def Libraries_ShowRenderContent() -> bool: ...
    @staticmethod
    def Libraries_UseDefaultLocation() -> bool: ...
    @staticmethod
    def LightPreviewCheckerColor() -> int: ...
    @staticmethod
    def MaxPreviewCacheMB() -> int: ...
    @staticmethod
    def MaxPreviewSeconds() -> int: ...
    @staticmethod
    def MultithreadedTextureEvaluation() -> bool: ...
    @staticmethod
    def PreferNativeRenderer() -> bool: ...
    @staticmethod
    def PreferredUnpackFolder() -> str: ...
    @staticmethod
    def PreviewCustomRenderMeshes() -> bool: ...
    @staticmethod
    def SetAlwaysShowSunPreview(b: bool) -> None: ...
    @staticmethod
    def SetAutoSaveKeepAmount(value: int) -> None: ...
    @staticmethod
    def SetAutoSaveRenderings(b: bool) -> None: ...
    @staticmethod
    def SetCheckSupportFilesBeforeRendering(b: bool) -> None: ...
    @staticmethod
    def SetCombineEditors(b: bool) -> None: ...
    @staticmethod
    def SetCustomLibraryPath(path: str) -> None: ...
    @staticmethod
    def SetCustomPaths(path: str) -> None: ...
    @staticmethod
    def SetHarvestContentParameters(b: bool) -> None: ...
    @staticmethod
    def SetLabelFormatLoc(value: int) -> None: ...
    @staticmethod
    def SetLabelFormatUtc(value: int) -> None: ...
    @staticmethod
    def SetLastNavigatedLocation(folder: str) -> None: ...
    @staticmethod
    def SetLibrariesInitialLocation(l: RdkInitialLocation) -> None: ...
    @staticmethod
    def SetLibrariesInitialLocationCustomFolder(path: str) -> None: ...
    @staticmethod
    def SetMultithreadedTextureEvaluation(b: bool) -> None: ...
    @staticmethod
    def SetPreferNativeRenderer(b: bool) -> None: ...
    @staticmethod
    def SetPreferredUnpackFolder(path: str) -> None: ...
    @staticmethod
    def SetPreviewCustomRenderMeshes(b: bool) -> None: ...
    @staticmethod
    def SetShowCustom(b: bool) -> None: ...
    @staticmethod
    def SetShowDetailsPanel(b: bool) -> None: ...
    @staticmethod
    def SetShowDocuments(b: bool) -> None: ...
    @staticmethod
    def SetShowRenderContent(b: bool) -> None: ...
    @staticmethod
    def SetSupportSharedUIs(b: bool) -> None: ...
    @staticmethod
    def SetTextureSize(size: RdkTextureSize, bSendEvent: bool) -> None: ...
    @staticmethod
    def SetUseDefaultLibraryPath(b: bool) -> None: ...
    @staticmethod
    def SetUsePreviewCache(b: bool) -> None: ...
    @staticmethod
    def SetUseQuickInitialPreview(b: bool) -> None: ...
    @staticmethod
    def ShowCustom() -> bool: ...
    @staticmethod
    def ShowDetailsPanel() -> bool: ...
    @staticmethod
    def ShowDocuments() -> bool: ...
    @staticmethod
    def ShowRenderContent() -> bool: ...
    @staticmethod
    def SupportSharedUIs() -> bool: ...
    @staticmethod
    def SupportSharedUIsNoCache() -> bool: ...
    @staticmethod
    def TextureSize() -> int: ...
    @staticmethod
    def UseDefaultLibraryPath() -> bool: ...
    @staticmethod
    def UsePreview() -> bool: ...
    @staticmethod
    def UsePreviewCache() -> bool: ...
    @staticmethod
    def UseQuickInitialPreview() -> bool: ...
    @staticmethod
    def UseRenderedPreview() -> bool: ...

class TextureEnvironmentMappingMode:
    """.NET: Rhino.Render.TextureEnvironmentMappingMode"""
    def __init__(self, *args) -> None: ...
    ...

class TextureEvaluator:
    """.NET: Rhino.Render.TextureEvaluator"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetColor(self, uvw: Point3d, duvwdx: Vector3d, duvwdy: Vector3d, color: Color4f) -> bool: ...
    def Initialize(self, ) -> bool: ...
    def WriteToByteArray(self, width: int, height: int) -> SimpleArrayByte: ...
    def WriteToByteArray2(self, width: int, height: int) -> StdVectorByte: ...
    def WriteToFloatArray(self, width: int, height: int) -> SimpleArrayFloat: ...
    def WriteToFloatArray2(self, width: int, height: int) -> StdVectorFloat: ...

class TextureGeneration:
    """.NET: Rhino.Render.TextureGeneration"""
    def __init__(self, *args) -> None: ...
    ...

class TextureGraphInfo:
    """.NET: Rhino.Render.TextureGraphInfo"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ActiveAxis(self, ) -> Axis: ...
    def ActiveChannel(self, ) -> Channel: ...
    def AmountU(self, ) -> float: ...
    def AmountV(self, ) -> float: ...
    def AmountW(self, ) -> float: ...
    def Dispose(self, ) -> None: ...
    def SetActiveAxis(self, axis: Axis) -> None: ...
    def SetActiveChannel(self, channel: Channel) -> None: ...
    def SetAmountU(self, d: float) -> None: ...
    def SetAmountV(self, d: float) -> None: ...
    def SetAmountW(self, d: float) -> None: ...

class TextureMapping(ModelComponent):
    """.NET: Rhino.Render.TextureMapping"""
    def __init__(self, *args) -> None: ...
    MappingType: TextureMappingType
    Capped: bool
    TextureSpace: TextureSpace
    Projection: Projection
    Id: Guid
    UvwTransform: Transform
    PrimativeTransform: Transform
    PrimitiveTransform: Transform
    NormalTransform: Transform
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    Name: str
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    @staticmethod
    def CreateBoxMapping(plane: Plane, dx: Interval, dy: Interval, dz: Interval, capped: bool) -> TextureMapping: ...
    @staticmethod
    def CreateCustomMeshMapping(mesh: Mesh) -> TextureMapping: ...
    @staticmethod
    def CreateCylinderMapping(cylinder: Cylinder, capped: bool) -> TextureMapping: ...
    @staticmethod
    def CreateOcsMapping(plane: Plane) -> TextureMapping: ...
    @staticmethod
    def CreatePlaneMapping(plane: Plane, dx: Interval, dy: Interval, dz: Interval, capped: bool) -> TextureMapping: ...
    @staticmethod
    def CreateSphereMapping(sphere: Sphere) -> TextureMapping: ...
    @staticmethod
    def CreateSurfaceParameterMapping() -> TextureMapping: ...
    def Evaluate(self, p: Point3d, n: Vector3d, t: Point3d, pXform: Transform, nXform: Transform) -> int: ...
    def TryGetMappingBox(self, plane: Plane, dx: Interval, dy: Interval, dz: Interval, capped: bool) -> bool: ...
    def TryGetMappingCylinder(self, cylinder: Cylinder, capped: bool) -> bool: ...
    def TryGetMappingMesh(self, mesh: Mesh) -> bool: ...
    def TryGetMappingPlane(self, plane: Plane, dx: Interval, dy: Interval, dz: Interval, capped: bool) -> bool: ...
    def TryGetMappingSphere(self, sphere: Sphere) -> bool: ...

class TextureMappingType:
    """.NET: Rhino.Render.TextureMappingType"""
    def __init__(self, *args) -> None: ...
    ...

class TextureMode:
    """.NET: Rhino.Render.TextureMode"""
    def __init__(self, *args) -> None: ...
    ...

class TextureProjectionMode:
    """.NET: Rhino.Render.TextureProjectionMode"""
    def __init__(self, *args) -> None: ...
    ...

class TextureRenderHashFlags:
    """.NET: Rhino.Render.TextureRenderHashFlags"""
    def __init__(self, *args) -> None: ...
    ...

class TextureSpace:
    """.NET: Rhino.Render.TextureSpace"""
    def __init__(self, *args) -> None: ...
    ...

class TextureWrapType:
    """.NET: Rhino.Render.TextureWrapType"""
    def __init__(self, *args) -> None: ...
    ...

class TexturedColor(TexturedValue):
    """.NET: Rhino.Render.TexturedColor"""
    def __init__(self, *args) -> None: ...
    ...

class TexturedFloat(TexturedValue):
    """.NET: Rhino.Render.TexturedFloat"""
    def __init__(self, *args) -> None: ...
    ...

class TexturedValue:
    """.NET: Rhino.Render.TexturedValue`1"""
    def __init__(self, *args) -> None: ...
    ...

class TimeZone:
    """.NET: Rhino.Render.TimeZone"""
    def __init__(self, *args) -> None: ...
    Name: str
    Hours: float
    Longitude: float
    Latitude: float
    @staticmethod
    def TimeZoneAt(index: int) -> TimeZone: ...
    @staticmethod
    def TimeZones() -> int: ...

class TwoColorRenderTexture(RenderTexture):
    """.NET: Rhino.Render.TwoColorRenderTexture"""
    def __init__(self, *args) -> None: ...
    Color1: Color4f
    Color2: Color4f
    Texture1On: bool
    Texture2On: bool
    Texture1Amount: float
    Texture2Amount: float
    SwapColors: bool
    SuperSample: bool
    RenderHashWithoutLocalMapping: int
    RenderHashWithoutLocalMappingOrLinearWorkflow: int
    LocalMappingTransform: Transform
    PixelSize2: Nullable
    Fields: FieldDictionary
    CppPointer: IntPtr
    TypeName: str
    TypeDescription: str
    DisplayName: str
    Name: str
    Notes: str
    Tags: str
    ChildSlotDisplayName: str
    Category: str
    Id: Guid
    TypeId: Guid
    GroupId: Guid
    RenderHash: int
    TopLevel: bool
    Hidden: bool
    IsHiddenByAutoDelete: bool
    CanBeEdited: bool
    IsDefaultInstance: bool
    ProxyType: ProxyTypes
    Parent: RenderContent
    FirstChild: RenderContent
    NextSibling: RenderContent
    TopLevelParent: RenderContent
    Document: RhinoDoc
    DocumentOwner: RhinoDoc
    DocumentRegistered: RhinoDoc
    DocumentAssoc: RhinoDoc
    Xml: str
    IsLocked: bool
    ChildSlotName: str
    FilesToEmbed: IEnumerable
    Filename: str
    Styles: RenderContentStyles

class UndoRedo:
    """.NET: Rhino.Render.UndoRedo"""
    def __init__(self, *args) -> None: ...
    ...

class Utilities:
    """.NET: Rhino.Render.Utilities"""
    def __init__(self, *args) -> None: ...
    DefaultRenderPlugInId: Guid
    ShowIncompatibleMaterials: bool
    ShowIncompatibleEnvironments: bool
    ShowIncompatibleTextures: bool
    @staticmethod
    def ChangeContentType(oldContent: RenderContent, newType: Guid, harvestParameters: bool) -> RenderContent: ...
    @staticmethod
    def FindFile(doc: RhinoDoc, fullPathToFile: str, unpackFromBitmapTableIfNecessary: bool) -> str: ...
    @staticmethod
    def GetUnpackedFilesCacheFolder(doc: RhinoDoc, create: bool) -> str: ...
    @staticmethod
    def IsCachedTextureFileInUse(textureFileName: str) -> bool: ...
    @staticmethod
    def LoadPersistentRenderContentFromFile(docSerialNumber: int, filename: str) -> RenderContent: ...
    @staticmethod
    def MoveWindow(hwnd: IntPtr, rect: Rectangle, bRepaint: bool, bRepaintNC: bool) -> None: ...
    @staticmethod
    def PromptForSaveImageFileParameters(filename: str, width: int, height: int, colorDepth: int) -> str: ...
    @staticmethod
    def SafeFrameEnabled(doc: RhinoDoc) -> bool: ...
    @staticmethod
    def SetDefaultRenderPlugIn(pluginId: Guid) -> bool: ...
    @staticmethod
    def ShowContentChooser(doc: RhinoDoc, defaultType: Guid, defaultInstanceId: Guid, kinds: RenderContentKind, flags: ShowContentChooserFlags, presetCategory: str, categories: IEnumerable, types: IEnumerable, instanceIdsOut: list) -> ShowContentChooserResults: ...
    @staticmethod
    def ShowIORMenu(hwnd: IntPtr, pt: Point, outIOR: float, outString: str) -> bool: ...

class it_strategy:
    """.NET: Rhino.Render.it_strategy"""
    def __init__(self, *args) -> None: ...
    ...
