# Auto-generated — Rhino 8 — Rhino.Render.DataSources

class AssignBys:
    """.NET: Rhino.Render.DataSources.AssignBys"""
    def __init__(self, *args) -> None: ...
    ...

class ContentFactories:
    """.NET: Rhino.Render.DataSources.ContentFactories"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Dispose(self, ) -> None: ...
    def FindFactory(self, uuid: Guid) -> ContentFactory: ...
    def FirstFactory(self, ) -> ContentFactory: ...
    def NextFactory(self, ) -> ContentFactory: ...

class ContentFactory:
    """.NET: Rhino.Render.DataSources.ContentFactory"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ContentTypeId(self, ) -> Guid: ...
    def Dispose(self, ) -> None: ...
    def Kind(self, ) -> RenderContentKind: ...
    def NewContent(self, ) -> RenderContent: ...

class MetaData:
    """.NET: Rhino.Render.DataSources.MetaData"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ContentInstanceId(self, ) -> Guid: ...
    def Dispose(self, ) -> None: ...
    def Geometry(self, ) -> str: ...

class Modes:
    """.NET: Rhino.Render.DataSources.Modes"""
    def __init__(self, *args) -> None: ...
    ...

class RdkEdit:
    """.NET: Rhino.Render.DataSources.RdkEdit"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Dispose(self, ) -> None: ...
    def Execute(self, collection: RenderContentCollection) -> bool: ...

class RdkModalEditContentBucket:
    """.NET: Rhino.Render.DataSources.RdkModalEditContentBucket"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def ContentsIn(self, ) -> RenderContentCollection: ...
    def Dispose(self, ) -> None: ...
    def SetContentsOut(self, collection: RenderContentCollection) -> None: ...

class RdkSelectionNavigator:
    """.NET: Rhino.Render.DataSources.RdkSelectionNavigator"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Add(self, selectedContentArray: RenderContentCollection) -> None: ...
    def CanGoBackwards(self, ) -> bool: ...
    def CanGoForwards(self, ) -> bool: ...
    def Clear(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def GoBackwards(self, selectedContentArray: RenderContentCollection) -> bool: ...
    def GoForwards(self, selectedContentArray: RenderContentCollection) -> bool: ...

class RhinoSettings:
    """.NET: Rhino.Render.DataSources.RhinoSettings"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    CustomImageSizeIsPreset: bool
    def ActiveView(self, ) -> RhinoView: ...
    def Dispose(self, ) -> None: ...
    def GetCurrentRenderer(self, ) -> Guid: ...
    def GetCustomRenderSizes(self, ) -> List: ...
    def GetRenderSettings(self, ) -> RenderSettings: ...
    def GroundPlaneOnInViewDisplayMode(self, view: RhinoView) -> bool: ...
    def RenderingView(self, ) -> ViewInfo: ...
    def SetCurrentRenderer(self, g: Guid) -> None: ...
    def SetGroundPlaneOnInViewDisplayMode(self, view: RhinoView, bOn: bool) -> None: ...
    def SetRenderSettings(self, renderSettings: RenderSettings) -> None: ...
    def ViewSupportsShading(self, view: RhinoView) -> bool: ...

class Shapes:
    """.NET: Rhino.Render.DataSources.Shapes"""
    def __init__(self, *args) -> None: ...
    ...

class Sizes:
    """.NET: Rhino.Render.DataSources.Sizes"""
    def __init__(self, *args) -> None: ...
    ...
