# Auto-generated — Rhino 8 — Rhino.Render.PostEffects

class CustomPostEffectAttribute(Attribute):
    """.NET: Rhino.Render.PostEffects.CustomPostEffectAttribute"""
    def __init__(self, *args) -> None: ...
    PostEffectType: PostEffectType
    Styles: PostEffectStyles
    ExecuteWhileRenderingOption: PostEffectExecuteWhileRenderingOptions
    CanDisplayHelp: bool
    Name: str
    ExecuteWhileRenderingDelay: int
    TypeId: object

class IPostEffects:
    """.NET: Rhino.Render.PostEffects.IPostEffects"""
    def __init__(self, *args) -> None: ...
    def GetPostEffects(self, type: PostEffectType) -> list: ...
    def PostEffectFromId(self, uuid: Guid) -> PostEffect: ...

class PostEffect:
    """.NET: Rhino.Render.PostEffects.PostEffect"""
    def __init__(self, *args) -> None: ...
    SerialNumber: int
    Id: Guid
    PostEffectType: PostEffectType
    Styles: PostEffectStyles
    LocalName: str
    CanDisplayHelp: bool
    ExecuteWhileRenderingOption: PostEffectExecuteWhileRenderingOptions
    On: bool
    Shown: bool
    IsSelected: bool
    RequiredChannels: list
    def AddUISections(self, ui: PostEffectUI) -> None: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def CanExecute(self, pipeline: PostEffectPipeline) -> bool: ...
    def Changed(self, ) -> None: ...
    def DisplayHelp(self, ) -> bool: ...
    def Dispose(self, bDisposing: bool) -> None: ...
    def EndChange(self, ) -> bool: ...
    def Execute(self, pipeline: PostEffectPipeline, rect: Rectangle) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetParam(self, param: str, v: object) -> bool: ...
    def ReadFromDocumentDefaults(self, doc: RhinoDoc) -> bool: ...
    def ReadState(self, state: PostEffectState) -> bool: ...
    @staticmethod
    def RegisterPostEffect(assembly: Assembly, pluginId: Guid) -> list: ...
    def ResetToFactoryDefaults(self, ) -> None: ...
    def SetParam(self, param: str, v: object) -> bool: ...
    def WriteState(self, state: PostEffectState) -> bool: ...
    def WriteToDocumentDefaults(self, doc: RhinoDoc) -> bool: ...

class PostEffectChannel:
    """.NET: Rhino.Render.PostEffects.PostEffectChannel"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    PixelSize: int
    def CPU(self, ) -> Channel: ...
    def Clone(self, ) -> PostEffectChannel: ...
    def Commit(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def GPU(self, ) -> ChannelGPU: ...

class PostEffectCollection(DocumentOrFreeFloatingBase):
    """.NET: Rhino.Render.PostEffects.PostEffectCollection"""
    def __init__(self, *args) -> None: ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetSelectedPostEffect(self, type: PostEffectType, id: Guid) -> bool: ...
    def MovePostEffectBefore(self, id_move: Guid, id_before: Guid) -> bool: ...
    def PostEffectDataFromId(self, id: Guid) -> PostEffectData: ...
    def SetSelectedPostEffect(self, type: PostEffectType, id: Guid) -> None: ...

class PostEffectData:
    """.NET: Rhino.Render.PostEffects.PostEffectData"""
    def __init__(self, *args) -> None: ...
    Collection: PostEffectCollection
    Id: Guid
    Type: PostEffectType
    LocalName: str
    On: bool
    Shown: bool
    def DataCRC(self, current_remainder: int) -> int: ...
    def Dispose(self, ) -> None: ...
    def GetParameter(self, param_name: str) -> IConvertible: ...
    def SetParameter(self, param_name: str, param_value: object) -> bool: ...

class PostEffectExecuteContexts:
    """.NET: Rhino.Render.PostEffects.PostEffectExecuteContexts"""
    def __init__(self, *args) -> None: ...
    ...

class PostEffectExecuteWhileRenderingOptions:
    """.NET: Rhino.Render.PostEffects.PostEffectExecuteWhileRenderingOptions"""
    def __init__(self, *args) -> None: ...
    ...

class PostEffectExecutionControl:
    """.NET: Rhino.Render.PostEffects.PostEffectExecutionControl"""
    def __init__(self, *args) -> None: ...
    def Detach(self, ) -> IntPtr: ...
    def Dispose(self, bDisposing: bool) -> None: ...
    def ReadyToExecutePostEffect(self, pep_id: Guid) -> bool: ...

class PostEffectHistograms:
    """.NET: Rhino.Render.PostEffects.PostEffectHistograms"""
    def __init__(self, *args) -> None: ...
    ...

class PostEffectJob:
    """.NET: Rhino.Render.PostEffects.PostEffectJob"""
    def __init__(self, *args) -> None: ...
    def Clone(self, ) -> PostEffectJob: ...
    def Dispose(self, bDisposing: bool) -> None: ...
    def Execute(self, rect: Rectangle, access: PostEffectJobChannels) -> bool: ...

class PostEffectJobChannels:
    """.NET: Rhino.Render.PostEffects.PostEffectJobChannels"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetChannel(self, channelId: Guid) -> PostEffectChannel: ...

class PostEffectPipeline:
    """.NET: Rhino.Render.PostEffects.PostEffectPipeline"""
    def __init__(self, *args) -> None: ...
    RenderingId: Guid
    GPUAllowed: bool
    IsRendering: bool
    def Dimensions(self, ) -> Size: ...
    def Dispose(self, ) -> None: ...
    def Execute(self, p: Rectangle, renderingInProgress: bool, usageContexts: PostEffectExecuteContexts, histogramsToUpdate: PostEffectHistograms) -> bool: ...
    def ExecutionOrder(self, ) -> list: ...
    def GetChannelForRead(self, id: Guid) -> PostEffectChannel: ...
    def GetChannelForWrite(self, id: Guid) -> PostEffectChannel: ...
    def GetEndTimeInMilliseconds(self, ) -> int: ...
    def GetMaxLuminance(self, ) -> float: ...
    def GetStartTimeInMilliseconds(self, ) -> int: ...
    def SetStartTimeInMilliseconds(self, ms: int) -> None: ...
    def ThreadEngine(self, ) -> PostEffectThreadEngine: ...

class PostEffectState:
    """.NET: Rhino.Render.PostEffects.PostEffectState"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def SetValue(self, name: str, vValue: T) -> bool: ...
    def TryGetValue(self, name: str, vValue: T) -> bool: ...

class PostEffectStyles:
    """.NET: Rhino.Render.PostEffects.PostEffectStyles"""
    def __init__(self, *args) -> None: ...
    ...

class PostEffectThreadEngine:
    """.NET: Rhino.Render.PostEffects.PostEffectThreadEngine"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def RunPostEffect(self, job: PostEffectJob, pipeline: PostEffectPipeline, plugin: PostEffect, rect: Rectangle, channels: list) -> bool: ...

class PostEffectType:
    """.NET: Rhino.Render.PostEffects.PostEffectType"""
    def __init__(self, *args) -> None: ...
    ...

class PostEffectUI:
    """.NET: Rhino.Render.PostEffects.PostEffectUI"""
    def __init__(self, *args) -> None: ...
    def AddSection(self, section: ICollapsibleSection) -> None: ...
    def Dispose(self, ) -> None: ...

class PostEffectUuids:
    """.NET: Rhino.Render.PostEffects.PostEffectUuids"""
    def __init__(self, *args) -> None: ...
    Glare: Guid
    Bloom: Guid
    Glow: Guid
    Fog: Guid
    DepthOfField: Guid
    Multiplier: Guid
    Noise: Guid
    GaussianBlur: Guid
    WireframePointsRGBA: Guid
    WireframeCurvesRGBA: Guid
    WireframeIsocurvesRGBA: Guid
    WireframeAnnotationsRGBA: Guid
    ToneMapper_Clamp: Guid
    ToneMapper_BlackWhitePoint: Guid
    ToneMapper_Logarithmic: Guid
    ToneMapper_FalseColor: Guid
    ToneMapper_Filmic: Guid
    Gamma: Guid
    Dithering: Guid
    Watermark: Guid
    HueSatLum: Guid
    BriCon: Guid
