# Auto-generated — Rhino 8 — Rhino.Render.UI

class IUserInterfaceSection:
    """.NET: Rhino.Render.UI.IUserInterfaceSection"""
    def __init__(self, *args) -> None: ...
    Hidden: bool
    def OnUserInterfaceSectionExpanding(self, userInterfaceSection: UserInterfaceSection, expanding: bool) -> None: ...
    def UserInterfaceDisplayData(self, userInterfaceSection: UserInterfaceSection, renderContentList: list) -> None: ...

class UserInterfaceSection:
    """.NET: Rhino.Render.UI.UserInterfaceSection"""
    def __init__(self, *args) -> None: ...
    RenderContent: RenderContent
    Window: object
    def Expand(self, expand: bool) -> None: ...
    @staticmethod
    def FromWindow(window: object) -> UserInterfaceSection: ...
    def GetContentList(self, ) -> list: ...
    def Show(self, visible: bool) -> None: ...

class WorldMapDayNight:
    """.NET: Rhino.Render.UI.WorldMapDayNight"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def HasMapForCurrentSettings(self, ) -> bool: ...
    def LocationToMap(self, latlong: Point2d) -> Point: ...
    def MakeMapBitmap(self, ) -> None: ...
    def Map(self, ) -> Image: ...
    def MapToLocation(self, mapPoint: Point) -> Point2d: ...
    def SetDayNightDisplay(self, bOn: bool) -> None: ...
    def SetEnabled(self, bEnabled: bool) -> None: ...
    def SetTimeInfo(self, dt: DateTime, timezone: float, daylightSavingMinutes: int, bDaylightSavingsOn: bool) -> None: ...
