# Auto-generated — Rhino 8 — Rhino

class AngleUnitSystem:
    """.NET: Rhino.AngleUnitSystem"""
    def __init__(self, *args) -> None: ...
    ...

class AntialiasLevel:
    """.NET: Rhino.AntialiasLevel"""
    def __init__(self, *args) -> None: ...
    ...

class BitmapExtensions:
    """.NET: Rhino.BitmapExtensions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def BitmapAsTextureFileReference(bitmap: Bitmap, crc: int) -> FileReference: ...
    @staticmethod
    def ConvertToNormalMap(bitmap: Bitmap, bLossyCompressionSource: bool, bPositiveZComponent: bool) -> Bitmap: ...
    @staticmethod
    def IsNormalMap(bitmap: Bitmap, bLossyCompressionSource: bool, bPositiveZComponent: bool) -> bool: ...

class DisplayDeviceInfo:
    """.NET: Rhino.DisplayDeviceInfo"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GpuDeviceInfos() -> List: ...
    @staticmethod
    def GpuNames() -> List: ...

class DocumentEventArgs(EventArgs):
    """.NET: Rhino.DocumentEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentId: int
    DocumentSerialNumber: int
    Document: RhinoDoc

class DocumentOpenEventArgs(DocumentEventArgs):
    """.NET: Rhino.DocumentOpenEventArgs"""
    def __init__(self, *args) -> None: ...
    FileName: str
    Merge: bool
    Reference: bool
    DocumentId: int
    DocumentSerialNumber: int
    Document: RhinoDoc

class DocumentSaveEventArgs(DocumentEventArgs):
    """.NET: Rhino.DocumentSaveEventArgs"""
    def __init__(self, *args) -> None: ...
    FileName: str
    ExportSelected: bool
    DocumentId: int
    DocumentSerialNumber: int
    Document: RhinoDoc

class GpuDeviceInfo:
    """.NET: Rhino.GpuDeviceInfo"""
    def __init__(self, *args) -> None: ...
    Name: str
    Vendor: str
    Memory: int
    MemoryAsString: str
    DriverDateAsString: str

class IEpsilonComparable:
    """.NET: Rhino.IEpsilonComparable`1"""
    def __init__(self, *args) -> None: ...
    def EpsilonEquals(self, other: T, epsilon: float) -> bool: ...

class IEpsilonFComparable:
    """.NET: Rhino.IEpsilonFComparable`1"""
    def __init__(self, *args) -> None: ...
    def EpsilonEquals(self, other: T, epsilon: float) -> bool: ...

class IRhinoDocObserver:
    """.NET: Rhino.IRhinoDocObserver"""
    def __init__(self, *args) -> None: ...
    def ActiveRhinoDocChanged(self, e: RhinoDocObserverArgs) -> None: ...
    def RhinoDocClosed(self, e: RhinoDocObserverArgs) -> None: ...

class IndexPair:
    """.NET: Rhino.IndexPair"""
    def __init__(self, *args) -> None: ...
    I: int
    J: int
    Item: int
    Count: int
    def Contains(self, item: int) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: int) -> int: ...

class LengthValue:
    """.NET: Rhino.LengthValue"""
    def __init__(self, *args) -> None: ...
    LengthString: str
    ParseSettings: StringParserSettings
    UnitSystem: UnitSystem
    LengthStringFormat: StringFormat
    ContextLocaleId: int
    ContextAngleUnitSystem: AngleUnitSystem
    def ChangeLength(self, newLength: float) -> LengthValue: ...
    def ChangeUnitSystem(self, newUnits: UnitSystem) -> LengthValue: ...
    @staticmethod
    def Create(length: float, us: UnitSystem, format: StringFormat, localeId: int) -> LengthValue: ...
    def Dispose(self, ) -> None: ...
    def IsUnset(self, ) -> bool: ...
    def Length(self, units: UnitSystem) -> float: ...

class LinkedInstanceDefinitionUpdateStyle:
    """.NET: Rhino.LinkedInstanceDefinitionUpdateStyle"""
    def __init__(self, *args) -> None: ...
    ...

class PersistentSettings:
    """.NET: Rhino.PersistentSettings"""
    def __init__(self, *args) -> None: ...
    HiddenFromUserInterface: bool
    Keys: ICollection
    ChildKeys: ICollection
    RhinoAppSettings: PersistentSettings
    StringListRootKey: str
    def AddChild(self, key: str) -> PersistentSettings: ...
    def ClearChangedFlag(self, ) -> None: ...
    def ContainsChangedValues(self, ) -> bool: ...
    def ContainsModifiedValues(self, allUserSettings: PersistentSettings) -> bool: ...
    def DeleteChild(self, key: str) -> None: ...
    def DeleteItem(self, key: str) -> None: ...
    @staticmethod
    def FromPlugInId(pluginId: Guid) -> PersistentSettings: ...
    def GetBool(self, key: str, defaultValue: bool, legacyKeyList: IEnumerable) -> bool: ...
    def GetByte(self, key: str, defaultValue: int, legacyKeyList: IEnumerable) -> int: ...
    def GetChar(self, key: str, defaultValue: str, legacyKeyList: IEnumerable) -> str: ...
    def GetChild(self, key: str) -> PersistentSettings: ...
    def GetColor(self, key: str, defaultValue: Color, legacyKeyList: IEnumerable) -> Color: ...
    def GetDate(self, key: str, defaultValue: DateTime, legacyKeyList: IEnumerable) -> DateTime: ...
    def GetDouble(self, key: str, defaultValue: float, legacyKeyList: IEnumerable) -> float: ...
    def GetEnumValue(self, key: str, defaultValue: T) -> T: ...
    def GetGuid(self, key: str, defaultValue: Guid, legacyKeyList: IEnumerable) -> Guid: ...
    def GetInteger(self, key: str, defaultValue: int, bound: int, boundIsLower: bool) -> int: ...
    def GetPoint(self, key: str, defaultValue: Point, legacyKeyList: IEnumerable) -> Point: ...
    def GetPoint3d(self, key: str, defaultValue: Point3d, legacyKeyList: IEnumerable) -> Point3d: ...
    def GetRectangle(self, key: str, defaultValue: Rectangle, legacyKeyList: IEnumerable) -> Rectangle: ...
    def GetSettingIsHiddenFromUserInterface(self, key: str, legacyKeyList: IEnumerable) -> bool: ...
    def GetSettingIsReadOnly(self, key: str) -> bool: ...
    def GetSettingType(self, key: str) -> Type: ...
    def GetSize(self, key: str, defaultValue: Size, legacyKeyList: IEnumerable) -> Size: ...
    def GetString(self, key: str, defaultValue: str, legacyKeyList: IEnumerable) -> str: ...
    def GetStringDictionary(self, key: str, defaultValue: list, legacyKeyList: IEnumerable) -> list: ...
    def GetStringList(self, key: str, defaultValue: list, legacyKeyList: IEnumerable) -> list: ...
    def GetUnsignedInteger(self, key: str, defaultValue: int, legacyKeyList: IEnumerable) -> int: ...
    def GetValidator(self, key: str) -> EventHandler: ...
    def HideSettingFromUserInterface(self, key: str) -> None: ...
    def RegisterSettingsValidator(self, key: str, validator: EventHandler) -> None: ...
    def SetBool(self, key: str, value: bool) -> None: ...
    def SetByte(self, key: str, value: int) -> None: ...
    def SetChar(self, key: str, value: str) -> None: ...
    def SetColor(self, key: str, value: Color) -> None: ...
    def SetDate(self, key: str, value: DateTime) -> None: ...
    def SetDefault(self, key: str, value: bool) -> None: ...
    def SetDouble(self, key: str, value: float) -> None: ...
    def SetEnumValue(self, key: str, value: T) -> None: ...
    def SetGuid(self, key: str, value: Guid) -> None: ...
    def SetInteger(self, key: str, value: int) -> None: ...
    def SetPoint(self, key: str, value: Point) -> None: ...
    def SetPoint3d(self, key: str, value: Point3d) -> None: ...
    def SetRectangle(self, key: str, value: Rectangle) -> None: ...
    def SetSize(self, key: str, value: Size) -> None: ...
    def SetString(self, key: str, value: str) -> None: ...
    def SetStringDictionary(self, key: str, value: list) -> None: ...
    def SetStringList(self, key: str, value: list) -> None: ...
    def SetUnsignedInteger(self, key: str, value: int) -> None: ...
    def TryGetBool(self, key: str, value: bool, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetByte(self, key: str, value: int, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetChar(self, key: str, value: str, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetChild(self, key: str, value: PersistentSettings) -> bool: ...
    def TryGetColor(self, key: str, value: Color, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetDate(self, key: str, value: DateTime, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetDefault(self, key: str, value: bool) -> bool: ...
    def TryGetDouble(self, key: str, value: float, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetEnumValue(self, key: str, enumValue: T) -> bool: ...
    def TryGetGuid(self, key: str, value: Guid, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetInteger(self, key: str, value: int, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetPoint(self, key: str, value: Point, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetPoint3d(self, key: str, value: Point3d, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetRectangle(self, key: str, value: Rectangle, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetSettingIsHiddenFromUserInterface(self, key: str, value: bool, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetSettingIsReadOnly(self, key: str, value: bool) -> bool: ...
    def TryGetSettingType(self, key: str, type: Type) -> bool: ...
    def TryGetSize(self, key: str, value: Size, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetString(self, key: str, value: str, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetStringDictionary(self, key: str, value: list, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetStringList(self, key: str, value: list, legacyKeyList: IEnumerable) -> bool: ...
    def TryGetUnsignedInteger(self, key: str, value: int, legacyKeyList: IEnumerable) -> bool: ...

class PersistentSettingsConverter:
    """.NET: Rhino.PersistentSettingsConverter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def IsStringDictionary(s: str) -> bool: ...
    @staticmethod
    def IsStringList(s: str) -> bool: ...
    @staticmethod
    def ToString(values: list) -> str: ...
    @staticmethod
    def TryParseDouble(s: str, value: float) -> bool: ...
    @staticmethod
    def TryParseEnum(type: Type, intValueAsString: str, value: str) -> bool: ...
    @staticmethod
    def TryParseStringDictionary(s: str, value: list) -> bool: ...
    @staticmethod
    def TryParseStringList(s: str, value: list) -> bool: ...

class PersistentSettingsEventArgs(EventArgs):
    """.NET: Rhino.PersistentSettingsEventArgs | Rhino.PersistentSettingsEventArgs`1"""
    def __init__(self, *args) -> None: ...
    Cancel: bool
    CurrentValue: T
    NewValue: T

class PersistentSettingsSavedEventArgs(EventArgs):
    """.NET: Rhino.PersistentSettingsSavedEventArgs"""
    def __init__(self, *args) -> None: ...
    SavedByThisRhino: bool
    PlugInSettings: PersistentSettings
    def CommandSettings(self, englishCommandName: str) -> PersistentSettings: ...

class ReadFileResult:
    """.NET: Rhino.ReadFileResult"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoApp:
    """.NET: Rhino.RhinoApp"""
    def __init__(self, *args) -> None: ...
    SdkVersion: int
    SdkServiceRelease: int
    ExeVersion: int
    ExeServiceRelease: int
    BuildDate: DateTime
    VersionControlRevision: str
    Version: Version
    SerialNumber: str
    LicenseUserName: str
    LicenseUserOrganization: str
    InstallationTypeString: str
    Name: str
    NodeType: LicenseNode
    InstallationType: Installation
    SchemeName: str
    CheckNewObject: bool
    Rhino2Id: Guid
    Rhino3Id: Guid
    Rhino4Id: Guid
    Rhino5Id: Guid
    Rhino6Id: Guid
    Rhino7Id: Guid
    CurrentRhinoId: Guid
    IsParentDesktop: bool
    IsRunningAutomated: bool
    IsRunningHeadless: bool
    IsSafeModeEnabled: bool
    IsSkinned: bool
    CommandLineOut: CommandLineTextWriter
    CommandWindowCaptureEnabled: bool
    SendWriteToConsole: bool
    InCommand: int
    CommandPrompt: str
    CommandHistoryWindowText: str
    InvokeRequired: bool
    MainApplicationWindow: RhinoWindow
    LicenseExpires: bool
    IsEvaluation: bool
    IsPreRelease: bool
    IsLicenseValidated: bool
    IsCloudZooNode: bool
    IsInternetAccessAllowed: bool
    IsOnMainThread: bool
    CanSave: bool
    UpdatesAndStatisticsStatus: int
    ValidationGracePeriodDaysLeft: int
    DaysUntilExpiration: int
    LoggedInUserName: str
    LoggedInUserAvatar: Image
    UserIsLoggedIn: bool
    IsClosing: bool
    IsExiting: bool
    ToolbarFiles: ToolbarFileCollection
    DefaultUiFont: Font
    @staticmethod
    def AskUserForRhinoLicense(standAlone: bool, parentWindow: object) -> bool: ...
    @staticmethod
    def CapturedCommandWindowStrings(clearBuffer: bool) -> list: ...
    @staticmethod
    def ChangeLicenseKey(pluginId: Guid) -> bool: ...
    @staticmethod
    def ClearCommandHistoryWindow() -> None: ...
    @staticmethod
    def ExecuteCommand(document: RhinoDoc, commandName: str) -> Result: ...
    @staticmethod
    def Exit(allowCancel: bool) -> None: ...
    @staticmethod
    def GetDataDirectory(localUser: bool, forceDirectoryCreation: bool, subDirectory: str) -> str: ...
    @staticmethod
    def GetExecutableDirectory() -> DirectoryInfo: ...
    @staticmethod
    def GetPlugInObject(pluginId: Guid) -> object: ...
    @staticmethod
    def InFullScreen() -> bool: ...
    @staticmethod
    def InvokeAndWait(action: Action) -> None: ...
    @staticmethod
    def InvokeOnUiThread(method: Delegate, args: list) -> None: ...
    @staticmethod
    def IsInstallationBeta(licenseType: Installation) -> bool: ...
    @staticmethod
    def IsInstallationCommercial(licenseType: Installation) -> bool: ...
    @staticmethod
    def IsInstallationEvaluation(licenseType: Installation) -> bool: ...
    @staticmethod
    def LoginToCloudZoo() -> bool: ...
    @staticmethod
    def MainWindow() -> IWin32Window: ...
    @staticmethod
    def MainWindowHandle() -> IntPtr: ...
    @staticmethod
    def OutputDebugString(str: str) -> None: ...
    @staticmethod
    def ParseTextField(formula: str, obj: RhinoObject, topParentObject: RhinoObject, immediateParent: InstanceObject) -> str: ...
    @staticmethod
    def PostCancelEvent(runtimeDocSerialNumber: int) -> None: ...
    @staticmethod
    def PostEnterEvent(runtimeDocSerialNumber: int, bRepeatedEnter: bool) -> None: ...
    @staticmethod
    def RefreshRhinoLicense() -> bool: ...
    @staticmethod
    def ReleaseMouseCapture() -> bool: ...
    @staticmethod
    def RunMenuScript(script: str) -> bool: ...
    @staticmethod
    def RunScript(documentSerialNumber: int, script: str, mruDisplayString: str, echo: bool) -> bool: ...
    @staticmethod
    def RunningInRdp() -> bool: ...
    @staticmethod
    def RunningOnVMWare() -> bool: ...
    @staticmethod
    def SendKeystrokes(characters: str, appendReturn: bool) -> None: ...
    @staticmethod
    def SetCommandPrompt(prompt: str, promptDefault: str) -> None: ...
    @staticmethod
    def SetCommandPromptMessage(prompt: str) -> None: ...
    @staticmethod
    def SetFocusToMainWindow(doc: RhinoDoc) -> None: ...
    @staticmethod
    def Wait() -> None: ...
    @staticmethod
    def Write(format: str, arg0: object, arg1: object, arg2: object) -> None: ...
    @staticmethod
    def WriteLine(format: str, arg0: object, arg1: object, arg2: object) -> None: ...

class RhinoDoc:
    """.NET: Rhino.RhinoDoc"""
    def __init__(self, *args) -> None: ...
    IsHeadless: bool
    ActiveDoc: RhinoDoc
    Name: str
    Path: str
    Notes: str
    NotesLocked: bool
    DateCreated: DateTime
    DateLastEdited: DateTime
    LinkedInstanceDefinitionUpdate: LinkedInstanceDefinitionUpdateStyle
    ActiveCommandId: Guid
    ModelAbsoluteTolerance: float
    ModelAngleToleranceRadians: float
    ModelAngleToleranceDegrees: float
    ModelRelativeTolerance: float
    ModelDistanceDisplayPrecision: int
    PageDistanceDisplayPrecision: int
    PageAbsoluteTolerance: float
    PageAngleToleranceRadians: float
    PageAngleToleranceDegrees: float
    PageRelativeTolerance: float
    ModelDistanceDisplayMode: DistanceDisplayMode
    PageDistanceDisplayMode: DistanceDisplayMode
    ModelBasepoint: Point3d
    Modified: bool
    SubDAppearance: SubDComponentLocation
    ModelUnitSystem: UnitSystem
    PageUnitSystem: UnitSystem
    DistanceDisplayPrecision: int
    ActiveSpace: ActiveSpace
    IsReadOnly: bool
    IsLocked: bool
    IsInitializing: bool
    IsCreating: bool
    IsOpening: bool
    IsAvailable: bool
    IsClosing: bool
    DocumentId: int
    RuntimeSerialNumber: int
    EarthAnchorPoint: EarthAnchorPoint
    RenderSettings: RenderSettings
    AnimationProperties: AnimationProperties
    CustomRenderSizes: List
    MeshingParameterStyle: MeshingParameterStyle
    ModelSpaceHatchScale: float
    ModelSpaceHatchScalingEnabled: bool
    ModelSpaceTextScale: float
    ModelSpaceAnnotationScalingEnabled: bool
    LayoutSpaceAnnotationScalingEnabled: bool
    Worksession: Worksession
    Views: ViewTable
    Objects: ObjectTable
    Manifest: ManifestTable
    Bitmaps: BitmapTable
    Materials: MaterialTable
    Linetypes: LinetypeTable
    Layers: LayerTable
    Groups: GroupTable
    Fonts: FontTable
    DimStyles: DimStyleTable
    Lights: LightTable
    HatchPatterns: HatchPatternTable
    InstanceDefinitions: InstanceDefinitionTable
    NamedConstructionPlanes: NamedConstructionPlaneTable
    NamedViews: NamedViewTable
    Strings: StringTable
    RuntimeData: RuntimeDocumentDataTable
    NamedPositions: NamedPositionTable
    Snapshots: SnapshotTable
    NamedLayerStates: NamedLayerStateTable
    RenderMaterials: RenderMaterialTable
    RenderEnvironments: RenderEnvironmentTable
    RenderTextures: RenderTextureTable
    CurrentEnvironment: ICurrentEnvironment
    PostEffects: IPostEffects
    GroundPlane: GroundPlane
    InGetPoint: bool
    IsSendingMail: bool
    TemplateFileUsed: str
    UndoRecordingEnabled: bool
    UndoRecordingIsActive: bool
    NextUndoRecordSerialNumber: int
    CurrentUndoRecordSerialNumber: int
    UndoActive: bool
    RedoActive: bool
    IsCommandRunning: bool
    def AddCustomUndoEvent(self, description: str, handler: EventHandler, tag: object) -> bool: ...
    def AdjustModelUnitSystem(self, newUnitSystem: UnitSystem, scale: bool) -> None: ...
    def AdjustPageUnitSystem(self, newUnitSystem: UnitSystem, scale: bool) -> None: ...
    def Audit(self, textLog: TextLog, attemptRepair: bool) -> bool: ...
    def BeginUndoRecord(self, description: str) -> int: ...
    def ClearRedoRecords(self, ) -> None: ...
    def ClearUndoRecords(self, undoSerialNumber: int, purgeDeletedObjects: bool) -> None: ...
    @staticmethod
    def Create(modelTemplateFileName: str) -> RhinoDoc: ...
    def CreateDefaultAttributes(self, ) -> ObjectAttributes: ...
    @staticmethod
    def CreateHeadless(file3dmTemplatePath: str) -> RhinoDoc: ...
    def CustomRenderMeshesBoundingBox(self, mt: MeshType, vp: ViewportInfo, flags: Flags, plugin: PlugIn, attrs: DisplayPipelineAttributes, boundingBox: BoundingBox) -> bool: ...
    def Dispose(self, ) -> None: ...
    def EndUndoRecord(self, undoRecordSerialNumber: int) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    def Export(self, filePath: str, options: ArchivableDictionary) -> bool: ...
    def ExportSelected(self, filePath: str, options: ArchivableDictionary) -> bool: ...
    @staticmethod
    def ExtractPreviewImage(path: str) -> Bitmap: ...
    def FindFile(self, filename: str) -> str: ...
    def FormatNumber(self, value: float, appendUnitSystemName: bool, abbreviate: bool) -> str: ...
    @staticmethod
    def FromFilePath(filePath: str) -> RhinoDoc: ...
    @staticmethod
    def FromId(docId: int) -> RhinoDoc: ...
    @staticmethod
    def FromRuntimeSerialNumber(serialNumber: int) -> RhinoDoc: ...
    def GetAnalysisMeshingParameters(self, ) -> MeshingParameters: ...
    def GetCurrentMeshingParameters(self, ) -> MeshingParameters: ...
    def GetCustomUnitSystem(self, modelUnits: bool, customUnitName: str, metersPerCustomUnit: float) -> bool: ...
    def GetEmbeddedFilesList(self, missingOnly: bool) -> list: ...
    def GetGridDefaults(self, ) -> ConstructionPlaneGridDefaults: ...
    def GetGumballPlane(self, plane: Plane) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetMeshingParameters(self, style: MeshingParameterStyle) -> MeshingParameters: ...
    def GetRenderPrimitiveList(self, viewport: ViewportInfo, attrs: DisplayPipelineAttributes) -> RenderPrimitiveList: ...
    def GetRenderPrimitives(self, plugInId: Guid, viewport: ViewportInfo, forceTriangleMeshes: bool, quietly: bool) -> IEnumerable: ...
    def GetUnitSystemName(self, modelUnits: bool, capitalize: bool, singular: bool, abbreviate: bool) -> str: ...
    def HasCustomRenderMeshes(self, mt: MeshType, vp: ViewportInfo, flags: Flags, plugin: PlugIn, attrs: DisplayPipelineAttributes) -> bool: ...
    def Import(self, filePath: str, options: ArchivableDictionary) -> bool: ...
    def InCommand(self, bIgnoreScriptRunnerCommands: bool) -> int: ...
    def IsMetricUnitSystem(self, modelUnits: bool) -> bool: ...
    @staticmethod
    def Open(filePath: str, wasAlreadyOpen: bool) -> RhinoDoc: ...
    @staticmethod
    def OpenDocuments(includeHeadless: bool) -> list: ...
    @staticmethod
    def OpenFile(path: str) -> bool: ...
    @staticmethod
    def OpenHeadless(filePath: str, options: ArchivableDictionary) -> RhinoDoc: ...
    @staticmethod
    def ReadFile(path: str, options: FileReadOptions) -> bool: ...
    def ReadFileVersion(self, ) -> int: ...
    def Redo(self, ) -> bool: ...
    def RenderMeshes(self, mt: MeshType, vp: ViewportInfo, flags: Flags, plugin: PlugIn, attrs: DisplayPipelineAttributes) -> list: ...
    def Save(self, ) -> bool: ...
    def SaveAs(self, file3dmPath: str, version: int, saveSmall: bool, saveTextures: bool, saveGeometryOnly: bool, savePluginData: bool) -> bool: ...
    def SaveAsTemplate(self, file3dmTemplatePath: str, version: int) -> bool: ...
    def SelectRenderContentInEditor(self, collection: RenderContentCollection, append: bool) -> None: ...
    def SetCustomMeshingParameters(self, mp: MeshingParameters) -> None: ...
    def SetCustomUnitSystem(self, modelUnits: bool, customUnitName: str, metersPerCustomUnit: float, scale: bool) -> bool: ...
    def SetGridDefaults(self, defaults: ConstructionPlaneGridDefaults) -> None: ...
    def SupportsRenderPrimitiveList(self, viewport: ViewportInfo, attrs: DisplayPipelineAttributes) -> bool: ...
    def TryGetRenderPrimitiveBoundingBox(self, viewport: ViewportInfo, attrs: DisplayPipelineAttributes, boundingBox: BoundingBox) -> bool: ...
    def Undo(self, ) -> bool: ...
    def Write3dmFile(self, path: str, options: FileWriteOptions) -> bool: ...
    def WriteFile(self, path: str, options: FileWriteOptions) -> bool: ...

class RhinoDocObserverArgs:
    """.NET: Rhino.RhinoDocObserverArgs"""
    def __init__(self, *args) -> None: ...
    Doc: RhinoDoc
    RuntimeSerialNumber: int

class RhinoDocUndoRecord:
    """.NET: Rhino.RhinoDocUndoRecord"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class RhinoFileWatcherChangeReason:
    """.NET: Rhino.RhinoFileWatcherChangeReason"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoMath:
    """.NET: Rhino.RhinoMath"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CRC32(currentRemainder: int, buffer: list) -> int: ...
    @staticmethod
    def Clamp(value: int, bound1: int, bound2: int) -> int: ...
    @staticmethod
    def EpsilonEquals(x: float, y: float, epsilon: float) -> bool: ...
    @staticmethod
    def EvaluateNormal(limitDirection: int, ds: Vector3d, dt: Vector3d, dss: Vector3d, dst: Vector3d, dtt: Vector3d, n: Vector3d) -> bool: ...
    @staticmethod
    def EvaluateNormalPartials(ds: Vector3d, dt: Vector3d, dss: Vector3d, dst: Vector3d, dtt: Vector3d, ns: Vector3d, nt: Vector3d) -> bool: ...
    @staticmethod
    def EvaluateSectionalCurvature(ds: Vector3d, dt: Vector3d, dss: Vector3d, dst: Vector3d, dtt: Vector3d, planeNormal: Vector3d, k: Vector3d) -> bool: ...
    @staticmethod
    def IntIndexToString(index: int) -> str: ...
    @staticmethod
    def IsValidDouble(x: float) -> bool: ...
    @staticmethod
    def IsValidSingle(x: float) -> bool: ...
    @staticmethod
    def MetersPerUnit(units: UnitSystem) -> float: ...
    @staticmethod
    def ParseNumber(expression: str) -> float: ...
    @staticmethod
    def ToDegrees(radians: float) -> float: ...
    @staticmethod
    def ToRadians(degrees: float) -> float: ...
    @staticmethod
    def TryParseNumber(expression: str, result: float) -> bool: ...
    @staticmethod
    def UnitScale(from_: UnitSystem, fromMetersPerUnit: float, to: UnitSystem, toMetersPerUnit: float) -> float: ...
    @staticmethod
    def Wrap(value: float, bound1: float, bound2: float) -> float: ...

class RhinoWindow:
    """.NET: Rhino.RhinoWindow"""
    def __init__(self, *args) -> None: ...
    Handle: IntPtr
    InvokeRequired: bool
    def Invoke(self, method: Delegate) -> None: ...

class RuntimeEnvironment:
    """.NET: Rhino.RuntimeEnvironment"""
    def __init__(self, *args) -> None: ...
    ...

class ScaleValue:
    """.NET: Rhino.ScaleValue"""
    def __init__(self, *args) -> None: ...
    LeftToRightScale: float
    RightToLeftScale: float
    @staticmethod
    def Create(left: LengthValue, right: LengthValue, format: ScaleStringFormat) -> ScaleValue: ...
    def Dispose(self, ) -> None: ...
    def IsUnset(self, ) -> bool: ...
    def LeftLengthValue(self, ) -> LengthValue: ...
    @staticmethod
    def OneToOne() -> ScaleValue: ...
    def RightLengthValue(self, ) -> LengthValue: ...

class Symbols:
    """.NET: Rhino.Symbols"""
    def __init__(self, *args) -> None: ...
    DegreeSymbol: str
    RadiusSymbol: str
    DiameterSymbol: str
    PlusMinusSymbol: str

class UnitSystem:
    """.NET: Rhino.UnitSystem"""
    def __init__(self, *args) -> None: ...
    ...

class UnitsChangedWithScalingEventArgs(EventArgs):
    """.NET: Rhino.UnitsChangedWithScalingEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentSerialNumber: int
    Document: RhinoDoc
    Scale: float
