# Auto-generated — Rhino 8 — Rhino.Collections

class ArchivableDictionary:
    """.NET: Rhino.Collections.ArchivableDictionary"""
    def __init__(self, *args) -> None: ...
    Version: int
    Name: str
    ChangeSerialNumber: int
    ParentUserData: UserData
    Keys: list
    Values: list
    Item: object
    Count: int
    def AddContentsFrom(self, source: ArchivableDictionary) -> bool: ...
    def Clear(self, ) -> None: ...
    def Clone(self, ) -> ArchivableDictionary: ...
    def ContainsKey(self, key: str) -> bool: ...
    def GetBool(self, key: str, defaultValue: bool) -> bool: ...
    def GetBytes(self, key: str, defaultValue: list) -> list: ...
    def GetDictionary(self, key: str, defaultValue: ArchivableDictionary) -> ArchivableDictionary: ...
    def GetDouble(self, key: str, defaultValue: float) -> float: ...
    def GetEnumValue(self, key: str) -> T: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetFloat(self, key: str, defaultValue: float) -> float: ...
    def GetGuid(self, key: str, defaultValue: Guid) -> Guid: ...
    def GetInteger(self, key: str, defaultValue: int) -> int: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    def GetPlane(self, key: str, defaultValue: Plane) -> Plane: ...
    def GetPoint3d(self, key: str, defaultValue: Point3d) -> Point3d: ...
    def GetPoint3f(self, key: str, defaultValue: Point3f) -> Point3f: ...
    def GetString(self, key: str, defaultValue: str) -> str: ...
    def GetVector3d(self, key: str, defaultValue: Vector3d) -> Vector3d: ...
    def Getint(self, key: str, defaultValue: int) -> int: ...
    def Remove(self, key: str) -> bool: ...
    def RemoveEnumValue(self, ) -> bool: ...
    def ReplaceContentsWith(self, source: ArchivableDictionary) -> bool: ...
    def Set(self, key: str, val: bool) -> bool: ...
    def SetEnumValue(self, key: str, enumValue: T) -> bool: ...
    def TryGetBool(self, key: str, value: bool) -> bool: ...
    def TryGetBytes(self, key: str, value: list) -> bool: ...
    def TryGetDictionary(self, key: str, value: ArchivableDictionary) -> bool: ...
    def TryGetDouble(self, key: str, value: float) -> bool: ...
    def TryGetEnumValue(self, key: str, enumValue: T) -> bool: ...
    def TryGetFloat(self, key: str, value: float) -> bool: ...
    def TryGetGuid(self, key: str, value: Guid) -> bool: ...
    def TryGetInteger(self, key: str, value: int) -> bool: ...
    def TryGetPlane(self, key: str, value: Plane) -> bool: ...
    def TryGetPoint3d(self, key: str, value: Point3d) -> bool: ...
    def TryGetPoint3f(self, key: str, value: Point3f) -> bool: ...
    def TryGetString(self, key: str, value: str) -> bool: ...
    def TryGetValue(self, key: str, value: object) -> bool: ...
    def TryGetVector3d(self, key: str, value: Vector3d) -> bool: ...

class CurveList(RhinoList):
    """.NET: Rhino.Collections.CurveList"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    NullCount: int
    Item: Curve
    First: Curve
    Last: Curve
    def Add(self, line: Line) -> None: ...
    def Insert(self, index: int, line: Line) -> None: ...
    def Transform(self, xform: Transform) -> bool: ...

class IResizableList:
    """.NET: Rhino.Collections.IResizableList`1"""
    def __init__(self, *args) -> None: ...
    Count: int

class Point3dList(RhinoList):
    """.NET: Rhino.Collections.Point3dList"""
    def __init__(self, *args) -> None: ...
    BoundingBox: BoundingBox
    X: XAccess
    Y: YAccess
    Z: ZAccess
    Capacity: int
    Count: int
    NullCount: int
    Item: Point3d
    First: Point3d
    Last: Point3d
    def Add(self, x: float, y: float, z: float) -> None: ...
    def ClosestIndex(self, testPoint: Point3d) -> int: ...
    @staticmethod
    def ClosestIndexInList(list: IList, testPoint: Point3d) -> int: ...
    @staticmethod
    def ClosestPointInList(list: IList, testPoint: Point3d) -> Point3d: ...
    def Duplicate(self, ) -> Point3dList: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def SetAllX(self, xValue: float) -> None: ...
    def SetAllY(self, yValue: float) -> None: ...
    def SetAllZ(self, zValue: float) -> None: ...
    def Transform(self, xform: Transform) -> None: ...

class RhinoList:
    """.NET: Rhino.Collections.RhinoList | Rhino.Collections.RhinoList`1"""
    def __init__(self, *args) -> None: ...
    Capacity: int
    Count: int
    NullCount: int
    Item: T
    First: T
    Last: T
    def Add(self, item: T) -> None: ...
    def AddRange(self, collection: IEnumerable) -> None: ...
    def AsReadOnly(self, ) -> ReadOnlyCollection: ...
    def BinarySearch(self, index: int, count: int, item: T, comparer: IComparer) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: T) -> bool: ...
    def ConvertAll(self, converter: Converter) -> RhinoList: ...
    def CopyTo(self, index: int, array: list, arrayIndex: int, count: int) -> None: ...
    def Duplicate(self, ) -> RhinoList: ...
    def Exists(self, match: Predicate) -> bool: ...
    def Find(self, match: Predicate) -> T: ...
    def FindAll(self, match: Predicate) -> RhinoList: ...
    def FindIndex(self, startIndex: int, count: int, match: Predicate) -> int: ...
    def FindLast(self, match: Predicate) -> T: ...
    def FindLastIndex(self, startIndex: int, count: int, match: Predicate) -> int: ...
    def ForEach(self, action: Action) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetRange(self, index: int, count: int) -> RhinoList: ...
    def IndexOf(self, item: T, index: int, count: int) -> int: ...
    def Insert(self, index: int, item: T) -> None: ...
    def InsertRange(self, index: int, collection: IEnumerable) -> None: ...
    def LastIndexOf(self, item: T, index: int, count: int) -> int: ...
    @staticmethod
    def Point2dKNeighbors(hayPoints: IEnumerable, needlePoints: IEnumerable, amount: int) -> IEnumerable: ...
    @staticmethod
    def Point2fKNeighbors(hayPoints: IEnumerable, needlePoints: IEnumerable, amount: int) -> IEnumerable: ...
    @staticmethod
    def Point3dKNeighbors(hayPoints: IEnumerable, needlePoints: IEnumerable, amount: int) -> IEnumerable: ...
    @staticmethod
    def Point3fKNeighbors(hayPoints: IEnumerable, needlePoints: IEnumerable, amount: int) -> IEnumerable: ...
    @staticmethod
    def PointCloudKNeighbors(pointcloud: PointCloud, needlePoints: IEnumerable, amount: int) -> IEnumerable: ...
    def RemapIndex(self, index: int) -> int: ...
    def Remove(self, item: T) -> bool: ...
    def RemoveAll(self, match: Predicate) -> int: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveNulls(self, ) -> int: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def Reverse(self, index: int, count: int) -> None: ...
    def Sort(self, index: int, count: int, comparer: IComparer) -> None: ...
    def ToArray(self, ) -> list: ...
    def TrimExcess(self, ) -> None: ...
    def TrueForAll(self, match: Predicate) -> bool: ...

class TransformObjectList:
    """.NET: Rhino.Collections.TransformObjectList"""
    def __init__(self, *args) -> None: ...
    DisplayFeedbackEnabled: bool
    Count: int
    GripCount: int
    GripOwnerCount: int
    def Add(self, rhinoObject: RhinoObject) -> None: ...
    def AddObjects(self, go: GetObject, allowGrips: bool) -> int: ...
    def Clear(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetBoundingBox(self, regularObjects: bool, grips: bool) -> BoundingBox: ...
    def GripArray(self, ) -> list: ...
    def GripOwnerArray(self, ) -> list: ...
    def ObjectArray(self, ) -> list: ...
    def UpdateDisplayFeedbackTransform(self, xform: Transform) -> bool: ...
