# Auto-generated — Rhino 8 — Rhino.Display

class BackgroundStyle:
    """.NET: Rhino.Display.BackgroundStyle"""
    def __init__(self, *args) -> None: ...
    ...

class BlendMode:
    """.NET: Rhino.Display.BlendMode"""
    def __init__(self, *args) -> None: ...
    ...

class CalculateBoundingBoxEventArgs(DrawEventArgs):
    """.NET: Rhino.Display.CalculateBoundingBoxEventArgs"""
    def __init__(self, *args) -> None: ...
    BoundingBox: BoundingBox
    Viewport: RhinoViewport
    Display: DisplayPipeline
    RhinoDoc: RhinoDoc
    def IncludeBoundingBox(self, box: BoundingBox) -> None: ...

class Color4f:
    """.NET: Rhino.Display.Color4f"""
    def __init__(self, *args) -> None: ...
    Empty: Color4f
    Black: Color4f
    White: Color4f
    R: float
    G: float
    B: float
    A: float
    L: float
    @staticmethod
    def ApplyGamma(col: Color4f, gamma: float) -> Color4f: ...
    def AsSystemColor(self, ) -> Color: ...
    def BlendTo(self, t: float, col: Color4f) -> Color4f: ...
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def FromArgb(a: float, r: float, g: float, b: float) -> Color4f: ...
    def GetHashCode(self, ) -> int: ...

class ColorCMYK:
    """.NET: Rhino.Display.ColorCMYK"""
    def __init__(self, *args) -> None: ...
    C: float
    M: float
    Y: float
    K: float
    A: float
    @staticmethod
    def CreateFromHSL(hsl: ColorHSL) -> ColorCMYK: ...
    @staticmethod
    def CreateFromHSV(hsv: ColorHSV) -> ColorCMYK: ...
    @staticmethod
    def CreateFromLAB(lab: ColorLAB) -> ColorCMYK: ...
    @staticmethod
    def CreateFromLCH(lch: ColorLCH) -> ColorCMYK: ...
    @staticmethod
    def CreateFromRGBA(rgba: ColorRGBA) -> ColorCMYK: ...
    @staticmethod
    def CreateFromXYZ(xyz: ColorXYZ) -> ColorCMYK: ...

class ColorGradient:
    """.NET: Rhino.Display.ColorGradient"""
    def __init__(self, *args) -> None: ...
    GradientType: GradientType
    Repeat: float
    StartPoint: Point3d
    EndPoint: Point3d
    def Duplicate(self, ) -> ColorGradient: ...
    def GetColorStops(self, ) -> list: ...
    def SetColorStops(self, stops: IEnumerable) -> None: ...

class ColorHSL:
    """.NET: Rhino.Display.ColorHSL"""
    def __init__(self, *args) -> None: ...
    H: float
    S: float
    L: float
    A: float
    @staticmethod
    def CreateFromCMYK(cmyk: ColorCMYK) -> ColorHSL: ...
    @staticmethod
    def CreateFromHSV(hsv: ColorHSV) -> ColorHSL: ...
    @staticmethod
    def CreateFromLAB(lab: ColorLAB) -> ColorHSL: ...
    @staticmethod
    def CreateFromLCH(lch: ColorLCH) -> ColorHSL: ...
    @staticmethod
    def CreateFromRGBA(rgba: ColorRGBA) -> ColorHSL: ...
    @staticmethod
    def CreateFromXYZ(xyz: ColorXYZ) -> ColorHSL: ...
    def ToArgbColor(self, ) -> Color: ...

class ColorHSV:
    """.NET: Rhino.Display.ColorHSV"""
    def __init__(self, *args) -> None: ...
    H: float
    S: float
    V: float
    A: float
    @staticmethod
    def CreateFromCMYK(cmyk: ColorCMYK) -> ColorHSV: ...
    @staticmethod
    def CreateFromHSL(hsl: ColorHSL) -> ColorHSV: ...
    @staticmethod
    def CreateFromLAB(lab: ColorLAB) -> ColorHSV: ...
    @staticmethod
    def CreateFromLCH(lch: ColorLCH) -> ColorHSV: ...
    @staticmethod
    def CreateFromRGBA(rgba: ColorRGBA) -> ColorHSV: ...
    @staticmethod
    def CreateFromXYZ(xyz: ColorXYZ) -> ColorHSV: ...
    def ToArgbColor(self, ) -> Color: ...

class ColorLAB:
    """.NET: Rhino.Display.ColorLAB"""
    def __init__(self, *args) -> None: ...
    L: float
    A: float
    B: float
    Alpha: float
    @staticmethod
    def CreateFromCMYK(cmyk: ColorCMYK) -> ColorLAB: ...
    @staticmethod
    def CreateFromHSL(hsl: ColorHSL) -> ColorLAB: ...
    @staticmethod
    def CreateFromHSV(hsv: ColorHSV) -> ColorLAB: ...
    @staticmethod
    def CreateFromLCH(lch: ColorLCH) -> ColorLAB: ...
    @staticmethod
    def CreateFromRGBA(rgb: ColorRGBA) -> ColorLAB: ...
    @staticmethod
    def CreateFromXYZ(xyz: ColorXYZ) -> ColorLAB: ...

class ColorLCH:
    """.NET: Rhino.Display.ColorLCH"""
    def __init__(self, *args) -> None: ...
    L: float
    C: float
    H: float
    A: float
    @staticmethod
    def CreateFromCMYK(cmyk: ColorCMYK) -> ColorLCH: ...
    @staticmethod
    def CreateFromHSL(hsl: ColorHSL) -> ColorLCH: ...
    @staticmethod
    def CreateFromLAB(lab: ColorLAB) -> ColorLCH: ...
    @staticmethod
    def CreateFromRGBA(rgb: ColorRGBA) -> ColorLCH: ...
    @staticmethod
    def CreateFromXYZ(xyz: ColorXYZ) -> ColorLCH: ...
    def MakePositive(self, ) -> None: ...

class ColorRGBA:
    """.NET: Rhino.Display.ColorRGBA"""
    def __init__(self, *args) -> None: ...
    R: float
    G: float
    B: float
    A: float
    Black: ColorRGBA
    White: ColorRGBA
    Red: ColorRGBA
    Green: ColorRGBA
    Blue: ColorRGBA
    @staticmethod
    def ApplyGamma(col: ColorRGBA, gamma: float) -> ColorRGBA: ...
    def BlendTo(self, col: ColorRGBA, coefficient: float) -> ColorRGBA: ...
    def CompareTo(self, other: ColorRGBA) -> int: ...
    @staticmethod
    def CreateFromArgb(alpha: int, red: int, green: int, blue: int) -> ColorRGBA: ...
    @staticmethod
    def CreateFromCMYK(cmyk: ColorCMYK) -> ColorRGBA: ...
    @staticmethod
    def CreateFromHSL(hsl: ColorHSL) -> ColorRGBA: ...
    @staticmethod
    def CreateFromHSV(hsv: ColorHSV) -> ColorRGBA: ...
    @staticmethod
    def CreateFromLAB(lab: ColorLAB) -> ColorRGBA: ...
    @staticmethod
    def CreateFromLCH(lch: ColorLCH) -> ColorRGBA: ...
    @staticmethod
    def CreateFromXYZ(xyz: ColorXYZ) -> ColorRGBA: ...
    def EpsilonEquals(self, other: ColorRGBA, epsilon: float) -> bool: ...
    def Equals(self, other: ColorRGBA) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def ToArgb(self, ) -> int: ...
    def ToString(self, format: str, formatProvider: IFormatProvider) -> str: ...

class ColorStop:
    """.NET: Rhino.Display.ColorStop"""
    def __init__(self, *args) -> None: ...
    Color: Color
    Position: float

class ColorXYZ:
    """.NET: Rhino.Display.ColorXYZ"""
    def __init__(self, *args) -> None: ...
    X: float
    Y: float
    Z: float
    A: float
    @staticmethod
    def CreateFromCMYK(cmyk: ColorCMYK) -> ColorXYZ: ...
    @staticmethod
    def CreateFromHSL(hsl: ColorHSL) -> ColorXYZ: ...
    @staticmethod
    def CreateFromHSV(hsv: ColorHSV) -> ColorXYZ: ...
    @staticmethod
    def CreateFromLAB(lab: ColorLAB) -> ColorXYZ: ...
    @staticmethod
    def CreateFromLCH(lch: ColorLCH) -> ColorXYZ: ...
    @staticmethod
    def CreateFromRGBA(rgba: ColorRGBA) -> ColorXYZ: ...

class CullFaceMode:
    """.NET: Rhino.Display.CullFaceMode"""
    def __init__(self, *args) -> None: ...
    ...

class CullObjectEventArgs(DrawEventArgs):
    """.NET: Rhino.Display.CullObjectEventArgs"""
    def __init__(self, *args) -> None: ...
    RhinoObject: RhinoObject
    RhinoObjectSerialNumber: int
    CullObject: bool
    Viewport: RhinoViewport
    Display: DisplayPipeline
    RhinoDoc: RhinoDoc

class CustomDisplay:
    """.NET: Rhino.Display.CustomDisplay"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    IsDisposed: bool
    ClippingBox: BoundingBox
    def AddArc(self, arc: Arc, color: Color, thickness: int) -> None: ...
    def AddCircle(self, circle: Circle, color: Color, thickness: int) -> None: ...
    def AddCurve(self, curve: Curve, color: Color, thickness: int) -> None: ...
    def AddLine(self, line: Line, color: Color, thickness: int) -> None: ...
    def AddPoint(self, point: Point3d, color: Color, style: PointStyle, radius: int) -> None: ...
    def AddPoints(self, points: IEnumerable, color: Color, style: PointStyle, radius: int) -> None: ...
    def AddPolygon(self, polygon: IEnumerable, fillColor: Color, edgeColor: Color, drawFill: bool, drawEdge: bool) -> None: ...
    def AddText(self, text: str, plane: Plane, size: float, color: Color) -> None: ...
    def AddVector(self, anchor: Point3d, span: Vector3d, color: Color, drawAnchor: bool) -> None: ...
    def Clear(self, ) -> None: ...
    def Dispose(self, ) -> None: ...

class DefinedViewportProjection:
    """.NET: Rhino.Display.DefinedViewportProjection"""
    def __init__(self, *args) -> None: ...
    ...

class DepthMode:
    """.NET: Rhino.Display.DepthMode"""
    def __init__(self, *args) -> None: ...
    ...

class DisplayBitmap:
    """.NET: Rhino.Display.DisplayBitmap"""
    def __init__(self, *args) -> None: ...
    Size: Size
    def Dispose(self, ) -> None: ...
    def GetBlendModes(self, source: BlendMode, destination: BlendMode) -> None: ...
    @staticmethod
    def Load(path: str) -> DisplayBitmap: ...
    def SetBlendFunction(self, source: BlendMode, destination: BlendMode) -> None: ...
    def Update(self, bitmap: Bitmap) -> None: ...

class DisplayBitmapDrawList:
    """.NET: Rhino.Display.DisplayBitmapDrawList"""
    def __init__(self, *args) -> None: ...
    BoundingBox: BoundingBox
    MaximumCachedSortLists: int
    SortAngleTolerance: float
    def SetPoints(self, points: IEnumerable, blendColor: Color) -> None: ...
    def Sort(self, cameraDirection: Vector3d) -> list: ...

class DisplayConduit:
    """.NET: Rhino.Display.DisplayConduit"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    GeometryFilter: ObjectType
    SpaceFilter: ActiveSpace
    def GetSelectionFilter(self, on: bool, checkSubObjects: bool) -> None: ...
    def SetObjectIdFilter(self, id: Guid) -> None: ...
    def SetSelectionFilter(self, on: bool, checkSubObjects: bool) -> None: ...

class DisplayEngine:
    """.NET: Rhino.Display.DisplayEngine"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class DisplayMaterial:
    """.NET: Rhino.Display.DisplayMaterial"""
    def __init__(self, *args) -> None: ...
    Diffuse: Color
    BackDiffuse: Color
    Specular: Color
    BackSpecular: Color
    Ambient: Color
    BackAmbient: Color
    Emission: Color
    BackEmission: Color
    Shine: float
    BackShine: float
    Transparency: float
    BackTransparency: float
    IsTwoSided: bool
    def Dispose(self, ) -> None: ...
    def GetBitmapTexture(self, front: bool) -> Texture: ...
    def GetBumpTexture(self, front: bool) -> Texture: ...
    def GetEnvironmentTexture(self, front: bool) -> Texture: ...
    def GetTransparencyTexture(self, front: bool) -> Texture: ...
    def SetBitmapTexture(self, filename: str, front: bool) -> bool: ...
    def SetBumpTexture(self, filename: str, front: bool) -> bool: ...
    def SetEnvironmentTexture(self, filename: str, front: bool) -> bool: ...
    def SetTransparencyTexture(self, filename: str, front: bool) -> bool: ...

class DisplayModeChangedEventArgs(EventArgs):
    """.NET: Rhino.Display.DisplayModeChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    Viewport: RhinoViewport
    RhinoDoc: RhinoDoc
    OldDisplayModeId: Guid
    ChangedDisplayModeId: Guid

class DisplayModeDescription:
    """.NET: Rhino.Display.DisplayModeDescription"""
    def __init__(self, *args) -> None: ...
    InMenu: bool
    SupportsShadeCommand: bool
    SupportsShading: bool
    AllowObjectAssignment: bool
    ShadedPipelineRequired: bool
    WireframePipelineRequired: bool
    PipelineLocked: bool
    DisplayAttributes: DisplayPipelineAttributes
    EnglishName: str
    Id: Guid
    LocalName: str
    ArtisticId: Guid
    GhostedId: Guid
    PenId: Guid
    RenderedId: Guid
    RenderedShadowsId: Guid
    ShadedId: Guid
    TechId: Guid
    WireframeId: Guid
    XRayId: Guid
    AmbientOcclusionId: Guid
    RaytracedId: Guid
    MonochromeId: Guid
    @staticmethod
    def AddDisplayMode(displayMode: DisplayModeDescription) -> Guid: ...
    @staticmethod
    def CopyDisplayMode(id: Guid, name: str) -> Guid: ...
    @staticmethod
    def DeleteDiplayMode(id: Guid) -> bool: ...
    @staticmethod
    def DeleteDisplayMode(id: Guid) -> bool: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def ExportToFile(displayMode: DisplayModeDescription, filename: str) -> bool: ...
    @staticmethod
    def FindByName(englishName: str) -> DisplayModeDescription: ...
    @staticmethod
    def GetDisplayMode(id: Guid) -> DisplayModeDescription: ...
    @staticmethod
    def GetDisplayModes() -> list: ...
    @staticmethod
    def ImportFromFile(filename: str, interactive: bool) -> Guid: ...
    @staticmethod
    def UpdateDisplayMode(displayMode: DisplayModeDescription) -> bool: ...

class DisplayPen:
    """.NET: Rhino.Display.DisplayPen"""
    def __init__(self, *args) -> None: ...
    Color: Color
    Thickness: float
    ThicknessSpace: CoordinateSystem
    CapStyle: LineCapStyle
    JoinStyle: LineJoinStyle
    HaloThickness: float
    HaloColor: Color
    PatternOffset: float
    PatternBySegment: bool
    PatternLengthInWorldUnits: bool
    def Duplicate(self, ) -> DisplayPen: ...
    @staticmethod
    def FromLinetype(linetype: Linetype, color: Color, patternScale: float) -> DisplayPen: ...
    def PatternAsArray(self, ) -> list: ...
    def SetPattern(self, dashesAndGaps: IEnumerable) -> None: ...
    def SetTaper(self, startThickness: float, endThickness: float, taperPoint: Point2f) -> None: ...
    def TaperAsArray(self, ) -> list: ...

class DisplayPipeline:
    """.NET: Rhino.Display.DisplayPipeline"""
    def __init__(self, *args) -> None: ...
    Technology: DisplayTechnology
    FrameSize: Size
    FrameBuffer: Bitmap
    DefaultCurveThickness: int
    IsOpenGL: bool
    IsStereoMode: bool
    IsPrinting: bool
    IsInViewCapture: bool
    IsDynamicDisplay: bool
    SupportsShading: bool
    StereoProjection: int
    ModelTransform: Transform
    ModelTransformIsIdentity: bool
    RenderPass: int
    NestLevel: int
    ActiveTopLevelObject: RhinoObject
    ActiveObject: RhinoObject
    ActiveObjectNestingLevel: int
    ActiveObjectNestingStack: list
    IsOpen: bool
    DrawingWires: bool
    DrawingGrips: bool
    DrawingSurfaces: bool
    ShadingRequired: bool
    Viewport: RhinoViewport
    DisplayPipelineAttributes: DisplayPipelineAttributes
    DpiScale: float
    DepthMode: DepthMode
    ZBiasMode: ZBiasMode
    def AddClippingPlane(self, point: Point3d, normal: Vector3d) -> int: ...
    @staticmethod
    def AvailableOpenGLVersion(coreProfile: bool) -> int: ...
    def ClearFrameBuffer(self, color: Color) -> None: ...
    def Clone(self, viewport: RhinoViewport) -> DisplayPipeline: ...
    def Close(self, ) -> bool: ...
    @staticmethod
    def CullControlPolygon() -> bool: ...
    def Draw2dLine(self, from_: Point, to: Point, color: Color, thickness: float) -> None: ...
    def Draw2dRectangle(self, rectangle: Rectangle, strokeColor: Color, thickness: int, fillColor: Color) -> None: ...
    def Draw2dText(self, text: str, color: Color, screenCoordinate: Point2d, middleJustified: bool, height: int, fontface: str) -> None: ...
    def Draw3dText(self, text: str, color: Color, textPlane: Plane, height: float, fontface: str, bold: bool, italic: bool, horizontalAlignment: TextHorizontalAlignment, verticalAlignment: TextVerticalAlignment) -> None: ...
    def DrawActivePoint(self, point: Point3d) -> None: ...
    def DrawAnnotation(self, annotation: AnnotationBase, color: Color) -> None: ...
    def DrawAnnotationArrowhead(self, arrowhead: Arrowhead, xform: Transform, color: Color) -> None: ...
    def DrawArc(self, arc: Arc, color: Color, thickness: int) -> None: ...
    def DrawArrow(self, line: Line, color: Color, screenSize: float, relativeSize: float) -> None: ...
    def DrawArrowHead(self, tip: Point3d, direction: Vector3d, color: Color, screenSize: float, worldSize: float) -> None: ...
    def DrawArrows(self, lines: list, color: Color) -> None: ...
    def DrawBitmap(self, bitmap: DisplayBitmap, left: int, top: int) -> None: ...
    def DrawBox(self, box: BoundingBox, color: Color, thickness: int) -> None: ...
    def DrawBoxCorners(self, box: BoundingBox, color: Color, size: float, thickness: int) -> None: ...
    def DrawBrepShaded(self, brep: Brep, material: DisplayMaterial) -> None: ...
    def DrawBrepWires(self, brep: Brep, color: Color, wireDensity: int) -> None: ...
    def DrawCircle(self, circle: Circle, color: Color, thickness: int) -> None: ...
    def DrawCone(self, cone: Cone, color: Color, thickness: int) -> None: ...
    def DrawConstructionPlane(self, constructionPlane: ConstructionPlane) -> None: ...
    def DrawCurvatureGraph(self, curve: Curve, color: Color, hairScale: int, hairDensity: int, sampleDensity: int) -> None: ...
    def DrawCurve(self, curve: Curve, color: Color, thickness: int) -> None: ...
    def DrawCylinder(self, cylinder: Cylinder, color: Color, thickness: int) -> None: ...
    def DrawDirectionArrow(self, location: Point3d, direction: Vector3d, color: Color) -> None: ...
    def DrawDot(self, screenX: float, screenY: float, text: str, dotColor: Color, textColor: Color) -> None: ...
    def DrawDottedLine(self, from_: Point3d, to: Point3d, color: Color) -> None: ...
    def DrawDottedPolyline(self, points: IEnumerable, color: Color, close: bool) -> None: ...
    def DrawExtrusionWires(self, extrusion: Extrusion, color: Color, wireDensity: int) -> None: ...
    def DrawGradientHatch(self, hatch: Hatch, color1: Color, color2: Color, point1: Point3d, point2: Point3d, linearGradient: bool, boundaryThickness: float, boundaryColor: Color) -> None: ...
    def DrawGradientLines(self, lines: IEnumerable, strokeWidth: float, stops: IEnumerable, point1: Point3d, point2: Point3d, linearGradient: bool, repeat: float) -> None: ...
    def DrawGradientMesh(self, mesh: Mesh, stops: IEnumerable, point1: Point3d, point2: Point3d, linearGradient: bool, repeat: float) -> None: ...
    def DrawHatch(self, hatch: Hatch, hatchColor: Color, boundary: DisplayPen, backgroundFillColor: Color) -> None: ...
    def DrawInferenceLine(self, P: Point3d, O: Point3d, color: Color, type: InferenceLineType) -> None: ...
    def DrawInstanceDefinition(self, instanceDefinition: InstanceDefinition, xform: Transform) -> None: ...
    def DrawInstanceDefinitionShaded(self, instanceDefinition: InstanceDefinition, material: DisplayMaterial, xform: Transform) -> None: ...
    def DrawLight(self, light: Light, wireframeColor: Color) -> None: ...
    def DrawLine(self, from_: Point3d, to: Point3d, color: Color, thickness: int) -> None: ...
    def DrawLineArrow(self, line: Line, color: Color, thickness: int, size: float) -> None: ...
    def DrawLineNoClip(self, from_: Point3d, to: Point3d, color: Color, thickness: int) -> None: ...
    def DrawLines(self, lines: IEnumerable, color: Color, thickness: int) -> None: ...
    def DrawLinesNoClip(self, lines: IEnumerable, color: Color, thickness: int) -> None: ...
    def DrawMarker(self, tip: Point3d, direction: Vector3d, color: Color, thickness: int, size: float, rotation: float) -> None: ...
    def DrawMeshFalseColors(self, mesh: Mesh) -> None: ...
    def DrawMeshShaded(self, mesh: Mesh, material: DisplayMaterial, faceIndices: list) -> None: ...
    def DrawMeshVertices(self, mesh: Mesh, color: Color) -> None: ...
    def DrawMeshWires(self, mesh: Mesh, color: Color, thickness: int) -> None: ...
    def DrawObject(self, rhinoObject: RhinoObject, xform: Transform) -> None: ...
    def DrawParticles(self, particles: ParticleSystem, bitmap: DisplayBitmap) -> None: ...
    def DrawPatternedLine(self, from_: Point3d, to: Point3d, color: Color, pattern: int, thickness: int) -> None: ...
    def DrawPatternedPolyline(self, points: IEnumerable, color: Color, pattern: int, thickness: int, close: bool) -> None: ...
    def DrawPoint(self, point: Point3d, style: PointStyle, strokeColor: Color, fillColor: Color, radius: float, strokeWidth: float, secondarySize: float, rotationRadians: float, diameterIsInPixels: bool, autoScaleForDpi: bool) -> None: ...
    def DrawPointCloud(self, cloud: PointCloud, size: float, color: Color) -> None: ...
    def DrawPoints(self, points: IEnumerable, style: PointStyle, strokeColor: Color, fillColor: Color, radius: float, strokeWidth: float, secondarySize: float, rotationRadians: float, diameterIsInPixels: bool, autoScaleForDpi: bool) -> None: ...
    def DrawPolygon(self, points: IEnumerable, color: Color, filled: bool) -> None: ...
    def DrawPolyline(self, polyline: IEnumerable, color: Color, thickness: int) -> None: ...
    def DrawRoundedRectangle(self, center: PointF, pixelWidth: float, pixelHeight: float, cornerRadius: float, strokeColor: Color, strokeWidth: float, fillColor: Color) -> None: ...
    def DrawSphere(self, sphere: Sphere, color: Color, thickness: int) -> None: ...
    def DrawSprite(self, bitmap: DisplayBitmap, worldLocation: Point3d, size: float, blendColor: Color, sizeInWorldSpace: bool) -> None: ...
    def DrawSprites(self, bitmap: DisplayBitmap, items: DisplayBitmapDrawList, size: float, translation: Vector3d, sizeInWorldSpace: bool) -> None: ...
    def DrawStereoFrameBuffer(self, viewportLeft: ViewportInfo, viewportRight: ViewportInfo, handleLeft: int, handleRight: int) -> bool: ...
    def DrawSubDShaded(self, subd: SubD, material: DisplayMaterial) -> None: ...
    def DrawSubDWires(self, subd: SubD, boundaryPen: DisplayPen, smoothInteriorPen: DisplayPen, creasePen: DisplayPen, nonmanifoldPen: DisplayPen) -> None: ...
    def DrawSurface(self, surface: Surface, wireColor: Color, wireDensity: int) -> None: ...
    def DrawText(self, text: TextEntity, color: Color, scale: float) -> None: ...
    @staticmethod
    def DrawToBitmap(viewport: RhinoViewport, width: int, height: int) -> Bitmap: ...
    def DrawTorus(self, torus: Torus, color: Color, thickness: int) -> None: ...
    def DrawZebraPreview(self, brep: Brep, color: Color) -> None: ...
    def DraweInferencePoint(self, P: Point3d, color: Color) -> None: ...
    def EnableClippingPlanes(self, enable: bool) -> None: ...
    def EnableColorWriting(self, enable: bool) -> None: ...
    def EnableDepthTesting(self, enable: bool) -> None: ...
    def EnableDepthWriting(self, enable: bool) -> None: ...
    def EnableLighting(self, enable: bool) -> None: ...
    def Flush(self, ) -> None: ...
    @staticmethod
    def GetDrawListSerialNumbers(modelSerialNumber: int, pageSerialNumber: int) -> None: ...
    def GetLights(self, ) -> list: ...
    def GetOpenGLCameraToClip(self, ) -> list: ...
    def GetOpenGLWorldToCamera(self, includeModelTransform: bool) -> list: ...
    def GetOpenGLWorldToClip(self, includeModelTransform: bool) -> list: ...
    def InterruptDrawing(self, ) -> bool: ...
    def IsActive(self, rhinoObject: RhinoObject) -> bool: ...
    def IsInTiledDraw(self, fullSize: Size, currentTile: Rectangle) -> bool: ...
    def IsVisible(self, worldCoordinate: Point3d) -> bool: ...
    @staticmethod
    def MakeDefaultOpenGLContextCurrent() -> bool: ...
    def Measure2dText(self, text: str, definitionPoint: Point2d, middleJustified: bool, rotationRadians: float, height: int, fontFace: str) -> Rectangle: ...
    def Open(self, ) -> bool: ...
    def PopClipTesting(self, ) -> None: ...
    def PopCullFaceMode(self, ) -> None: ...
    def PopDepthTesting(self, ) -> None: ...
    def PopDepthWriting(self, ) -> None: ...
    def PopModelTransform(self, ) -> None: ...
    def PopProjection(self, ) -> None: ...
    def Push2dProjection(self, ) -> None: ...
    def PushClipTesting(self, enable: bool) -> None: ...
    def PushCullFaceMode(self, mode: CullFaceMode) -> None: ...
    def PushDepthTesting(self, enable: bool) -> None: ...
    def PushDepthWriting(self, enable: bool) -> None: ...
    def PushModelTransform(self, xform: Transform) -> None: ...
    def RemoveClippingPlane(self, index: int) -> None: ...
    def SetupDisplayMaterial(self, doc: RhinoDoc, rhinoObject: RhinoObject, attributes: ObjectAttributes, instanceTransform: Transform) -> DisplayMaterial: ...

class DisplayPipelineAttributes:
    """.NET: Rhino.Display.DisplayPipelineAttributes"""
    def __init__(self, *args) -> None: ...
    XrayAllObjects: bool
    IgnoreHighlights: bool
    DisableConduits: bool
    DisableTransparency: bool
    ObjectColor: Color
    ShowGrips: bool
    FillMode: FrameBufferFillMode
    BoundingBoxMode: BoundingBoxDisplayMode
    ShowClippingPlanes: bool
    ShowClipIntersectionSurfaces: bool
    ShowClipIntersectionEdges: bool
    ViewSpecificAttributes: ViewDisplayAttributes
    UseAssignedObjectMaterial: bool
    UseCustomObjectColor: bool
    UseCustomObjectMaterial: bool
    UseCustomObjectColorBackfaces: bool
    UseCustomObjectMaterialBackfaces: bool
    BackfaceDisplayStyle: BackfaceStyle
    UseBackfaceMaterial: bool
    UseObjectBackfaceMaterial: bool
    UseCustomBackface: bool
    ShowCurves: bool
    UseSingleCurveColor: bool
    CurveThicknessUsage: CurveThicknessUse
    CurveThickness: int
    CurveThicknessScale: float
    CurveColor: Color
    ShadingEnabled: bool
    ShadeVertexColors: bool
    ShowIsoCurves: bool
    ShowSurfaceEdges: bool
    ShowTangentEdges: bool
    ShowTangentSeams: bool
    SurfaceEdgeThickness: int
    SurfaceIsoShowForFlatFaces: bool
    SurfaceIsoThicknessUsed: bool
    SurfaceEdgeApplyPattern: bool
    SurfaceNakedEdgeApplyPattern: bool
    ShowSurfaceEdge: bool
    ShowSurfaceNakedEdge: bool
    SurfaceEdgeColorUsage: SurfaceEdgeColorUse
    SurfaceNakedEdgeColorUsage: SurfaceNakedEdgeColorUse
    SurfaceIsoSingleColor: bool
    SurfaceIsoColorsUsed: bool
    SurfaceEdgeColor: Color
    SurfaceNakedEdgeColor: Color
    SurfaceIsoUVColor: Color
    SurfaceIsoUColor: Color
    SurfaceIsoVColor: Color
    SurfaceEdgeColorReduction: int
    SurfaceNakedAdgeColorReduction: int
    SurfaceEdgeColorReductionPercent: int
    SurfaceNakedEdgeColorReductionPercent: int
    SurfaceNakedEdgeThickness: int
    SurfaceIsoThickness: int
    SurfaceIsoUThickness: int
    SurfaceIsoVThickness: int
    SurfaceEdgeThicknessScale: float
    SurfaceNakedEdgeThicknessScale: float
    SurfaceIsoThicknessUScale: float
    SurfaceIsoThicknessVScale: float
    SurfaceIsoThicknessWScale: float
    LockedObjectsDrawBehindOthers: bool
    MeshSpecificAttributes: MeshDisplayAttributes
    ShowText: bool
    ShowAnnotations: bool
    ShowLights: bool
    LightingScheme: LightingSchema
    AmbientLightingColor: Color
    ShadowColor: Color
    ColorReductionPct: int
    CastShadows: bool
    ShowPoints: bool
    PointStyle: PointStyle
    PointRadius: float
    ShowPointClouds: bool
    PointCloudStyle: PointStyle
    PointCloudRadius: float
    Id: Guid
    EnglishName: str
    LocalName: str
    ContextForDraw: ContextsForDraw
    RealtimeDisplayId: Guid
    RealtimeRenderPasses: int
    ShowRealtimeRenderProgressBar: bool
    StereoContext: StereoContext
    FrontMaterialShine: float
    BackMaterialShine: float
    FrontMaterialTransparency: float
    BackMaterialTransparency: float
    BackMaterialDiffuseColor: Color
    CullBackfaces: bool
    SubDSmoothInteriorColorReduction: int
    SubDCreaseInteriorColorReduction: int
    SubDNonManifoldColorReduction: int
    SubDBoundaryColorReduction: int
    SubDSmoothInteriorEdgeColorUsage: SubDEdgeColorUse
    SubDCreaseInteriorEdgeColorUsage: SubDEdgeColorUse
    SubDNonManifoldEdgeColorUsage: SubDEdgeColorUse
    SubDBoundaryEdgeColorUsage: SubDEdgeColorUse
    SubDReflectionPlaneColorUsage: SubDReflectionPlaneColorUse
    SubDReflectionPlaneColorReduction: int
    MeshEdgeThickness: int
    MeshNakedEdgeThickness: int
    MeshNonmanifoldEdgeThickness: int
    MeshVertexSize: int
    MeshEdgeColorReduction: int
    MeshNakedEdgeColorReduction: int
    MeshNonmanifoldEdgeColorReduction: int
    SubDSmoothInteriorThicknessScale: float
    SubDCreaseInteriorThicknessScale: float
    SubDNonManifoldThicknessScale: float
    SubDBoundaryThicknessScale: float
    SubDSmoothInteriorEdgeThickness: float
    SubDCreaseInteriorEdgeThickness: float
    SubDNonManifoldEdgeThickness: float
    SubDBoundaryEdgeThickness: float
    SubDThicknessUsage: SubDThicknessUse
    SubDSmoothInteriorThicknessUsage: SubDThicknessUse
    SubDCreaseInteriorThicknessUsage: SubDThicknessUse
    SubDNonManifoldThicknessUsage: SubDThicknessUse
    SubDBoundaryThicknessUsage: SubDThicknessUse
    SubDSmoothInteriorApplyPattern: bool
    SubDCreaseInteriorApplyPattern: bool
    SubDNonManifoldApplyPattern: bool
    SubDBoundaryApplyPattern: bool
    SubDReflectionPlaneAxisLineOn: bool
    SubDSmoothInteriorEdgeColor: Color
    SubDCreaseInteriorEdgeColor: Color
    SubDNonManifoldEdgeColor: Color
    SubDBoundaryEdgeColor: Color
    SubDReflectionAxisLineColor: Color
    SubDReflectionPlaneColor: Color
    MeshEdgeColor: Color
    MeshNakedEdgeColor: Color
    MeshNonmanifoldEdgeColor: Color
    CustomGroundPlaneAltitude: float
    CustomGroundPlaneOn: bool
    CustomGroundPlaneShadowOnly: bool
    CustomGroundPlaneAutomaticAltitude: bool
    ShowSubDEdges: bool
    ShowSubDCreases: bool
    ShowSubDBoundary: bool
    ShowSubDNonmanifoldEdges: bool
    ShowSubDReflectionPlanePreview: bool
    ShowMeshEdges: bool
    ShowMeshNakedEdges: bool
    ShowMeshNonmanifoldEdges: bool
    UseLightColor: bool
    ShowClippingFills: bool
    ShowClippingEdges: bool
    ClippingShadeSelectedPlane: bool
    ClipSelectionHighlight: bool
    ClippingPlaneFillColorUsage: ClippingPlaneFillColorUse
    ClippingFillColor: Color
    ClippingEdgeColorUsage: ClippingEdgeColorUse
    ClippingEdgeColor: Color
    ClippingShadeColorUsage: ClippingShadeColorUse
    ClippingShadeColor: Color
    ClippingEdgeThickness: int
    ClippingShadeTransparency: int
    UseSectionStyles: bool
    ControlPolygonWireThickness: int
    ControlPolygonStyle: PointStyle
    ControlPolygonGripSize: int
    LockedObjectTransparency: int
    LockedObjectUsage: LockedObjectUse
    DynamicDisplayUsage: DynamicDisplayUse
    HighlightSurfaces: bool
    ControlPolygonUseSolidLines: bool
    ControlPolygonUseFixedSingleColor: bool
    ControlPolygonShowPoints: bool
    ControlPolygonShowSurface: bool
    ControlPolygonShow: bool
    ControlPolygonHighlight: bool
    GhostLockedObjects: bool
    LayersFollowLockUsage: bool
    ControlPolygonColor: Color
    LockedColor: Color
    ShadowsOn: bool
    ShadowIntensity: int
    ShadowMemoryUsage: int
    SkylightShadowQuality: int
    ShadowSoftEdgeQuality: int
    ShadowEdgeBlur: float
    ShadowBiasX: float
    ShadowTransparencyTolerance: int
    ShadowClippingRadius: float
    ShadowsIgnoreUserDefinedClippingPlanes: bool
    AxesSizePercentage: int
    GridTransparency: int
    GridPlaneTransparency: int
    GridPlaneVisibility: GridPlaneVisibilityMode
    WorldAxesIconColorUsage: WorldAxesIconColorUse
    PlaneUsesGridColor: bool
    GridPlaneColor: Color
    GroundPlaneUsage: GroundPlaneUsages
    LinearWorkflowUsage: LinearWorkflowUsages
    PreProcessColors: bool
    PreProcessTextures: bool
    PreProcessGamma: float
    PostProcessFrameBuffer: bool
    PostProcessGamma: bool
    FrontFlatShaded: bool
    FrontOverrideObjectColor: bool
    FrontOverrideObjectTransparency: bool
    FrontOverrideObjectReflectivity: bool
    BackOverrideObjectTransparency: bool
    BackOverrideObjectReflectivity: bool
    FrontDiffuse: Color
    BakeTextures: bool
    def Dispose(self, ) -> None: ...
    def GetColorFadeEffect(self, fadeColor: Color, fadeAmount: float) -> None: ...
    def GetCurveThicknessUsage(self, ) -> CurveThicknessUse: ...
    def GetDiagonalHatchEffect(self, hatchStrength: float, hatchWidth: float) -> None: ...
    def GetDitherTransparencyEffect(self, ) -> float: ...
    def GetFill(self, topLeft: Color, bottomLeft: Color, topRight: Color, bottomRight: Color) -> None: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
    def GetSurfaceEdgeThicknessUsage(self, ) -> SurfaceThicknessUse: ...
    def GetSurfaceIsoApplyPattern(self, u: bool, v: bool, w: bool) -> None: ...
    def GetSurfaceIsoColorUsage(self, ) -> SurfaceIsoColorUse: ...
    def GetSurfaceIsoThicknessUsage(self, ) -> SurfaceIsoThicknessUse: ...
    def GetSurfaceNakedEdgeThicknessUsage(self, ) -> SurfaceNakedEdgeThicknessUse: ...
    def HasColorFadeEffect(self, ) -> bool: ...
    def HasDiagonalHatchEffect(self, ) -> bool: ...
    def HasDitherTransparencyEffect(self, ) -> bool: ...
    def SetColorFadeEffect(self, fadeColor: Color, fadeAmount: float) -> None: ...
    def SetCurveThicknessUsage(self, usage: CurveThicknessUse) -> None: ...
    def SetDiagonalHatchEffect(self, hatchStrength: float, hatchWidth: float) -> None: ...
    def SetDitherTransparencyEffect(self, transparencyAmount: float) -> None: ...
    def SetFill(self, gradientTopLeft: Color, gradientBottomLeft: Color, gradientTopRight: Color, gradientBottomRight: Color) -> None: ...
    def SetSurfaceEdgeThicknessUsage(self, use: SurfaceThicknessUse) -> None: ...
    def SetSurfaceIsoApplyPattern(self, u: bool, v: bool, w: bool) -> None: ...
    def SetSurfaceIsoColorUsage(self, use: SurfaceIsoColorUse) -> None: ...
    def SetSurfaceIsoThicknessUsage(self, value: SurfaceIsoThicknessUse) -> None: ...
    def SetSurfaceNakedEdgeThicknessUsage(self, use: SurfaceNakedEdgeThicknessUse) -> None: ...

class DisplayPoint:
    """.NET: Rhino.Display.DisplayPoint"""
    def __init__(self, *args) -> None: ...
    Location: Point3d
    def WithAttributes(self, attributes: DisplayPointAttributes) -> DisplayPoint: ...

class DisplayPointAttributes:
    """.NET: Rhino.Display.DisplayPointAttributes"""
    def __init__(self, *args) -> None: ...
    PointStyle: Nullable
    StrokeColor: Nullable
    FillColor: Nullable
    Diameter: Nullable
    StrokeWidth: Nullable
    SecondarySize: Nullable
    RotationRadians: Nullable

class DisplayPointSet:
    """.NET: Rhino.Display.DisplayPointSet"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Create(points: IEnumerable) -> DisplayPointSet: ...
    def Dispose(self, ) -> None: ...

class DisplayTechnology:
    """.NET: Rhino.Display.DisplayTechnology"""
    def __init__(self, *args) -> None: ...
    ...

class DrawEventArgs(EventArgs):
    """.NET: Rhino.Display.DrawEventArgs"""
    def __init__(self, *args) -> None: ...
    Viewport: RhinoViewport
    Display: DisplayPipeline
    RhinoDoc: RhinoDoc

class DrawForegroundEventArgs(DrawEventArgs):
    """.NET: Rhino.Display.DrawForegroundEventArgs"""
    def __init__(self, *args) -> None: ...
    WorldAxesDrawn: bool
    DrawWorldAxes: bool
    Viewport: RhinoViewport
    Display: DisplayPipeline
    RhinoDoc: RhinoDoc

class DrawFrameStages:
    """.NET: Rhino.Display.DrawFrameStages"""
    def __init__(self, *args) -> None: ...
    ...

class DrawObjectEventArgs(DrawEventArgs):
    """.NET: Rhino.Display.DrawObjectEventArgs"""
    def __init__(self, *args) -> None: ...
    RhinoObject: RhinoObject
    DrawObject: bool
    Viewport: RhinoViewport
    Display: DisplayPipeline
    RhinoDoc: RhinoDoc

class FlairLayer:
    """.NET: Rhino.Display.FlairLayer"""
    def __init__(self, *args) -> None: ...
    ...

class GradientType:
    """.NET: Rhino.Display.GradientType"""
    def __init__(self, *args) -> None: ...
    ...

class InitFrameBufferEventArgs(EventArgs):
    """.NET: Rhino.Display.InitFrameBufferEventArgs"""
    def __init__(self, *args) -> None: ...
    def SetFill(self, topLeft: Color, bottomLeft: Color, topRight: Color, bottomRight: Color) -> None: ...

class IsometricCamera:
    """.NET: Rhino.Display.IsometricCamera"""
    def __init__(self, *args) -> None: ...
    ...

class PageViewPropertiesChangeEventArgs(EventArgs):
    """.NET: Rhino.Display.PageViewPropertiesChangeEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentSerialNumber: int
    PageViewSerialNumber: int
    Document: RhinoDoc
    PageView: RhinoPageView

class PageViewSpaceChangeEventArgs(EventArgs):
    """.NET: Rhino.Display.PageViewSpaceChangeEventArgs"""
    def __init__(self, *args) -> None: ...
    PageView: RhinoPageView
    NewActiveDetailId: Guid
    OldActiveDetailId: Guid

class PointStyle:
    """.NET: Rhino.Display.PointStyle"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoPageView(RhinoView):
    """.NET: Rhino.Display.RhinoPageView"""
    def __init__(self, *args) -> None: ...
    ActiveViewport: RhinoViewport
    ActiveDetailId: Guid
    ActiveDetail: DetailViewObject
    PageIsActive: bool
    PageNumber: int
    PageWidth: float
    PageHeight: float
    PageName: str
    PrinterName: str
    PaperName: str
    RuntimeSerialNumber: int
    Handle: IntPtr
    DisplayPipeline: DisplayPipeline
    RealtimeDisplayMode: RealtimeDisplayMode
    Bounds: Rectangle
    ClientRectangle: Rectangle
    ScreenRectangle: Rectangle
    Size: Size
    InDynamicViewChange: bool
    Document: RhinoDoc
    MainViewport: RhinoViewport
    ActiveViewportID: Guid
    TitleVisible: bool
    Maximized: bool
    Floating: bool
    def AddDetailView(self, title: str, corner0: Point2d, corner1: Point2d, initialProjection: DefinedViewportProjection) -> DetailViewObject: ...
    def Duplicate(self, duplicatePageGeometry: bool) -> RhinoPageView: ...
    def GetDetailViews(self, ) -> list: ...
    def GetPreviewImage(self, size: Size, grayScale: bool) -> Bitmap: ...
    def SetActiveDetail(self, detailName: str, compareCase: bool) -> bool: ...
    def SetPageAsActive(self, ) -> None: ...

class RhinoView:
    """.NET: Rhino.Display.RhinoView"""
    def __init__(self, *args) -> None: ...
    RuntimeSerialNumber: int
    Handle: IntPtr
    DisplayPipeline: DisplayPipeline
    RealtimeDisplayMode: RealtimeDisplayMode
    Bounds: Rectangle
    ClientRectangle: Rectangle
    ScreenRectangle: Rectangle
    Size: Size
    EnableDrawing: bool
    InDynamicViewChange: bool
    Document: RhinoDoc
    MainViewport: RhinoViewport
    ActiveViewport: RhinoViewport
    ActiveViewportID: Guid
    TitleVisible: bool
    Maximized: bool
    Floating: bool
    def CaptureToBitmap(self, size: Size, grid: bool, worldAxes: bool, cplaneAxes: bool) -> Bitmap: ...
    def ClientToScreen(self, clientPoint: Point) -> Point: ...
    def Close(self, ) -> bool: ...
    def CreateShadedPreviewImage(self, imagePath: str, size: Size, ignoreHighlights: bool, drawConstructionPlane: bool, useGhostedShading: bool) -> bool: ...
    def CreateWireframePreviewImage(self, imagePath: str, size: Size, ignoreHighlights: bool, drawConstructionPlane: bool) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    @staticmethod
    def FromRuntimeSerialNumber(serialNumber: int) -> RhinoView: ...
    def GetHashCode(self, ) -> int: ...
    def MouseCaptured(self, bIncludeMovement: bool) -> bool: ...
    def Redraw(self, ) -> None: ...
    def ScreenToClient(self, screenPoint: Point) -> Point: ...
    def ShowToast(self, message: str, textHeight: int, location: PointF) -> int: ...
    def SpeedTest(self, frameCount: int, freezeDrawList: bool, direction: int, angleDeltaRadians: float) -> float: ...

class RhinoViewport:
    """.NET: Rhino.Display.RhinoViewport"""
    def __init__(self, *args) -> None: ...
    ParentView: RhinoView
    Id: Guid
    ChangeCounter: int
    Size: Size
    LockedProjection: bool
    Name: str
    CameraTarget: Point3d
    ConstructionGridVisible: bool
    ConstructionAxesVisible: bool
    WorldAxesVisible: bool
    IsPlanView: bool
    UserStringCount: int
    IsValidCamera: bool
    IsValidFrustum: bool
    IsPerspectiveProjection: bool
    IsTwoPointPerspectiveProjection: bool
    IsParallelProjection: bool
    CameraLocation: Point3d
    CameraDirection: Vector3d
    CameraUp: Vector3d
    CameraX: Vector3d
    CameraY: Vector3d
    CameraZ: Vector3d
    FrustumAspect: float
    Bounds: Rectangle
    ScreenPortAspect: float
    Camera35mmLensLength: float
    WallpaperFilename: str
    WallpaperGrayscale: bool
    WallpaperVisible: bool
    ViewportType: ViewportType
    DisplayMode: DisplayModeDescription
    def ChangeToParallelProjection(self, symmetricFrustum: bool) -> bool: ...
    def ChangeToParallelReflectedProjection(self, ) -> bool: ...
    def ChangeToPerspectiveProjection(self, targetDistance: float, symmetricFrustum: bool, lensLength: float) -> bool: ...
    def ChangeToTwoPointPerspectiveProjection(self, targetDistance: float, up: Vector3d, lensLength: float) -> bool: ...
    def ClearTraceImage(self, ) -> None: ...
    def ClientToScreen(self, clientPoint: Point2d) -> Point: ...
    def ClientToWorld(self, clientPoint: Point) -> Line: ...
    def ConstructionPlane(self, ) -> Plane: ...
    def DeleteAllUserStrings(self, ) -> None: ...
    def DeleteUserString(self, key: str) -> bool: ...
    def Dispose(self, ) -> None: ...
    @staticmethod
    def FromId(id: Guid) -> RhinoViewport: ...
    def GetCameraAngle(self, halfDiagonalAngle: float, halfVerticalAngle: float, halfHorizontalAngle: float) -> bool: ...
    def GetCameraExtents(self, points: IEnumerable) -> BoundingBox: ...
    def GetCameraFrame(self, frame: Plane) -> bool: ...
    def GetConstructionPlane(self, ) -> ConstructionPlane: ...
    def GetDepth(self, bbox: BoundingBox, nearDistance: float, farDistance: float) -> bool: ...
    def GetFarRect(self, ) -> list: ...
    def GetFrustum(self, left: float, right: float, bottom: float, top: float, nearDistance: float, farDistance: float) -> bool: ...
    def GetFrustumBottomPlane(self, plane: Plane) -> bool: ...
    def GetFrustumBoundingBox(self, ) -> BoundingBox: ...
    def GetFrustumCenter(self, center: Point3d) -> bool: ...
    def GetFrustumFarPlane(self, plane: Plane) -> bool: ...
    def GetFrustumLeftPlane(self, plane: Plane) -> bool: ...
    def GetFrustumLine(self, screenX: float, screenY: float, worldLine: Line) -> bool: ...
    def GetFrustumNearPlane(self, plane: Plane) -> bool: ...
    def GetFrustumRightPlane(self, plane: Plane) -> bool: ...
    def GetFrustumTopPlane(self, plane: Plane) -> bool: ...
    def GetNearRect(self, ) -> list: ...
    def GetPickTransform(self, clientX: int, clientY: int) -> Transform: ...
    def GetScreenPort(self, portLeft: int, portRight: int, portBottom: int, portTop: int, portNear: int, portFar: int) -> bool: ...
    def GetTransform(self, sourceSystem: CoordinateSystem, destinationSystem: CoordinateSystem) -> Transform: ...
    def GetUserString(self, key: str) -> str: ...
    def GetUserStrings(self, ) -> NameValueCollection: ...
    def GetViewScale(self, ) -> list: ...
    def GetWorldToScreenScale(self, pointInFrustum: Point3d, pixelsPerUnit: float) -> bool: ...
    def IsVisible(self, bbox: BoundingBox) -> bool: ...
    def KeyboardDolly(self, leftRight: bool, amount: float) -> bool: ...
    def KeyboardDollyInOut(self, amount: float) -> bool: ...
    def KeyboardRotate(self, leftRight: bool, angleRadians: float) -> bool: ...
    def Magnify(self, magnificationFactor: float, mode: bool, fixedScreenPoint: Point) -> bool: ...
    def MouseAdjustLensLength(self, mousePreviousPoint: Point, mouseCurrentPoint: Point, moveTarget: bool) -> bool: ...
    def MouseDollyZoom(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def MouseInOutDolly(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def MouseLateralDolly(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def MouseMagnify(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def MouseRotateAroundTarget(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def MouseRotateCamera(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def MouseTilt(self, mousePreviousPoint: Point, mouseCurrentPoint: Point) -> bool: ...
    def NextConstructionPlane(self, ) -> bool: ...
    def NextViewProjection(self, ) -> bool: ...
    def PopConstructionPlane(self, ) -> bool: ...
    def PopViewProjection(self, ) -> bool: ...
    def PreviousConstructionPlane(self, ) -> bool: ...
    def PreviousViewProjection(self, ) -> bool: ...
    def PushConstructionPlane(self, cplane: ConstructionPlane) -> None: ...
    def PushViewInfo(self, viewinfo: ViewInfo, includeTraceImage: bool) -> bool: ...
    def PushViewProjection(self, ) -> None: ...
    def Rotate(self, angleRadians: float, rotationAxis: Vector3d, rotationCenter: Point3d) -> bool: ...
    def ScreenToClient(self, screenPoint: Point) -> Point: ...
    def SetCameraDirection(self, cameraDirection: Vector3d, updateTargetLocation: bool) -> None: ...
    def SetCameraLocation(self, cameraLocation: Point3d, updateTargetLocation: bool) -> None: ...
    def SetCameraLocations(self, targetLocation: Point3d, cameraLocation: Point3d) -> None: ...
    def SetCameraTarget(self, targetLocation: Point3d, updateCameraLocation: bool) -> None: ...
    def SetClippingPlanes(self, box: BoundingBox) -> None: ...
    def SetConstructionPlane(self, plane: Plane) -> None: ...
    def SetProjection(self, projection: DefinedViewportProjection, viewName: str, updateConstructionPlane: bool) -> bool: ...
    def SetToPlanView(self, planeOrigin: Point3d, planeXaxis: Vector3d, planeYaxis: Vector3d, setConstructionPlane: bool) -> bool: ...
    def SetTraceImage(self, bitmapFileName: str, plane: Plane, width: float, height: float, grayscale: bool, filtered: bool) -> bool: ...
    def SetUserString(self, key: str, value: str) -> bool: ...
    def SetUserStrings(self, items: IEnumerable, replace: bool) -> bool: ...
    def SetViewProjection(self, projection: ViewportInfo, updateTargetLocation: bool) -> bool: ...
    def SetWallpaper(self, imageFilename: str, grayscale: bool, visible: bool) -> bool: ...
    def WorldToClient(self, worldPoint: Point3d) -> Point2d: ...
    def ZoomBoundingBox(self, box: BoundingBox) -> bool: ...
    def ZoomExtents(self, ) -> bool: ...
    def ZoomExtentsSelected(self, ) -> bool: ...
    def ZoomWindow(self, rect: Rectangle) -> bool: ...

class ShaderLanguage:
    """.NET: Rhino.Display.ShaderLanguage"""
    def __init__(self, *args) -> None: ...
    ...

class StereoContext:
    """.NET: Rhino.Display.StereoContext"""
    def __init__(self, *args) -> None: ...
    ...

class Text3d:
    """.NET: Rhino.Display.Text3d"""
    def __init__(self, *args) -> None: ...
    Text: str
    TextPlane: Plane
    Height: float
    FontFace: str
    Bold: bool
    Italic: bool
    BoundingBox: BoundingBox
    HorizontalAlignment: TextHorizontalAlignment
    VerticalAlignment: TextVerticalAlignment
    def Dispose(self, ) -> None: ...

class ViewCapture:
    """.NET: Rhino.Display.ViewCapture"""
    def __init__(self, *args) -> None: ...
    Width: int
    Height: int
    ScaleScreenItems: bool
    DrawGrid: bool
    DrawAxes: bool
    DrawGridAxes: bool
    TransparentBackground: bool
    Preview: bool
    RealtimeRenderPasses: int
    def CaptureToBitmap(self, sourceView: RhinoView) -> Bitmap: ...
    @staticmethod
    def CaptureToSvg(settings: ViewCaptureSettings) -> XmlDocument: ...
    @staticmethod
    def SendToPrinter(printerName: str, settings: list, copies: int) -> bool: ...

class ViewCaptureSettings:
    """.NET: Rhino.Display.ViewCaptureSettings"""
    def __init__(self, *args) -> None: ...
    Document: RhinoDoc
    ViewArea: ViewAreaMapping
    RasterMode: bool
    MatchLinetypePatternDefinition: bool
    ApplyDisplayModeThicknessScales: bool
    MediaSize: Size
    DrawRectangle: Rectangle
    Resolution: float
    CropRectangle: Rectangle
    OffsetAnchor: AnchorLocation
    IsValid: bool
    DrawBackground: bool
    DrawGrid: bool
    DrawAxis: bool
    DrawLockedObjects: bool
    DrawMargins: bool
    DrawSelectedObjectsOnly: bool
    DrawClippingPlanes: bool
    DrawLights: bool
    DrawBackgroundBitmap: bool
    DrawWallpaper: bool
    UsePrintWidths: bool
    WireThicknessScale: float
    PointSizeMillimeters: float
    ArrowheadSizeMillimeters: float
    TextDotPointSize: float
    DefaultPrintWidthMillimeters: float
    HorizontalScale: float
    VerticalScale: float
    OutputColor: ColorMode
    HeaderText: str
    FooterText: str
    IsScaleToFit: bool
    ModelScaleType: int
    LinetypeWidthUnitsArePageLengths: bool
    def CreatePreviewSettings(self, size: Size) -> ViewCaptureSettings: ...
    def Dispose(self, ) -> None: ...
    def Equals(self, other: ViewCaptureSettings) -> bool: ...
    def GetMargins(self, lengthUnits: UnitSystem, left: float, top: float, right: float, bottom: float) -> bool: ...
    def GetModelScale(self, pageUnits: UnitSystem, modelUnits: UnitSystem) -> float: ...
    def GetOffset(self, lengthUnits: UnitSystem, fromMargin: bool, x: float, y: float) -> None: ...
    def GetViewport(self, ) -> RhinoViewport: ...
    def Load(self, name: str, settings: PersistentSettings) -> bool: ...
    def MatchViewportAspectRatio(self, ) -> bool: ...
    def MaximizePrintableArea(self, ) -> None: ...
    def Save(self, name: str, settings: PersistentSettings) -> None: ...
    def SetLayout(self, mediaSize: Size, cropRectangle: Rectangle) -> None: ...
    def SetMarginBottom(self, lengthUnits: UnitSystem, distance: float) -> bool: ...
    def SetMarginLeft(self, lengthUnits: UnitSystem, distance: float) -> bool: ...
    def SetMarginRight(self, lengthUnits: UnitSystem, distance: float) -> bool: ...
    def SetMarginTop(self, lengthUnits: UnitSystem, distance: float) -> bool: ...
    def SetMargins(self, lengthUnits: UnitSystem, left: float, top: float, right: float, bottom: float) -> bool: ...
    def SetModelScaleToFit(self, promptOnChange: bool) -> None: ...
    def SetModelScaleToValue(self, scale: float) -> None: ...
    def SetOffset(self, lengthUnits: UnitSystem, fromMargin: bool, x: float, y: float) -> None: ...
    def SetViewport(self, viewport: RhinoViewport) -> None: ...
    def SetWindowRect(self, screenPoint1: Point2d, screenPoint2: Point2d) -> None: ...

class ViewEnableDrawingEventArgs(EventArgs):
    """.NET: Rhino.Display.ViewEnableDrawingEventArgs"""
    def __init__(self, *args) -> None: ...
    DocumentSerialNumber: int
    DrawingEnabled: bool
    Document: RhinoDoc

class ViewEventArgs(EventArgs):
    """.NET: Rhino.Display.ViewEventArgs"""
    def __init__(self, *args) -> None: ...
    View: RhinoView

class ViewTypeFilter:
    """.NET: Rhino.Display.ViewTypeFilter"""
    def __init__(self, *args) -> None: ...
    ...

class ViewportType:
    """.NET: Rhino.Display.ViewportType"""
    def __init__(self, *args) -> None: ...
    ...

class VisualAnalysisMode:
    """.NET: Rhino.Display.VisualAnalysisMode"""
    def __init__(self, *args) -> None: ...
    RhinoEdgeAnalysisModeId: Guid
    RhinoCurvatureGraphAnalysisModeId: Guid
    RhinoZebraStripeAnalysisModeId: Guid
    RhinoEmapAnalysisModeId: Guid
    RhinoCurvatureColorAnalyisModeId: Guid
    RhinoDraftAngleAnalysisModeId: Guid
    RhinoThicknessAnalysisModeId: Guid
    RhinoEdgeContinuityAlalysisModeId: Guid
    Name: str
    Style: AnalysisStyle
    Id: Guid
    ShowIsoCurves: bool
    @staticmethod
    def AdjustAnalysisMeshes(doc: RhinoDoc, analysisModeId: Guid) -> bool: ...
    def EnableUserInterface(self, on: bool) -> None: ...
    @staticmethod
    def Find(id: Guid) -> VisualAnalysisMode: ...
    def ObjectSupportsAnalysisMode(self, obj: RhinoObject) -> bool: ...
    @staticmethod
    def Register(customAnalysisModeType: Type) -> VisualAnalysisMode: ...

class ZBiasMode:
    """.NET: Rhino.Display.ZBiasMode"""
    def __init__(self, *args) -> None: ...
    ...

class ZBufferCapture:
    """.NET: Rhino.Display.ZBufferCapture"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def GrayscaleDib(self, ) -> Bitmap: ...
    def HitCount(self, ) -> int: ...
    def MaxZ(self, ) -> float: ...
    def MinZ(self, ) -> float: ...
    def SetDisplayMode(self, modeId: Guid) -> None: ...
    def ShowAnnotations(self, on: bool) -> None: ...
    def ShowCurves(self, on: bool) -> None: ...
    def ShowIsocurves(self, on: bool) -> None: ...
    def ShowLights(self, on: bool) -> None: ...
    def ShowMeshWires(self, on: bool) -> None: ...
    def ShowPoints(self, on: bool) -> None: ...
    def ShowText(self, on: bool) -> None: ...
    def WorldPointAt(self, x: int, y: int) -> Point3d: ...
    def ZValueAt(self, x: int, y: int) -> float: ...
