# Auto-generated — Rhino 8 — Rhino.FileIO

class BinaryArchiveException(IOException):
    """.NET: Rhino.FileIO.BinaryArchiveException"""
    def __init__(self, *args) -> None: ...
    TargetSite: MethodBase
    Message: str
    Data: IDictionary
    InnerException: Exception
    HelpLink: str
    Source: str
    HResult: int
    StackTrace: str

class BinaryArchiveFile:
    """.NET: Rhino.FileIO.BinaryArchiveFile"""
    def __init__(self, *args) -> None: ...
    Reader: BinaryArchiveReader
    Writer: BinaryArchiveWriter
    def Close(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def Open(self, ) -> bool: ...

class BinaryArchiveMode:
    """.NET: Rhino.FileIO.BinaryArchiveMode"""
    def __init__(self, *args) -> None: ...
    ...

class BinaryArchiveReader:
    """.NET: Rhino.FileIO.BinaryArchiveReader"""
    def __init__(self, *args) -> None: ...
    ReadErrorOccured: bool
    Archive3dmVersion: int
    CurrentPosition: int
    def AtEnd(self, ) -> bool: ...
    def BeginRead3dmChunk(self, expectedTypeCode: int, majorVersion: int, minorVersion: int) -> bool: ...
    def Dump3dmChunk(self, log: TextLog) -> int: ...
    def EnableCRCCalculation(self, enable: bool) -> bool: ...
    def EndRead3dmChunk(self, suppressPartiallyReadChunkWarning: bool) -> bool: ...
    def Read3dmChunkVersion(self, major: int, minor: int) -> None: ...
    def Read3dmStartSection(self, version: int, comment: str) -> bool: ...
    def ReadBool(self, ) -> bool: ...
    def ReadBoolArray(self, ) -> list: ...
    def ReadBoundingBox(self, ) -> BoundingBox: ...
    def ReadByte(self, ) -> int: ...
    def ReadByteArray(self, ) -> list: ...
    def ReadCheckSum(self, ) -> None: ...
    def ReadColor(self, ) -> Color: ...
    def ReadCompressedBuffer(self, ) -> list: ...
    def ReadDictionary(self, ) -> ArchivableDictionary: ...
    def ReadDouble(self, ) -> float: ...
    def ReadDoubleArray(self, ) -> list: ...
    def ReadFont(self, ) -> Font: ...
    def ReadGeometry(self, ) -> GeometryBase: ...
    def ReadGeometryArray(self, ) -> list: ...
    def ReadGuid(self, ) -> Guid: ...
    def ReadGuidArray(self, ) -> list: ...
    def ReadInt(self, ) -> int: ...
    def ReadInt64(self, ) -> int: ...
    def ReadIntArray(self, ) -> list: ...
    def ReadInterval(self, ) -> Interval: ...
    def ReadLine(self, ) -> Line: ...
    def ReadMeshingParameters(self, ) -> MeshingParameters: ...
    def ReadObjRef(self, ) -> ObjRef: ...
    def ReadObjRefArray(self, ) -> list: ...
    def ReadPlane(self, ) -> Plane: ...
    def ReadPoint(self, ) -> Point: ...
    def ReadPoint2d(self, ) -> Point2d: ...
    def ReadPoint3d(self, ) -> Point3d: ...
    def ReadPoint3f(self, ) -> Point3f: ...
    def ReadPoint4d(self, ) -> Point4d: ...
    def ReadPointF(self, ) -> PointF: ...
    def ReadRay3d(self, ) -> Ray3d: ...
    def ReadRectangle(self, ) -> Rectangle: ...
    def ReadRectangleF(self, ) -> RectangleF: ...
    def ReadRenderSettings(self, ) -> RenderSettings: ...
    def ReadSByte(self, ) -> int: ...
    def ReadSByteArray(self, ) -> list: ...
    def ReadShort(self, ) -> int: ...
    def ReadShortArray(self, ) -> list: ...
    def ReadSingle(self, ) -> float: ...
    def ReadSingleArray(self, ) -> list: ...
    def ReadSize(self, ) -> Size: ...
    def ReadSizeF(self, ) -> SizeF: ...
    def ReadString(self, ) -> str: ...
    def ReadStringArray(self, ) -> list: ...
    def ReadTransform(self, ) -> Transform: ...
    def ReadUInt(self, ) -> int: ...
    def ReadUShort(self, ) -> int: ...
    def ReadUtf8String(self, ) -> str: ...
    def ReadVector2d(self, ) -> Vector2d: ...
    def ReadVector3d(self, ) -> Vector3d: ...
    def ReadVector3f(self, ) -> Vector3f: ...
    def SeekFromCurrentPosition(self, byteOffset: int, forward: bool) -> bool: ...
    def SeekFromStart(self, byteOffset: int) -> bool: ...

class BinaryArchiveWriter:
    """.NET: Rhino.FileIO.BinaryArchiveWriter"""
    def __init__(self, *args) -> None: ...
    WriteErrorOccured: bool
    Archive3dmVersion: int
    def BeginWrite3dmChunk(self, typecode: int, majorVersion: int, minorVersion: int) -> bool: ...
    def EnableCRCCalculation(self, enable: bool) -> bool: ...
    def EndWrite3dmChunk(self, ) -> bool: ...
    def Write3dmChunkVersion(self, major: int, minor: int) -> None: ...
    def WriteBool(self, value: bool) -> None: ...
    def WriteBoolArray(self, value: IEnumerable) -> None: ...
    def WriteBoundingBox(self, value: BoundingBox) -> None: ...
    def WriteByte(self, value: int) -> None: ...
    def WriteByteArray(self, value: IEnumerable) -> None: ...
    def WriteColor(self, value: Color) -> None: ...
    def WriteCompressedBuffer(self, value: IEnumerable) -> None: ...
    def WriteDictionary(self, dictionary: ArchivableDictionary) -> None: ...
    def WriteDouble(self, value: float) -> None: ...
    def WriteDoubleArray(self, value: IEnumerable) -> None: ...
    def WriteEmptyCheckSum(self, ) -> None: ...
    def WriteFont(self, value: Font) -> None: ...
    def WriteGeometry(self, value: GeometryBase) -> None: ...
    def WriteGeometryArray(self, geometry: IEnumerable) -> None: ...
    def WriteGuid(self, value: Guid) -> None: ...
    def WriteGuidArray(self, value: IEnumerable) -> None: ...
    def WriteInt(self, value: int) -> None: ...
    def WriteInt64(self, value: int) -> None: ...
    def WriteIntArray(self, value: IEnumerable) -> None: ...
    def WriteInterval(self, value: Interval) -> None: ...
    def WriteLine(self, value: Line) -> None: ...
    def WriteMeshingParameters(self, value: MeshingParameters) -> None: ...
    def WriteObjRef(self, objref: ObjRef) -> None: ...
    def WriteObjRefArray(self, objrefs: IEnumerable) -> None: ...
    def WritePlane(self, value: Plane) -> None: ...
    def WritePoint(self, value: Point) -> None: ...
    def WritePoint2d(self, value: Point2d) -> None: ...
    def WritePoint3d(self, value: Point3d) -> None: ...
    def WritePoint3f(self, value: Point3f) -> None: ...
    def WritePoint4d(self, value: Point4d) -> None: ...
    def WritePointF(self, value: PointF) -> None: ...
    def WriteRay3d(self, value: Ray3d) -> None: ...
    def WriteRectangle(self, value: Rectangle) -> None: ...
    def WriteRectangleF(self, value: RectangleF) -> None: ...
    def WriteRenderSettings(self, value: RenderSettings) -> None: ...
    def WriteSByte(self, value: int) -> None: ...
    def WriteSByteArray(self, value: IEnumerable) -> None: ...
    def WriteShort(self, value: int) -> None: ...
    def WriteShortArray(self, value: IEnumerable) -> None: ...
    def WriteSingle(self, value: float) -> None: ...
    def WriteSingleArray(self, value: IEnumerable) -> None: ...
    def WriteSize(self, value: Size) -> None: ...
    def WriteSizeF(self, value: SizeF) -> None: ...
    def WriteString(self, value: str) -> None: ...
    def WriteStringArray(self, value: IEnumerable) -> None: ...
    def WriteTransform(self, value: Transform) -> None: ...
    def WriteUInt(self, value: int) -> None: ...
    def WriteUShort(self, value: int) -> None: ...
    def WriteUtf8String(self, value: str) -> None: ...
    def WriteVector2d(self, value: Vector2d) -> None: ...
    def WriteVector3d(self, value: Vector3d) -> None: ...
    def WriteVector3f(self, value: Vector3f) -> None: ...

class CommonComponentTable:
    """.NET: Rhino.FileIO.CommonComponentTable`1"""
    def __init__(self, *args) -> None: ...
    Count: int
    ComponentType: ModelComponentType
    def Clear(self, ) -> None: ...
    def Delete(self, item: T) -> bool: ...
    def FindId(self, id: Guid) -> T: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class ContentHash:
    """.NET: Rhino.FileIO.ContentHash"""
    def __init__(self, *args) -> None: ...
    Sha1NameHash: list
    ByteCount: int
    Sha1ContentHash: list
    HashTime: DateTime
    def Clone(self, ) -> ContentHash: ...
    @staticmethod
    def CreateFromFile(path: str) -> ContentHash: ...
    def Equals(self, other: ContentHash) -> bool: ...
    def GetHashCode(self, ) -> int: ...

class DracoColorFormat:
    """.NET: Rhino.FileIO.DracoColorFormat"""
    def __init__(self, *args) -> None: ...
    ...

class DracoCompression:
    """.NET: Rhino.FileIO.DracoCompression"""
    def __init__(self, *args) -> None: ...
    VertexAttributePosition: int
    NormalAttributePosition: int
    TextureCoordinatesAttributePosition: int
    VertexColorAttributePosition: int
    @staticmethod
    def Compress(mesh: Mesh, options: DracoCompressionOptions) -> DracoCompression: ...
    @staticmethod
    def DecompressBase64String(encoded: str) -> GeometryBase: ...
    @staticmethod
    def DecompressByteArray(bytes: list) -> GeometryBase: ...
    @staticmethod
    def DecompressFile(path: str) -> GeometryBase: ...
    def Dispose(self, ) -> None: ...
    def ToBase64String(self, ) -> str: ...
    def ToByteArray(self, ) -> list: ...
    def Write(self, path: str) -> bool: ...

class DracoCompressionOptions:
    """.NET: Rhino.FileIO.DracoCompressionOptions"""
    def __init__(self, *args) -> None: ...
    CompressionLevel: int
    PositionQuantizationBits: int
    TextureCoordintateQuantizationBits: int
    NormalQuantizationBits: int

class File3dm:
    """.NET: Rhino.FileIO.File3dm"""
    def __init__(self, *args) -> None: ...
    StartSectionComments: str
    ArchiveVersion: int
    Notes: File3dmNotes
    ApplicationName: str
    ApplicationUrl: str
    ApplicationDetails: str
    CreatedBy: str
    LastEditedBy: str
    Created: DateTime
    LastEdited: DateTime
    Revision: int
    EarthAnchorPoint: EarthAnchorPoint
    Settings: File3dmSettings
    Manifest: ManifestTable
    Objects: File3dmObjectTable
    Materials: IList
    AllMaterials: File3dmMaterialTable
    Linetypes: IList
    AllLinetypes: File3dmLinetypeTable
    Layers: IList
    AllLayers: File3dmLayerTable
    AllGroups: File3dmGroupTable
    DimStyles: IList
    AllDimStyles: File3dmDimStyleTable
    HatchPatterns: IList
    AllHatchPatterns: File3dmHatchPatternTable
    InstanceDefinitions: IList
    AllInstanceDefinitions: File3dmInstanceDefinitionTable
    Views: IList
    AllViews: File3dmViewTable
    NamedViews: IList
    AllNamedViews: File3dmViewTable
    NamedConstructionPlanes: IList
    AllNamedConstructionPlanes: File3dmNamedConstructionPlanes
    PlugInData: File3dmPlugInDataTable
    Strings: File3dmStringTable
    EmbeddedFiles: File3dmEmbeddedFiles
    RenderMaterials: File3dmRenderMaterials
    RenderEnvironments: File3dmRenderEnvironments
    RenderTextures: File3dmRenderTextures
    def Audit(self, attemptRepair: bool, repairCount: int, errors: str, warnings: list) -> int: ...
    def Dispose(self, ) -> None: ...
    def Dump(self, ) -> str: ...
    def DumpSummary(self, ) -> str: ...
    def DumpToTextLog(self, log: TextLog) -> None: ...
    @staticmethod
    def FromByteArray(bytes: list) -> File3dm: ...
    def GetPreviewImage(self, ) -> Bitmap: ...
    def IsValid(self, errors: str) -> bool: ...
    def Polish(self, ) -> None: ...
    @staticmethod
    def Read(path: str, tableTypeFilterFilter: TableTypeFilter, objectTypeFilter: ObjectTypeFilter) -> File3dm: ...
    @staticmethod
    def ReadApplicationData(path: str, applicationName: str, applicationUrl: str, applicationDetails: str) -> None: ...
    @staticmethod
    def ReadArchiveVersion(path: str) -> int: ...
    @staticmethod
    def ReadDimensionStyles(path: str) -> list: ...
    @staticmethod
    def ReadEarthAnchorPoint(path: str) -> EarthAnchorPoint: ...
    @staticmethod
    def ReadNotes(path: str) -> str: ...
    @staticmethod
    def ReadPreviewImage(path: str) -> Bitmap: ...
    @staticmethod
    def ReadRevisionHistory(path: str, createdBy: str, lastEditedBy: str, revision: int, createdOn: DateTime, lastEditedOn: DateTime) -> bool: ...
    @staticmethod
    def ReadWithLog(path: str, tableTypeFilterFilter: TableTypeFilter, objectTypeFilter: ObjectTypeFilter, errorLog: str) -> File3dm: ...
    def SetPreviewImage(self, image: Bitmap) -> None: ...
    def ToByteArray(self, options: File3dmWriteOptions) -> list: ...
    def Write(self, path: str, version: int) -> bool: ...
    @staticmethod
    def WriteMultipleObjects(path: str, geometry: IEnumerable) -> bool: ...
    @staticmethod
    def WriteOneObject(path: str, geometry: GeometryBase) -> bool: ...
    def WriteWithLog(self, path: str, version: int, errorLog: str) -> bool: ...

class File3dmCommonComponentTable(CommonComponentTable):
    """.NET: Rhino.FileIO.File3dmCommonComponentTable`1"""
    def __init__(self, *args) -> None: ...
    Count: int
    ComponentType: ModelComponentType
    def Add(self, item: T) -> None: ...
    def Delete(self, item: T) -> bool: ...
    def Dump(self, ) -> str: ...

class File3dmCurvePiping:
    """.NET: Rhino.FileIO.File3dmCurvePiping"""
    def __init__(self, *args) -> None: ...
    On: bool
    Radius: float
    Segments: int
    Faceted: bool
    Accuracy: int
    CapType: CapTypes

class File3dmDimStyleTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmDimStyleTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def FindIndex(self, index: int) -> DimensionStyle: ...
    def FindName(self, name: str) -> DimensionStyle: ...
    def FindNameHash(self, nameHash: NameHash) -> DimensionStyle: ...

class File3dmDisplacement:
    """.NET: Rhino.FileIO.File3dmDisplacement"""
    def __init__(self, *args) -> None: ...
    On: bool
    TextureId: Guid
    MappingChannel: int
    BlackPoint: float
    WhitePoint: float
    InitialQuality: int
    FinalMaxFacesOn: bool
    FinalMaxFaces: int
    FairingOn: bool
    Fairing: int
    PostWeldAngle: float
    MeshMemoryLimit: int
    RefineSteps: int
    RefineSensitivity: float
    SweepResolutionFormula: SweepResolutionFormulas
    def AddSubItem(self, face_index: int, on: bool, texture: Guid, mapping_channel: int, black_point: float, white_point: float) -> bool: ...
    def DeleteAllSubItems(self, ) -> None: ...
    def DeleteSubItem(self, face_index: int) -> None: ...
    def GetSubItemFaceIndexes(self, ) -> list: ...
    def SetSubItemBlackPoint(self, face_index: int, black_point: float) -> None: ...
    def SetSubItemMappingChannel(self, face_index: int, chan: int) -> None: ...
    def SetSubItemOn(self, face_index: int, on: bool) -> None: ...
    def SetSubItemTexture(self, face_index: int, texture_id: Guid) -> None: ...
    def SetSubItemWhitePoint(self, face_index: int, white_point: float) -> None: ...
    def SubItemBlackPoint(self, face_index: int) -> float: ...
    def SubItemMappingChannel(self, face_index: int) -> int: ...
    def SubItemOn(self, face_index: int) -> bool: ...
    def SubItemTexture(self, face_index: int) -> Guid: ...
    def SubItemWhitePoint(self, face_index: int) -> float: ...

class File3dmEdgeSoftening:
    """.NET: Rhino.FileIO.File3dmEdgeSoftening"""
    def __init__(self, *args) -> None: ...
    On: bool
    Softening: float
    Chamfer: bool
    Faceted: bool
    EdgeAngleThreshold: float
    ForceSoftening: bool

class File3dmEmbeddedFile(ModelComponent):
    """.NET: Rhino.FileIO.File3dmEmbeddedFile"""
    def __init__(self, *args) -> None: ...
    Filename: str
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    Id: Guid
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    Name: str
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def SaveToFile(self, filename: str) -> bool: ...

class File3dmEmbeddedFiles:
    """.NET: Rhino.FileIO.File3dmEmbeddedFiles"""
    def __init__(self, *args) -> None: ...
    def Add(self, filename: str) -> bool: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class File3dmGroupTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmGroupTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def AddGroup(self, ) -> int: ...
    def FindIndex(self, groupIndex: int) -> Group: ...
    def FindName(self, name: str) -> Group: ...
    def FindNameHash(self, nameHash: NameHash) -> Group: ...
    def GroupMembers(self, groupIndex: int) -> list: ...

class File3dmHatchPatternTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmHatchPatternTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def FindIndex(self, index: int) -> HatchPattern: ...
    def FindName(self, name: str) -> HatchPattern: ...
    def FindNameHash(self, nameHash: NameHash) -> HatchPattern: ...

class File3dmInstanceDefinitionTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmInstanceDefinitionTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def Add(self, name: str, description: str, url: str, urlTag: str, basePoint: Point3d, geometry: IEnumerable, attributes: IEnumerable) -> int: ...
    def AddLinked(self, filename: str, name: str, description: str) -> int: ...
    def FindName(self, name: str) -> InstanceDefinitionGeometry: ...
    def FindNameHash(self, nameHash: NameHash) -> InstanceDefinitionGeometry: ...

class File3dmLayerTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmLayerTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def AddDefaultLayer(self, name: str, color: Color) -> int: ...
    def AddLayer(self, name: str, color: Color, parentId: Guid) -> int: ...
    def FindIndex(self, index: int) -> Layer: ...
    def FindName(self, name: str, parentId: Guid) -> Layer: ...
    def FindNameHash(self, nameHash: NameHash) -> Layer: ...

class File3dmLinetypeTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmLinetypeTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def FindIndex(self, index: int) -> Linetype: ...
    def FindName(self, name: str) -> Linetype: ...
    def FindNameHash(self, nameHash: NameHash) -> Linetype: ...

class File3dmMaterialTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmMaterialTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def AddMaterial(self, material: Material) -> int: ...
    def FindIndex(self, index: int) -> Material: ...

class File3dmMeshModifiers:
    """.NET: Rhino.FileIO.File3dmMeshModifiers"""
    def __init__(self, *args) -> None: ...
    Displacement: File3dmDisplacement
    EdgeSoftening: File3dmEdgeSoftening
    Thickening: File3dmThickening
    CurvePiping: File3dmCurvePiping
    ShutLining: File3dmShutLining

class File3dmNamedConstructionPlanes:
    """.NET: Rhino.FileIO.File3dmNamedConstructionPlanes"""
    def __init__(self, *args) -> None: ...
    Item: ConstructionPlane
    Count: int
    def Add(self, name: str, plane: Plane) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, cplane: ConstructionPlane) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def Delete(self, index: int) -> bool: ...
    def FindName(self, name: str) -> ConstructionPlane: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, cplane: ConstructionPlane) -> int: ...

class File3dmNotes:
    """.NET: Rhino.FileIO.File3dmNotes"""
    def __init__(self, *args) -> None: ...
    Notes: str
    IsVisible: bool
    IsHtml: bool
    WindowRectangle: Rectangle

class File3dmObject(ModelComponent):
    """.NET: Rhino.FileIO.File3dmObject"""
    def __init__(self, *args) -> None: ...
    Geometry: GeometryBase
    Attributes: ObjectAttributes
    Name: str
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    Id: Guid
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def GetTextureMapping(self, mappingChannelId: int, xform: Transform) -> TextureMapping: ...
    def TryReadUserData(self, userDataId: Guid, readFromAttributes: bool, dataReader: Func) -> bool: ...

class File3dmObjectTable(File3dmCommonComponentTable):
    """.NET: Rhino.FileIO.File3dmObjectTable"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    Count: int
    def Add(self, item: GeometryBase, attributes: ObjectAttributes) -> Guid: ...
    def AddAngularDimension(self, dimension: AngularDimension, attributes: ObjectAttributes) -> Guid: ...
    def AddArc(self, arc: Arc, attributes: ObjectAttributes) -> Guid: ...
    def AddBrep(self, brep: Brep, attributes: ObjectAttributes) -> Guid: ...
    def AddCircle(self, circle: Circle, attributes: ObjectAttributes) -> Guid: ...
    def AddClippingPlane(self, plane: Plane, uMagnitude: float, vMagnitude: float, clippedViewportIds: IEnumerable, attributes: ObjectAttributes) -> Guid: ...
    def AddCurve(self, curve: Curve, attributes: ObjectAttributes) -> Guid: ...
    def AddEllipse(self, ellipse: Ellipse, attributes: ObjectAttributes) -> Guid: ...
    def AddExtrusion(self, extrusion: Extrusion, attributes: ObjectAttributes) -> Guid: ...
    def AddHatch(self, hatch: Hatch, attributes: ObjectAttributes) -> Guid: ...
    def AddInstanceObject(self, instanceDefinitionIndex: int, instanceXform: Transform, attributes: ObjectAttributes) -> Guid: ...
    def AddLeader(self, text: str, plane: Plane, points: IEnumerable, attributes: ObjectAttributes) -> Guid: ...
    def AddLine(self, from_: Point3d, to: Point3d, attributes: ObjectAttributes) -> Guid: ...
    def AddLinearDimension(self, dimension: LinearDimension, attributes: ObjectAttributes) -> Guid: ...
    def AddMesh(self, mesh: Mesh, attributes: ObjectAttributes) -> Guid: ...
    def AddOrdinateDimension(self, dimension: OrdinateDimension, attributes: ObjectAttributes) -> Guid: ...
    def AddPoint(self, x: float, y: float, z: float) -> Guid: ...
    def AddPointCloud(self, cloud: PointCloud, attributes: ObjectAttributes) -> Guid: ...
    def AddPoints(self, points: IEnumerable, attributes: ObjectAttributes) -> list: ...
    def AddPolyline(self, points: IEnumerable, attributes: ObjectAttributes) -> Guid: ...
    def AddRadialDimension(self, dimension: RadialDimension, attributes: ObjectAttributes) -> Guid: ...
    def AddSphere(self, sphere: Sphere, attributes: ObjectAttributes) -> Guid: ...
    def AddSubD(self, subd: SubD, attributes: ObjectAttributes) -> Guid: ...
    def AddSurface(self, surface: Surface, attributes: ObjectAttributes) -> Guid: ...
    def AddText(self, text: str, plane: Plane, height: float, fontName: str, bold: bool, italic: bool, justification: TextJustification, attributes: ObjectAttributes) -> Guid: ...
    def AddTextDot(self, text: str, location: Point3d, attributes: ObjectAttributes) -> Guid: ...
    def Delete(self, objectId: Guid) -> bool: ...
    def FindByGroup(self, group: Group) -> list: ...
    def FindByLayer(self, layer: str) -> list: ...
    def GetBoundingBox(self, ) -> BoundingBox: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class File3dmPlugInData:
    """.NET: Rhino.FileIO.File3dmPlugInData"""
    def __init__(self, *args) -> None: ...
    PlugInId: Guid

class File3dmPlugInDataTable:
    """.NET: Rhino.FileIO.File3dmPlugInDataTable"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: File3dmPlugInData
    def Clear(self, ) -> None: ...
    def Dump(self, ) -> str: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def TryRead(self, pluginData: File3dmPlugInData, dataReader: Func) -> bool: ...

class File3dmRenderContent(ModelComponent):
    """.NET: Rhino.FileIO.File3dmRenderContent"""
    def __init__(self, *args) -> None: ...
    Kind: str
    TypeName: str
    TypeId: Guid
    RenderEngineId: Guid
    PlugInId: Guid
    GroupId: Guid
    Notes: str
    Tags: str
    Hidden: bool
    Reference: bool
    AutoDelete: bool
    File3dmParent: File3dm
    Parent: File3dmRenderContent
    TopLevel: File3dmRenderContent
    Children: IEnumerable
    IsTopLevel: bool
    IsChild: bool
    ChildSlotName: str
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    Id: Guid
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    Name: str
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def ChildSlotOn(self, child_slot_name: str) -> bool: ...
    def DeleteChild(self, child_slot_name: str) -> bool: ...
    def FindChild(self, child_slot_name: str) -> File3dmRenderContent: ...
    def GetParameter(self, param: str) -> IConvertible: ...
    def SetParameter(self, param: str, value: object) -> bool: ...
    def XML(self, recursive: bool) -> str: ...

class File3dmRenderEnvironment(File3dmRenderContent):
    """.NET: Rhino.FileIO.File3dmRenderEnvironment"""
    def __init__(self, *args) -> None: ...
    Kind: str
    TypeName: str
    TypeId: Guid
    RenderEngineId: Guid
    PlugInId: Guid
    GroupId: Guid
    Notes: str
    Tags: str
    Hidden: bool
    Reference: bool
    AutoDelete: bool
    File3dmParent: File3dm
    Parent: File3dmRenderContent
    TopLevel: File3dmRenderContent
    Children: IEnumerable
    IsTopLevel: bool
    IsChild: bool
    ChildSlotName: str
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    Id: Guid
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    Name: str
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def ToEnvironment(self, ) -> Environment: ...

class File3dmRenderEnvironments:
    """.NET: Rhino.FileIO.File3dmRenderEnvironments"""
    def __init__(self, *args) -> None: ...
    def Find(self, g: Guid) -> File3dmRenderEnvironment: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class File3dmRenderMaterial(File3dmRenderContent):
    """.NET: Rhino.FileIO.File3dmRenderMaterial"""
    def __init__(self, *args) -> None: ...
    Kind: str
    TypeName: str
    TypeId: Guid
    RenderEngineId: Guid
    PlugInId: Guid
    GroupId: Guid
    Notes: str
    Tags: str
    Hidden: bool
    Reference: bool
    AutoDelete: bool
    File3dmParent: File3dm
    Parent: File3dmRenderContent
    TopLevel: File3dmRenderContent
    Children: IEnumerable
    IsTopLevel: bool
    IsChild: bool
    ChildSlotName: str
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    Id: Guid
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    Name: str
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def ToMaterial(self, ) -> Material: ...

class File3dmRenderMaterials:
    """.NET: Rhino.FileIO.File3dmRenderMaterials"""
    def __init__(self, *args) -> None: ...
    def Find(self, g: Guid) -> File3dmRenderMaterial: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class File3dmRenderTexture(File3dmRenderContent):
    """.NET: Rhino.FileIO.File3dmRenderTexture"""
    def __init__(self, *args) -> None: ...
    Filename: str
    Kind: str
    TypeName: str
    TypeId: Guid
    RenderEngineId: Guid
    PlugInId: Guid
    GroupId: Guid
    Notes: str
    Tags: str
    Hidden: bool
    Reference: bool
    AutoDelete: bool
    File3dmParent: File3dm
    Parent: File3dmRenderContent
    TopLevel: File3dmRenderContent
    Children: IEnumerable
    IsTopLevel: bool
    IsChild: bool
    ChildSlotName: str
    ComponentType: ModelComponentType
    IsSystemComponent: bool
    IsDeleted: bool
    IsReference: bool
    Id: Guid
    HasId: bool
    IdIsLocked: bool
    Index: int
    HasIndex: bool
    IndexIsLocked: bool
    ComponentStatus: ComponentStatus
    IsComponentStatusLocked: bool
    Name: str
    HasName: bool
    NameIsLocked: bool
    DeletedName: str
    ModelSerialNumber: int
    ReferenceModelSerialNumber: int
    InstanceDefinitionModelSerialNumber: int
    IsDocumentControlled: bool
    IsValid: bool
    Disposed: bool
    HasUserData: bool
    UserData: UserDataList
    UserDictionary: ArchivableDictionary
    def ToTexture(self, ) -> Texture: ...

class File3dmRenderTextures:
    """.NET: Rhino.FileIO.File3dmRenderTextures"""
    def __init__(self, *args) -> None: ...
    def Find(self, g: Guid) -> File3dmRenderTexture: ...
    def GetEnumerator(self, ) -> IEnumerator: ...

class File3dmSettings:
    """.NET: Rhino.FileIO.File3dmSettings"""
    def __init__(self, *args) -> None: ...
    ModelUrl: str
    ModelBasepoint: Point3d
    ModelAbsoluteTolerance: float
    ModelAngleToleranceRadians: float
    ModelAngleToleranceDegrees: float
    ModelRelativeTolerance: float
    PageAbsoluteTolerance: float
    PageAngleToleranceRadians: float
    PageAngleToleranceDegrees: float
    PageRelativeTolerance: float
    ModelUnitSystem: UnitSystem
    PageUnitSystem: UnitSystem
    ModelDistanceDisplayMode: DistanceDisplayMode
    PageDistanceDisplayMode: DistanceDisplayMode
    ModelDistanceDisplayPrecision: int
    PageDistanceDisplayPrecision: int
    RenderSettings: RenderSettings
    ActiveViewId: Guid
    CurrentLayerId: Guid
    CurrentRenderMaterialId: Guid
    CurrentLinePatternId: Guid
    CurrentTextStyleId: Guid
    CurrentDimensionStyleId: Guid
    CurrentHatchPatternId: Guid
    CurrentColor: Color
    CurrentPlotColor: Color
    CurrentWireDensity: int
    InstanceDefinitionLinkUpdate: int
    SaveTextureBitmapsInFile: bool
    LinetypeDisplayScale: float
    MeshingParameters: MeshingParameters
    AnalysisMeshingParameters: MeshingParameters
    CustomRenderMeshingParameters: MeshingParameters
    GridDefaults: ConstructionPlaneGridDefaults

class File3dmShutLining:
    """.NET: Rhino.FileIO.File3dmShutLining"""
    def __init__(self, *args) -> None: ...
    On: bool
    Faceted: bool
    AutoUpdate: bool
    ForceUpdate: bool
    def AddCurve(self, ) -> Guid: ...
    def CurveEnabled(self, curve_id: Guid) -> bool: ...
    def CurveIsBump(self, curve_id: Guid) -> bool: ...
    def CurveProfile(self, curve_id: Guid) -> int: ...
    def CurvePull(self, curve_id: Guid) -> bool: ...
    def CurveRadius(self, curve_id: Guid) -> float: ...
    def DeleteAllCurves(self, ) -> None: ...
    def GetCurves(self, ) -> list: ...
    def SetCurveEnabled(self, curve_id: Guid, enabled: bool) -> None: ...
    def SetCurveIsBump(self, curve_id: Guid, b: bool) -> None: ...
    def SetCurveProfile(self, curve_id: Guid, profile: int) -> None: ...
    def SetCurvePull(self, curve_id: Guid, pull: bool) -> None: ...
    def SetCurveRadius(self, curve_id: Guid, radius: float) -> None: ...

class File3dmStringTable:
    """.NET: Rhino.FileIO.File3dmStringTable"""
    def __init__(self, *args) -> None: ...
    Count: int
    DocumentUserTextCount: int
    def Delete(self, section: str, entry: str) -> None: ...
    def GetEntryNames(self, section: str) -> list: ...
    def GetKey(self, i: int) -> str: ...
    def GetSectionNames(self, ) -> list: ...
    def GetValue(self, section: str, entry: str) -> str: ...
    def SetString(self, section: str, entry: str, value: str) -> str: ...

class File3dmThickening:
    """.NET: Rhino.FileIO.File3dmThickening"""
    def __init__(self, *args) -> None: ...
    On: bool
    Distance: float
    Solid: bool
    OffsetOnly: bool
    BothSides: bool

class File3dmTypeCodes:
    """.NET: Rhino.FileIO.File3dmTypeCodes"""
    def __init__(self, *args) -> None: ...
    ...

class File3dmViewTable:
    """.NET: Rhino.FileIO.File3dmViewTable"""
    def __init__(self, *args) -> None: ...
    Item: ViewInfo
    Count: int
    def Add(self, item: ViewInfo) -> None: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: ViewInfo) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def Delete(self, index: int) -> bool: ...
    def FindName(self, name: str) -> ViewInfo: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def IndexOf(self, item: ViewInfo) -> int: ...

class File3dmWriteOptions:
    """.NET: Rhino.FileIO.File3dmWriteOptions"""
    def __init__(self, *args) -> None: ...
    Version: int
    SaveRenderMeshes: bool
    SaveAnalysisMeshes: bool
    SaveUserData: bool
    def EnableAnalysisMeshes(self, objectType: ObjectType, enable: bool) -> None: ...
    def EnableRenderMeshes(self, objectType: ObjectType, enable: bool) -> None: ...

class File3ds:
    """.NET: Rhino.FileIO.File3ds"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: File3dsReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: File3dsWriteOptions) -> bool: ...

class File3dsReadOptions:
    """.NET: Rhino.FileIO.File3dsReadOptions"""
    def __init__(self, *args) -> None: ...
    Unweld: bool
    UnweldAngle: float
    ImportLights: bool
    ImportCameras: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class File3dsWriteOptions:
    """.NET: Rhino.FileIO.File3dsWriteOptions"""
    def __init__(self, *args) -> None: ...
    SaveViews: bool
    SaveLights: bool
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class File3mf:
    """.NET: Rhino.FileIO.File3mf"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: File3mfWriteOptions) -> bool: ...

class File3mfWriteOptions:
    """.NET: Rhino.FileIO.File3mfWriteOptions"""
    def __init__(self, *args) -> None: ...
    Title: str
    Designer: str
    Description: str
    Copyright: str
    LicenseTerms: str
    Rating: str
    MoveOutputToPositiveXYZOctant: bool
    Metadata: Dictionary
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileAi:
    """.NET: Rhino.FileIO.FileAi"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileAiReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileAiWriteOptions) -> bool: ...

class FileAiReadOptions:
    """.NET: Rhino.FileIO.FileAiReadOptions"""
    def __init__(self, *args) -> None: ...
    PreserveModelScale: bool
    RhinoScale: float
    AiUnits: Units
    AiScale: float
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileAiWriteOptions:
    """.NET: Rhino.FileIO.FileAiWriteOptions"""
    def __init__(self, *args) -> None: ...
    PreserveModelScale: bool
    RhinoScale: float
    AiUnits: Units
    AIScale: float
    UseCMYK: bool
    ExportViewBoundary: bool
    ExportHatchesAsSolidFills: bool
    OrderLayers: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileAmf:
    """.NET: Rhino.FileIO.FileAmf"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileAmfWriteOptions) -> bool: ...

class FileAmfWriteOptions:
    """.NET: Rhino.FileIO.FileAmfWriteOptions"""
    def __init__(self, *args) -> None: ...
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileCd:
    """.NET: Rhino.FileIO.FileCd"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileCdWriteOptions) -> bool: ...

class FileCdWriteOptions:
    """.NET: Rhino.FileIO.FileCdWriteOptions"""
    def __init__(self, *args) -> None: ...
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileCsv:
    """.NET: Rhino.FileIO.FileCsv"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileCsvWriteOptions) -> bool: ...

class FileCsvWriteOptions:
    """.NET: Rhino.FileIO.FileCsvWriteOptions"""
    def __init__(self, *args) -> None: ...
    Header: bool
    LayerName: bool
    LayerIndex: bool
    LayerColor: bool
    LayerHierarchy: bool
    GroupName: bool
    GroupIndexes: bool
    ObjectName: bool
    ObjectColor: bool
    ObjectID: bool
    ObjectMaterial: bool
    ObjectDescription: bool
    SurroundPointsWithDoubleQuotes: bool
    Length: bool
    Perimeter: bool
    Area: bool
    Volume: bool
    AreaCentroid: bool
    VolumeCentroid: bool
    AreaMoments: bool
    VolumeMoments: bool
    CumulativeMassProperties: bool
    AttributesKeys: bool
    AttributesTexts: bool
    ObjectKeys: bool
    ObjectsTexts: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileDgn:
    """.NET: Rhino.FileIO.FileDgn"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileDgnReadOptions) -> bool: ...

class FileDgnReadOptions:
    """.NET: Rhino.FileIO.FileDgnReadOptions"""
    def __init__(self, *args) -> None: ...
    ImportUnreferencedLayers: bool
    ImportUnreferencedBlocks: bool
    ImportUnreferencedLineStyles: bool
    ImportViews: bool
    GroupCellHeaders: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileDst:
    """.NET: Rhino.FileIO.FileDst"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileDstReadOptions) -> bool: ...

class FileDstReadOptions:
    """.NET: Rhino.FileIO.FileDstReadOptions"""
    def __init__(self, *args) -> None: ...
    ImportJumps: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileDwg:
    """.NET: Rhino.FileIO.FileDwg"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileDwgReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileDwgWriteOptions) -> bool: ...

class FileDwgReadOptions:
    """.NET: Rhino.FileIO.FileDwgReadOptions"""
    def __init__(self, *args) -> None: ...
    ImportUnreferencedLayers: bool
    ImportUnreferencedBlocks: bool
    ImportUnreferencedLinetypes: bool
    ConvertWidePolylinesToSurfaces: bool
    IgnoreThickness: bool
    ConvertRegionsToCurves: bool
    MeshPrecision: MeshPrecisionMode
    ModelUnits: UnitSystem
    LayoutUnits: UnitSystem
    SetLayerMaterialToLayerColor: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileDwgWriteOptions:
    """.NET: Rhino.FileIO.FileDwgWriteOptions"""
    def __init__(self, *args) -> None: ...
    Version: AutocadVersion
    SimplifyTolerance: float
    MinPointDistance: float
    CurveUseMaxAngle: bool
    CurveUseChordHeight: bool
    CurveUseSegmentLength: bool
    CurveMaxAngleRadians: float
    CurveMaxAngleDegrees: float
    CurveChordHeight: float
    CurveSegmentLength: float
    ExportMeshesAs: ExportMeshMode
    ExportSurfacesAs: ExportSurfaceMode
    ExportLinesAs: ExportLineMode
    ExportArcsAs: ExportArcMode
    ExportSplinesAs: ExportSplineMode
    ExportPolylinesAs: ExportPolylineMode
    ExportPolycurvesAs: ExportPolycurveMode
    Flatten: FlattenMode
    SplitPolycurves: bool
    SplitSplines: bool
    Simplify: bool
    NoDxfHeader: bool
    IsDefault: bool
    FullLayerPath: bool
    ColorMethod: ColorMethodType
    PreserveArcNormals: bool
    UseLWPolylines: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileEps:
    """.NET: Rhino.FileIO.FileEps"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileEpsReadOptions) -> bool: ...

class FileEpsReadOptions:
    """.NET: Rhino.FileIO.FileEpsReadOptions"""
    def __init__(self, *args) -> None: ...
    PreserveModelScale: bool
    RhinoScale: float
    EpsUnits: Units
    EpsScale: float
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileFbx:
    """.NET: Rhino.FileIO.FileFbx"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileFbxReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileFbxWriteOptions) -> bool: ...

class FileFbxReadOptions:
    """.NET: Rhino.FileIO.FileFbxReadOptions"""
    def __init__(self, *args) -> None: ...
    Unweld: bool
    UnweldAngle: float
    ImportMeshesAsSubD: bool
    ImportLights: bool
    ImportCameras: bool
    MapFbxYtoRhinoZ: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileFbxWriteOptions:
    """.NET: Rhino.FileIO.FileFbxWriteOptions"""
    def __init__(self, *args) -> None: ...
    SaveObjectsAs: ObjectType
    SaveMaterialsAs: MaterialType
    SaveViews: bool
    SaveLights: bool
    SaveVertexNormals: bool
    MapRhinoZtoFbxY: bool
    SaveFileAs: FileType
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileFindPreference:
    """.NET: Rhino.FileIO.FileFindPreference"""
    def __init__(self, *args) -> None: ...
    ...

class FileGHS:
    """.NET: Rhino.FileIO.FileGHS"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileGHSReadOptions) -> bool: ...

class FileGHSReadOptions:
    """.NET: Rhino.FileIO.FileGHSReadOptions"""
    def __init__(self, *args) -> None: ...
    AttachGhsData: bool
    RemoveColinearPoints: bool
    ViewType: ReadViewType
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileGltf:
    """.NET: Rhino.FileIO.FileGltf"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileGltfWriteOptions) -> bool: ...

class FileGltfWriteOptions:
    """.NET: Rhino.FileIO.FileGltfWriteOptions"""
    def __init__(self, *args) -> None: ...
    MapZToY: bool
    ExportMaterials: bool
    CullBackfaces: bool
    UseDisplayColorForUnsetMaterials: bool
    SubDMeshType: SubDMeshing
    SubDSurfaceMeshingDensity: int
    ExportTextureCoordinates: bool
    ExportVertexNormals: bool
    ExportOpenMeshes: bool
    ExportVertexColors: bool
    UseDracoCompression: bool
    DracoCompressionLevel: int
    DracoQuantizationBitsPosition: int
    DracoQuantizationBitsNormal: int
    DracoQuantizationBitsTextureCoordinate: int
    ExportLayers: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileGts:
    """.NET: Rhino.FileIO.FileGts"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileGtsWriteOptions) -> bool: ...

class FileGtsWriteOptions:
    """.NET: Rhino.FileIO.FileGtsWriteOptions"""
    def __init__(self, *args) -> None: ...
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileIgs:
    """.NET: Rhino.FileIO.FileIgs"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileIgsWriteOptions) -> bool: ...

class FileIgsWriteOptions:
    """.NET: Rhino.FileIO.FileIgsWriteOptions"""
    def __init__(self, *args) -> None: ...
    Author: str
    Organization: str
    Sender: str
    Receiver: str
    Units: UnitSystem
    IgesStringType: IgesStringTypeMode
    Tolerance: float
    NotesInStartSection: bool
    RenderColorAsIgesColor: bool
    IgesVersion: IgeswVersionMode
    EolType: EolMode
    Scale: float
    HideDependentObjects: bool
    DoublesUseE: bool
    NoZerosInTSection: bool
    PointType: PointObjectsMode
    CurveMaxDegree: MaxDegreeMode
    CompositeCurvesAsSingleBsplines: bool
    SimplifyCurves: bool
    FitRationalCurves: bool
    ClampCurveEndKnots: bool
    UseParentLabelOnCurves: bool
    ForceBezierKnotsOnCurves: bool
    FlagDependentCurvesAs03: bool
    WriteNonPlanarUnitNormal: bool
    SurfaceType: SurfacesMode
    PolySurfaceType: PolySurfacesMode
    MaxSurfaceDegree: MaxDegreeMode
    SolidType: SolidsMode
    MeshType: MeshesMode
    SimplifySurfaces: bool
    FitRationalSurfaces: bool
    ClampSurfaceEndKnots: bool
    UseParentLabelOnSurfaces: bool
    ForceBezierKnotsOnSurfaces: bool
    FlagDependentSurfacesAs03: bool
    SplitClosedSurfaces: bool
    SplitBiPolarSurfaces: bool
    ForceTrimmedSurfaces: bool
    CatiaVersion: int
    CatiaTolsize: float
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileLwo:
    """.NET: Rhino.FileIO.FileLwo"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileLwoReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileLwoWriteOptions) -> bool: ...

class FileLwoReadOptions:
    """.NET: Rhino.FileIO.FileLwoReadOptions"""
    def __init__(self, *args) -> None: ...
    Unweld: bool
    UnweldAngle: float
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileLwoWriteOptions:
    """.NET: Rhino.FileIO.FileLwoWriteOptions"""
    def __init__(self, *args) -> None: ...
    WriteVersion6: bool
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileObj:
    """.NET: Rhino.FileIO.FileObj"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(filename: str, doc: RhinoDoc, options: FileObjReadOptions) -> bool: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileObjWriteOptions) -> WriteFileResult: ...

class FileObjReadOptions:
    """.NET: Rhino.FileIO.FileObjReadOptions"""
    def __init__(self, *args) -> None: ...
    UseObjGroupsAs: UseObjGsAs
    UseObjObjectsAs: UseObjOsAs
    MapYtoZ: bool
    MorphTargetOnly: bool
    ReverseGroupOrder: bool
    IgnoreTextures: bool
    DisplayColorFromObjMaterial: bool
    Split32BitTextures: bool
    def GetTransform(self, ) -> Transform: ...

class FileObjWriteOptions:
    """.NET: Rhino.FileIO.FileObjWriteOptions"""
    def __init__(self, *args) -> None: ...
    ActualFilePathOnMac: str
    EolType: AsciiEol
    TrimCurveType: CurveType
    ObjectType: GeometryType
    ExportObjectNames: ObjObjectNames
    ExportGroupNameLayerNames: ObjGroupNames
    ExportMaterialDefinitions: bool
    UseDisplayColorForMaterial: bool
    MapZtoY: bool
    SignificantDigits: int
    WrapLongLines: bool
    MergeNestedGroupingNames: bool
    SortObjGroups: bool
    PolylineType: PolylineExportType
    MeshType: VertexWelding
    SubDMeshType: SubDMeshing
    CreateNgons: bool
    NgonMode: NGons
    IncludeUnweldedEdgesInNgons: bool
    CullUnnecessaryVertexesInNgons: bool
    MinNgonFaceCount: int
    ExportTcs: bool
    ExportNormals: bool
    ExportAsTriangles: bool
    ExportVcs: bool
    VcsFormat: int
    ExportOpenMeshes: bool
    UseRenderMeshes: bool
    UnderbarMaterialNames: bool
    UseSimpleDialog: bool
    MeshParameters: MeshingParameters
    UseRelativeIndexing: bool
    SubDSurfaceMeshingDensity: int
    def GetTransform(self, ) -> Transform: ...

class FilePdf:
    """.NET: Rhino.FileIO.FilePdf"""
    def __init__(self, *args) -> None: ...
    LayersAsOptionalContentGroups: bool
    def AddPage(self, widthInDots: int, heightInDots: int, dotsPerInch: int) -> int: ...
    @staticmethod
    def Create() -> FilePdf: ...
    def DrawBitmap(self, pageNumber: int, bitmap: Bitmap, left: float, top: float, width: float, height: float, rotationInDegrees: float) -> None: ...
    def DrawLine(self, pageNumber: int, from_: PointF, to: PointF, strokeColor: Color, strokeWidth: float) -> None: ...
    def DrawPolyline(self, pageNumber: int, polyline: list, fillColor: Color, strokeColor: Color, strokeWidth: float) -> None: ...
    def DrawText(self, pageNumber: int, text: str, x: float, y: float, heightPoints: float, onfont: Font, fillColor: Color, strokeColor: Color, strokeWidth: float, angleDegrees: float, horizontalAlignment: TextHorizontalAlignment, verticalAlignment: TextVerticalAlignment) -> None: ...
    def PdfDocumentImplementation(self, ) -> object: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FilePdfReadOptions) -> bool: ...
    def Write(self, filename: str) -> None: ...

class FilePdfEventArgs(EventArgs):
    """.NET: Rhino.FileIO.FilePdfEventArgs"""
    def __init__(self, *args) -> None: ...
    Pdf: FilePdf

class FilePdfReadOptions:
    """.NET: Rhino.FileIO.FilePdfReadOptions"""
    def __init__(self, *args) -> None: ...
    PreserveModelScale: bool
    RhinoScale: float
    PdfUnits: PDF_UNITS
    PDFScale: float
    ImportFillsAsHatches: bool
    LoadText: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FilePly:
    """.NET: Rhino.FileIO.FilePly"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FilePlyReadOptions) -> bool: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FilePlyWriteOptions) -> WriteFileResult: ...

class FilePlyReadOptions:
    """.NET: Rhino.FileIO.FilePlyReadOptions"""
    def __init__(self, *args) -> None: ...
    PLYModelUnits: UnitSystem
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FilePlyWriteOptions:
    """.NET: Rhino.FileIO.FilePlyWriteOptions"""
    def __init__(self, *args) -> None: ...
    UseSimpleDialog: bool
    ExportASCII: bool
    ExportDoubles: bool
    ExportNormals: bool
    ExportColors: bool
    ExportMaterial: bool
    MeshingParameters: MeshingParameters

class FilePov:
    """.NET: Rhino.FileIO.FilePov"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FilePovWriteOptions) -> bool: ...

class FilePovWriteOptions:
    """.NET: Rhino.FileIO.FilePovWriteOptions"""
    def __init__(self, *args) -> None: ...
    ExportAsOneFile: bool
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileRaw:
    """.NET: Rhino.FileIO.FileRaw"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileRawReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileRawWriteOptions) -> bool: ...

class FileRawReadOptions:
    """.NET: Rhino.FileIO.FileRawReadOptions"""
    def __init__(self, *args) -> None: ...
    RawModelUnits: UnitSystem
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileRawWriteOptions:
    """.NET: Rhino.FileIO.FileRawWriteOptions"""
    def __init__(self, *args) -> None: ...
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileReadOptions:
    """.NET: Rhino.FileIO.FileReadOptions"""
    def __init__(self, *args) -> None: ...
    ImportMode: bool
    OpenMode: bool
    NewMode: bool
    InsertMode: bool
    ImportReferenceMode: bool
    BatchMode: bool
    UseScaleGeometry: bool
    ScaleGeometry: bool
    WorkSessionReferenceModelSerialNumber: int
    LinkedInstanceDefinitionSerialNumber: int
    ReferenceModelGrandParentLayerId: Guid
    OptionsDictionary: ArchivableDictionary
    def Dispose(self, ) -> None: ...

class FileReference:
    """.NET: Rhino.FileIO.FileReference"""
    def __init__(self, *args) -> None: ...
    FullPath: str
    RelativePath: str
    ContentHash: ContentHash
    FullPathStatus: FileReferenceStatus
    IsSet: bool
    @staticmethod
    def CreateFromFullAndRelativePaths(fullPath: str, relativePath: str) -> FileReference: ...
    @staticmethod
    def CreateFromFullPath(fullPath: str) -> FileReference: ...
    def Dispose(self, ) -> None: ...

class FileReferenceStatus:
    """.NET: Rhino.FileIO.FileReferenceStatus"""
    def __init__(self, *args) -> None: ...
    ...

class FileSW:
    """.NET: Rhino.FileIO.FileSW"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileSwReadOptions) -> bool: ...

class FileSat:
    """.NET: Rhino.FileIO.FileSat"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileSatWriteOptions) -> bool: ...

class FileSatWriteOptions:
    """.NET: Rhino.FileIO.FileSatWriteOptions"""
    def __init__(self, *args) -> None: ...
    Type: SatTypes
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileSkp:
    """.NET: Rhino.FileIO.FileSkp"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileSkpReadOptions) -> bool: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileSkpWriteOptions) -> bool: ...

class FileSkpReadOptions:
    """.NET: Rhino.FileIO.FileSkpReadOptions"""
    def __init__(self, *args) -> None: ...
    ImportFacesAsMeshes: bool
    ImportCurves: bool
    JoinEdges: bool
    JoinFaces: bool
    Weld: bool
    WeldAngle: float
    UseGroupLayers: bool
    AddObjectsToGroups: bool
    EmbedTexturesInModel: bool
    UseSketchUpTextureWriter: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileSkpWriteOptions:
    """.NET: Rhino.FileIO.FileSkpWriteOptions"""
    def __init__(self, *args) -> None: ...
    Version: SketchUpVersion
    ExportPlanarRegionsAsPolygons: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileSlc:
    """.NET: Rhino.FileIO.FileSlc"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileSlcWriteOptions) -> bool: ...

class FileSlcWriteOptions:
    """.NET: Rhino.FileIO.FileSlcWriteOptions"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point3d
    EndPoint: Point3d
    SliceDistance: float
    UseMeshes: bool
    AngleBetweenSegmentsDegrees: float

class FileStl:
    """.NET: Rhino.FileIO.FileStl"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileStlReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileStlWriteOptions) -> bool: ...

class FileStlReadOptions:
    """.NET: Rhino.FileIO.FileStlReadOptions"""
    def __init__(self, *args) -> None: ...
    Weld: bool
    WeldAngle: float
    SplitDisjointMeshes: bool
    STLModelUnits: UnitSystem
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileStlWriteOptions:
    """.NET: Rhino.FileIO.FileStlWriteOptions"""
    def __init__(self, *args) -> None: ...
    BinaryFile: bool
    ExportOpenObjects: bool
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileStp:
    """.NET: Rhino.FileIO.FileStp"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileStpReadOptions) -> bool: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileStpWriteOptions) -> bool: ...

class FileStpReadOptions:
    """.NET: Rhino.FileIO.FileStpReadOptions"""
    def __init__(self, *args) -> None: ...
    JoinSurfaces: bool
    LimitFaces: bool
    MaxFaceCount: int
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileStpWriteOptions:
    """.NET: Rhino.FileIO.FileStpWriteOptions"""
    def __init__(self, *args) -> None: ...
    Schema: StepSchema
    Export2dCurves: bool
    ExportBlack: bool
    SplitClosedSurfaces: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileSvg:
    """.NET: Rhino.FileIO.FileSvg"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileSvgReadOptions) -> bool: ...

class FileSvgReadOptions:
    """.NET: Rhino.FileIO.FileSvgReadOptions"""
    def __init__(self, *args) -> None: ...
    RetainGrouping: bool
    GroupMultiCurvePaths: bool
    ImportFilledObjectAs: ImportFillMode
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileSwReadOptions:
    """.NET: Rhino.FileIO.FileSwReadOptions"""
    def __init__(self, *args) -> None: ...
    ImportPartsAsBlocks: bool
    RotateYtoZ: bool
    ImportConstructionGeometry: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileTxt:
    """.NET: Rhino.FileIO.FileTxt"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Read(path: str, doc: RhinoDoc, options: FileTxtReadOptions) -> bool: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileTxtWriteOptions) -> bool: ...

class FileTxtReadOptions:
    """.NET: Rhino.FileIO.FileTxtReadOptions"""
    def __init__(self, *args) -> None: ...
    Delimiter: DelimiterMode
    DelimiterCharacter: str
    CreatePointCloud: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileTxtWriteOptions:
    """.NET: Rhino.FileIO.FileTxtWriteOptions"""
    def __init__(self, *args) -> None: ...
    Delimiter: DelimiterMode
    DelimiterCharacter: str
    Precision: int
    ExportVertexColors: bool
    SurroundWithDoubleQuotes: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileType:
    """.NET: Rhino.FileIO.FileType"""
    def __init__(self, *args) -> None: ...
    Description: str
    Extension: str

class FileUdo:
    """.NET: Rhino.FileIO.FileUdo"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileUdoWriteOptions) -> bool: ...

class FileUdoWriteOptions:
    """.NET: Rhino.FileIO.FileUdoWriteOptions"""
    def __init__(self, *args) -> None: ...
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileUsd:
    """.NET: Rhino.FileIO.FileUsd"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileUsdWriteOptions) -> bool: ...

class FileUsdWriteOptions:
    """.NET: Rhino.FileIO.FileUsdWriteOptions"""
    def __init__(self, *args) -> None: ...
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileVda:
    """.NET: Rhino.FileIO.FileVda"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileVdaWriteOptions) -> bool: ...

class FileVdaWriteOptions:
    """.NET: Rhino.FileIO.FileVdaWriteOptions"""
    def __init__(self, *args) -> None: ...
    SendingCompany: str
    SendersName: str
    TelephoneNumber: str
    Address: str
    ProjectName: str
    ObjectCode: str
    Variant: str
    Confidentiality: str
    DateEffective: str
    CompanyName: str
    ReceivingDepartment: str
    PointDeviationHairsAsMDI: bool
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileVrml:
    """.NET: Rhino.FileIO.FileVrml"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileVrmlWriteOptions) -> bool: ...

class FileVrmlWriteOptions:
    """.NET: Rhino.FileIO.FileVrmlWriteOptions"""
    def __init__(self, *args) -> None: ...
    Version: int
    ExportTextureCoordinates: bool
    ExportVertexNormals: bool
    ExportVertexColors: bool
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileWriteOptions:
    """.NET: Rhino.FileIO.FileWriteOptions"""
    def __init__(self, *args) -> None: ...
    UpdateDocumentPath: bool
    WriteSelectedObjectsOnly: bool
    IncludeRenderMeshes: bool
    IncludePreviewImage: bool
    IncludeBitmapTable: bool
    IncludeHistory: bool
    WriteAsTemplate: bool
    SuppressDialogBoxes: bool
    SuppressAllInput: bool
    WriteGeometryOnly: bool
    WriteUserData: bool
    FileVersion: int
    Xform: Transform
    DestinationFileName: str
    RhinoDoc: RhinoDoc
    OptionsDictionary: ArchivableDictionary
    def Dispose(self, ) -> None: ...

class FileX3dv:
    """.NET: Rhino.FileIO.FileX3dv"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileX3dvWriteOptions) -> bool: ...

class FileX3dvWriteOptions:
    """.NET: Rhino.FileIO.FileX3dvWriteOptions"""
    def __init__(self, *args) -> None: ...
    ExportTextureCoordinates: bool
    ExportVertexNormals: bool
    ExportVertexColors: bool
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileX_T:
    """.NET: Rhino.FileIO.FileX_T"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(filename: str, doc: RhinoDoc, options: FileX_TWriteOptions) -> bool: ...

class FileX_TWriteOptions:
    """.NET: Rhino.FileIO.FileX_TWriteOptions"""
    def __init__(self, *args) -> None: ...
    Type: X_T_Types
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class FileXaml:
    """.NET: Rhino.FileIO.FileXaml"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Write(path: str, doc: RhinoDoc, options: FileFbxWriteOptions) -> bool: ...

class FileXamlWriteOptions:
    """.NET: Rhino.FileIO.FileXamlWriteOptions"""
    def __init__(self, *args) -> None: ...
    UseExistingRenderMeshes: bool
    AddRotationScrollbars: bool
    UseOriginForRotationCenter: bool
    AddRotationAnimation: bool
    AnimationAxis: AnimationMode
    MeshingParameters: MeshingParameters
    def ToDictionary(self, ) -> ArchivableDictionary: ...

class ICommonComponentTable:
    """.NET: Rhino.FileIO.ICommonComponentTable`1"""
    def __init__(self, *args) -> None: ...
    ComponentType: ModelComponentType
    def FindId(self, id: Guid) -> T: ...
    def FindNameHash(self, nameHash: NameHash) -> T: ...

class ImageFile:
    """.NET: Rhino.FileIO.ImageFile"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def SupportsAlphaChannel(filename: str) -> bool: ...

class ManifestTable:
    """.NET: Rhino.FileIO.ManifestTable"""
    def __init__(self, *args) -> None: ...
    Parent: object
    Count: int
    LongCount: int
    ComponentType: ModelComponentType
    def ActiveObjectCount(self, type: ModelComponentType) -> int: ...
    def Clear(self, ) -> None: ...
    def Contains(self, item: ModelComponent) -> bool: ...
    def CopyTo(self, array: list, arrayIndex: int) -> None: ...
    def FindId(self, id: Guid, type: ModelComponentType) -> ModelComponent: ...
    def FindIndex(self, index: int, type: ModelComponentType) -> ModelComponent: ...
    def FindName(self, name: str, type: ModelComponentType, parent: Guid) -> ModelComponent: ...
    def FindNameHash(self, nameHash: NameHash, type: ModelComponentType) -> ModelComponent: ...
    def GetEnumerator(self, type: ModelComponentType) -> IEnumerator: ...
    @staticmethod
    def GetModelComponentTypeFromGenericType() -> ModelComponentType: ...

class NameHash:
    """.NET: Rhino.FileIO.NameHash"""
    def __init__(self, *args) -> None: ...
    Sha1Hash: list
    MappedCodePoints: int
    ParentId: Guid
    def Clone(self, ) -> NameHash: ...
    @staticmethod
    def CreateFilePathHash(path: str) -> NameHash: ...
    def Equals(self, other: NameHash) -> bool: ...
    def GetHashCode(self, ) -> int: ...

class SHA1OpenNURBS(SHA1):
    """.NET: Rhino.FileIO.SHA1OpenNURBS"""
    def __init__(self, *args) -> None: ...
    HashSize: int
    Hash: list
    InputBlockSize: int
    OutputBlockSize: int
    CanTransformMultipleBlocks: bool
    CanReuseTransform: bool
    @staticmethod
    def FileSystemPathHash(path: str, ignoreCase: Nullable) -> list: ...
    def Initialize(self, ) -> None: ...
    @staticmethod
    def StringHash(input: str) -> list: ...

class SerializationOptions:
    """.NET: Rhino.FileIO.SerializationOptions"""
    def __init__(self, *args) -> None: ...
    MinRhinoVersion: int
    MaxRhinoVersion: int
    RhinoVersion: int
    WriteUserData: bool
    WriteRenderMeshes: bool
    WriteAnalysisMeshes: bool

class TextLog:
    """.NET: Rhino.FileIO.TextLog"""
    def __init__(self, *args) -> None: ...
    IndentSize: int
    def Dispose(self, ) -> None: ...
    @staticmethod
    def NewCommandLine() -> TextLog: ...
    def PopIndent(self, ) -> None: ...
    def Print(self, format: str, arg0: object, arg1: object) -> None: ...
    def PrintWrappedText(self, text: str, lineLength: int) -> None: ...
    def PushIndent(self, ) -> None: ...
    def ToString(self, ) -> str: ...
