# Auto-generated — Rhino 8 — Rhino.NodeInCode

class ComponentFunctionInfo:
    """.NET: Rhino.NodeInCode.ComponentFunctionInfo"""
    def __init__(self, *args) -> None: ...
    Name: str
    Namespace: str
    IsDefault: bool
    Description: str
    InputNames: IReadOnlyList
    InputDescriptions: IReadOnlyList
    InputTypeNames: IReadOnlyList
    InputsOptional: IReadOnlyList
    OutputNames: IReadOnlyList
    OutputDescriptions: IReadOnlyList
    OutputTypeNames: IReadOnlyList
    ComponentGuid: Guid
    FullName: str
    FullScriptingName: str
    Delegate: Delegate
    DelegateNoWarnings: Delegate
    DelegateTree: Delegate
    DelegateTreeNoWarnings: Delegate
    def Evaluate(self, args: IEnumerable, keepTree: bool, warnings: list) -> list: ...
    def Invoke(self, args: list) -> list: ...
    def InvokeKeepTree(self, args: list) -> list: ...
    def InvokeKeepTreeSilenceWarnings(self, args: list) -> list: ...
    def InvokeSilenceWarnings(self, args: list) -> list: ...
    def ToString(self, ) -> str: ...

class Components:
    """.NET: Rhino.NodeInCode.Components"""
    def __init__(self, *args) -> None: ...
    NodeInCodeFunctions: NodeInCodeTable
    @staticmethod
    def FindComponent(fullName: str) -> ComponentFunctionInfo: ...

class NodeInCodeTable(DynamicObject):
    """.NET: Rhino.NodeInCode.NodeInCodeTable"""
    def __init__(self, *args) -> None: ...
    Count: int
    def Add(self, item: ComponentFunctionInfo) -> None: ...
    def Contains(self, fullName: str) -> bool: ...
    def GetDynamicMemberNames(self, ) -> IEnumerable: ...
    def GetDynamicMembers(self, ) -> IEnumerable: ...
    def TryGetIndex(self, binder: GetIndexBinder, indexes: list, result: object) -> bool: ...
    def TryGetMember(self, binder: GetMemberBinder, result: object) -> bool: ...
    def TryInvokeMember(self, binder: InvokeMemberBinder, args: list, result: object) -> bool: ...
