# Auto-generated — Rhino 8 — Rhino.PlugIns

class CustomRenderSaveFileTypes:
    """.NET: Rhino.PlugIns.CustomRenderSaveFileTypes"""
    def __init__(self, *args) -> None: ...
    def RegisterFileType(self, extensions: IEnumerable, description: str, saveFileHandler: SaveFileHandler) -> None: ...

class DescriptionType:
    """.NET: Rhino.PlugIns.DescriptionType"""
    def __init__(self, *args) -> None: ...
    ...

class DigitizerPlugIn(PlugIn):
    """.NET: Rhino.PlugIns.DigitizerPlugIn"""
    def __init__(self, *args) -> None: ...
    Assembly: Assembly
    Id: Guid
    LicenseId: Guid
    Name: str
    Version: str
    Description: str
    LoadAtStartup: bool
    LoadTime: PlugInLoadTime
    AddToHelpMenu: bool
    SettingsDirectoryAllUsers: str
    SettingsDirectory: str
    Settings: PersistentSettings
    WindowPositionSettings: PersistentSettings
    def SendPoint(self, point: Point3d, mousebuttons: MouseButton, shiftKey: bool, controlKey: bool) -> None: ...
    def SendRay(self, ray: Ray3d, mousebuttons: MouseButton, shiftKey: bool, controlKey: bool) -> None: ...

class FileExportPlugIn(PlugIn):
    """.NET: Rhino.PlugIns.FileExportPlugIn"""
    def __init__(self, *args) -> None: ...
    Assembly: Assembly
    Id: Guid
    LicenseId: Guid
    Name: str
    Version: str
    Description: str
    LoadAtStartup: bool
    LoadTime: PlugInLoadTime
    AddToHelpMenu: bool
    SettingsDirectoryAllUsers: str
    SettingsDirectory: str
    Settings: PersistentSettings
    WindowPositionSettings: PersistentSettings

class FileImportPlugIn(PlugIn):
    """.NET: Rhino.PlugIns.FileImportPlugIn"""
    def __init__(self, *args) -> None: ...
    Assembly: Assembly
    Id: Guid
    LicenseId: Guid
    Name: str
    Version: str
    Description: str
    LoadAtStartup: bool
    LoadTime: PlugInLoadTime
    AddToHelpMenu: bool
    SettingsDirectoryAllUsers: str
    SettingsDirectory: str
    Settings: PersistentSettings
    WindowPositionSettings: PersistentSettings

class FileTypeList:
    """.NET: Rhino.PlugIns.FileTypeList"""
    def __init__(self, *args) -> None: ...
    def AddFileType(self, description: str, extension1: str, extension2: str, showOptionsButtonInFileDialog: bool) -> int: ...

class LicenseBuildType:
    """.NET: Rhino.PlugIns.LicenseBuildType"""
    def __init__(self, *args) -> None: ...
    ...

class LicenseCapabilities:
    """.NET: Rhino.PlugIns.LicenseCapabilities"""
    def __init__(self, *args) -> None: ...
    ...

class LicenseChangedEventArgs(EventArgs):
    """.NET: Rhino.PlugIns.LicenseChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class LicenseData:
    """.NET: Rhino.PlugIns.LicenseData"""
    def __init__(self, *args) -> None: ...
    ProductLicense: str
    SerialNumber: str
    LicenseTitle: str
    BuildType: LicenseBuildType
    LicenseCount: int
    DateToExpire: Nullable
    RequiresOnlineValidation: bool
    IsUpgradeFromPreviousVersion: bool
    ErrorMessage: str
    ProductIcon: Icon
    LicenseExpires: bool
    def Dispose(self, ) -> None: ...
    @staticmethod
    def IsNotValid(data: LicenseData) -> bool: ...
    def IsValid(self, ignoreExpirationDate: bool) -> bool: ...

class LicenseIdAttribute(Attribute):
    """.NET: Rhino.PlugIns.LicenseIdAttribute"""
    def __init__(self, *args) -> None: ...
    Value: str
    TypeId: object

class LicenseLease:
    """.NET: Rhino.PlugIns.LicenseLease"""
    def __init__(self, *args) -> None: ...
    ProductId: str
    GroupName: str
    GroupId: str
    UserName: str
    UserId: str
    ProductTitle: str
    ProductVersion: str
    ProductEdition: str
    LeaseId: str
    IssuedAt: DateTime
    Expiration: DateTime
    RenewableUntil: Nullable

class LicenseLeaseChangedEventArgs:
    """.NET: Rhino.PlugIns.LicenseLeaseChangedEventArgs"""
    def __init__(self, *args) -> None: ...
    Lease: LicenseLease

class LicenseStatus:
    """.NET: Rhino.PlugIns.LicenseStatus"""
    def __init__(self, *args) -> None: ...
    PluginId: Guid
    ProductId: Guid
    BuildType: LicenseBuildType
    LicenseTitle: str
    SerialNumber: str
    LicenseType: LicenseType
    ExpirationDate: Nullable
    CheckOutExpirationDate: Nullable
    RegisteredOwner: str
    RegisteredOrganization: str
    ProductIcon: Icon
    CloudZooLeaseIsValid: bool
    CloudZooLeaseExpiration: Nullable

class LicenseType:
    """.NET: Rhino.PlugIns.LicenseType"""
    def __init__(self, *args) -> None: ...
    ...

class LicenseUtils:
    """.NET: Rhino.PlugIns.LicenseUtils"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AskUserForLicense(productType: int, standAlone: bool, parentWindow: object, textMask: str, validateProductKeyDelegate: ValidateProductKeyDelegate, onLeaseChangedDelegate: OnLeaseChangedDelegate, verifyLicenseKeyDelegate: VerifyLicenseKeyDelegate, verifyPreviousVersionLicenseKeyDelegate: VerifyPreviousVersionLicenseDelegate, product_path: str, product_title: str, pluginId: Guid, licenseId: Guid, capabilities: LicenseCapabilities) -> bool: ...
    @staticmethod
    def CheckInLicense(productId: Guid) -> bool: ...
    @staticmethod
    def CheckOutLicense(productId: Guid) -> bool: ...
    @staticmethod
    def ConvertLicense(productId: Guid) -> bool: ...
    @staticmethod
    def DeleteLicense(productId: Guid) -> bool: ...
    @staticmethod
    def Echo(message: str) -> str: ...
    @staticmethod
    def GetLicense(validateProductKeyDelegate: ValidateProductKeyDelegate, leaseChangedDelegate: OnLeaseChangedDelegate, verifyLicenseKeyDelegate: VerifyLicenseKeyDelegate, verifyPreviousVersionLicenseKeyDelegate: VerifyPreviousVersionLicenseDelegate, product_type: int, capabilities: int, textMask: str, product_path: str, product_title: str, pluginId: Guid, licenseId: Guid) -> bool: ...
    @staticmethod
    def GetLicenseCapabilities(filter: int) -> LicenseCapabilities: ...
    @staticmethod
    def GetLicenseStatus() -> list: ...
    @staticmethod
    def GetLicenseType(productId: Guid) -> int: ...
    @staticmethod
    def GetOneLicenseStatus(productid: Guid) -> LicenseStatus: ...
    @staticmethod
    def Initialize() -> bool: ...
    @staticmethod
    def IsCheckOutEnabled() -> bool: ...
    @staticmethod
    def LicenseOptionsHandler(pluginId: Guid, licenseId: Guid, productTitle: str, standAlone: bool) -> bool: ...
    @staticmethod
    def LoginToCloudZoo() -> bool: ...
    @staticmethod
    def LogoutOfCloudZoo() -> bool: ...
    @staticmethod
    def ReturnLicense(productId: Guid) -> bool: ...
    @staticmethod
    def ShowBuyLicenseUi(productId: Guid) -> None: ...
    @staticmethod
    def ShowLicenseValidationUi(cdkey: str) -> bool: ...
    @staticmethod
    def ShowRhinoExpiredMessage(mode: Mode, result: int) -> bool: ...

class LoadPlugInResult:
    """.NET: Rhino.PlugIns.LoadPlugInResult"""
    def __init__(self, *args) -> None: ...
    ...

class LoadReturnCode:
    """.NET: Rhino.PlugIns.LoadReturnCode"""
    def __init__(self, *args) -> None: ...
    ...

class OnLeaseChangedDelegate:
    """.NET: Rhino.PlugIns.OnLeaseChangedDelegate"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, args: LicenseLeaseChangedEventArgs, icon: Icon, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, icon: Icon, result: IAsyncResult) -> None: ...
    def Invoke(self, args: LicenseLeaseChangedEventArgs, icon: Icon) -> None: ...

class PlugIn:
    """.NET: Rhino.PlugIns.PlugIn"""
    def __init__(self, *args) -> None: ...
    Assembly: Assembly
    Id: Guid
    LicenseId: Guid
    Name: str
    Version: str
    Description: str
    LoadAtStartup: bool
    LoadTime: PlugInLoadTime
    AddToHelpMenu: bool
    SettingsDirectoryAllUsers: str
    SettingsDirectory: str
    Settings: PersistentSettings
    WindowPositionSettings: PersistentSettings
    AskOnLoadProtection: bool
    InstalledPlugInCount: int
    def CommandSettings(self, name: str) -> PersistentSettings: ...
    def DisplayHelp(self, windowHandle: IntPtr) -> bool: ...
    @staticmethod
    def Find(pluginAssembly: Assembly) -> PlugIn: ...
    @staticmethod
    def FlushSettingsSavedQueue() -> None: ...
    def GetCommands(self, ) -> list: ...
    @staticmethod
    def GetEnglishCommandNames(pluginId: Guid) -> list: ...
    @staticmethod
    def GetInstalledPlugInFolders() -> list: ...
    @staticmethod
    def GetInstalledPlugInNames(typeFilter: PlugInType, loaded: bool, unloaded: bool, localizedPlugInName: bool) -> list: ...
    @staticmethod
    def GetInstalledPlugIns(localizedPlugInName: bool) -> Dictionary: ...
    @staticmethod
    def GetLoadProtection(pluginId: Guid, loadSilently: bool) -> bool: ...
    @staticmethod
    def GetPlugInInfo(pluginId: Guid) -> PlugInInfo: ...
    def GetPlugInObject(self, ) -> object: ...
    @staticmethod
    def GetPluginSettings(plugInId: Guid, load: bool) -> PersistentSettings: ...
    def Icon(self, size: Size) -> Bitmap: ...
    @staticmethod
    def IdFromFileName(filename: str) -> Guid: ...
    @staticmethod
    def IdFromName(pluginName: str) -> Guid: ...
    @staticmethod
    def IdFromPath(pluginPath: str) -> Guid: ...
    def IsTextureSupported(self, texture: RenderTexture) -> bool: ...
    @staticmethod
    def LoadComputeExtensionPlugins() -> None: ...
    @staticmethod
    def LoadPlugIn(pluginId: Guid, loadQuietly: bool, forceLoad: bool) -> bool: ...
    @staticmethod
    def NameFromPath(pluginPath: str) -> str: ...
    @staticmethod
    def PathFromId(pluginId: Guid) -> str: ...
    @staticmethod
    def PathFromName(pluginName: str) -> str: ...
    @staticmethod
    def PlugInExists(id: Guid, loaded: bool, loadProtected: bool) -> bool: ...
    @staticmethod
    def RaiseOnPlugInSettingsSavedEvent() -> None: ...
    @staticmethod
    def SavePluginSettings(plugInId: Guid) -> None: ...
    def SaveSettings(self, ) -> None: ...
    @staticmethod
    def SetLoadProtection(pluginId: Guid, loadSilently: bool) -> None: ...

class PlugInDescriptionAttribute(Attribute):
    """.NET: Rhino.PlugIns.PlugInDescriptionAttribute"""
    def __init__(self, *args) -> None: ...
    DescriptionType: DescriptionType
    Value: str
    TypeId: object

class PlugInInfo:
    """.NET: Rhino.PlugIns.PlugInInfo"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    RegistryPath: str
    Name: str
    Description: str
    FileName: str
    Version: str
    Organization: str
    Address: str
    Country: str
    Email: str
    Phone: str
    Fax: str
    WebSite: str
    UpdateUrl: str
    PlugInType: PlugInType
    PlugInLoadTime: PlugInLoadTime
    IsLoaded: bool
    ShipsWithRhino: bool
    IsDotNet: bool
    CommandNames: list
    FileTypeDescriptions: list
    FileTypeExtensions: list
    def Icon(self, size: Size) -> Bitmap: ...
    def IsLoadProtected(self, loadSilently: bool) -> bool: ...

class PlugInLoadTime:
    """.NET: Rhino.PlugIns.PlugInLoadTime"""
    def __init__(self, *args) -> None: ...
    ...

class PlugInType:
    """.NET: Rhino.PlugIns.PlugInType"""
    def __init__(self, *args) -> None: ...
    ...

class PreviewNotification:
    """.NET: Rhino.PlugIns.PreviewNotification"""
    def __init__(self, *args) -> None: ...
    def NotifyIntermediateUpdate(self, rw: RenderWindow) -> None: ...

class RenderPlugIn(PlugIn):
    """.NET: Rhino.PlugIns.RenderPlugIn"""
    def __init__(self, *args) -> None: ...
    PerferBasicContent: bool
    Assembly: Assembly
    Id: Guid
    LicenseId: Guid
    Name: str
    Version: str
    Description: str
    LoadAtStartup: bool
    LoadTime: PlugInLoadTime
    AddToHelpMenu: bool
    SettingsDirectoryAllUsers: str
    SettingsDirectory: str
    Settings: PersistentSettings
    WindowPositionSettings: PersistentSettings
    @staticmethod
    def CurrentRendererSupportsFeature(feature: RenderFeature) -> bool: ...
    def EnableAssignMaterialButton(self, ) -> bool: ...
    def EnableCreateMaterialButton(self, ) -> bool: ...
    def EnableEditMaterialButton(self, doc: RhinoDoc, material: Material) -> bool: ...
    def GetRenderSettingsSections(self, ) -> List: ...
    def OnAssignMaterial(self, parent: IntPtr, doc: RhinoDoc, material: Material) -> bool: ...
    def OnCreateMaterial(self, parent: IntPtr, doc: RhinoDoc, material: Material) -> bool: ...
    def OnEditMaterial(self, parent: IntPtr, doc: RhinoDoc, material: Material) -> bool: ...
    def RenderSettingsCustomSections(self, sections: List) -> None: ...
    def SunCustomSections(self, sections: List) -> None: ...

class ValidateProductKeyDelegate:
    """.NET: Rhino.PlugIns.ValidateProductKeyDelegate"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, productKey: str, licenseData: LicenseData, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, licenseData: LicenseData, result: IAsyncResult) -> ValidateResult: ...
    def Invoke(self, productKey: str, licenseData: LicenseData) -> ValidateResult: ...

class ValidateResult:
    """.NET: Rhino.PlugIns.ValidateResult"""
    def __init__(self, *args) -> None: ...
    ...

class VerifyLicenseKeyDelegate:
    """.NET: Rhino.PlugIns.VerifyLicenseKeyDelegate"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, licenseKey: str, validationCode: str, validationCodeInstallDate: DateTime, gracePeriodExpired: bool, licenseData: LicenseData, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, licenseData: LicenseData, result: IAsyncResult) -> ValidateResult: ...
    def Invoke(self, licenseKey: str, validationCode: str, validationCodeInstallDate: DateTime, gracePeriodExpired: bool, licenseData: LicenseData) -> ValidateResult: ...

class VerifyPreviousVersionLicenseDelegate:
    """.NET: Rhino.PlugIns.VerifyPreviousVersionLicenseDelegate"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, license: str, previousVersionLicense: str, errorMessage: str, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, errorMessage: str, result: IAsyncResult) -> bool: ...
    def Invoke(self, license: str, previousVersionLicense: str, errorMessage: str) -> bool: ...

class WriteFileResult:
    """.NET: Rhino.PlugIns.WriteFileResult"""
    def __init__(self, *args) -> None: ...
    ...
