# Auto-generated — Tekla 2026 — Tekla.Structures.ModelInternal.BuildingSpaces

class Space(ModelObject):
    """.NET: Tekla.Structures.ModelInternal.BuildingSpaces.Space"""
    def __init__(self, *args) -> None: ...
    Name: str
    Number: int
    Zone: str
    Description: str
    Height: float
    BottomOffset: float
    Volume: float
    Contour: Contour
    BrepShapeName: str
    Parent: Storey
    ModificationTime: Nullable
    IsUpToDate: bool
    Identifier: Identifier
    def Delete(self, ) -> bool: ...
    def GetSolid(self, ) -> Solid: ...
    def HideAssignedObjects(self, ) -> None: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...
    def SelectAssignedObjects(self, ) -> None: ...
    def ShowAssignedObjects(self, ) -> None: ...
    def ShowOnlyAssignedObjects(self, ) -> None: ...
