# Auto-generated — Tekla 2026 — Tekla.Structures.ModelInternal.BuildingHierarchy

class Building(BuildingHierarchyItem):
    """.NET: Tekla.Structures.ModelInternal.BuildingHierarchy.Building"""
    def __init__(self, *args) -> None: ...
    Description: str
    BottomElevation: float
    TopElevation: float
    IsBuildingSection: bool
    Contour: Contour
    Name: str
    ModificationTime: Nullable
    IsUpToDate: bool
    Identifier: Identifier
    def Delete(self, ) -> bool: ...
    def GetBuildings(self, ) -> IList: ...
    def GetSolid(self, ) -> Solid: ...
    def GetSpaces(self, ) -> List: ...
    def GetStoreys(self, ) -> List: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class BuildingHierarchyItem(ModelObject):
    """.NET: Tekla.Structures.ModelInternal.BuildingHierarchy.BuildingHierarchyItem"""
    def __init__(self, *args) -> None: ...
    Name: str
    ModificationTime: Nullable
    IsUpToDate: bool
    Identifier: Identifier
    def GetGuid(self, ) -> Guid: ...
    def HideAssignedObjects(self, ) -> None: ...
    def SelectAssignedObjects(self, ) -> None: ...
    def SetGuid(self, guid: Guid) -> None: ...
    def ShowAssignedObjects(self, ) -> None: ...
    def ShowOnlyAssignedObjects(self, ) -> None: ...

class Site(BuildingHierarchyItem):
    """.NET: Tekla.Structures.ModelInternal.BuildingHierarchy.Site"""
    def __init__(self, *args) -> None: ...
    Description: str
    Name: str
    ModificationTime: Nullable
    IsUpToDate: bool
    Identifier: Identifier
    def Delete(self, ) -> bool: ...
    def GetBuildings(self, ) -> List: ...
    def GetSpaces(self, ) -> List: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class Storey(BuildingHierarchyItem):
    """.NET: Tekla.Structures.ModelInternal.BuildingHierarchy.Storey"""
    def __init__(self, *args) -> None: ...
    Elevation: float
    LevelOffset: float
    Description: str
    BottomOffset: float
    LevelInfo: str
    Parent: Building
    Name: str
    ModificationTime: Nullable
    IsUpToDate: bool
    Identifier: Identifier
    def Delete(self, ) -> bool: ...
    def GetManualObjectOverrides(self, ) -> List: ...
    def GetObjects(self, ) -> List: ...
    def GetSpaces(self, ) -> List: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def RemoveManualObjectOverrides(self, overrideObjects: List) -> bool: ...
    def Select(self, ) -> bool: ...
    def SetManualObjectOverrides(self, overrideObjects: List) -> bool: ...
