# Auto-generated — Rhino 8 — Rhino.UI

class Analytics:
    """.NET: Rhino.UI.Analytics"""
    def __init__(self, *args) -> None: ...
    GoogleAnalyticsTrackingID: str
    AppName: str
    AppPlatform: str
    AppInstallerId: str
    AppVersion: str
    UsageStatisticsEnabled: bool
    UserId: Guid
    def Send(self, Category: str, Action: str, Label: str, Value: int) -> None: ...

class CursorStyle:
    """.NET: Rhino.UI.CursorStyle"""
    def __init__(self, *args) -> None: ...
    ...

class DataSerializer:
    """.NET: Rhino.UI.DataSerializer"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def SerializeToJson(m_data: object) -> str: ...

class Dialogs:
    """.NET: Rhino.UI.Dialogs"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def KillSplash() -> None: ...
    @staticmethod
    def SetCustomColorDialog(handler: EventHandler) -> None: ...
    @staticmethod
    def ShowAboutDialog(forceSimpleDialog: bool) -> None: ...
    @staticmethod
    def ShowCheckListBox(title: str, message: str, items: IList, checkState: IList) -> list: ...
    @staticmethod
    def ShowColorDialog(parent: object, color: Color4f, allowAlpha: bool, namedColorList: NamedColorList, colorCallback: OnColorChangedEvent) -> bool: ...
    @staticmethod
    def ShowComboListBox(title: str, message: str, items: IList) -> object: ...
    @staticmethod
    def ShowContextMenu(items: IEnumerable, screenPoint: Point, modes: IEnumerable) -> int: ...
    @staticmethod
    def ShowEditBox(title: str, message: str, defaultText: str, multiline: bool, text: str) -> bool: ...
    @staticmethod
    def ShowLayerMaterialDialog(doc: RhinoDoc, layerIndices: IEnumerable) -> bool: ...
    @staticmethod
    def ShowLineTypes(title: str, message: str, doc: RhinoDoc, selectedLineTypeId: Guid) -> Guid: ...
    @staticmethod
    def ShowListBox(title: str, message: str, items: IList, selectedItem: object) -> object: ...
    @staticmethod
    def ShowMessage(parent: object, message: str, title: str, buttons: ShowMessageButton, icon: ShowMessageIcon, defaultButton: ShowMessageDefaultButton, options: ShowMessageOptions, mode: ShowMessageMode) -> ShowMessageResult: ...
    @staticmethod
    def ShowMessageBox(message: str, title: str, buttons: MessageBoxButtons, icon: MessageBoxIcon) -> DialogResult: ...
    @staticmethod
    def ShowMultiListBox(title: str, message: str, items: IList, defaults: IList) -> list: ...
    @staticmethod
    def ShowNumberBox(title: str, message: str, number: float, minimum: float, maximum: float) -> bool: ...
    @staticmethod
    def ShowPrintWidths(title: str, message: str, selectedWidth: float) -> float: ...
    @staticmethod
    def ShowPropertyListBox(title: str, message: str, items: IList, values: IList) -> list: ...
    @staticmethod
    def ShowSelectLayerDialog(layerIndex: int, dialogTitle: str, showNewLayerButton: bool, showSetCurrentButton: bool, initialSetCurrentState: bool) -> bool: ...
    @staticmethod
    def ShowSelectLinetypeDialog(linetypeIndex: int, displayByLayer: bool) -> bool: ...
    @staticmethod
    def ShowSelectMultipleLayersDialog(defaultLayerIndices: IEnumerable, dialogTitle: str, showNewLayerButton: bool, layerIndices: list) -> bool: ...
    @staticmethod
    def ShowSemiModal(form: Form) -> DialogResult: ...
    @staticmethod
    def ShowSunDialog(sun: Sun) -> bool: ...
    @staticmethod
    def ShowTextDialog(message: str, title: str) -> None: ...

class DistanceDisplayMode:
    """.NET: Rhino.UI.DistanceDisplayMode"""
    def __init__(self, *args) -> None: ...
    ...

class DrawingUtilities:
    """.NET: Rhino.UI.DrawingUtilities"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def BitmapFromIconResource(resourceName: str, bitmapSize: Size, assembly: Assembly) -> Bitmap: ...
    @staticmethod
    def BitmapFromSvg(svg: str, width: int, height: int, adjustForDarkMode: bool) -> Bitmap: ...
    @staticmethod
    def CreateCurvePreviewGeometry(curve: Curve, linetype: Linetype, width: int, height: int) -> List: ...
    @staticmethod
    def CreateMeshPreviewImage(doc: RhinoDoc, meshes: IEnumerable, colors: IEnumerable, size: Size) -> Bitmap: ...
    @staticmethod
    def DarkModeConvertPixel(r: int, g: int, b: int) -> None: ...
    @staticmethod
    def DarkModeConvertPixels(rgbaBytes: list) -> None: ...
    @staticmethod
    def IconFromResource(resourceName: str, size: Size, assembly: Assembly) -> Icon: ...
    @staticmethod
    def ImageFromResource(resourceName: str, assembly: Assembly) -> Image: ...
    @staticmethod
    def LoadBitmapWithScaleDown(iconName: str, sizeDesired: int, assembly: Assembly) -> Bitmap: ...
    @staticmethod
    def LoadIconWithScaleDown(iconName: str, sizeDesired: int, assembly: Assembly) -> Icon: ...
    @staticmethod
    def MakeArgb(a: int, r: int, g: int, b: int) -> int: ...
    @staticmethod
    def PixelsFromSvg(svg: str, width: int, height: int, premultiplyAlpha: bool, backgroundColor: Color) -> list: ...
    @staticmethod
    def SvgToRhinoDibIntPtr(svg: str, width: int, height: int, adjustForDarkMode: bool, pRhinoDib: IntPtr) -> None: ...

class EtoExtensions:
    """.NET: Rhino.UI.EtoExtensions"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetRhinoDoc(form: Form) -> RhinoDoc: ...
    @staticmethod
    def LocalizeAndRestore(window: Window, type: Type) -> None: ...
    @staticmethod
    def PushPickButton(panel: Panel, pickFunction: EventHandler) -> None: ...
    @staticmethod
    def RestorePosition(window: Window, type: Type) -> bool: ...
    @staticmethod
    def SavePosition(window: Window, type: Type) -> None: ...
    @staticmethod
    def Show(form: Form, doc: RhinoDoc) -> None: ...
    @staticmethod
    def ShowSemiModal(dialog: Dialog, doc: RhinoDoc, parent: Control) -> T: ...
    @staticmethod
    def ToColor4f(color: Color) -> Color4f: ...
    @staticmethod
    def ToEto(font: Font, size: float, decoration: FontDecoration) -> Font: ...
    @staticmethod
    def ToEtoScreen(point: Point, screen: Screen) -> PointF: ...
    @staticmethod
    def ToSystemDrawing(color: Color) -> Color: ...
    @staticmethod
    def ToSystemDrawingScreen(point: PointF, screen: Screen) -> Point: ...
    @staticmethod
    def UseRhinoStyle(control: Control) -> None: ...
    @staticmethod
    def WindowsFromDocument(doc: RhinoDoc) -> IEnumerable: ...

class Fonts:
    """.NET: Rhino.UI.Fonts"""
    def __init__(self, *args) -> None: ...
    NormalFont: Font
    HeadingFont: Font
    BoldHeadingFont: Font
    TitleFont: Font
    SmallFont: Font
    @staticmethod
    def GetUiFont(style: Style, size: Size) -> Font: ...

class GetColorEventArgs(EventArgs):
    """.NET: Rhino.UI.GetColorEventArgs"""
    def __init__(self, *args) -> None: ...
    InputColor: Color
    SelectedColor: Color
    IncludeButtonColors: bool
    Title: str

class IDialogService:
    """.NET: Rhino.UI.IDialogService"""
    def __init__(self, *args) -> None: ...
    def ObjectToWindowHandle(self, window: object, useMainRhinoWindowWhenNull: bool) -> IntPtr: ...
    def ShowColorDialog(self, parent: object, color: Color4f, allowAlpha: bool, colorCallback: OnColorChangedEvent) -> bool: ...
    def ShowMultiListBox(self, title: str, message: str, items: IList, defaults: IList) -> list: ...
    def WrapAsIWin32Window(self, handle: IntPtr) -> object: ...

class IHelp:
    """.NET: Rhino.UI.IHelp"""
    def __init__(self, *args) -> None: ...
    HelpUrl: str

class ILocalizationService:
    """.NET: Rhino.UI.ILocalizationService"""
    def __init__(self, *args) -> None: ...
    def LocalizeCommandName(self, assembly: Assembly, languageId: int, english: str) -> str: ...
    def LocalizeDialogItem(self, assembly: Assembly, languageId: int, key: str, english: str) -> str: ...
    def LocalizeForm(self, assembly: Assembly, languageId: int, formOrUserControl: object) -> None: ...
    def LocalizeString(self, assembly: Assembly, languageId: int, english: str, contextId: int) -> str: ...

class IPanel:
    """.NET: Rhino.UI.IPanel"""
    def __init__(self, *args) -> None: ...
    def PanelClosing(self, documentSerialNumber: int, onCloseDocument: bool) -> None: ...
    def PanelHidden(self, documentSerialNumber: int, reason: ShowPanelReason) -> None: ...
    def PanelShown(self, documentSerialNumber: int, reason: ShowPanelReason) -> None: ...

class IPanelsService:
    """.NET: Rhino.UI.IPanelsService"""
    def __init__(self, *args) -> None: ...
    def CreateDockBar(self, options: object) -> bool: ...
    def DestroyNativeWindow(self, host: object, nativeObject: object, disposeOfNativeObject: bool) -> None: ...
    def DockBarIdInUse(self, barId: Guid) -> bool: ...
    def DockBarIsVisible(self, barId: Guid) -> bool: ...
    def FactoryResetSettings(self, ) -> None: ...
    def Float(self, barId: Guid, point: Point) -> bool: ...
    def ResizeFloating(self, barId: Guid, size: Size) -> bool: ...
    def SetF1Hook(self, nativeObject: object, hook: EventHandler) -> None: ...
    def ShowDockBar(self, barId: Guid, show: bool) -> bool: ...
    def StartDraggingDockBar(self, barId: Guid, mouseDownPoint: Point, screenStartPoint: Point) -> bool: ...
    def SupportedType(self, type: Type, exceptionMessage: str) -> bool: ...
    def ToggleDocking(self, barId: Guid) -> bool: ...
    def UnhookDeleteAndDestroyDockBar(self, id: Guid) -> bool: ...

class IRhinoUiDialogService:
    """.NET: Rhino.UI.IRhinoUiDialogService"""
    def __init__(self, *args) -> None: ...
    def DetectColorScheme(self, defaultLightMode: bool, defaultDarkMode: bool) -> None: ...
    def IconFromResourceId(self, iconAssembly: Assembly, iconResourceId: str) -> Icon: ...
    def SetToDefaultColorScheme(self, dark: bool) -> bool: ...
    def ShowCheckListBox(self, title: str, message: str, items: IList, checkState: IList) -> list: ...
    def ShowComboListBox(self, title: str, message: str, items: IList) -> object: ...
    def ShowEditBox(self, title: str, message: str, defaultText: str, multiline: bool, text: str) -> bool: ...
    def ShowLineTypes(self, title: str, message: str, doc: RhinoDoc, selectedLinetypeId: Guid) -> Guid: ...
    def ShowListBox(self, title: str, message: str, items: IList, selectedItem: object) -> object: ...
    def ShowMultiListBox(self, items: IList, message: str, title: str, defaults: IList) -> list: ...
    def ShowNumberBox(self, title: str, message: str, number: float, minimum: float, maximum: float) -> bool: ...
    def ShowPopupMenu(self, arrItems: list, arrModes: list, screenPointX: Nullable, screenPointY: Nullable) -> int: ...
    def ShowPrintWidths(self, title: str, message: str, selectedWidth: float) -> float: ...
    def ShowPropertyListBox(self, title: str, message: str, items: IList, values: IList) -> list: ...

class IStackedDialogPageService:
    """.NET: Rhino.UI.IStackedDialogPageService"""
    def __init__(self, *args) -> None: ...
    def GetImageHandle(self, image: Image, canBeNull: bool) -> IntPtr: ...
    def GetNativePageWindow(self, pageObject: object, isRhinoPanel: bool, applyPanelStyles: bool, nativeWindowObject: object, host: object) -> IntPtr: ...
    def NativeHandle(self, host: object) -> IntPtr: ...
    def RedrawPageControl(self, pageControl: object) -> None: ...
    def SetNativeParent(self, hwndParent: IntPtr, host: object) -> bool: ...
    def TryGetControlMinimumSize(self, controlObject: object, size: SizeF) -> bool: ...

class ImageResources:
    """.NET: Rhino.UI.ImageResources"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateBitmap(resourceId: Guid, width: int, height: int, adjustForDarkMode: bool, forceDarkMode: bool) -> Bitmap: ...
    @staticmethod
    def CreateEtoBitmap(fullPathToResource: str, assembly: Assembly, width: int, height: int, adjustForDarkMode: bool) -> Bitmap: ...
    @staticmethod
    def CreateEtoIcon(fullPathToResource: str, assembly: Assembly, width: int, height: int, adjustForDarkMode: bool) -> Icon: ...
    @staticmethod
    def ModifySvgForCustomDarkModeAttributes(svgContent: str, adjustmentsMade: bool) -> str: ...
    @staticmethod
    def SvgFromResourceId(fullPathToResource: str, assembly: Assembly) -> str: ...
    @staticmethod
    def SvgResourceFromId(resourceId: Guid) -> Tuple: ...

class KeyboardKey:
    """.NET: Rhino.UI.KeyboardKey"""
    def __init__(self, *args) -> None: ...
    ...

class LOC:
    """.NET: Rhino.UI.LOC"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def COMMANDNAME(english: str) -> str: ...
    @staticmethod
    def CON(english: str, assemblyFromObject: object) -> LocalizeStringPair: ...
    @staticmethod
    def COV(english: str, assemblyFromObject: object) -> LocalizeStringPair: ...
    @staticmethod
    def STR(english: str, assemblyOrObject: object) -> str: ...

class Localization:
    """.NET: Rhino.UI.Localization"""
    def __init__(self, *args) -> None: ...
    CurrentLanguageId: int
    RunningAsEnglish: bool
    @staticmethod
    def FormatArea(area: float, units: UnitSystem, dimStyle: DimensionStyle, alternate: bool) -> str: ...
    @staticmethod
    def FormatDistanceAndTolerance(distance: float, units: UnitSystem, dimStyle: DimensionStyle, alternate: bool) -> str: ...
    @staticmethod
    def FormatNumber(x: float, units: UnitSystem, mode: DistanceDisplayMode, precision: int, appendUnitSystemName: bool) -> str: ...
    @staticmethod
    def FormatVolume(volume: float, units: UnitSystem, dimStyle: DimensionStyle, alternate: bool) -> str: ...
    @staticmethod
    def GetLanguages(ids: SimpleArrayInt, names: ClassArrayString) -> bool: ...
    @staticmethod
    def LocalizeCommandName(english: str, assemblyOrObject: object) -> str: ...
    @staticmethod
    def LocalizeCommandOptionName(english: str, assemblyOrObject: object, contextId: int) -> LocalizeStringPair: ...
    @staticmethod
    def LocalizeCommandOptionValue(english: str, assemblyOrObject: object, contextId: int) -> LocalizeStringPair: ...
    @staticmethod
    def LocalizeDialogItem(assemblyOrObject: object, key: str, english: str) -> str: ...
    @staticmethod
    def LocalizeForm(formOrUserControl: object) -> None: ...
    @staticmethod
    def LocalizeString(english: str, wrongcontextId: int, contextId: int) -> str: ...
    @staticmethod
    def LogicalSort(string1: str, string2: str) -> int: ...
    @staticmethod
    def SetLanguageId(id: int) -> bool: ...
    @staticmethod
    def UnitSystemName(units: UnitSystem, capitalize: bool, singular: bool, abbreviate: bool) -> str: ...

class LocalizeStringPair:
    """.NET: Rhino.UI.LocalizeStringPair"""
    def __init__(self, *args) -> None: ...
    English: str
    Local: str
    def ToString(self, ) -> str: ...

class ModifierKey:
    """.NET: Rhino.UI.ModifierKey"""
    def __init__(self, *args) -> None: ...
    ...

class MouseButton:
    """.NET: Rhino.UI.MouseButton"""
    def __init__(self, *args) -> None: ...
    ...

class MouseCallback:
    """.NET: Rhino.UI.MouseCallback"""
    def __init__(self, *args) -> None: ...
    Enabled: bool

class MouseCallbackEventArgs(CancelEventArgs):
    """.NET: Rhino.UI.MouseCallbackEventArgs"""
    def __init__(self, *args) -> None: ...
    View: RhinoView
    MouseButton: MouseButton
    Button: MouseButtons
    ShiftKeyDown: bool
    CtrlKeyDown: bool
    ViewportPoint: Point
    Cancel: bool
    def IsOverGumball(self, ) -> GumballMode: ...

class MouseCursor:
    """.NET: Rhino.UI.MouseCursor"""
    def __init__(self, *args) -> None: ...
    Location: Point2d
    @staticmethod
    def SetToolTip(tooltip: str) -> None: ...

class NamedColor:
    """.NET: Rhino.UI.NamedColor"""
    def __init__(self, *args) -> None: ...
    Name: str
    Color: Color

class NamedColorList(List):
    """.NET: Rhino.UI.NamedColorList"""
    def __init__(self, *args) -> None: ...
    Name: str
    Default: NamedColorList
    Capacity: int
    Count: int
    Item: NamedColor

class ObjectPropertiesPage:
    """.NET: Rhino.UI.ObjectPropertiesPage"""
    def __init__(self, *args) -> None: ...
    Icon: Icon
    PageControl: object
    EnglishPageTitle: str
    SupportedTypes: ObjectType
    AllObjectsMustBeSupported: bool
    Index: int
    SupportsSubObjects: bool
    LocalPageTitle: str
    PageType: PropertyPageType
    PageIconEmbeddedResourceString: str
    SelectedObjects: list
    def AnySelectedObject(self, allMustMatch: bool) -> bool: ...
    def GetSelectedObjects(self, filter: ObjectType) -> list: ...
    def InitializeControls(self, rhObj: RhinoObject) -> None: ...
    def ModifyPage(self, callbackAction: Action) -> None: ...
    def OnActivate(self, active: bool) -> bool: ...
    def OnCreateParent(self, hwndParent: IntPtr) -> None: ...
    def OnHelp(self, ) -> None: ...
    def OnSizeParent(self, width: int, height: int) -> None: ...
    def PageIcon(self, sizeInPixels: Size) -> Icon: ...
    def RunScript(self, doc: RhinoDoc, objectList: list) -> Result: ...
    def ShouldDisplay(self, rhObj: RhinoObject) -> bool: ...
    def UpdatePage(self, e: ObjectPropertiesPageEventArgs) -> None: ...

class ObjectPropertiesPageCollection:
    """.NET: Rhino.UI.ObjectPropertiesPageCollection"""
    def __init__(self, *args) -> None: ...
    DocumentRuntimeSerialNumber: int
    Document: RhinoDoc
    def Add(self, page: ObjectPropertiesPage) -> None: ...

class ObjectPropertiesPageEventArgs:
    """.NET: Rhino.UI.ObjectPropertiesPageEventArgs"""
    def __init__(self, *args) -> None: ...
    Page: ObjectPropertiesPage
    EventRuntimeSerialNumber: int
    Objects: list
    ObjectCount: int
    ObjectTypes: int
    View: RhinoView
    Viewport: RhinoViewport
    DocRuntimeSerialNumber: int
    Document: RhinoDoc
    def GetObjects(self, filter: ObjectType) -> list: ...
    def IncludesObjectsType(self, objectTypes: ObjectType, allMustMatch: bool) -> bool: ...

class OldRhinoAnalytics:
    """.NET: Rhino.UI.OldRhinoAnalytics"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Send(Category: str, Action: str, Label: str, Value: int, cutoffDate: DateTime) -> None: ...

class OpenFileDialog:
    """.NET: Rhino.UI.OpenFileDialog"""
    def __init__(self, *args) -> None: ...
    DefaultExt: str
    FileName: str
    Title: str
    Filter: str
    InitialDirectory: str
    MultiSelect: bool
    FileNames: list
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowOpenDialog(self, ) -> bool: ...

class OptionPageButtons:
    """.NET: Rhino.UI.OptionPageButtons"""
    def __init__(self, *args) -> None: ...
    ...

class OptionsDialogPage(StackedDialogPage):
    """.NET: Rhino.UI.OptionsDialogPage"""
    def __init__(self, *args) -> None: ...
    OptionsPageType: PageType
    Children: List
    HasChildren: bool
    Modified: bool
    Handle: IntPtr
    PageControl: object
    EnglishPageTitle: str
    LocalPageTitle: str
    PageImage: Image
    ShowDefaultsButton: bool
    ShowApplyButton: bool
    NavigationTextIsBold: bool
    NavigationTextColor: Color
    def RunScript(self, doc: RhinoDoc, mode: RunMode) -> Result: ...

class PanelEventArgs(EventArgs):
    """.NET: Rhino.UI.PanelEventArgs"""
    def __init__(self, *args) -> None: ...
    PanelId: Guid
    DocumentSerialNumber: int
    Document: RhinoDoc

class PanelIds:
    """.NET: Rhino.UI.PanelIds"""
    def __init__(self, *args) -> None: ...
    Materials: Guid
    Environment: Guid
    Texture: Guid
    LightManager: Guid
    Sun: Guid
    GroundPlane: Guid
    Layers: Guid
    ObjectProperties: Guid
    Display: Guid
    ContextHelp: Guid
    Notes: Guid
    Rendering: Guid
    Libraries: Guid
    FileExplorer: Guid
    BoxEdit: Guid

class PanelType:
    """.NET: Rhino.UI.PanelType"""
    def __init__(self, *args) -> None: ...
    ...

class Panels:
    """.NET: Rhino.UI.Panels"""
    def __init__(self, *args) -> None: ...
    EtoPanelStyleName: str
    IconSize: Size
    IconSizeInPixels: Size
    ScaledIconSize: Size
    @staticmethod
    def ChangePanelIcon(panelType: Type, fullPathToResource: str) -> None: ...
    @staticmethod
    def ClosePanel(panelId: Guid, doc: RhinoDoc) -> None: ...
    @staticmethod
    def DockBarIdInUse(dockBarId: Guid) -> bool: ...
    @staticmethod
    def FloatPanel(panelType: Type, mode: FloatPanelMode) -> bool: ...
    @staticmethod
    def GetOpenPanelIds() -> list: ...
    @staticmethod
    def GetPanel(panelId: Guid, documentSerialNumber: int) -> object: ...
    @staticmethod
    def GetPanels(panelId: Guid, doc: RhinoDoc) -> list: ...
    @staticmethod
    def IsHiding(reason: ShowPanelReason) -> bool: ...
    @staticmethod
    def IsPanelVisible(panelId: Guid, isSelectedTab: bool) -> bool: ...
    @staticmethod
    def IsShowing(reason: ShowPanelReason) -> bool: ...
    @staticmethod
    def OnClosePanel(panelId: Guid, documentSerialNumber: int) -> None: ...
    @staticmethod
    def OnShowPanel(panelId: Guid, documentSerialNumber: int, show: bool) -> None: ...
    @staticmethod
    def OpenPanel(dockBarId: Guid, panelId: Guid, makeSelectedPanel: bool) -> Guid: ...
    @staticmethod
    def OpenPanelAsSibling(panelId: Guid, siblingPanelId: Guid, makeSelectedPanel: bool) -> bool: ...
    @staticmethod
    def PanelDockBar(panelId: Guid) -> Guid: ...
    @staticmethod
    def PanelDockBars(panelId: Guid) -> list: ...
    @staticmethod
    def RegisterPanel(plugIn: PlugIn, type: Type, caption: str, iconAssembly: Assembly, iconResourceId: str, panelType: PanelType) -> None: ...

class PropertyPageType:
    """.NET: Rhino.UI.PropertyPageType"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoAnalytics:
    """.NET: Rhino.UI.RhinoAnalytics"""
    def __init__(self, *args) -> None: ...
    Instance: RhinoAnalytics
    Analytics: Analytics
    def Add(self, key: str, value: str) -> None: ...
    def AddListValue(self, key: str, value: object) -> None: ...
    def CachePluginLoad(self, data: Dictionary) -> None: ...
    def Clear(self, ) -> None: ...
    def Send(self, ) -> None: ...
    def SendLegacyEvent(self, Category: str, Action: str, Label: str, Value: int) -> None: ...
    def SendOnSchedule(self, ) -> None: ...

class RhinoEtoApp:
    """.NET: Rhino.UI.RhinoEtoApp"""
    def __init__(self, *args) -> None: ...
    MainWindow: Window
    MainWindowForOwner: Window
    @staticmethod
    def ApplicationPreferencesWindowForPage(page: OptionsDialogPage) -> Window: ...
    @staticmethod
    def DocumentPropertiesWindowForPage(page: OptionsDialogPage) -> Window: ...
    @staticmethod
    def MainWindowForDocument(doc: RhinoDoc) -> Window: ...

class RhinoGetPlotWidthArgs:
    """.NET: Rhino.UI.RhinoGetPlotWidthArgs"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoHelp:
    """.NET: Rhino.UI.RhinoHelp"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Show(helpLink: str) -> bool: ...

class RhinoPageInterop:
    """.NET: Rhino.UI.RhinoPageInterop"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def NewPropertiesPanelPagePointer(page: ObjectPropertiesPage, rhinoDocRuntimeSn: int) -> IntPtr: ...
    @staticmethod
    def StackedDialogPageFromUnmanagedPointer(pointer: IntPtr) -> StackedDialogPage: ...

class RhinoPlotWidthType:
    """.NET: Rhino.UI.RhinoPlotWidthType"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoPlotWidthValue:
    """.NET: Rhino.UI.RhinoPlotWidthValue"""
    def __init__(self, *args) -> None: ...
    ...

class RuiUpdateUi(EventArgs):
    """.NET: Rhino.UI.RuiUpdateUi"""
    def __init__(self, *args) -> None: ...
    Enabled: bool
    Checked: bool
    RadioChecked: bool
    Text: str
    FileId: Guid
    MenuId: Guid
    MenuItemId: Guid
    MenuHandle: IntPtr
    MenuIndex: int
    WindowsMenuItemId: int
    @staticmethod
    def RegisterMenuItem(file: Guid, menu: Guid, item: Guid, callBack: UpdateMenuItemEventHandler) -> bool: ...

class SaveFileDialog:
    """.NET: Rhino.UI.SaveFileDialog"""
    def __init__(self, *args) -> None: ...
    DefaultExt: str
    FileName: str
    Title: str
    Filter: str
    InitialDirectory: str
    def ShowDialog(self, ) -> DialogResult: ...
    def ShowSaveDialog(self, ) -> bool: ...

class ShowMessageButton:
    """.NET: Rhino.UI.ShowMessageButton"""
    def __init__(self, *args) -> None: ...
    ...

class ShowMessageDefaultButton:
    """.NET: Rhino.UI.ShowMessageDefaultButton"""
    def __init__(self, *args) -> None: ...
    ...

class ShowMessageIcon:
    """.NET: Rhino.UI.ShowMessageIcon"""
    def __init__(self, *args) -> None: ...
    ...

class ShowMessageMode:
    """.NET: Rhino.UI.ShowMessageMode"""
    def __init__(self, *args) -> None: ...
    ...

class ShowMessageOptions:
    """.NET: Rhino.UI.ShowMessageOptions"""
    def __init__(self, *args) -> None: ...
    ...

class ShowMessageResult:
    """.NET: Rhino.UI.ShowMessageResult"""
    def __init__(self, *args) -> None: ...
    ...

class ShowPanelEventArgs(PanelEventArgs):
    """.NET: Rhino.UI.ShowPanelEventArgs"""
    def __init__(self, *args) -> None: ...
    Show: bool
    PanelId: Guid
    DocumentSerialNumber: int
    Document: RhinoDoc

class ShowPanelReason:
    """.NET: Rhino.UI.ShowPanelReason"""
    def __init__(self, *args) -> None: ...
    ...

class StackedDialogPage:
    """.NET: Rhino.UI.StackedDialogPage"""
    def __init__(self, *args) -> None: ...
    Children: List
    HasChildren: bool
    Modified: bool
    Handle: IntPtr
    PageControl: object
    EnglishPageTitle: str
    LocalPageTitle: str
    PageImage: Image
    ShowDefaultsButton: bool
    ShowApplyButton: bool
    NavigationTextIsBold: bool
    NavigationTextColor: Color
    def AddChildPage(self, pageToAdd: StackedDialogPage) -> None: ...
    def MakeActivePage(self, ) -> None: ...
    def OnActivate(self, active: bool) -> bool: ...
    def OnApply(self, ) -> bool: ...
    def OnCancel(self, ) -> None: ...
    def OnCreateParent(self, hwndParent: IntPtr) -> None: ...
    def OnDefaults(self, ) -> None: ...
    def OnHelp(self, ) -> None: ...
    def OnSizeParent(self, width: int, height: int) -> None: ...
    def RemovePage(self, ) -> None: ...
    def SetActivePageTo(self, pageName: str, documentPropertiesPage: bool) -> bool: ...
    def SetEnglishPageTitle(self, newPageTile: str) -> None: ...

class StatusBar:
    """.NET: Rhino.UI.StatusBar"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ClearMessagePane() -> None: ...
    @staticmethod
    def HideProgressMeter(docSerialNumber: int) -> None: ...
    @staticmethod
    def SetDistancePane(distance: float) -> None: ...
    @staticmethod
    def SetMessagePane(message: str) -> None: ...
    @staticmethod
    def SetNumberPane(number: float) -> None: ...
    @staticmethod
    def SetPointPane(point: Point3d) -> None: ...
    @staticmethod
    def ShowProgressMeter(docSerialNumber: int, lowerLimit: int, upperLimit: int, label: str, embedLabel: bool, showPercentComplete: bool) -> int: ...
    @staticmethod
    def UpdateProgressMeter(docSerialNumber: int, label: str, position: int, absolute: bool) -> int: ...

class ThemeSettings:
    """.NET: Rhino.UI.ThemeSettings"""
    def __init__(self, *args) -> None: ...
    Content: ContentThemeZone
    Frame: FrameThemeZone

class Toolbar:
    """.NET: Rhino.UI.Toolbar"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    Name: str
    BitmapSize: Size
    TabSize: Size

class ToolbarFile:
    """.NET: Rhino.UI.ToolbarFile"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    Path: str
    Name: str
    GroupCount: int
    ToolbarCount: int
    def Close(self, prompt: bool) -> bool: ...
    def GetGroup(self, index: int) -> ToolbarGroup: ...
    def GetToolbar(self, index: int) -> Toolbar: ...
    def Save(self, ) -> bool: ...
    def SaveAs(self, path: str) -> bool: ...

class ToolbarFileCollection:
    """.NET: Rhino.UI.ToolbarFileCollection"""
    def __init__(self, *args) -> None: ...
    Count: int
    Item: ToolbarFile
    SidebarIsVisible: bool
    MruSidebarIsVisible: bool
    def FindByName(self, name: str, ignoreCase: bool) -> ToolbarFile: ...
    def FindByPath(self, path: str) -> ToolbarFile: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def Open(self, path: str) -> ToolbarFile: ...

class ToolbarGroup:
    """.NET: Rhino.UI.ToolbarGroup"""
    def __init__(self, *args) -> None: ...
    Id: Guid
    Name: str
    Visible: bool
    IsDocked: bool

class ViewModel:
    """.NET: Rhino.UI.ViewModel"""
    def __init__(self, *args) -> None: ...
    ModelUnitSystem: UnitSystem
    PageUnitSystem: UnitSystem
    ModelDistanceDisplayMode: DistanceDisplayMode
    PageDistanceDisplayMode: DistanceDisplayMode
    ModelDistanceDisplayPrecision: int
    PageDistanceDisplayPrecision: int
    def DistanceDisplayPrecisionFromDoc(self, doc: RhinoDoc) -> None: ...
    def OkToClose(self, parent: object) -> bool: ...
    def UnitsAndDistanceDisplayFromDoc(self, doc: RhinoDoc) -> None: ...
    def UnitsDistanceDisplayAndPrecisionFromDoc(self, doc: RhinoDoc) -> None: ...

class WaitCursor:
    """.NET: Rhino.UI.WaitCursor"""
    def __init__(self, *args) -> None: ...
    def Clear(self, ) -> None: ...
    def Dispose(self, ) -> None: ...
    def Set(self, ) -> None: ...
