# Auto-generated — Rhino 8 — Rhino.UI.Interfaces

class IGradient:
    """.NET: Rhino.UI.Interfaces.IGradient"""
    def __init__(self, *args) -> None: ...
    def Draw(self, graphics: Graphics, dest: RectangleF) -> None: ...
    def GetColorStops(self, ) -> list: ...
    def MouseDown(self, dest: RectangleF, point: PointF) -> bool: ...
    def MouseMove(self, dest: RectangleF, point: PointF) -> bool: ...
    def MouseUp(self, dest: RectangleF, point: PointF, deselect: bool) -> bool: ...
    def SetColorStops(self, stops: IEnumerable) -> None: ...
