# Auto-generated — Rhino 8 — Rhino.UI.Runtime

class HostUtils:
    """.NET: Rhino.UI.Runtime.HostUtils"""
    def __init__(self, *args) -> None: ...
    ...

class IPlatformService:
    """.NET: Rhino.UI.Runtime.IPlatformService"""
    def __init__(self, *args) -> None: ...
    MainRhinoWindow: Window
    def BringCurrentProcessToForeground(self, ) -> None: ...
    def ControlPadding(self, control: Control, left: float, top: float, right: float, bottom: float) -> None: ...
    def GetEtoUiFont(self, style: Style, size: Size) -> Font: ...
    def GetEtoWindow(self, handle: IntPtr) -> Window: ...
    def GetNumericUpDownScrollWidth(self, control: NumericStepper) -> int: ...
    def GetRhinoDocumentPropertiesWindow(self, page: OptionsDialogPage) -> Window: ...
    def GetRhinoDocumentWindow(self, docRuntimeSerialNumber: int) -> Window: ...
    def GetRhinoPreferencesWindow(self, page: OptionsDialogPage) -> Window: ...
    def InvokeRequired(self, control: Control) -> bool: ...
    def PlaySoundFile(self, fileName: str) -> None: ...
    def PushPickButton(self, window: Window, pickFunction: EventHandler) -> None: ...
    def SelectedImageFromIcon(self, icon: Icon, scaledSize: Size) -> Image: ...
    def SetControlPadding(self, control: Control, left: float, top: float, right: float, bottom: float) -> None: ...
    def SetImageTemplateProperty(self, image: Image, value: bool) -> None: ...
    def SetWindowPos(self, window: Window, rectangle: RectangleF, move: bool, resize: bool) -> bool: ...
    def ShowSemiModal(self, dialog: Dialog, doc: RhinoDoc, parent: Control) -> None: ...
    def TextBoxHorizontalContentAlignment(self, control: TextBox, alignment: TextAlignment) -> None: ...
    def ToEto(self, bmp: Bitmap, background_color: Color) -> Bitmap: ...
    def ToEtoBitmap(self, nativeImagePointer: IntPtr) -> Bitmap: ...
    def ToEtoControl(self, nativeControlHandle: IntPtr) -> Control: ...
    def ToEtoFont(self, font: Font, size: float, decoration: FontDecoration) -> Font: ...
    def ToEtoFontTypeface(self, font: Font) -> FontTypeface: ...
    def ToEtoIcon(self, nativeImagePointer: IntPtr) -> Icon: ...
    def ToEtoScreen(self, point: Point, screen: Screen) -> PointF: ...
    def ToSystemDrawingScreen(self, point: PointF, screen: Screen) -> Point: ...

class PlatformServiceProvider:
    """.NET: Rhino.UI.Runtime.PlatformServiceProvider"""
    def __init__(self, *args) -> None: ...
    Service: IPlatformService

class RhinoUiServiceLocator:
    """.NET: Rhino.UI.Runtime.RhinoUiServiceLocator"""
    def __init__(self, *args) -> None: ...
    def GetService(self, ) -> T: ...
