# Auto-generated — Rhino 8 — Rhino.UI.Tether

class CurveTetherStyle:
    """.NET: Rhino.UI.Tether.CurveTetherStyle"""
    def __init__(self, *args) -> None: ...
    ...

class TetherDestroyedEventArgs(EventArgs):
    """.NET: Rhino.UI.Tether.TetherDestroyedEventArgs"""
    def __init__(self, *args) -> None: ...
    ...

class TetherDestroyedEventHandler:
    """.NET: Rhino.UI.Tether.TetherDestroyedEventHandler"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, source: object, e: TetherDestroyedEventArgs, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, source: object, e: TetherDestroyedEventArgs) -> None: ...
