# Auto-generated — Rhino 8 — Rhino.UI.Controls.ThumbnailUI

class IRhRdkContentThumbnail:
    """.NET: Rhino.UI.Controls.ThumbnailUI.IRhRdkContentThumbnail"""
    def __init__(self, *args) -> None: ...
    def ChildContent(self, ) -> RenderContent: ...
    def GroupId(self, ) -> Guid: ...
    def TopLevelContent(self, ) -> RenderContent: ...

class IRhRdkContentThumbnailList_Sizes:
    """.NET: Rhino.UI.Controls.ThumbnailUI.IRhRdkContentThumbnailList_Sizes"""
    def __init__(self, *args) -> None: ...
    ...

class IRhRdkThumbnail:
    """.NET: Rhino.UI.Controls.ThumbnailUI.IRhRdkThumbnail"""
    def __init__(self, *args) -> None: ...
    def Dib(self, dibOut: Bitmap) -> None: ...
    def GetDib(self, ) -> Bitmap: ...
    def GetDisplayRect(self, rectOut: RectangleF) -> None: ...
    def Id(self, ) -> Guid: ...
    def IsHot(self, ) -> bool: ...
    def IsSelected(self, ) -> bool: ...
    def Label(self, ) -> str: ...

class IRhRdkThumbnailList:
    """.NET: Rhino.UI.Controls.ThumbnailUI.IRhRdkThumbnailList"""
    def __init__(self, *args) -> None: ...
    def Add(self, t: Thumbnail) -> None: ...
    def Clear(self, ) -> None: ...
    def Get(self, u: Guid) -> IRhRdkThumbnail: ...
    def GetGridMetrics(self, w: int, h: int, ox: int, oy: int) -> None: ...
    def GetSize(self, ) -> IRhRdkContentThumbnailList_Sizes: ...
    def GetStatisticsHeaderHeight(self, ) -> None: ...
    def Mode(self, ) -> IRhRdkThumbnailList_Modes: ...
    def SetClientText(self, w: str) -> None: ...
    def SetCustomBitmapSize(self, w: int, h: int) -> None: ...
    def SetMode(self, m: IRhRdkThumbnailList_Modes, b: bool) -> None: ...
    def SetShowLabels(self, b: bool) -> None: ...
    def Shape(self, ) -> IRhRdkThumbnailList_Shapes: ...
    def ShowLabels(self, ) -> bool: ...
    def UUID(self, ) -> Guid: ...

class IRhRdkThumbnailList_Modes:
    """.NET: Rhino.UI.Controls.ThumbnailUI.IRhRdkThumbnailList_Modes"""
    def __init__(self, *args) -> None: ...
    ...

class IRhRdkThumbnailList_Shapes:
    """.NET: Rhino.UI.Controls.ThumbnailUI.IRhRdkThumbnailList_Shapes"""
    def __init__(self, *args) -> None: ...
    ...

class ThumbData:
    """.NET: Rhino.UI.Controls.ThumbnailUI.ThumbData"""
    def __init__(self, *args) -> None: ...
    TopLevel: bool
    InUseColor: List
    Content: RenderContent
    PreviewAppearance: PreviewAppearance
    Image: Bitmap
    Children: List
    Parent: ThumbData
    Name: str
    Selected: bool
    Type: str
    Intensity: str
    Id: Guid
    InUse: bool
    Tags: List
    @staticmethod
    def GetPreviewHeigth(thumb_size: Sizes, shape: Shapes) -> int: ...
    @staticmethod
    def GetPreviewWidth(thumb_size: Sizes, shape: Shapes) -> int: ...

class Thumbnail:
    """.NET: Rhino.UI.Controls.ThumbnailUI.Thumbnail"""
    def __init__(self, *args) -> None: ...
    CppPointer: IntPtr
    def Dib(self, dibOut: Bitmap) -> None: ...
    def Dispose(self, ) -> None: ...
    def GetDib(self, ) -> Bitmap: ...
    def GetDisplayRect(self, rectOut: RectangleF) -> None: ...
    def Id(self, ) -> Guid: ...
    def IsHot(self, ) -> bool: ...
    def IsSelected(self, ) -> bool: ...
    def Label(self, ) -> str: ...

class ThumbnailViewModelFactory(InternalRdkViewModelFactory):
    """.NET: Rhino.UI.Controls.ThumbnailUI.ThumbnailViewModelFactory"""
    def __init__(self, *args) -> None: ...
    def Get(self, id: Guid) -> IntPtr: ...
