# Auto-generated — Rhino 8 — Rhino.Input

class GetBoxMode:
    """.NET: Rhino.Input.GetBoxMode"""
    def __init__(self, *args) -> None: ...
    ...

class GetResult:
    """.NET: Rhino.Input.GetResult"""
    def __init__(self, *args) -> None: ...
    ...

class RhinoGet:
    """.NET: Rhino.Input.RhinoGet"""
    def __init__(self, *args) -> None: ...
    AllBitmapFileTypes: BitmapFileTypes
    @staticmethod
    def Get2dRectangle(solidPen: bool, rectangle: Rectangle, rectView: RhinoView) -> Result: ...
    @staticmethod
    def GetAngle(commandPrompt: str, basePoint: Point3d, referencePoint: Point3d, defaultAngleRadians: float, angleRadians: float) -> Result: ...
    @staticmethod
    def GetArc(arc: Arc) -> Result: ...
    @staticmethod
    def GetBool(prompt: str, acceptNothing: bool, offPrompt: str, onPrompt: str, boolValue: bool) -> Result: ...
    @staticmethod
    def GetBox(box: Box, mode: GetBoxMode, basePoint: Point3d, prompt1: str, prompt2: str, prompt3: str) -> Result: ...
    @staticmethod
    def GetBoxWithCounts(xMin: int, xCount: int, yMin: int, yCount: int, zMin: int, zCount: int, corners: list) -> Result: ...
    @staticmethod
    def GetCircle(circle: Circle) -> Result: ...
    @staticmethod
    def GetColor(prompt: str, acceptNothing: bool, color: Color) -> Result: ...
    @staticmethod
    def GetFileName(mode: GetFileNameMode, defaultName: str, title: str, parent: object, fileTypes: BitmapFileTypes) -> str: ...
    @staticmethod
    def GetFileNameScripted(mode: GetFileNameMode, defaultName: str) -> str: ...
    @staticmethod
    def GetGrip(grip: GripObject, prompt: str) -> Result: ...
    @staticmethod
    def GetGrips(grips: list, prompt: str) -> Result: ...
    @staticmethod
    def GetHelix(helix: NurbsCurve) -> Result: ...
    @staticmethod
    def GetInteger(prompt: str, acceptNothing: bool, outputNumber: int, lowerLimit: int, upperLimit: int) -> Result: ...
    @staticmethod
    def GetLine(line: Line) -> Result: ...
    @staticmethod
    def GetLinearDimension(dimension: LinearDimension) -> Result: ...
    @staticmethod
    def GetMeshParameters(doc: RhinoDoc, parameters: MeshingParameters, uiStyle: int) -> Result: ...
    @staticmethod
    def GetMultipleObjects(prompt: str, acceptNothing: bool, filter: ObjectType, rhObjects: list) -> Result: ...
    @staticmethod
    def GetNumber(prompt: str, acceptNothing: bool, outputNumber: float, lowerLimit: float, upperLimit: float) -> Result: ...
    @staticmethod
    def GetOneObject(prompt: str, acceptNothing: bool, filter: ObjectType, rhObject: ObjRef) -> Result: ...
    @staticmethod
    def GetPlane(plane: Plane) -> Result: ...
    @staticmethod
    def GetPoint(prompt: str, acceptNothing: bool, point: Point3d) -> Result: ...
    @staticmethod
    def GetPointOnMesh(doc: RhinoDoc, meshObjectId: Guid, prompt: str, acceptNothing: bool, point: Point3d) -> Result: ...
    @staticmethod
    def GetPolygon(useActiveLayerLinetype: bool, numberSides: int, inscribed: bool, polyline: Polyline) -> Result: ...
    @staticmethod
    def GetPolyline(polyline: Polyline) -> Result: ...
    @staticmethod
    def GetPrintWindow(settings: ViewCaptureSettings) -> Result: ...
    @staticmethod
    def GetRectangle(mode: GetBoxMode, firstPoint: Point3d, prompts: IEnumerable, corners: list) -> Result: ...
    @staticmethod
    def GetRectangleWithCounts(xMin: int, xCount: int, yMin: int, yCount: int, corners: list) -> Result: ...
    @staticmethod
    def GetSpiral(spiral: NurbsCurve) -> Result: ...
    @staticmethod
    def GetString(prompt: str, acceptNothing: bool, outputString: str) -> Result: ...
    @staticmethod
    def GetView(commandPrompt: str, view: RhinoView) -> Result: ...
    @staticmethod
    def InGet(doc: RhinoDoc) -> bool: ...
    @staticmethod
    def InGetObject(doc: RhinoDoc) -> bool: ...
    @staticmethod
    def InGetPoint(doc: RhinoDoc) -> bool: ...
    @staticmethod
    def StringToCommandOptionName(englishString: str, localizedString: str) -> LocalizeStringPair: ...

class StringParser:
    """.NET: Rhino.Input.StringParser"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ParseAngleExpession(expression: str, start_offset: int, expression_length: int, parse_settings_in: StringParserSettings, output_angle_unit_system: AngleUnitSystem, value_out: float, parse_results: StringParserSettings, parsed_unit_system: AngleUnitSystem) -> int: ...
    @staticmethod
    def ParseAngleExpressionDegrees(expression: str, angle_degrees: float) -> bool: ...
    @staticmethod
    def ParseAngleExpressionRadians(expression: str, angle_radians: float) -> bool: ...
    @staticmethod
    def ParseLengthExpession(expression: str, start_offset: int, expression_length: int, parse_settings_in: StringParserSettings, output_unit_system: UnitSystem, value_out: float, parse_results: StringParserSettings, parsed_unit_system: UnitSystem) -> int: ...
    @staticmethod
    def ParseNumber(expression: str, max_count: int, settings_in: StringParserSettings, settings_out: StringParserSettings, answer: float) -> int: ...

class StringParserSettings:
    """.NET: Rhino.Input.StringParserSettings"""
    def __init__(self, *args) -> None: ...
    DefaultParseSettings: StringParserSettings
    ParseSettingsRadians: StringParserSettings
    ParseSettingsDegrees: StringParserSettings
    ParseSettingsIntegerNumber: StringParserSettings
    ParseSettingsRationalNumber: StringParserSettings
    ParseSettingsDoubleNumber: StringParserSettings
    ParseSettingsRealNumber: StringParserSettings
    ParseSettingsEmpty: StringParserSettings
    DefaultAngleUnitSystem: AngleUnitSystem
    DefaultLengthUnitSystem: UnitSystem
    ParseLeadingWhiteSpace: bool
    ParseArithmeticExpression: bool
    ParseMathFunctions: bool
    ParseExplicitFormulaExpression: bool
    ParseUnaryMinus: bool
    ParseUnaryPlus: bool
    ParseSignificandIntegerPart: bool
    ParseSignificandFractionalPart: bool
    ParseSignificandDigitSeparators: bool
    ParseScientificENotation: bool
    ParseDAsExponentInScientificENotation: bool
    ParseFullStopAsDecimalPoint: bool
    ParseFullStopAsDigitSeparator: bool
    ParseCommaAsDecimalPoint: bool
    ParseCommaAsDigitSeparator: bool
    ParseSpaceAsDigitSeparator: bool
    ParseHyphenMinusAsNumberDash: bool
    ParseHyphenAsNumberDash: bool
    ParseRationalNumber: bool
    ParsePi: bool
    ParseMultiplication: bool
    ParseDivision: bool
    ParseAddition: bool
    ParseSubtraction: bool
    ParsePairedParentheses: bool
    ParseIntegerDashFraction: bool
    ParseFeetInches: bool
    ParseArcDegreesMinutesSeconds: bool
    ParseSurveyorsNotation: bool
    PreferedLocaleId: int
    def Dispose(self, ) -> None: ...
    def SetAllExpressionSettingsToFalse(self, ) -> None: ...
    def SetAllFieldsToFalse(self, ) -> None: ...
