# Auto-generated — Rhino 8 — Rhino.Input.Custom

class CommandLineOption:
    """.NET: Rhino.Input.Custom.CommandLineOption"""
    def __init__(self, *args) -> None: ...
    Index: int
    OptionType: CommandLineOptionType
    EnglishName: str
    LocalName: str
    StringOptionValue: str
    CurrentListOptionIndex: int
    CurrentToggleValue: Nullable
    CurrentNumericValue: float
    @staticmethod
    def IsValidOptionName(optionName: str) -> bool: ...
    @staticmethod
    def IsValidOptionValueName(optionValue: str) -> bool: ...
    def ListOptions(self, english: bool) -> list: ...
    def ToggleValues(self, english: bool, offValue: str, onValue: str) -> None: ...

class CommandLineOptionType:
    """.NET: Rhino.Input.Custom.CommandLineOptionType"""
    def __init__(self, *args) -> None: ...
    ...

class ConeConstraint:
    """.NET: Rhino.Input.Custom.ConeConstraint"""
    def __init__(self, *args) -> None: ...
    ...

class CylinderConstraint:
    """.NET: Rhino.Input.Custom.CylinderConstraint"""
    def __init__(self, *args) -> None: ...
    ...

class GeometryAttributeFilter:
    """.NET: Rhino.Input.Custom.GeometryAttributeFilter"""
    def __init__(self, *args) -> None: ...
    ...

class GetArc:
    """.NET: Rhino.Input.Custom.GetArc"""
    def __init__(self, *args) -> None: ...
    AllowDeformable: bool
    Deformable: bool
    DeformablePointCount: int
    DeformableDegree: int
    DefaultRadius: float
    UseActiveLayerLinetypeForCurves: bool
    def Dispose(self, ) -> None: ...
    def Get(self, arc: Arc) -> Result: ...

class GetBaseClass:
    """.NET: Rhino.Input.Custom.GetBaseClass"""
    def __init__(self, *args) -> None: ...
    def AcceptColor(self, enable: bool) -> None: ...
    def AcceptCustomMessage(self, enable: bool) -> None: ...
    def AcceptEnterWhenDone(self, enable: bool) -> None: ...
    def AcceptNothing(self, enable: bool) -> None: ...
    def AcceptNumber(self, enable: bool, acceptZero: bool) -> None: ...
    def AcceptPoint(self, enable: bool) -> None: ...
    def AcceptString(self, enable: bool) -> None: ...
    def AcceptUndo(self, enable: bool) -> None: ...
    def AddOption(self, englishOption: str, englishOptionValue: str, hiddenOption: bool) -> int: ...
    def AddOptionColor(self, optionName: LocalizeStringPair, colorValue: OptionColor, prompt: str) -> int: ...
    def AddOptionDouble(self, englishName: str, numberValue: OptionDouble, prompt: str) -> int: ...
    def AddOptionEnumList(self, englishOptionName: str, defaultValue: T, include: list) -> int: ...
    def AddOptionEnumSelectionList(self, englishOptionName: str, enumSelection: IEnumerable, listCurrentIndex: int) -> int: ...
    def AddOptionInteger(self, englishName: str, intValue: OptionInteger, prompt: str) -> int: ...
    def AddOptionList(self, englishOptionName: str, listValues: IEnumerable, listCurrentIndex: int) -> int: ...
    def AddOptionToggle(self, englishName: str, toggleValue: OptionToggle) -> int: ...
    def ClearCommandOptions(self, ) -> None: ...
    def ClearDefault(self, ) -> None: ...
    def Color(self, ) -> Color: ...
    def CommandResult(self, ) -> Result: ...
    def CustomMessage(self, ) -> object: ...
    def Dispose(self, ) -> None: ...
    def EnableTransparentCommands(self, enable: bool) -> None: ...
    def GetSelectedEnumValue(self, ) -> T: ...
    def GetSelectedEnumValueFromSelectionList(self, selectionList: IEnumerable) -> T: ...
    def GotDefault(self, ) -> bool: ...
    @staticmethod
    def IsValidOptionName(optionName: str) -> bool: ...
    @staticmethod
    def IsValidOptionValueName(optionValueName: str) -> bool: ...
    def Line2d(self, ) -> list: ...
    def Number(self, ) -> float: ...
    def Option(self, ) -> CommandLineOption: ...
    def OptionIndex(self, ) -> int: ...
    def PickRectangle(self, ) -> Rectangle: ...
    def Point(self, ) -> Point3d: ...
    def Point2d(self, ) -> Point: ...
    @staticmethod
    def PostCustomMessage(messageData: object) -> None: ...
    def Rectangle2d(self, ) -> Rectangle: ...
    def Result(self, ) -> GetResult: ...
    def SetCommandPrompt(self, prompt: str) -> None: ...
    def SetCommandPromptDefault(self, defaultValue: str) -> None: ...
    def SetDefaultColor(self, defaultColor: Color) -> None: ...
    def SetDefaultInteger(self, defaultValue: int) -> None: ...
    def SetDefaultNumber(self, defaultNumber: float) -> None: ...
    def SetDefaultPoint(self, point: Point3d) -> None: ...
    def SetDefaultString(self, defaultValue: str) -> None: ...
    def SetOptionVaries(self, optionIndex: int, varies: bool) -> None: ...
    def SetWaitDuration(self, milliseconds: int) -> None: ...
    def StringResult(self, ) -> str: ...
    def Vector(self, ) -> Vector3d: ...
    def View(self, ) -> RhinoView: ...

class GetCancel(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetCancel"""
    def __init__(self, *args) -> None: ...
    Token: CancellationToken
    ProgressReporting: bool
    ProgressMessage: str
    Progress: IProgress
    def Wait(self, task: Task, doc: RhinoDoc) -> Result: ...
    def WaitAll(self, tasks: IEnumerable, doc: RhinoDoc) -> Result: ...

class GetCircle:
    """.NET: Rhino.Input.Custom.GetCircle"""
    def __init__(self, *args) -> None: ...
    AllowDeformable: bool
    Deformable: bool
    DeformablePointCount: int
    DeformableDegree: int
    DefaultSize: float
    InDiameterMode: bool
    UseActiveLayerLinetypeForCurves: bool
    def Dispose(self, ) -> None: ...
    def Get(self, circle: Circle) -> Result: ...

class GetCone:
    """.NET: Rhino.Input.Custom.GetCone"""
    def __init__(self, *args) -> None: ...
    ConeConstraint: ConeConstraint
    DefaultSize: float
    InDiameterMode: bool
    ApexAngleDegrees: float
    BaseAngleDegrees: float
    Height: float
    Cap: bool
    AllowInputAngle: bool
    def Dispose(self, ) -> None: ...
    def Get(self, cone: Cone) -> Result: ...
    def GetMesh(self, verticalFaces: int, aroundFaces: int, capStyle: int, cone: Cone) -> Result: ...

class GetCylinder:
    """.NET: Rhino.Input.Custom.GetCylinder"""
    def __init__(self, *args) -> None: ...
    CylinderConstraint: CylinderConstraint
    DefaultSize: float
    InDiameterMode: bool
    BothSidesOption: bool
    Height: float
    Cap: bool
    def Dispose(self, ) -> None: ...
    def Get(self, cylinder: Cylinder) -> Result: ...
    def GetMesh(self, verticalFaces: int, aroundFaces: int, capStyle: int, cylinder: Cylinder) -> Result: ...

class GetEllipse:
    """.NET: Rhino.Input.Custom.GetEllipse"""
    def __init__(self, *args) -> None: ...
    MarkFoci: bool
    IsModeFromFoci: bool
    FirstPoint: Point3d
    SecondPoint: Point3d
    def Dispose(self, ) -> None: ...
    def Get(self, ellipse: NurbsCurve) -> Result: ...

class GetEllipsoid:
    """.NET: Rhino.Input.Custom.GetEllipsoid"""
    def __init__(self, *args) -> None: ...
    MarkFoci: bool
    IsModeFromFoci: bool
    FirstPoint: Point3d
    SecondPoint: Point3d
    Plane: Plane
    def Dispose(self, ) -> None: ...
    def Get(self, ellipsoid: NurbsSurface) -> Result: ...
    def GetMesh(self, verticalFaces: int, aroundFaces: int, quadCaps: bool, ellipsoid: Mesh) -> Result: ...

class GetFileNameMode:
    """.NET: Rhino.Input.Custom.GetFileNameMode"""
    def __init__(self, *args) -> None: ...
    ...

class GetInteger(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetInteger"""
    def __init__(self, *args) -> None: ...
    def Get(self, ) -> GetResult: ...
    def Number(self, ) -> int: ...
    def SetLowerLimit(self, lowerLimit: int, strictlyGreaterThan: bool) -> None: ...
    def SetUpperLimit(self, upperLimit: int, strictlyLessThan: bool) -> None: ...

class GetLine:
    """.NET: Rhino.Input.Custom.GetLine"""
    def __init__(self, *args) -> None: ...
    FirstPointPrompt: str
    MidPointPrompt: str
    SecondPointPrompt: str
    AcceptZeroLengthLine: bool
    HaveFeedbackColor: bool
    FeedbackColor: Color
    FixedLength: float
    GetLineMode: GetLineMode
    def Dispose(self, ) -> None: ...
    def EnableAllVariations(self, on: bool) -> None: ...
    def EnableFromBothSidesOption(self, on: bool) -> None: ...
    def EnableFromMidPointOption(self, on: bool) -> None: ...
    def Get(self, line: Line) -> Result: ...
    def SetFirstPoint(self, point: Point3d) -> None: ...

class GetLineMode:
    """.NET: Rhino.Input.Custom.GetLineMode"""
    def __init__(self, *args) -> None: ...
    ...

class GetNumber(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetNumber"""
    def __init__(self, *args) -> None: ...
    def Get(self, ) -> GetResult: ...
    def SetLowerLimit(self, lowerLimit: float, strictlyGreaterThan: bool) -> None: ...
    def SetUpperLimit(self, upperLimit: float, strictlyLessThan: bool) -> None: ...

class GetObject(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetObject"""
    def __init__(self, *args) -> None: ...
    GeometryFilter: ObjectType
    GeometryAttributeFilter: GeometryAttributeFilter
    DeselectAllBeforePostSelect: bool
    OneByOnePostSelect: bool
    SubObjectSelect: bool
    ChooseOneQuestion: bool
    BottomObjectPreference: bool
    GroupSelect: bool
    ProxyBrepFromSubD: bool
    InactiveDetailPickEnabled: bool
    ReferenceObjectSelect: bool
    AlreadySelectedObjectSelect: bool
    ObjectCount: int
    ObjectsWerePreselected: bool
    SerialNumber: int
    @staticmethod
    def ActiveGetObject(doc: RhinoDoc) -> GetObject: ...
    def AppendToPickList(self, objref: ObjRef) -> None: ...
    def ClearObjects(self, ) -> None: ...
    def CustomGeometryFilter(self, rhObject: RhinoObject, geometry: GeometryBase, componentIndex: ComponentIndex) -> bool: ...
    def DisablePreSelect(self, ) -> None: ...
    def EnableClearObjectsOnEntry(self, enable: bool) -> None: ...
    def EnableHighlight(self, enable: bool) -> None: ...
    def EnableIgnoreGrips(self, enable: bool) -> None: ...
    def EnablePostSelect(self, enable: bool) -> None: ...
    def EnablePreSelect(self, enable: bool, ignoreUnacceptablePreselectedObjects: bool) -> None: ...
    def EnablePressEnterWhenDonePrompt(self, enable: bool) -> None: ...
    def EnableSelPrevious(self, enable: bool) -> None: ...
    def EnableUnselectObjectsOnExit(self, enable: bool) -> None: ...
    def Get(self, ) -> GetResult: ...
    def GetMultiple(self, minimumNumber: int, maximumNumber: int) -> GetResult: ...
    def Object(self, index: int) -> ObjRef: ...
    def Objects(self, ) -> list: ...
    def PassesGeometryAttributeFilter(self, rhObject: RhinoObject, geometry: GeometryBase, componentIndex: ComponentIndex) -> bool: ...
    def SetCustomGeometryFilter(self, filter: GetObjectGeometryFilter) -> None: ...
    def SetPressEnterWhenDonePrompt(self, prompt: str) -> None: ...

class GetObjectGeometryFilter:
    """.NET: Rhino.Input.Custom.GetObjectGeometryFilter"""
    def __init__(self, *args) -> None: ...
    Target: object
    Method: MethodInfo
    def BeginInvoke(self, rhObject: RhinoObject, geometry: GeometryBase, componentIndex: ComponentIndex, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, rhObject: RhinoObject, geometry: GeometryBase, componentIndex: ComponentIndex) -> bool: ...

class GetOption(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetOption"""
    def __init__(self, *args) -> None: ...
    def Get(self, ) -> GetResult: ...

class GetPoint(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetPoint"""
    def __init__(self, *args) -> None: ...
    DynamicDrawColor: Color
    Tag: object
    FullFrameRedrawDuringGet: bool
    OsnapEventType: OsnapModes
    def AddConstructionPoint(self, point: Point3d) -> int: ...
    def AddConstructionPoints(self, points: list) -> int: ...
    def AddSnapPoint(self, point: Point3d) -> int: ...
    def AddSnapPoints(self, points: list) -> int: ...
    def ClearConstraints(self, ) -> None: ...
    def ClearConstructionPoints(self, ) -> None: ...
    def ClearSnapPoints(self, ) -> None: ...
    def Constrain(self, brep: Brep, wireDensity: int, faceIndex: int, allowPickingPointOffObject: bool) -> bool: ...
    def ConstrainDistanceFromBasePoint(self, distance: float) -> None: ...
    def ConstrainToConstructionPlane(self, throughBasePoint: bool) -> bool: ...
    def ConstrainToTargetPlane(self, ) -> None: ...
    def ConstrainToVirtualCPlaneIntersection(self, plane: Plane) -> bool: ...
    def DrawLineFromPoint(self, startPoint: Point3d, showDistanceInStatusBar: bool) -> None: ...
    def EnableCurveSnapArrow(self, drawDirectionArrowAtSnapPoint: bool, reverseArrow: bool) -> None: ...
    def EnableCurveSnapPerpBar(self, drawPerpBarAtSnapPoint: bool, drawEndPoints: bool) -> None: ...
    def EnableCurveSnapTangentBar(self, drawTangentBarAtSnapPoint: bool, drawEndPoints: bool) -> None: ...
    def EnableDrawLineFromPoint(self, enable: bool) -> None: ...
    def EnableNoRedrawOnExit(self, noRedraw: bool) -> None: ...
    def EnableObjectSnapCursors(self, enable: bool) -> None: ...
    def EnableSnapToCurves(self, enable: bool) -> None: ...
    def Get(self, onMouseUp: bool, get2DPoint: bool) -> GetResult: ...
    def GetConstructionPoints(self, ) -> list: ...
    def GetPlanarConstraint(self, vp: RhinoViewport, plane: Plane) -> bool: ...
    def GetSnapPoints(self, ) -> list: ...
    def InterruptMouseMove(self, ) -> bool: ...
    def NumberPreview(self, number: float) -> bool: ...
    def PermitConstraintOptions(self, permit: bool) -> None: ...
    def PermitElevatorMode(self, permitMode: int) -> None: ...
    def PermitFromOption(self, permit: bool) -> None: ...
    def PermitObjectSnap(self, permit: bool) -> None: ...
    def PermitOrthoSnap(self, permit: bool) -> None: ...
    def PermitTabMode(self, permit: bool) -> None: ...
    def PointOnBrep(self, u: float, v: float) -> BrepFace: ...
    def PointOnCurve(self, t: float) -> Curve: ...
    def PointOnObject(self, ) -> ObjRef: ...
    def PointOnSurface(self, u: float, v: float) -> Surface: ...
    def SetBasePoint(self, basePoint: Point3d, showDistanceInStatusBar: bool) -> None: ...
    def SetCursor(self, cursor: CursorStyle) -> None: ...
    def TryGetBasePoint(self, basePoint: Point3d) -> bool: ...

class GetPointDrawEventArgs(DrawEventArgs):
    """.NET: Rhino.Input.Custom.GetPointDrawEventArgs"""
    def __init__(self, *args) -> None: ...
    CurrentPoint: Point3d
    Source: GetPoint
    Viewport: RhinoViewport
    Display: DisplayPipeline
    RhinoDoc: RhinoDoc

class GetPointMouseEventArgs(EventArgs):
    """.NET: Rhino.Input.Custom.GetPointMouseEventArgs"""
    def __init__(self, *args) -> None: ...
    Source: GetPoint
    Viewport: RhinoViewport
    Point: Point3d
    WindowPoint: Point
    LeftButtonDown: bool
    RightButtonDown: bool
    ShiftKeyDown: bool
    ControlKeyDown: bool
    MiddleButtonDown: bool

class GetPolyline:
    """.NET: Rhino.Input.Custom.GetPolyline"""
    def __init__(self, *args) -> None: ...
    FirstPointPrompt: str
    SecondPointPrompt: str
    ThirdPointPrompt: str
    FourthPointPrompt: str
    MinPointCount: int
    MaxPointCount: int
    def Dispose(self, ) -> None: ...
    def Get(self, polyline: Polyline) -> Result: ...
    def SetFirstPoint(self, point: Point3d) -> None: ...

class GetSphere:
    """.NET: Rhino.Input.Custom.GetSphere"""
    def __init__(self, *args) -> None: ...
    DefaultSize: float
    InDiameterMode: bool
    def Dispose(self, ) -> None: ...
    def Get(self, sphere: Sphere) -> Result: ...
    def GetMesh(self, style: MeshSphereStyle, verticalFaces: int, aroundFaces: int, triangleSubdivisions: int, quadSubdivisions: int, sphere: Sphere) -> Result: ...

class GetString(GetBaseClass):
    """.NET: Rhino.Input.Custom.GetString"""
    def __init__(self, *args) -> None: ...
    def Get(self, ) -> GetResult: ...
    def GetLiteralString(self, ) -> GetResult: ...

class GetTorus:
    """.NET: Rhino.Input.Custom.GetTorus"""
    def __init__(self, *args) -> None: ...
    DefaultSize: float
    InDiameterMode: bool
    FixInnerRadius: bool
    InSecondDiameterMode: bool
    SecondSize: float
    PromptForMeshDensity: bool
    VerticalDirectionCount: int
    VerticalDirectionMinimumCount: int
    AroundDirectionCount: int
    AroundDirectionMinimumCount: int
    def Dispose(self, ) -> None: ...
    def Get(self, torus: Torus) -> Result: ...
    def GetMesh(self, verticalFaces: int, aroundFaces: int, torus: Torus) -> Result: ...

class GetTransform(GetPoint):
    """.NET: Rhino.Input.Custom.GetTransform"""
    def __init__(self, *args) -> None: ...
    HaveTransform: bool
    Transform: Transform
    ObjectList: TransformObjectList
    DynamicDrawColor: Color
    Tag: object
    FullFrameRedrawDuringGet: bool
    OsnapEventType: OsnapModes
    def AddTransformObjects(self, list: TransformObjectList) -> None: ...
    def CalculateTransform(self, viewport: RhinoViewport, point: Point3d) -> Transform: ...
    def GetXform(self, ) -> GetResult: ...

class GetTruncatedCone:
    """.NET: Rhino.Input.Custom.GetTruncatedCone"""
    def __init__(self, *args) -> None: ...
    CylinderConstraint: CylinderConstraint
    DefaultSize: float
    InDiameterMode: bool
    Cap: bool
    Height: float
    SecondRadius: float
    def Dispose(self, ) -> None: ...
    def Get(self, truncatedCone: Brep) -> Result: ...
    def GetMesh(self, verticalFaces: int, aroundFaces: int, capStyle: int, truncatedCone: Mesh) -> Result: ...

class OptionColor:
    """.NET: Rhino.Input.Custom.OptionColor"""
    def __init__(self, *args) -> None: ...
    CurrentValue: Color
    InitialValue: Color
    def Dispose(self, ) -> None: ...

class OptionDouble:
    """.NET: Rhino.Input.Custom.OptionDouble"""
    def __init__(self, *args) -> None: ...
    CurrentValue: float
    InitialValue: float
    def Dispose(self, ) -> None: ...

class OptionInteger:
    """.NET: Rhino.Input.Custom.OptionInteger"""
    def __init__(self, *args) -> None: ...
    CurrentValue: int
    InitialValue: int
    def Dispose(self, ) -> None: ...

class OptionToggle:
    """.NET: Rhino.Input.Custom.OptionToggle"""
    def __init__(self, *args) -> None: ...
    CurrentValue: bool
    InitialValue: bool
    def Dispose(self, ) -> None: ...

class PickContext:
    """.NET: Rhino.Input.Custom.PickContext"""
    def __init__(self, *args) -> None: ...
    View: RhinoView
    PickLine: Line
    PickStyle: PickStyle
    PickMode: PickMode
    PickGroupsEnabled: bool
    SubObjectSelectionEnabled: bool
    GetObjectUsed: GetObject
    def Dispose(self, ) -> None: ...
    def PickFrustumTest(self, mesh: Mesh, pickStyle: MeshPickStyle, hitPoint: Point3d, hitSurfaceUV: Point2d, hitTextureCoordinate: Point2d, depth: float, distance: float, hitFlag: MeshHitFlag, hitIndex: int) -> bool: ...
    def PickMeshTopologyVertices(self, mesh: Mesh) -> list: ...
    def SetPickTransform(self, transform: Transform) -> None: ...
    def UpdateClippingPlanes(self, ) -> None: ...

class PickMode:
    """.NET: Rhino.Input.Custom.PickMode"""
    def __init__(self, *args) -> None: ...
    ...

class PickStyle:
    """.NET: Rhino.Input.Custom.PickStyle"""
    def __init__(self, *args) -> None: ...
    ...

class TaskCompleteEventArgs(EventArgs):
    """.NET: Rhino.Input.Custom.TaskCompleteEventArgs"""
    def __init__(self, *args) -> None: ...
    Task: Task
    Doc: RhinoDoc
    Redraw: bool
