# Auto-generated — Tekla 2026 — Tekla.Structures.Drawing

class AlongLineOrWithLeaderLineAndParentObjectAlongPartPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.AlongLineOrWithLeaderLineAndParentObjectAlongPartPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class AlongLineOrWithLeaderLinePlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.AlongLineOrWithLeaderLinePlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class AlongLinePlacing(PlacingBase):
    """.NET: Tekla.Structures.Drawing.AlongLinePlacing"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class AlongLinePlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.AlongLinePlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class AlongPartCenteredPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.AlongPartCenteredPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class AngleDimension(DimensionBase):
    """.NET: Tekla.Structures.Drawing.AngleDimension"""
    def __init__(self, *args) -> None: ...
    Attributes: AngleDimensionAttributes
    Origin: Point
    Point1: Point
    Point2: Point
    Distance: float
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAngle(self, ) -> float: ...
    def GetDimensionSet(self, Select: bool) -> DimensionSetBase: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class AngleDimensionAttributes(DimensionSetBaseAttributes):
    """.NET: Tekla.Structures.Drawing.AngleDimensionAttributes"""
    def __init__(self, *args) -> None: ...
    Type: AngleTypes
    TriangleBase: int
    Arrowhead: ArrowheadAttributes
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    TransparentBackground: bool
    Format: DimensionFormatAttributes
    Placing: DimensionPlacingAttributes
    Text: DimensionTextAttributes
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadAttributes(self, AttributeFile: str) -> bool: ...

class AngleTypes:
    """.NET: Tekla.Structures.Drawing.AngleTypes"""
    def __init__(self, *args) -> None: ...
    ...

class Arc(OpenGraphicObject):
    """.NET: Tekla.Structures.Drawing.Arc"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Radius: float
    IsLargeArc: bool
    Attributes: ArcAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetGeometricalArc(self, ) -> Arc: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ArrowheadAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.ArrowheadAttributes"""
    def __init__(self, *args) -> None: ...
    ArrowPosition: ArrowheadPositions
    Head: ArrowheadTypes
    Height: float
    Width: float
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ArrowheadPositions:
    """.NET: Tekla.Structures.Drawing.ArrowheadPositions"""
    def __init__(self, *args) -> None: ...
    ...

class ArrowheadTypes:
    """.NET: Tekla.Structures.Drawing.ArrowheadTypes"""
    def __init__(self, *args) -> None: ...
    ...

class AssemblyDrawing(Drawing):
    """.NET: Tekla.Structures.Drawing.AssemblyDrawing"""
    def __init__(self, *args) -> None: ...
    AssemblyIdentifier: Identifier
    SheetNumber: int
    DrawingTypeStr: str
    Name: str
    UpToDateStatus: DrawingUpToDateStatus
    IsMasterDrawing: bool
    IsLocked: bool
    IsIssued: bool
    IsIssuedButModified: bool
    IsFrozen: bool
    IsReadyForIssue: bool
    Title1: str
    Title2: str
    Title3: str
    Mark: str
    CreationDate: DateTime
    ModificationDate: DateTime
    IssuingDate: DateTime
    OutputDate: DateTime
    Layout: LayoutAttributes
    SectionViewStartLabel: str
    IsReadyForIssueBy: str
    IsLockedBy: str
    CommitMessage: str
    QueryReturnValue: ReturnValuesEnum
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class AttributesBase:
    """.NET: Tekla.Structures.Drawing.AttributesBase"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadAttributes(self, AttributeFile: str) -> bool: ...

class AutoSizeOptions:
    """.NET: Tekla.Structures.Drawing.AutoSizeOptions"""
    def __init__(self, *args) -> None: ...
    ...

class BaseLinePlacing(PlacingBase):
    """.NET: Tekla.Structures.Drawing.BaseLinePlacing"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class BaseLinePlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.BaseLinePlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class BaseLineWithArrowAtEndPointPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.BaseLineWithArrowAtEndPointPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class BaseLineWithArrowAtStartPointPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.BaseLineWithArrowAtStartPointPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class Bolt(ModelObject):
    """.NET: Tekla.Structures.Drawing.Bolt"""
    def __init__(self, *args) -> None: ...
    Attributes: BoltAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class CannotCreateSectionViewFrom3dView(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotCreateSectionViewFrom3dView"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotDeleteActiveDrawingException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotDeleteActiveDrawingException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotGetAttributeForPluginDueToIncorrectTypeException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotGetAttributeForPluginDueToIncorrectTypeException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotGetAttributeForPluginDueToInexistantFieldException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotGetAttributeForPluginDueToInexistantFieldException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotGetAttributeForPluginException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotGetAttributeForPluginException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotInsertDrawingException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotInsertDrawingException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotLoadAttributesException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotLoadAttributesException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotModifyNonActiveDrawingException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotModifyNonActiveDrawingException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotPerformOperationDrawingEditorMustBeClosedException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotPerformOperationDrawingEditorMustBeClosedException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotPerformOperationDrawingIsActiveException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotPerformOperationDrawingIsActiveException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotPerformOperationDrawingMustBeActiveException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotPerformOperationDrawingMustBeActiveException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotPerformOperationDrawingNotUpToDateException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotPerformOperationDrawingNotUpToDateException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotPerformOperationNumberingNotUpToDate(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotPerformOperationNumberingNotUpToDate"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotSetAttributeForPluginDueToIncorrectTypeException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotSetAttributeForPluginDueToIncorrectTypeException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotSetAttributeForPluginDueToInexistantFieldException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotSetAttributeForPluginDueToInexistantFieldException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CannotSetAttributeForPluginException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.CannotSetAttributeForPluginException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class CastUnitDrawing(Drawing):
    """.NET: Tekla.Structures.Drawing.CastUnitDrawing"""
    def __init__(self, *args) -> None: ...
    CastUnitIdentifier: Identifier
    SheetNumber: int
    CastUnitById: bool
    DrawingTypeStr: str
    Name: str
    UpToDateStatus: DrawingUpToDateStatus
    IsMasterDrawing: bool
    IsLocked: bool
    IsIssued: bool
    IsIssuedButModified: bool
    IsFrozen: bool
    IsReadyForIssue: bool
    Title1: str
    Title2: str
    Title3: str
    Mark: str
    CreationDate: DateTime
    ModificationDate: DateTime
    IssuingDate: DateTime
    OutputDate: DateTime
    Layout: LayoutAttributes
    SectionViewStartLabel: str
    IsReadyForIssueBy: str
    IsLockedBy: str
    CommitMessage: str
    QueryReturnValue: ReturnValuesEnum
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class Circle(ClosedGraphicObject):
    """.NET: Tekla.Structures.Drawing.Circle"""
    def __init__(self, *args) -> None: ...
    CenterPoint: Point
    Radius: float
    Attributes: CircleAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ClosedGraphicObject(GraphicObject):
    """.NET: Tekla.Structures.Drawing.ClosedGraphicObject"""
    def __init__(self, *args) -> None: ...
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum

class Cloud(CloudBase):
    """.NET: Tekla.Structures.Drawing.Cloud"""
    def __init__(self, *args) -> None: ...
    Points: PointList
    Attributes: CloudAttributes
    Bulge: float
    ArcWidth: float
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class CloudBase(ClosedGraphicObject):
    """.NET: Tekla.Structures.Drawing.CloudBase"""
    def __init__(self, *args) -> None: ...
    Bulge: float
    ArcWidth: float
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum

class ColorSelection:
    """.NET: Tekla.Structures.Drawing.ColorSelection"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def ShowColorPalette(color: TeklaDrawingColor, hWndOwner: Nullable) -> TeklaDrawingColor: ...
    @staticmethod
    def ShowColorPaletteForHatchBackground(color: TeklaDrawingColor, hWndOwner: Nullable) -> TeklaDrawingColor: ...

class Connection(ModelObject):
    """.NET: Tekla.Structures.Drawing.Connection"""
    def __init__(self, *args) -> None: ...
    ModelIdentifier: Identifier
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ContainerElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.ContainerElement"""
    def __init__(self, *args) -> None: ...
    Frame: Frame
    Count: int
    IsSynchronized: bool
    SyncRoot: object
    def Add(self, value: ElementBase) -> None: ...
    def Clear(self, ) -> None: ...
    def Clone(self, ) -> object: ...
    def CopyTo(self, array: Array, index: int) -> None: ...
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ContainerView(ViewBase):
    """.NET: Tekla.Structures.Drawing.ContainerView"""
    def __init__(self, *args) -> None: ...
    Width: float
    Height: float
    FrameOrigin: Vector
    Origin: Point
    ExtremaCenter: Point
    IsSheet: bool
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def GetAllViews(self, ) -> DrawingObjectEnumerator: ...
    def GetViews(self, ) -> DrawingObjectEnumerator: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CurvedDimensionBase(DimensionBase):
    """.NET: Tekla.Structures.Drawing.CurvedDimensionBase"""
    def __init__(self, *args) -> None: ...
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    StartPoint: Point
    EndPoint: Point
    Distance: float
    Attributes: CurvedDimensionSetBaseAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetDimensionSet(self, ) -> DimensionSetBase: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class CurvedDimensionOrthogonal(CurvedDimensionBase):
    """.NET: Tekla.Structures.Drawing.CurvedDimensionOrthogonal"""
    def __init__(self, *args) -> None: ...
    Attributes: CurvedDimensionSetOrthogonalAttributes
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    StartPoint: Point
    EndPoint: Point
    Distance: float
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def GetDimensionSet(self, Select: bool) -> DimensionSetBase: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CurvedDimensionRadial(CurvedDimensionBase):
    """.NET: Tekla.Structures.Drawing.CurvedDimensionRadial"""
    def __init__(self, *args) -> None: ...
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    StartPoint: Point
    EndPoint: Point
    Distance: float
    Attributes: CurvedDimensionSetBaseAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def GetDimensionSet(self, Select: bool) -> DimensionSetBase: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CurvedDimensionSetBase(DimensionSetBase):
    """.NET: Tekla.Structures.Drawing.CurvedDimensionSetBase"""
    def __init__(self, *args) -> None: ...
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    Distance: float
    Attributes: DimensionSetBaseAttributes
    DimensionPoints: PointList
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class CurvedDimensionSetHandler:
    """.NET: Tekla.Structures.Drawing.CurvedDimensionSetHandler"""
    def __init__(self, *args) -> None: ...
    def CreateCurvedDimensionSetOrthogonal(self, View: ViewBase, ArcPoint1: Point, ArcPoint2: Point, ArcPoint3: Point, DimensionPoints: PointList, Distance: float, Attributes: CurvedDimensionSetOrthogonalAttributes) -> CurvedDimensionSetOrthogonal: ...
    def CreateCurvedDimensionSetRadial(self, View: ViewBase, ArcPoint1: Point, ArcPoint2: Point, ArcPoint3: Point, DimensionPoints: PointList, Distance: float, Attributes: CurvedDimensionSetRadialAttributes) -> CurvedDimensionSetRadial: ...

class CurvedDimensionSetOrthogonal(CurvedDimensionSetBase):
    """.NET: Tekla.Structures.Drawing.CurvedDimensionSetOrthogonal"""
    def __init__(self, *args) -> None: ...
    Attributes: CurvedDimensionSetOrthogonalAttributes
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    Distance: float
    DimensionPoints: PointList
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CurvedDimensionSetRadial(CurvedDimensionSetBase):
    """.NET: Tekla.Structures.Drawing.CurvedDimensionSetRadial"""
    def __init__(self, *args) -> None: ...
    Attributes: CurvedDimensionSetRadialAttributes
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    Distance: float
    DimensionPoints: PointList
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CurvedSectionMark(SectionMarkBase):
    """.NET: Tekla.Structures.Drawing.CurvedSectionMark"""
    def __init__(self, *args) -> None: ...
    MiddlePoint: Point
    LeftPoint: Point
    RightPoint: Point
    Attributes: SectionMarkAttributes
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CustomLineType(LineTypes):
    """.NET: Tekla.Structures.Drawing.CustomLineType"""
    def __init__(self, *args) -> None: ...
    Name: str
    Description: str
    LineDescription: List
    def Clone(self, ) -> object: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class CustomLineTypeCatalog:
    """.NET: Tekla.Structures.Drawing.CustomLineTypeCatalog"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Get(CustomLineTypeId: int) -> CustomLineType: ...

class DPMPrinterAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.DPMPrinterAttributes"""
    def __init__(self, *args) -> None: ...
    OutputType: DotPrintOutputType
    PrinterName: str
    PaperSize: DotPrintPaperSize
    ScalingMethod: DotPrintScalingType
    ScaleFactor: float
    Orientation: DotPrintOrientationType
    NumberOfCopies: int
    ColorMode: DotPrintColor
    OutputFileName: str
    OpenFileWhenFinished: bool
    PrintToMultipleSheet: DotPrintToMultipleSheet
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class DatabaseObject:
    """.NET: Tekla.Structures.Drawing.DatabaseObject"""
    def __init__(self, *args) -> None: ...
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetDoubleUserProperties(self, names: List, values: Dictionary) -> bool: ...
    def GetIntegerUserProperties(self, names: List, values: Dictionary) -> bool: ...
    def GetStringUserProperties(self, names: List, values: Dictionary) -> bool: ...
    def GetUserProperty(self, Name: str, Value: str) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsSameDatabaseObject(self, Object: DatabaseObject) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...
    def SetUserProperty(self, Name: str, Value: str) -> bool: ...

class DetailMark(DrawingObject):
    """.NET: Tekla.Structures.Drawing.DetailMark"""
    def __init__(self, *args) -> None: ...
    CenterPoint: Point
    BoundaryPoint: Point
    LabelPoint: Point
    Attributes: DetailMarkAttributes
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class DetailMarkSymbolAttributes(ViewMarkBasicSymbolAttributes):
    """.NET: Tekla.Structures.Drawing.DetailMarkSymbolAttributes"""
    def __init__(self, *args) -> None: ...
    Size: float
    Shape: MarkSymbolShape

class DetailMarkTagsAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.DetailMarkTagsAttributes"""
    def __init__(self, *args) -> None: ...
    TagA1: ViewMarkBasicTagAttributes
    TagA2: ViewMarkBasicTagAttributes
    TagA3: ViewMarkBasicTagAttributes
    TagA4: ViewMarkBasicTagAttributes
    TagA5: ViewMarkBasicTagAttributes
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class DimensionBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.DimensionBase"""
    def __init__(self, *args) -> None: ...
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def GetDimensionSet(self, Select: bool) -> DimensionSetBase: ...

class DimensionLink(DrawingObject):
    """.NET: Tekla.Structures.Drawing.DimensionLink"""
    def __init__(self, *args) -> None: ...
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetDimension1(self, ) -> StraightDimensionSet: ...
    def GetDimension2(self, ) -> StraightDimensionSet: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class DimensionSetBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.DimensionSetBase"""
    def __init__(self, *args) -> None: ...
    Attributes: DimensionSetBaseAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def AddToDimensionSet(self, SetToAdd: DimensionSetBase) -> bool: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...

class DimensionSetBaseAttributes(AttributesBase):
    """.NET: Tekla.Structures.Drawing.DimensionSetBaseAttributes"""
    def __init__(self, *args) -> None: ...
    Arrowhead: ArrowheadAttributes
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    TransparentBackground: bool
    Format: DimensionFormatAttributes
    Placing: DimensionPlacingAttributes
    Text: DimensionTextAttributes

class DotPrintAreaType:
    """.NET: Tekla.Structures.Drawing.DotPrintAreaType"""
    def __init__(self, *args) -> None: ...
    ...

class DotPrintColor:
    """.NET: Tekla.Structures.Drawing.DotPrintColor"""
    def __init__(self, *args) -> None: ...
    ...

class DotPrintOrientationType:
    """.NET: Tekla.Structures.Drawing.DotPrintOrientationType"""
    def __init__(self, *args) -> None: ...
    ...

class DotPrintOutputType:
    """.NET: Tekla.Structures.Drawing.DotPrintOutputType"""
    def __init__(self, *args) -> None: ...
    ...

class DotPrintPaperSize:
    """.NET: Tekla.Structures.Drawing.DotPrintPaperSize"""
    def __init__(self, *args) -> None: ...
    ...

class DotPrintScalingType:
    """.NET: Tekla.Structures.Drawing.DotPrintScalingType"""
    def __init__(self, *args) -> None: ...
    ...

class DotPrintToMultipleSheet:
    """.NET: Tekla.Structures.Drawing.DotPrintToMultipleSheet"""
    def __init__(self, *args) -> None: ...
    ...

class Drawing(DatabaseObject):
    """.NET: Tekla.Structures.Drawing.Drawing"""
    def __init__(self, *args) -> None: ...
    DrawingTypeStr: str
    Name: str
    UpToDateStatus: DrawingUpToDateStatus
    IsMasterDrawing: bool
    IsLocked: bool
    IsIssued: bool
    IsIssuedButModified: bool
    IsFrozen: bool
    IsReadyForIssue: bool
    Title1: str
    Title2: str
    Title3: str
    Mark: str
    CreationDate: DateTime
    ModificationDate: DateTime
    IssuingDate: DateTime
    OutputDate: DateTime
    Layout: LayoutAttributes
    SectionViewStartLabel: str
    IsReadyForIssueBy: str
    IsLockedBy: str
    CommitMessage: str
    QueryReturnValue: ReturnValuesEnum
    def CommitChanges(self, Message: str) -> bool: ...
    def Delete(self, ) -> bool: ...
    @staticmethod
    def GetIdsOfUnnumberedDrawings(drawingsToBeChecked: IList) -> IList: ...
    def GetPlotFileName(self, includeRevisionInfo: bool) -> str: ...
    def GetPlotFileNameExt(self, includeRevisionInfo: IncludeRevisionMarkEnum) -> str: ...
    def GetSheet(self, ) -> ContainerView: ...
    def IsSameDatabaseObject(self, Object: DatabaseObject) -> bool: ...
    def PlaceViews(self, ) -> bool: ...

class DrawingColors:
    """.NET: Tekla.Structures.Drawing.DrawingColors"""
    def __init__(self, *args) -> None: ...
    ...

class DrawingEnumerator(DrawingEnumeratorBase):
    """.NET: Tekla.Structures.Drawing.DrawingEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: Drawing

class DrawingEnumeratorBase:
    """.NET: Tekla.Structures.Drawing.DrawingEnumeratorBase"""
    def __init__(self, *args) -> None: ...
    AutoFetch: bool
    def GetEnumerator(self, ) -> IEnumerator: ...
    def GetSize(self, ) -> int: ...
    def MoveNext(self, ) -> bool: ...
    def Reset(self, ) -> None: ...

class DrawingHandler:
    """.NET: Tekla.Structures.Drawing.DrawingHandler"""
    def __init__(self, *args) -> None: ...
    def CloseActiveDrawing(self, save: bool) -> bool: ...
    def GetActiveDrawing(self, ) -> Drawing: ...
    def GetConnectionStatus(self, ) -> bool: ...
    def GetDrawingObjectSelector(self, ) -> DrawingObjectSelector: ...
    def GetDrawingSelector(self, ) -> DrawingSelector: ...
    def GetDrawings(self, ) -> DrawingEnumerator: ...
    @staticmethod
    def GetMessageExecutionStatus() -> MessageExecutionModeEnum: ...
    def GetModelObjectIdentifiers(self, drawing: Drawing) -> List: ...
    def GetPicker(self, ) -> Picker: ...
    def IsAnyDrawingOpen(self, ) -> bool: ...
    def IssueDrawing(self, drawing: Drawing) -> bool: ...
    def PrintDrawing(self, drawing: Drawing, printAttributes: PrintAttributes, fileName: str) -> bool: ...
    def PrintDrawings(self, drawings: IEnumerable, printAttributes: DPMPrinterAttributes, OutputFolder: str) -> bool: ...
    def SaveActiveDrawing(self, ) -> bool: ...
    def SetActiveDrawing(self, drawing: Drawing, showDrawing: bool, forceOpen: bool) -> bool: ...
    @staticmethod
    def SetMessageExecutionStatus(mode: MessageExecutionModeEnum) -> MessageExecutionModeEnum: ...
    def UnissueDrawing(self, drawing: Drawing) -> bool: ...
    def UpdateDrawing(self, drawing: Drawing) -> bool: ...

class DrawingHatchColors:
    """.NET: Tekla.Structures.Drawing.DrawingHatchColors"""
    def __init__(self, *args) -> None: ...
    ...

class DrawingLink(LinkBase):
    """.NET: Tekla.Structures.Drawing.DrawingLink"""
    def __init__(self, *args) -> None: ...
    Target: Drawing
    InsertionPoint: Point
    Attributes: LinkAttributes
    Text: str
    Angle: float
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class DrawingObject(DatabaseObject):
    """.NET: Tekla.Structures.Drawing.DrawingObject"""
    def __init__(self, *args) -> None: ...
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def GetDrawing(self, ) -> Drawing: ...
    def GetRelatedObjects(self, typeFilter: list) -> DrawingObjectEnumerator: ...
    def GetView(self, ) -> ViewBase: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def ToString(self, ) -> str: ...

class DrawingObjectEnumerator(DrawingEnumeratorBase):
    """.NET: Tekla.Structures.Drawing.DrawingObjectEnumerator"""
    def __init__(self, *args) -> None: ...
    Current: DrawingObject

class DrawingUpToDateStatus:
    """.NET: Tekla.Structures.Drawing.DrawingUpToDateStatus"""
    def __init__(self, *args) -> None: ...
    ...

class DwgObject(EmbeddedObjectBase):
    """.NET: Tekla.Structures.Drawing.DwgObject"""
    def __init__(self, *args) -> None: ...
    InsertionPoint: Point
    FileName: str
    Angle: float
    Size: Size
    Attributes: EmbeddedObjectAttributes
    QueryReturnValue: ReturnValuesEnum

class EdgeChamfer(ModelObject):
    """.NET: Tekla.Structures.Drawing.EdgeChamfer"""
    def __init__(self, *args) -> None: ...
    Attributes: EdgeChamferAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ElementBase:
    """.NET: Tekla.Structures.Drawing.ElementBase"""
    def __init__(self, *args) -> None: ...
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class EmbeddedObjectAttributes(AttributesBase):
    """.NET: Tekla.Structures.Drawing.EmbeddedObjectAttributes"""
    def __init__(self, *args) -> None: ...
    XScale: float
    YScale: float
    Scaling: EmbeddedObjectScalingOptions
    Frame: EmbeddedObjectFrame
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadAttributes(self, AttributeFile: str) -> bool: ...

class EmbeddedObjectBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.EmbeddedObjectBase"""
    def __init__(self, *args) -> None: ...
    InsertionPoint: Point
    FileName: str
    Angle: float
    Size: Size
    Attributes: EmbeddedObjectAttributes
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def MoveObjectRelative(self, moveVector: Vector) -> bool: ...
    def Resize(self, size: Size) -> bool: ...
    def Select(self, ) -> bool: ...

class EmbeddedObjectFrame:
    """.NET: Tekla.Structures.Drawing.EmbeddedObjectFrame"""
    def __init__(self, *args) -> None: ...
    Type: FrameTypes
    Line: LineTypeAttributes
    LineType: LineTypes
    Color: DrawingColors
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class EmbeddedObjectScalingOptions:
    """.NET: Tekla.Structures.Drawing.EmbeddedObjectScalingOptions"""
    def __init__(self, *args) -> None: ...
    ...

class Events(MarshalByRefObject):
    """.NET: Tekla.Structures.Drawing.Events"""
    def __init__(self, *args) -> None: ...
    HasDrawingUpdatedListeners: bool
    def Dispose(self, ) -> None: ...
    def InitializeLifetimeService(self, ) -> object: ...
    def OnDrawingChanged(self, eventName: str, parameters: list) -> None: ...
    def OnDrawingDeleted(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingInserted(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingReadyForIssuingChange(self, drawingGuid: str, isReadyForIssuing: bool) -> None: ...
    def OnDrawingStatusChanged(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingUpdated(self, eventName: str, parameters: list) -> None: ...
    def Register(self, ) -> None: ...
    def UnRegister(self, ) -> None: ...

class FontAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.FontAttributes"""
    def __init__(self, *args) -> None: ...
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    Height: float
    Name: str
    Italic: bool
    Bold: bool
    def Clone(self, ) -> object: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class FormatTypes:
    """.NET: Tekla.Structures.Drawing.FormatTypes"""
    def __init__(self, *args) -> None: ...
    ...

class Frame:
    """.NET: Tekla.Structures.Drawing.Frame"""
    def __init__(self, *args) -> None: ...
    Type: FrameTypes
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    def Clone(self, ) -> object: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class FrameTypes:
    """.NET: Tekla.Structures.Drawing.FrameTypes"""
    def __init__(self, *args) -> None: ...
    ...

class GADrawing(Drawing):
    """.NET: Tekla.Structures.Drawing.GADrawing"""
    def __init__(self, *args) -> None: ...
    DrawingTypeStr: str
    Name: str
    UpToDateStatus: DrawingUpToDateStatus
    IsMasterDrawing: bool
    IsLocked: bool
    IsIssued: bool
    IsIssuedButModified: bool
    IsFrozen: bool
    IsReadyForIssue: bool
    Title1: str
    Title2: str
    Title3: str
    Mark: str
    CreationDate: DateTime
    ModificationDate: DateTime
    IssuingDate: DateTime
    OutputDate: DateTime
    Layout: LayoutAttributes
    SectionViewStartLabel: str
    IsReadyForIssueBy: str
    IsLockedBy: str
    CommitMessage: str
    QueryReturnValue: ReturnValuesEnum
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class GenericAttributesBase:
    """.NET: Tekla.Structures.Drawing.GenericAttributesBase"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class GraphicObject(DrawingObject):
    """.NET: Tekla.Structures.Drawing.GraphicObject"""
    def __init__(self, *args) -> None: ...
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum

class GraphicObjectHatchAttributes(HatchAttributes):
    """.NET: Tekla.Structures.Drawing.GraphicObjectHatchAttributes"""
    def __init__(self, *args) -> None: ...
    OffsetX: float
    OffsetY: float
    Name: str
    Color: DrawingHatchColors
    TrueColor: TeklaDrawingColor
    BackgroundColor: DrawingHatchColors
    TrueBackgroundColor: TeklaDrawingColor
    DrawBackgroundColor: bool
    Angle: float
    FactorType: int
    ScaleX: float
    ScaleY: float
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class Grid(ModelObject):
    """.NET: Tekla.Structures.Drawing.Grid"""
    def __init__(self, *args) -> None: ...
    Attributes: GridAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class GridLine(ModelObject):
    """.NET: Tekla.Structures.Drawing.GridLine"""
    def __init__(self, *args) -> None: ...
    Attributes: GridLineAttributes
    StartLabel: GridLabel
    EndLabel: GridLabel
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class HatchAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.HatchAttributes"""
    def __init__(self, *args) -> None: ...
    Name: str
    Color: DrawingHatchColors
    TrueColor: TeklaDrawingColor
    BackgroundColor: DrawingHatchColors
    TrueBackgroundColor: TeklaDrawingColor
    DrawBackgroundColor: bool
    Angle: float
    FactorType: int
    ScaleX: float
    ScaleY: float

class HatchLine(ClosedGraphicObject):
    """.NET: Tekla.Structures.Drawing.HatchLine"""
    def __init__(self, *args) -> None: ...
    BaseLinePoints: PointList
    Attributes: HatchLineAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class Hideable:
    """.NET: Tekla.Structures.Drawing.Hideable"""
    def __init__(self, *args) -> None: ...
    IsHidden: bool
    def HideFromDrawing(self, ) -> None: ...
    def HideFromDrawingView(self, ) -> None: ...
    def ShowInDrawing(self, ) -> None: ...
    def ShowInDrawingView(self, ) -> None: ...

class HyperLink(LinkBase):
    """.NET: Tekla.Structures.Drawing.HyperLink"""
    def __init__(self, *args) -> None: ...
    Target: Uri
    InsertionPoint: Point
    Attributes: LinkAttributes
    Text: str
    Angle: float
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class IAxisAlignedBoundingBox:
    """.NET: Tekla.Structures.Drawing.IAxisAlignedBoundingBox"""
    def __init__(self, *args) -> None: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...

class IEvents:
    """.NET: Tekla.Structures.Drawing.IEvents"""
    def __init__(self, *args) -> None: ...
    HasDrawingUpdatedListeners: bool
    def OnDrawingChanged(self, eventName: str, parameters: list) -> None: ...
    def OnDrawingDeleted(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingInserted(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingReadyForIssuingChange(self, drawingGuid: str, isReadyForIssuing: bool) -> None: ...
    def OnDrawingStatusChanged(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingUpdated(self, eventName: str, parameters: list) -> None: ...
    def Register(self, ) -> None: ...
    def UnRegister(self, ) -> None: ...

class IHasChildren:
    """.NET: Tekla.Structures.Drawing.IHasChildren"""
    def __init__(self, *args) -> None: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...

class IHideable:
    """.NET: Tekla.Structures.Drawing.IHideable"""
    def __init__(self, *args) -> None: ...
    Hideable: Hideable

class IIsEqual:
    """.NET: Tekla.Structures.Drawing.IIsEqual"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class IMovableRelative:
    """.NET: Tekla.Structures.Drawing.IMovableRelative"""
    def __init__(self, *args) -> None: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...

class IObjectAlignedBoundingBox:
    """.NET: Tekla.Structures.Drawing.IObjectAlignedBoundingBox"""
    def __init__(self, *args) -> None: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...

class IPlacing:
    """.NET: Tekla.Structures.Drawing.IPlacing"""
    def __init__(self, *args) -> None: ...
    Placing: PlacingBase

class IPreferredPlacing:
    """.NET: Tekla.Structures.Drawing.IPreferredPlacing"""
    def __init__(self, *args) -> None: ...
    PreferredPlacing: PreferredPlacingTypeBase

class IRelatedObjects:
    """.NET: Tekla.Structures.Drawing.IRelatedObjects"""
    def __init__(self, *args) -> None: ...
    def GetRelatedObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...

class IResizeable:
    """.NET: Tekla.Structures.Drawing.IResizeable"""
    def __init__(self, *args) -> None: ...
    def Resize(self, size: Size) -> bool: ...

class Image(EmbeddedObjectBase):
    """.NET: Tekla.Structures.Drawing.Image"""
    def __init__(self, *args) -> None: ...
    InsertionPoint: Point
    FileName: str
    Angle: float
    Size: Size
    Attributes: EmbeddedObjectAttributes
    QueryReturnValue: ReturnValuesEnum

class IncludeRevisionMarkEnum:
    """.NET: Tekla.Structures.Drawing.IncludeRevisionMarkEnum"""
    def __init__(self, *args) -> None: ...
    ...

class InsidePartAlongPartOrWithLeaderLinePlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.InsidePartAlongPartOrWithLeaderLinePlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class InsidePartAlongPartPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.InsidePartAlongPartPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class InsidePartHorizontalOrWithLeaderLinePlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.InsidePartHorizontalOrWithLeaderLinePlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class InsidePartHorizontalPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.InsidePartHorizontalPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class IntList(CollectionBase):
    """.NET: Tekla.Structures.Drawing.IntList"""
    def __init__(self, *args) -> None: ...
    Item: int
    Capacity: int
    Count: int
    def Add(self, value: int) -> int: ...
    def Contains(self, value: int) -> bool: ...
    def GetRange(self, index: int, count: int) -> IntList: ...
    def IndexOf(self, value: int, startIndex: int, count: int) -> int: ...
    def Insert(self, index: int, value: int) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LastIndexOf(self, value: int, startIndex: int, count: int) -> int: ...
    def Remove(self, value: int) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def ToArray(self, ) -> list: ...

class InvalidAttributesForOperationException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.InvalidAttributesForOperationException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class InvalidPluginPickerInputException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.InvalidPluginPickerInputException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class InvalidTypeException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.InvalidTypeException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class LayoutAttributes(AttributesBase):
    """.NET: Tekla.Structures.Drawing.LayoutAttributes"""
    def __init__(self, *args) -> None: ...
    ListHiddenObjectsInTemplates: bool
    AutoSizeOptions: AutoSizeOptions
    SheetSize: Size
    SizeDefinitionMode: SizeDefinitionMode
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadAttributes(self, AttributeFile: str) -> bool: ...

class LeaderLine(DrawingObject):
    """.NET: Tekla.Structures.Drawing.LeaderLine"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    ElbowPoints: PointList
    LeaderLineType: LeaderLineTypes
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class LeaderLineAndParentObjectAlongPartPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.LeaderLineAndParentObjectAlongPartPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class LeaderLinePlacing(PlacingBase):
    """.NET: Tekla.Structures.Drawing.LeaderLinePlacing"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class LeaderLinePlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.LeaderLinePlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class LevelMark(DrawingObject):
    """.NET: Tekla.Structures.Drawing.LevelMark"""
    def __init__(self, *args) -> None: ...
    SubType: LevelMarkType
    Attributes: LevelMarkAttributes
    InsertionPoint: Point
    BasePoint: Point
    Placing: PlacingBase
    Hideable: Hideable
    ModelObjectIdentifier: Identifier
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...
    def Select(self, ) -> bool: ...

class Line(OpenGraphicObject):
    """.NET: Tekla.Structures.Drawing.Line"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Bulge: float
    Attributes: LineAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class LineTypeAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.LineTypeAttributes"""
    def __init__(self, *args) -> None: ...
    Type: LineTypes
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class LineTypes:
    """.NET: Tekla.Structures.Drawing.LineTypes"""
    def __init__(self, *args) -> None: ...
    def Clone(self, ) -> object: ...
    @staticmethod
    def Custom(CustomLineTypeName: str) -> LineTypes: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def ToString(self, ) -> str: ...

class LineTypesEnum:
    """.NET: Tekla.Structures.Drawing.LineTypesEnum"""
    def __init__(self, *args) -> None: ...
    ...

class LinkAttributes(AttributesBase):
    """.NET: Tekla.Structures.Drawing.LinkAttributes"""
    def __init__(self, *args) -> None: ...
    IsUnderlined: bool
    Font: FontAttributes
    Scaling: ScalingOptions
    Frame: LinkFrameAttributes
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadAttributes(self, AttributeFile: str) -> bool: ...

class LinkBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.LinkBase"""
    def __init__(self, *args) -> None: ...
    InsertionPoint: Point
    Attributes: LinkAttributes
    Text: str
    Angle: float
    QueryReturnValue: ReturnValuesEnum
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...
    def Resize(self, size: Size) -> bool: ...

class LinkFrameAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.LinkFrameAttributes"""
    def __init__(self, *args) -> None: ...
    Line: LineTypeAttributes
    LineType: LineTypes
    Color: DrawingColors
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class Mark(MarkBase):
    """.NET: Tekla.Structures.Drawing.Mark"""
    def __init__(self, *args) -> None: ...
    Attributes: MarkAttributes
    InsertionPoint: Point
    Placing: PlacingBase
    IsAssociativeNote: bool
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class MarkBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.MarkBase"""
    def __init__(self, *args) -> None: ...
    Attributes: MarkBaseAttributes
    InsertionPoint: Point
    Placing: PlacingBase
    IsAssociativeNote: bool
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...

class MarkSet(MarkBase):
    """.NET: Tekla.Structures.Drawing.MarkSet"""
    def __init__(self, *args) -> None: ...
    Attributes: MarkSetAttributes
    InsertionPoint: Point
    Placing: PlacingBase
    IsAssociativeNote: bool
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class MarkSymbolShape:
    """.NET: Tekla.Structures.Drawing.MarkSymbolShape"""
    def __init__(self, *args) -> None: ...
    ...

class ModelObject(DrawingObject):
    """.NET: Tekla.Structures.Drawing.ModelObject"""
    def __init__(self, *args) -> None: ...
    ModelIdentifier: Identifier
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum

class ModelObjectHatchAttributes(HatchAttributes):
    """.NET: Tekla.Structures.Drawing.ModelObjectHatchAttributes"""
    def __init__(self, *args) -> None: ...
    AutomaticScaling: bool
    Name: str
    Color: DrawingHatchColors
    TrueColor: TeklaDrawingColor
    BackgroundColor: DrawingHatchColors
    TrueBackgroundColor: TeklaDrawingColor
    DrawBackgroundColor: bool
    Angle: float
    FactorType: int
    ScaleX: float
    ScaleY: float
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class MultiDrawing(Drawing):
    """.NET: Tekla.Structures.Drawing.MultiDrawing"""
    def __init__(self, *args) -> None: ...
    DrawingTypeStr: str
    Name: str
    UpToDateStatus: DrawingUpToDateStatus
    IsMasterDrawing: bool
    IsLocked: bool
    IsIssued: bool
    IsIssuedButModified: bool
    IsFrozen: bool
    IsReadyForIssue: bool
    Title1: str
    Title2: str
    Title3: str
    Mark: str
    CreationDate: DateTime
    ModificationDate: DateTime
    IssuingDate: DateTime
    OutputDate: DateTime
    Layout: LayoutAttributes
    SectionViewStartLabel: str
    IsReadyForIssueBy: str
    IsLockedBy: str
    CommitMessage: str
    QueryReturnValue: ReturnValuesEnum
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class NewLineElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.NewLineElement"""
    def __init__(self, *args) -> None: ...
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class NormalLineType(LineTypes):
    """.NET: Tekla.Structures.Drawing.NormalLineType"""
    def __init__(self, *args) -> None: ...
    def Clone(self, ) -> object: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self, ) -> int: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class OpenGraphicObject(GraphicObject):
    """.NET: Tekla.Structures.Drawing.OpenGraphicObject"""
    def __init__(self, *args) -> None: ...
    Hideable: Hideable
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum

class Part(ModelObject):
    """.NET: Tekla.Structures.Drawing.Part"""
    def __init__(self, *args) -> None: ...
    Attributes: PartAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class PickerInput:
    """.NET: Tekla.Structures.Drawing.PickerInput"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputInterrupt(PickerInput):
    """.NET: Tekla.Structures.Drawing.PickerInputInterrupt"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputNPoints(PickerInputPointsWithinAView):
    """.NET: Tekla.Structures.Drawing.PickerInputNPoints"""
    def __init__(self, *args) -> None: ...
    PickedPoints: PointList
    PickedView: ViewBase

class PickerInputObject(PickerInputWithinAView):
    """.NET: Tekla.Structures.Drawing.PickerInputObject"""
    def __init__(self, *args) -> None: ...
    PickedObject: DrawingObject
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputObjectAndAPoint(PickerInputObject):
    """.NET: Tekla.Structures.Drawing.PickerInputObjectAndAPoint"""
    def __init__(self, *args) -> None: ...
    PickedPoint: Point
    PickedObject: DrawingObject
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputPoint(PickerInputPointsWithinAView):
    """.NET: Tekla.Structures.Drawing.PickerInputPoint"""
    def __init__(self, *args) -> None: ...
    PickedPoint: Point
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputPointsWithinAView(PickerInputWithinAView):
    """.NET: Tekla.Structures.Drawing.PickerInputPointsWithinAView"""
    def __init__(self, *args) -> None: ...
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputThreePoints(PickerInputPointsWithinAView):
    """.NET: Tekla.Structures.Drawing.PickerInputThreePoints"""
    def __init__(self, *args) -> None: ...
    FirstPickedPoint: Point
    SecondPickedPoint: Point
    ThirdPickedPoint: Point
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputTwoPoints(PickerInputPointsWithinAView):
    """.NET: Tekla.Structures.Drawing.PickerInputTwoPoints"""
    def __init__(self, *args) -> None: ...
    FirstPickedPoint: Point
    SecondPickedPoint: Point
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInputWithinAView(PickerInput):
    """.NET: Tekla.Structures.Drawing.PickerInputWithinAView"""
    def __init__(self, *args) -> None: ...
    PickedView: ViewBase
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PickerInterruptedException(TeklaStructuresDrawingsApplicationException):
    """.NET: Tekla.Structures.Drawing.PickerInterruptedException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class PlacingAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.PlacingAttributes"""
    def __init__(self, *args) -> None: ...
    IsFixed: bool
    PlacingDistance: PlacingDistanceAttributes
    PlacingQuarter: PlacingQuarterAttributes
    def Clone(self, ) -> object: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PlacingBase:
    """.NET: Tekla.Structures.Drawing.PlacingBase"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PlacingDirectionAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.PlacingDirectionAttributes"""
    def __init__(self, *args) -> None: ...
    Positive: bool
    Negative: bool
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PlacingDistanceAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.PlacingDistanceAttributes"""
    def __init__(self, *args) -> None: ...
    SearchMargin: float
    MinimalDistance: float
    MaximalDistance: float
    def Clone(self, ) -> object: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PlacingQuarterAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.PlacingQuarterAttributes"""
    def __init__(self, *args) -> None: ...
    TopLeft: bool
    TopRight: bool
    BottomLeft: bool
    BottomRight: bool
    def Clone(self, ) -> object: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PlacingTypes:
    """.NET: Tekla.Structures.Drawing.PlacingTypes"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AlongLinePlacing(StartPoint: Point, EndPoint: Point) -> PlacingBase: ...
    @staticmethod
    def BaseLinePlacing(StartPoint: Point, EndPoint: Point) -> PlacingBase: ...
    @staticmethod
    def LeaderLinePlacing(LeaderLineStartPoint: Point) -> PlacingBase: ...
    @staticmethod
    def PointPlacing() -> PlacingBase: ...

class Plugin(DrawingObject):
    """.NET: Tekla.Structures.Drawing.Plugin"""
    def __init__(self, *args) -> None: ...
    Name: str
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def ApplyStandardValues(self, Filename: str) -> bool: ...
    def Delete(self, ) -> bool: ...
    def GetDoubleAttribute(self, FieldName: str) -> float: ...
    def GetIntAttribute(self, FieldName: str) -> int: ...
    def GetPluginInput(self, ) -> ArrayList: ...
    def GetStringAttribute(self, FieldName: str) -> str: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadStandardValues(self, Filename: str) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...
    def SetAttribute(self, FieldName: str, fieldValue: int) -> None: ...
    def SetPickerInput(self, Input: PluginPickerInput) -> None: ...
    def TryGetAttribute(self, FieldName: str, FieldValue: int) -> bool: ...
    def TrySetAttribute(self, FieldName: str, fieldValue: int) -> bool: ...

class PluginPickerInput:
    """.NET: Tekla.Structures.Drawing.PluginPickerInput"""
    def __init__(self, *args) -> None: ...
    def Add(self, input: PickerInput) -> None: ...
    def AddRange(self, inputs: List) -> None: ...

class PointList(CollectionBase):
    """.NET: Tekla.Structures.Drawing.PointList"""
    def __init__(self, *args) -> None: ...
    Item: Point
    Capacity: int
    Count: int
    def Add(self, value: Point) -> int: ...
    def AddRange(self, value: PointList) -> None: ...
    def Contains(self, value: Point) -> bool: ...
    def GetRange(self, index: int, count: int) -> PointList: ...
    def IndexOf(self, value: Point, startIndex: int, count: int) -> int: ...
    def Insert(self, index: int, value: Point) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LastIndexOf(self, value: Point, startIndex: int, count: int) -> int: ...
    def Remove(self, value: Point) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def ToArray(self, ) -> list: ...

class PointPlacing(PlacingBase):
    """.NET: Tekla.Structures.Drawing.PointPlacing"""
    def __init__(self, *args) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PointPlacingType(PreferredPlacingTypeBase):
    """.NET: Tekla.Structures.Drawing.PointPlacingType"""
    def __init__(self, *args) -> None: ...
    ...

class Polygon(ClosedGraphicObject):
    """.NET: Tekla.Structures.Drawing.Polygon"""
    def __init__(self, *args) -> None: ...
    Points: PointList
    Bulges: List
    Bulge: float
    Attributes: PolygonAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class Polyline(OpenGraphicObject):
    """.NET: Tekla.Structures.Drawing.Polyline"""
    def __init__(self, *args) -> None: ...
    Points: PointList
    Bulges: List
    Bulge: float
    Attributes: PolylineAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class PourBreak(ModelObject):
    """.NET: Tekla.Structures.Drawing.PourBreak"""
    def __init__(self, *args) -> None: ...
    Attributes: PourBreakAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class PourObject(ModelObject):
    """.NET: Tekla.Structures.Drawing.PourObject"""
    def __init__(self, *args) -> None: ...
    Attributes: PourAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class PreferredMarkPlacingTypes:
    """.NET: Tekla.Structures.Drawing.PreferredMarkPlacingTypes"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AlongLineOrWithLeaderLineAndParentObjectAlongPartPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def AlongLineOrWithLeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def AlongLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def AlongPartCenteredPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartAlongPartOrWithLeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartAlongPartPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartHorizontalOrWithLeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartHorizontalPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def LeaderLineAndParentObjectAlongPartPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def LeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def PointPlacingType() -> PreferredPlacingTypeBase: ...

class PreferredPlacingTypeBase:
    """.NET: Tekla.Structures.Drawing.PreferredPlacingTypeBase"""
    def __init__(self, *args) -> None: ...
    ...

class PreferredPlacingTypes:
    """.NET: Tekla.Structures.Drawing.PreferredPlacingTypes"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AlongLineOrWithLeaderLineAndParentObjectAlongPartPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def AlongLineOrWithLeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def AlongLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def AlongPartCenteredPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def BaseLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def BaseLineWithArrowAtEndPointPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def BaseLineWithArrowAtStartPointPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartAlongPartOrWithLeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartAlongPartPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartHorizontalOrWithLeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def InsidePartHorizontalPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def LeaderLineAndParentObjectAlongPartPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def LeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def PointPlacingType() -> PreferredPlacingTypeBase: ...

class PreferredSymbolPlacingTypes:
    """.NET: Tekla.Structures.Drawing.PreferredSymbolPlacingTypes"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AlongLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def LeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def PointPlacingType() -> PreferredPlacingTypeBase: ...

class PreferredTextPlacingTypes:
    """.NET: Tekla.Structures.Drawing.PreferredTextPlacingTypes"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def AlongLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def BaseLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def BaseLineWithArrowAtEndPointPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def BaseLineWithArrowAtStartPointPlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def LeaderLinePlacingType() -> PreferredPlacingTypeBase: ...
    @staticmethod
    def PointPlacingType() -> PreferredPlacingTypeBase: ...

class PrintAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.PrintAttributes"""
    def __init__(self, *args) -> None: ...
    PrinterInstance: str
    ScalingType: DotPrintScalingType
    Scale: float
    PrintToMultipleSheet: bool
    NumberOfCopies: int
    Orientation: DotPrintOrientationType
    PrintArea: DotPrintAreaType
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class PropertyElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.PropertyElement"""
    def __init__(self, *args) -> None: ...
    Name: str
    Value: str
    Font: FontAttributes
    PropertyType: PropertyElementType
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class RadiusDimension(DimensionBase):
    """.NET: Tekla.Structures.Drawing.RadiusDimension"""
    def __init__(self, *args) -> None: ...
    Attributes: RadiusDimensionAttributes
    Distance: float
    ArcPoint1: Point
    ArcPoint2: Point
    ArcPoint3: Point
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetDimensionSet(self, Select: bool) -> DimensionSetBase: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class RadiusDimensionAttributes(DimensionSetBaseAttributes):
    """.NET: Tekla.Structures.Drawing.RadiusDimensionAttributes"""
    def __init__(self, *args) -> None: ...
    Arrowhead: ArrowheadAttributes
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    TransparentBackground: bool
    Format: DimensionFormatAttributes
    Placing: DimensionPlacingAttributes
    Text: DimensionTextAttributes
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LoadAttributes(self, AttributeFile: str) -> bool: ...

class Rectangle(ClosedGraphicObject):
    """.NET: Tekla.Structures.Drawing.Rectangle"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Width: float
    Height: float
    Angle: float
    Attributes: RectangleAttributes
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class RectangleBoundingBox(AABB):
    """.NET: Tekla.Structures.Drawing.RectangleBoundingBox"""
    def __init__(self, *args) -> None: ...
    UpperLeft: Point
    UpperRight: Point
    LowerLeft: Point
    LowerRight: Point
    Width: float
    Height: float
    AngleToAxis: float
    MinPoint: Point
    MaxPoint: Point
    @staticmethod
    def CreateRectangleBoundingBox(CenterPoint: Point, Width: float, Height: float, AngleToAxis: float) -> RectangleBoundingBox: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def ToString(self, ) -> str: ...

class RectangularCloud(CloudBase):
    """.NET: Tekla.Structures.Drawing.RectangularCloud"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Width: float
    Height: float
    Angle: float
    Attributes: RectangularCloudAttributes
    Bulge: float
    ArcWidth: float
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ReferenceModel(ModelObject):
    """.NET: Tekla.Structures.Drawing.ReferenceModel"""
    def __init__(self, *args) -> None: ...
    Attributes: ReferenceModelAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ReinforcementBase(ModelObject):
    """.NET: Tekla.Structures.Drawing.ReinforcementBase"""
    def __init__(self, *args) -> None: ...
    Attributes: ReinforcementBaseAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ReinforcementGroup(ReinforcementBase):
    """.NET: Tekla.Structures.Drawing.ReinforcementGroup"""
    def __init__(self, *args) -> None: ...
    Attributes: ReinforcementGroupAttributes
    ReinforcementCustomPosition: float
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ReinforcementMesh(ReinforcementBase):
    """.NET: Tekla.Structures.Drawing.ReinforcementMesh"""
    def __init__(self, *args) -> None: ...
    Attributes: ReinforcementMeshAttributes
    ReinforcementCustomPositionLongitudinal: float
    ReinforcementCustomPositionCrossing: float
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ReinforcementPulloutElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.ReinforcementPulloutElement"""
    def __init__(self, *args) -> None: ...
    Font: FontAttributes
    AutomaticScaling: bool
    ScaleX: float
    ScaleY: float
    RotationAxis: Rotation
    Exaggeration: bool
    BendingRadius: bool
    BendingAngle: bool
    Dimensioning: bool
    EndSymbolType: EndSymbols
    CouplersEndAnchorSymbols: bool
    CouplersScale: float
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ReinforcementSetGroup(ReinforcementBase):
    """.NET: Tekla.Structures.Drawing.ReinforcementSetGroup"""
    def __init__(self, *args) -> None: ...
    Attributes: ReinforcementSetGroupAttributes
    ReinforcementCustomPosition: float
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def GetModelIdentifiers(self, ) -> List: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ReinforcementSingle(ReinforcementBase):
    """.NET: Tekla.Structures.Drawing.ReinforcementSingle"""
    def __init__(self, *args) -> None: ...
    Attributes: ReinforcementSingleAttributes
    ReinforcementCustomPosition: float
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ReinforcementStrand(ReinforcementBase):
    """.NET: Tekla.Structures.Drawing.ReinforcementStrand"""
    def __init__(self, *args) -> None: ...
    Attributes: ReinforcementStrandAttributes
    ReinforcementCustomPosition: float
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ReportTemplateElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.ReportTemplateElement"""
    def __init__(self, *args) -> None: ...
    Template: TemplateInfo
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ScalingOptions:
    """.NET: Tekla.Structures.Drawing.ScalingOptions"""
    def __init__(self, *args) -> None: ...
    ...

class SectionMark(SectionMarkBase):
    """.NET: Tekla.Structures.Drawing.SectionMark"""
    def __init__(self, *args) -> None: ...
    LeftPoint: Point
    RightPoint: Point
    Attributes: SectionMarkAttributes
    QueryReturnValue: ReturnValuesEnum

class SectionMarkBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.SectionMarkBase"""
    def __init__(self, *args) -> None: ...
    LeftPoint: Point
    RightPoint: Point
    Attributes: SectionMarkAttributes
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class SinglePartDrawing(Drawing):
    """.NET: Tekla.Structures.Drawing.SinglePartDrawing"""
    def __init__(self, *args) -> None: ...
    PartIdentifier: Identifier
    SheetNumber: int
    DrawingTypeStr: str
    Name: str
    UpToDateStatus: DrawingUpToDateStatus
    IsMasterDrawing: bool
    IsLocked: bool
    IsIssued: bool
    IsIssuedButModified: bool
    IsFrozen: bool
    IsReadyForIssue: bool
    Title1: str
    Title2: str
    Title3: str
    Mark: str
    CreationDate: DateTime
    ModificationDate: DateTime
    IssuingDate: DateTime
    OutputDate: DateTime
    Layout: LayoutAttributes
    SectionViewStartLabel: str
    IsReadyForIssueBy: str
    IsLockedBy: str
    CommitMessage: str
    QueryReturnValue: ReturnValuesEnum
    def Insert(self, ) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class Size:
    """.NET: Tekla.Structures.Drawing.Size"""
    def __init__(self, *args) -> None: ...
    Width: float
    Height: float
    def ToString(self, formatProvider: IFormatProvider, separator: str) -> str: ...

class SizeDefinitionMode:
    """.NET: Tekla.Structures.Drawing.SizeDefinitionMode"""
    def __init__(self, *args) -> None: ...
    ...

class SpaceElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.SpaceElement"""
    def __init__(self, *args) -> None: ...
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class StraightDimension(DimensionBase):
    """.NET: Tekla.Structures.Drawing.StraightDimension"""
    def __init__(self, *args) -> None: ...
    StartPoint: Point
    EndPoint: Point
    Value: ContainerElement
    Attributes: StraightDimensionAttributes
    Distance: float
    UpDirection: Vector
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetDimensionSet(self, Select: bool) -> DimensionSetBase: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class StraightDimensionSet(DimensionSetBase):
    """.NET: Tekla.Structures.Drawing.StraightDimensionSet"""
    def __init__(self, *args) -> None: ...
    Attributes: StraightDimensionSetAttributes
    Distance: float
    LeftTagLineOffset: float
    RightTagLineOffset: float
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    @staticmethod
    def GetAllExcludePartsAccordingToFilter() -> List: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class StraightDimensionSetHandler:
    """.NET: Tekla.Structures.Drawing.StraightDimensionSetHandler"""
    def __init__(self, *args) -> None: ...
    def CreateDimensionSet(self, View: ViewBase, DimensionPoints: PointList, UpDirection: Vector, Distance: float, LeftTagLineOffset: float, RightTagLineOffset: float, Attributes: StraightDimensionSetAttributes) -> StraightDimensionSet: ...

class StringList(CollectionBase):
    """.NET: Tekla.Structures.Drawing.StringList"""
    def __init__(self, *args) -> None: ...
    Item: str
    Capacity: int
    Count: int
    def Add(self, value: str) -> int: ...
    def Contains(self, value: str) -> bool: ...
    def GetRange(self, index: int, count: int) -> StringList: ...
    def IndexOf(self, value: str, startIndex: int, count: int) -> int: ...
    def Insert(self, index: int, value: str) -> None: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def LastIndexOf(self, value: str, startIndex: int, count: int) -> int: ...
    def Remove(self, value: str) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def ToArray(self, ) -> list: ...

class Surfacing(ModelObject):
    """.NET: Tekla.Structures.Drawing.Surfacing"""
    def __init__(self, *args) -> None: ...
    Attributes: SurfacingAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class Symbol(DrawingObject):
    """.NET: Tekla.Structures.Drawing.Symbol"""
    def __init__(self, *args) -> None: ...
    Attributes: SymbolAttributes
    InsertionPoint: Point
    SymbolInfo: SymbolInfo
    Placing: PlacingBase
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...
    def Select(self, ) -> bool: ...

class SymbolElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.SymbolElement"""
    def __init__(self, *args) -> None: ...
    Symbol: SymbolInfo
    Color: DrawingColors
    TrueColor: TeklaDrawingColor
    Height: float
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class SymbolInfo:
    """.NET: Tekla.Structures.Drawing.SymbolInfo"""
    def __init__(self, *args) -> None: ...
    SymbolIndex: int
    SymbolFile: str
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class SymbolLibrary:
    """.NET: Tekla.Structures.Drawing.SymbolLibrary"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetSymbolLibraries(forceRefresh: bool) -> StringList: ...

class TagLocation:
    """.NET: Tekla.Structures.Drawing.TagLocation"""
    def __init__(self, *args) -> None: ...
    ...

class TeklaDrawingColor:
    """.NET: Tekla.Structures.Drawing.TeklaDrawingColor"""
    def __init__(self, *args) -> None: ...
    RGBColor: Color
    DrawingColorEnum: DrawingColors

class TeklaStructuresDrawingsApplicationException(ApplicationException):
    """.NET: Tekla.Structures.Drawing.TeklaStructuresDrawingsApplicationException"""
    def __init__(self, *args) -> None: ...
    Message: str
    Data: IDictionary
    InnerException: Exception
    TargetSite: MethodBase
    StackTrace: str
    HelpLink: str
    Source: str
    HResult: int

class TemplateInfo(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.TemplateInfo"""
    def __init__(self, *args) -> None: ...
    Name: str
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class Text(DrawingObject):
    """.NET: Tekla.Structures.Drawing.Text"""
    def __init__(self, *args) -> None: ...
    ResizeBehavior: TextResizeBehavior
    InsertionPoint: Point
    TextString: str
    IsRichText: bool
    Attributes: TextAttributes
    Placing: PlacingBase
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...
    def Select(self, ) -> bool: ...

class TextAlignment:
    """.NET: Tekla.Structures.Drawing.TextAlignment"""
    def __init__(self, *args) -> None: ...
    ...

class TextElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.TextElement"""
    def __init__(self, *args) -> None: ...
    Font: FontAttributes
    Value: str
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class TextFile(EmbeddedObjectBase):
    """.NET: Tekla.Structures.Drawing.TextFile"""
    def __init__(self, *args) -> None: ...
    Attributes: TextFileAttributes
    InsertionPoint: Point
    FileName: str
    Angle: float
    Size: Size
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class TextResizeBehavior:
    """.NET: Tekla.Structures.Drawing.TextResizeBehavior"""
    def __init__(self, *args) -> None: ...
    ...

class UnitAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.UnitAttributes"""
    def __init__(self, *args) -> None: ...
    Unit: Units
    Format: FormatTypes
    def Clone(self, ) -> object: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class Units:
    """.NET: Tekla.Structures.Drawing.Units"""
    def __init__(self, *args) -> None: ...
    ...

class UserDefinedElement(ElementBase):
    """.NET: Tekla.Structures.Drawing.UserDefinedElement"""
    def __init__(self, *args) -> None: ...
    Name: str
    Value: str
    Font: FontAttributes
    Unit: UnitAttributes
    def Clone(self, ) -> object: ...
    def GetUnformattedString(self, ) -> str: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class View(ViewBase):
    """.NET: Tekla.Structures.Drawing.View"""
    def __init__(self, *args) -> None: ...
    Attributes: ViewAttributes
    RestrictionBox: AABB
    Name: str
    ViewCoordinateSystem: CoordinateSystem
    DisplayCoordinateSystem: CoordinateSystem
    ViewType: ViewTypes
    Width: float
    Height: float
    FrameOrigin: Vector
    Origin: Point
    ExtremaCenter: Point
    IsSheet: bool
    QueryReturnValue: ReturnValuesEnum
    @staticmethod
    def Create3dView(drawing: Drawing, viewPlane: CoordinateSystem, displayPlane: CoordinateSystem, viewExtrema: AABB, viewInsertionPoint: Point, viewAttributes: ViewAttributes, view: View) -> bool: ...
    @staticmethod
    def CreateBackView(drawing: Drawing, viewInsertionPoint: Point, viewAttributes: ViewAttributes, view: View) -> bool: ...
    @staticmethod
    def CreateBottomView(drawing: Drawing, viewInsertionPoint: Point, viewAttributes: ViewAttributes, view: View) -> bool: ...
    @staticmethod
    def CreateCurvedSectionView(view: View, startPoint: Point, middlePoint: Point, endPoint: Point, viewInsertionPoint: Point, depthUp: float, depthDown: float, viewAttributes: ViewAttributes, sectionMarkAttributes: SectionMarkAttributes, curvedSectionView: View, sectionMark: CurvedSectionMark) -> bool: ...
    @staticmethod
    def CreateDetailView(view: View, centerPoint: Point, boundaryPoint: Point, labelPoint: Point, viewInsertionPoint: Point, viewAttributes: ViewAttributes, detailMarkAttributes: DetailMarkAttributes, detailView: View, detailMark: DetailMark) -> bool: ...
    @staticmethod
    def CreateFrontView(drawing: Drawing, viewInsertionPoint: Point, viewAttributes: ViewAttributes, view: View) -> bool: ...
    @staticmethod
    def CreateModelView(drawing: Drawing, modelViewId: int, useDrawingAttributes: bool, view: View) -> bool: ...
    @staticmethod
    def CreateSectionView(view: View, startPoint: Point, endPoint: Point, viewInsertionPoint: Point, depthUp: float, depthDown: float, viewAttributes: ViewAttributes, sectionMarkAttributes: SectionMarkAttributes, sectionView: View, sectionMark: SectionMark) -> bool: ...
    @staticmethod
    def CreateTopView(drawing: Drawing, viewInsertionPoint: Point, viewAttributes: ViewAttributes, view: View) -> bool: ...
    def GetModelObjects(self, ) -> DrawingObjectEnumerator: ...
    def GetPossibleFollowedObjects(self, ) -> IList: ...
    def GetPreferredFollowedObject(self, ) -> Identifier: ...
    def GetVisibleAreaRestrictionBoxes(self, ) -> IEnumerator: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def RotateViewOnAxisX(self, rotationAngle: float) -> bool: ...
    def RotateViewOnAxisY(self, rotationAngle: float) -> bool: ...
    def RotateViewOnAxisZ(self, rotationAngle: float) -> bool: ...
    def RotateViewOnDrawingPlane(self, rotationAngle: float) -> bool: ...
    def SetPreferredFollowedObject(self, identifier: Identifier) -> None: ...

class ViewBase(DrawingObject):
    """.NET: Tekla.Structures.Drawing.ViewBase"""
    def __init__(self, *args) -> None: ...
    Width: float
    Height: float
    FrameOrigin: Vector
    Origin: Point
    ExtremaCenter: Point
    IsSheet: bool
    Attributes: AttributesBase
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAllObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetModelObjects(self, ModelIdentifier: Identifier) -> DrawingObjectEnumerator: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def GetOriginalDrawing(self, ) -> Drawing: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class ViewMarkBasicSymbolAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.ViewMarkBasicSymbolAttributes"""
    def __init__(self, *args) -> None: ...
    Size: float
    Shape: MarkSymbolShape
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class ViewMarkBasicTagAttributes(GenericAttributesBase):
    """.NET: Tekla.Structures.Drawing.ViewMarkBasicTagAttributes"""
    def __init__(self, *args) -> None: ...
    Offset: Vector
    Location: TagLocation
    TagContent: ContainerElement
    def IsEqual(self, ObjectToCompare: object) -> bool: ...

class Weld(ModelObject):
    """.NET: Tekla.Structures.Drawing.Weld"""
    def __init__(self, *args) -> None: ...
    Attributes: WeldAttributes
    ModelIdentifier: Identifier
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def Select(self, ) -> bool: ...

class WeldMark(DrawingObject):
    """.NET: Tekla.Structures.Drawing.WeldMark"""
    def __init__(self, *args) -> None: ...
    ModelIdentifier: Identifier
    Attributes: WeldMarkAttributes
    InsertionPoint: Point
    Hideable: Hideable
    QueryReturnValue: ReturnValuesEnum
    def Delete(self, ) -> bool: ...
    def GetAxisAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjectAlignedBoundingBox(self, ) -> RectangleBoundingBox: ...
    def GetObjects(self, TypeFilter: list) -> DrawingObjectEnumerator: ...
    def Insert(self, ) -> bool: ...
    def IsEqual(self, ObjectToCompare: object) -> bool: ...
    def Modify(self, ) -> bool: ...
    def MoveObjectRelative(self, MoveVector: Vector) -> bool: ...
    def Select(self, ) -> bool: ...
