# Auto-generated — Tekla 2026 — Tekla.Structures.Drawing.Internal

class DgUtil:
    """.NET: Tekla.Structures.Drawing.Internal.DgUtil"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetDgFileNameByDrawingGuid(drawingGuid: Guid) -> str: ...
    @staticmethod
    def GetDgGuidByDrawingGuid(drawingGuid: Guid) -> Guid: ...

class FabricationDrawingType:
    """.NET: Tekla.Structures.Drawing.Internal.FabricationDrawingType"""
    def __init__(self, *args) -> None: ...
    ...
