# Auto-generated — Tekla 2026 — Tekla.Structures.Drawing.Operations

class Operation:
    """.NET: Tekla.Structures.Drawing.Operations.Operation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def MergeMarks(marks: IList, mergedMarks: List) -> bool: ...
    @staticmethod
    def SortObjectsByPresentationOrder(objects: IList, objectsByPresentationOrder: List) -> bool: ...
    @staticmethod
    def SplitMarks(marks: IList) -> bool: ...
