# Auto-generated — Tekla 2026 — Tekla.Structures.Drawing.Tools

class DrawingCoordinateConverter:
    """.NET: Tekla.Structures.Drawing.Tools.DrawingCoordinateConverter"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def Convert(fromView: ViewBase, toView: ViewBase, point: Point) -> Point: ...

class InputDefinitionFactory:
    """.NET: Tekla.Structures.Drawing.Tools.InputDefinitionFactory"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CreateInputDefinition(view: ViewBase, point1: Point, point2: Point, point3: Point) -> InputDefinition: ...
    @staticmethod
    def GetDrawingObject(input: InputDefinition) -> DrawingObject: ...
    @staticmethod
    def GetPoint(input: InputDefinition) -> Point: ...
    @staticmethod
    def GetPoints(input: InputDefinition) -> PointList: ...
    @staticmethod
    def GetView(input: InputDefinition) -> ViewBase: ...
