# Auto-generated — Tekla 2026 — Tekla.Structures.Drawing.UI

class DrawingObjectSelector:
    """.NET: Tekla.Structures.Drawing.UI.DrawingObjectSelector"""
    def __init__(self, *args) -> None: ...
    def GetSelected(self, ) -> DrawingObjectEnumerator: ...
    def SelectObject(self, DrawingObject: DrawingObject) -> bool: ...
    def SelectObjects(self, DrawingObjects: ArrayList, ExtendSelection: bool) -> bool: ...
    def UnselectAllObjects(self, ) -> bool: ...
    def UnselectObject(self, DrawingObject: DrawingObject) -> bool: ...
    def UnselectObjects(self, DrawingObjects: ArrayList) -> bool: ...

class DrawingSelector:
    """.NET: Tekla.Structures.Drawing.UI.DrawingSelector"""
    def __init__(self, *args) -> None: ...
    def GetSelected(self, ) -> DrawingEnumerator: ...

class Events(MarshalByRefObject):
    """.NET: Tekla.Structures.Drawing.UI.Events"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...
    def InitializeLifetimeService(self, ) -> object: ...
    def OnDocumentManagerClosed(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingEditorClose(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingEditorOpen(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingListSelectionChanged(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingLoaded(self, EventName: str, Parameters: list) -> None: ...
    def OnInterrupted(self, ) -> None: ...
    def OnLayoutEditingModeEntered(self, EventName: str, Parameters: list) -> None: ...
    def OnLayoutEditingModeExited(self, EventName: str, Parameters: list) -> None: ...
    def OnLayoutOptionModified(self, EventName: str, Parameters: list) -> None: ...
    def OnLayoutTableDeleted(self, EventName: str, Parameters: list) -> None: ...
    def OnLayoutTableInserted(self, EventName: str, Parameters: list) -> None: ...
    def OnLayoutTableLayoutModified(self, EventName: str, Parameters: list) -> None: ...
    def OnLayoutTableModified(self, EventName: str, Parameters: list) -> None: ...
    def OnSelectionChange(self, EventName: str, Parameters: list) -> None: ...
    def Register(self, ) -> None: ...
    def UnRegister(self, ) -> None: ...

class IUIEvents:
    """.NET: Tekla.Structures.Drawing.UI.IUIEvents"""
    def __init__(self, *args) -> None: ...
    def OnDocumentManagerClosed(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingEditorClose(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingEditorOpen(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingListSelectionChanged(self, EventName: str, Parameters: list) -> None: ...
    def OnDrawingLoaded(self, EventName: str, Parameters: list) -> None: ...
    def OnInterrupted(self, ) -> None: ...
    def OnSelectionChange(self, EventName: str, Parameters: list) -> None: ...
    def Register(self, ) -> None: ...
    def UnRegister(self, ) -> None: ...

class Picker:
    """.NET: Tekla.Structures.Drawing.UI.Picker"""
    def __init__(self, *args) -> None: ...
    def IsInteractive(self, ) -> bool: ...
    def PickObject(self, prompt: str, typeFilter: list, pickedObject: DrawingObject, pickedView: ViewBase, pickedPoint: Point) -> None: ...
    def PickObjectAndPoint(self, prompt: str) -> Tuple: ...
    def PickPoint(self, prompt: str, pickedPoint: Point, pickedView: ViewBase) -> None: ...
    def PickPoints(self, numberOfPicks: int, prompts: StringList, pickedPoints: PointList, pickedView: ViewBase) -> None: ...
    def PickThreePoints(self, firstPrompt: str, secondPrompt: str, thirdPrompt: str, firstPickedPoint: Point, secondPickedPoint: Point, thirdPickedPoint: Point, pickedView: ViewBase) -> None: ...
    def PickTwoPoints(self, firstPrompt: str, secondPrompt: str, firstPickedPoint: Point, secondPickedPoint: Point, pickedView: ViewBase) -> None: ...
