# Auto-generated — Tekla 2026 — Tekla.Structures.Model.Internal

class AssertEventDelegate:
    """.NET: Tekla.Structures.Model.Internal.AssertEventDelegate"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, assertEvent: dotAssertEvent_t, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, assertEvent: dotAssertEvent_t) -> None: ...

class CancellableProgressReportDelegate:
    """.NET: Tekla.Structures.Model.Internal.CancellableProgressReportDelegate"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, exportPhase: str, progressPercentage: int, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...
    def Invoke(self, exportPhase: str, progressPercentage: int) -> bool: ...

class Connect:
    """.NET: Tekla.Structures.Model.Internal.Connect"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetProjectId(projectInfo: ProjectInfo) -> ValueTuple: ...
    @staticmethod
    def GetUploads(modelInfo: ModelInfo, projectInfo: ProjectInfo) -> IUploads: ...

class ContourOperation:
    """.NET: Tekla.Structures.Model.Internal.ContourOperation"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def GetPartContour(PartId: Identifier) -> Polycurve: ...
    @staticmethod
    def GetPolycurveFromContourPoints(DotContourPoints: List) -> Polycurve: ...

class ExcelReportData:
    """.NET: Tekla.Structures.Model.Internal.ExcelReportData"""
    def __init__(self, *args) -> None: ...
    ...

class FarmiHelper:
    """.NET: Tekla.Structures.Model.Internal.FarmiHelper"""
    def __init__(self, *args) -> None: ...
    @staticmethod
    def CopyAndConvertModel(sourcePath: str, targetPath: str) -> None: ...
    @staticmethod
    def CopyDirectory(path: str, targetPath: str, throwExceptions: bool, clearReadOnlyFlag: bool, excludeRegex: str) -> None: ...

class IAssertEventCallback:
    """.NET: Tekla.Structures.Model.Internal.IAssertEventCallback"""
    def __init__(self, *args) -> None: ...
    def OnAssertOccured(self, assertEvent: dotAssertEvent_t) -> None: ...

class ICancellableProgressReportCallback:
    """.NET: Tekla.Structures.Model.Internal.ICancellableProgressReportCallback"""
    def __init__(self, *args) -> None: ...
    def OnCnacelanbleProgressChanged(self, exportPhase: str, progressPercentage: int) -> bool: ...

class IChangeSetCreatedCallback:
    """.NET: Tekla.Structures.Model.Internal.IChangeSetCreatedCallback"""
    def __init__(self, *args) -> None: ...
    def OnChangeSetCreated(self, data: list) -> None: ...

class IProgressReportCallback:
    """.NET: Tekla.Structures.Model.Internal.IProgressReportCallback"""
    def __init__(self, *args) -> None: ...
    def OnProgressChanged(self, exportPhase: str, progressPercentage: int) -> None: ...

class IReportingExcelDialogCallback:
    """.NET: Tekla.Structures.Model.Internal.IReportingExcelDialogCallback"""
    def __init__(self, *args) -> None: ...
    def OpenReportingExcelDialog(self, data: ExcelReportData) -> None: ...

class LiveSharingChangeSetDelegate:
    """.NET: Tekla.Structures.Model.Internal.LiveSharingChangeSetDelegate"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, bytes: list, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, bytes: list) -> None: ...

class LiveSharingModelType:
    """.NET: Tekla.Structures.Model.Internal.LiveSharingModelType"""
    def __init__(self, *args) -> None: ...
    ...

class ProgressReportDelegate:
    """.NET: Tekla.Structures.Model.Internal.ProgressReportDelegate"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, exportPhase: str, progressPercentage: int, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, exportPhase: str, progressPercentage: int) -> None: ...

class ReportingExcelDialogDelegate:
    """.NET: Tekla.Structures.Model.Internal.ReportingExcelDialogDelegate"""
    def __init__(self, *args) -> None: ...
    Method: MethodInfo
    Target: object
    def BeginInvoke(self, data: ExcelReportData, callback: AsyncCallback, object: object) -> IAsyncResult: ...
    def EndInvoke(self, data: ExcelReportData, result: IAsyncResult) -> None: ...
    def Invoke(self, data: ExcelReportData) -> None: ...

class WorkPlaneChanger:
    """.NET: Tekla.Structures.Model.Internal.WorkPlaneChanger"""
    def __init__(self, *args) -> None: ...
    def Dispose(self, ) -> None: ...

class dotAssertEvent_t:
    """.NET: Tekla.Structures.Model.Internal.dotAssertEvent_t"""
    def __init__(self, *args) -> None: ...
    ...
