# Auto-generated — Tekla 2026 — Tekla.Structures.Model.Internal.OverlayModel

class IOverlayModelEvents:
    """.NET: Tekla.Structures.Model.Internal.OverlayModel.IOverlayModelEvents"""
    def __init__(self, *args) -> None: ...
    ...

class OverlayModelCollectionChangesAction:
    """.NET: Tekla.Structures.Model.Internal.OverlayModel.OverlayModelCollectionChangesAction"""
    def __init__(self, *args) -> None: ...
    ...

class OverlayModelEvents(MarshalByRefObject):
    """.NET: Tekla.Structures.Model.Internal.OverlayModel.OverlayModelEvents"""
    def __init__(self, *args) -> None: ...
    def OnOverlayModelCollectionChangedEvent(self, path: str, action: OverlayModelCollectionChangesAction) -> None: ...
